### ISSUE TITLE
Junit4 test finder fails to find tests

### ISSUE THREAD

**Issue by vgcpge** [eclipse-jdt/eclipse.jdt.core#1039]
My tests had worked fine in 2022-12, but do not work in any later Eclipse release.

### Test steps
Import project https://github.com/basilevs/jstackfilter/tree/0.0.2/library
Create a new launch configuration that executes all tests in the project.
Run it

### Expected result
Some tests are found and executed, just like in 2022-12

### Actual result
No tests found.
No errors in error log.

The project in question is a bit strange - it is a Java modular project, that also plays a role of Eclipse plugin. Hence, it includes the tests folder (explicitly marked so).
Before the disaster I could run these tests in both pure JDT and in PDE.

**Comment by trancexpress** [comment]
The `@Test` annotation type is apparently not found. A `ProblemReferenceBinding` is created here:

```
"ModalContext" #159 prio=6 os_prio=0 cpu=75.42ms elapsed=3081.66s tid=0x00007f42a2b35590 nid=0x11856 at breakpoint [0x00007f41679fd000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.ProblemReferenceBinding.<init>(ProblemReferenceBinding.java:30)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getInaccessibleBinding(LookupEnvironment.java:2318)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getInaccessibleBinding(LookupEnvironment.java:2289)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:607)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:650)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:479)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:552)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2032)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1364)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1401)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1543)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
        at org.eclipse.jdt.internal.junit.launcher.JUnit4TestFinder.findTestsInContainer(JUnit4TestFinder.java:157)
        at org.eclipse.jdt.internal.junit.util.TestSearchEngine.lambda$0(TestSearchEngine.java:42)
        at org.eclipse.jdt.internal.junit.util.TestSearchEngine$$Lambda$1046/0x00000008006be958.run(Unknown Source)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

I'm not sure why the project is not able to see the type... Its in the unnamed module, in theory it should be visible from everywhere.

**Comment by iloveeclipse** [comment]
> I'm guessing the JUnit container will also need some sort of special handling, since it also doesn't have the `module` attribute set:
> 
> ```
> <classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4"/>
> ```

I've debugged around this search code and it seem to search types on module path, where the JUnit container is **not** added for the search, but obviously added at runtime.

Java editor even proposes to move container from classpath to modulepath:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/d944466b-9daf-4f65-b7fc-8d115bb61826)

Once that is done, classpath looks like

```
	<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
```

... and  everything works.

> I'm not sure why the project is not able to see the type... Its in the unnamed module, in theory it should be visible from everywhere.

If I understand the logic of `JavaSearchNameEnvironment.computeClasspathLocations()` correct, the "unnamed module" doesn't exist in this context. All types are either found from their own modules or by the project module. 

So the code that maps classpath entries to modules in `mapToClassPathLocation()` has to add entries that aren't modular to `defaultModule`. 

Maybe we can do a bit more refactoring, just a brain dump if that would work: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1066

It does a bit more than #1040, most likely if that would work, that should go to 4.29 M1.
