### ISSUE TITLE
Reflection APIs fail with NPE processing class file produced by JDT compiler

### ISSUE THREAD

**Issue by maximilianost** [eclipse-jdt/eclipse.jdt.core#1048]
For a method like
`
private Stream<Serializable> doMyStuff() {
        Stream<Serializable> s = Stream.empty(); 
        return Optional.ofNullable(s).orElseGet(Stream::of);
    }
`
The JDT compiler create an invalid method return type signature '+Ljava/util/stream/Stream<Ljava/io/Serializable;>;'

To reproduce the issue use the attached [Reproducer.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/11451597/Reproducer.zip)
Importing it into Eclipse and run the main method leads to the output:
`
void
java.util.stream.Stream<java.io.Serializable>
Exception in thread "main" java.lang.reflect.GenericSignatureFormatError: Signature Parse error: Expected Field Type Signature
	Remaining input: +Ljava/util/stream/Stream<Ljava/io/Serializable;>;
	at java.base/sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:291)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:277)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:469)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseReturnType(SignatureParser.java:611)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:561)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:58)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
	at java.base/sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
	at java.base/sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:54)
	at java.base/sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:47)
	at java.base/sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:60)
	at java.base/java.lang.reflect.Method.getGenericInfo(Method.java:112)
	at java.base/java.lang.reflect.Method.getGenericReturnType(Method.java:295)
	at Reproducer.testClassWithStreamAndOptional2(Reproducer.java:24)
	at Reproducer.main(Reproducer.java:15)`

Compile it with 'javac Reproducer.class' and run with 'java Reproducer' gives the output
`
void
interface java.util.stream.Stream
java.util.stream.Stream<java.io.Serializable>
void
`

See discussion in 
#https://gitlab.ow2.org/asm/asm/-/issues/318000
for further context.

**Comment by iloveeclipse** [comment]
I haven't verified if that is still an issue on master, there were few lambda related fixes recently. 

@srikanth-sankaran : could you please check?

**Comment by srikanth-sankaran** [comment]
The GenericSignatureFormatError itself very likely went away with the resolution of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/756

However, when I run the reproducer now, I get 

```
void
void
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Type.getTypeName()" because "t" is null
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.toString(ParameterizedTypeImpl.java:236)
	at java.base/java.lang.String.valueOf(String.java:4225)
	at java.base/java.io.PrintStream.println(PrintStream.java:1186)
	at Reproducer.testClassWithStreamAndOptional2(Reproducer.java:24)
	at Reproducer.main(Reproducer.java:15)
```

while with javac I get 

```
void
void
java.util.stream.Stream<java.io.Serializable>
interface java.util.stream.Stream
```

So this difference in behavior needs further investigation.

**Comment by srikanth-sankaran** [comment]
Inline test case:

```



import java.io.IOException;
import java.io.Serializable;
import java.lang.reflect.Method;
import java.util.Optional;
import java.util.stream.Stream;


public class Reproducer {
    
    public static void main(String[] args) {
        try {
            new Reproducer().testClassWithStreamAndOptional2();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void testClassWithStreamAndOptional2() throws IOException {
        Class<?> c = this.getClass();
        for (Method m : c.getDeclaredMethods()) {
          System.out.println(m.getGenericReturnType());
        }
    }
    
    
    private Stream<Serializable> doMyStuff() {
        Stream<Serializable> s = Stream.empty(); 
        return Optional.ofNullable(s).orElseGet(Stream::of);
    }
}

```
