### ISSUE TITLE
[Records 2.0] ECJ has two parallel mechanisms for canonical constructor generation

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#1090]
Follow up from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1085#issuecomment-1562223557

ECJ has two parallel mechanisms for canonical constructor generation for records implemented by

org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.createDefaultConstructorForRecord(boolean, boolean) and
org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.addSyntheticRecordCanonicalConstructor()

I would argue that the SMB based approach is more befitting of how things are done in ECJ - though that position cannot be maintained 100% of the time.

Problem with generating at record parse time is that we don't know if the record declaration has a programmer supplied canonical constructor - so ecj takes the (ugly) approach of generating one eagerly and later if it turns out, there is a clash to delete the synthesized method.

See org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods() which deals with clash - the clash can arise from either of the redundant strategy.

The fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=570399 introduced the second, redundant, parallel approach.
IMO, the single line fix made for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1085 here https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1089 would have sufficed to fix  https://bugs.eclipse.org/bugs/show_bug.cgi?id=570399 

But given where we are, we need to decide how to proceed and get rid of one of the approaches. (With the fix for  https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1085 most of the code introduced for  https://bugs.eclipse.org/bugs/show_bug.cgi?id=570399 is dead code but per earlier, that implements a strategy that fits overall ECJ philosophy better.

**Comment by srikanth-sankaran** [comment]
@mpalat - This is coming in next

**Comment by jarthana** [comment]
Here's one more issue I found with the now-reverted patch:

1. Add a compact constructor to /org.eclipse.jdt.compiler.apt.tests/resources/mod_locations/records/mod.records/records/R4.java
`	public R4 {}`
2. Now run the RecordElementsTest to find the following NPE:
```
java.lang.NullPointerException: Cannot read the array length because "methodDeclaration.arguments" is null
	at org.eclipse.jdt.internal.compiler.apt.model.ExecutableElementImpl.getParameters(ExecutableElementImpl.java:122)
	at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.testRecords10(RecordElementProcessor.java:590)
```

**Comment by jarthana** [comment]
I found one more issue with the first patch. I have captured this in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3931.

Here's the affected code in R4.java:

```
record R4(@Marker4 int... i) {}
// record R4(@Marker4  @Marker5() @Marker5() int... i) {} // This will cause failures in RecordElementProcessor#testRecords10
```

Comment out the first line and uncomment the latter and run RecordElementsTests.testRecords10() to see the problem. One can run testRecords10Javac to observe the difference between Javac and ECJ.

**Comment by srikanth-sankaran** [comment]
Many thanks Jay, I am on the case.
