### ISSUE TITLE
testCopyConstructorInDifferentProject failure

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1094]
Intermittent failure
https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.jdt.core.tests.model_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

No delta found for class Y [in Y.java [in <default> [in src [in P2]]]] Y(String), all deltas: [Java Model[*]: {CHILDREN} P2[*]: {CHILDREN} src[*]: {CHILDREN} <default>[*]: {CHILDREN} Y.java[*]: {CONTENT | PRIMARY RESOURCE}]

junit.framework.AssertionFailedError: No delta found for class Y [in Y.java [in <default> [in src [in P2]]]]
Y(String), all deltas: [Java Model[*]: {CHILDREN}
P2[*]: {CHILDREN}
src[*]: {CHILDREN}
<default>[*]: {CHILDREN}
Y.java[*]: {CONTENT | PRIMARY RESOURCE}]
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.jdt.core.tests.model.CopyMoveTests.copyPositive(CopyMoveTests.java:122)
at org.eclipse.jdt.core.tests.model.CopyMoveElementsTests.testCopyConstructorInDifferentProject(CopyMoveElementsTests.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:983)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:98)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:86)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:95)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
at org.junit.platf

Earlier also there were internmittent failures - ref: https://bugs.eclipse.org/bugs/show_bug.cgi?id=577224
See a probably similar issue - 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=578922

Investigate if any further changes can be done to the above fix

**Comment by stephan-herrmann** [comment]
I hope this is covered by the fix in #2629
