### ISSUE TITLE
NPE in BlockScope.correlateTrackingVarsIfElse

### ISSUE THREAD

**Issue by volosied** [eclipse-jdt/eclipse.jdt.core#1135]
Has anyone seen an NPE like this one?  It occurred on version 3.26 when compiling a translate JSP.   I'll try to provide more details soon.

```
exception occurred: java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.correlateTrackingVarsIfElse(BlockScope.java:1257)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.correlateTrackingVarsIfElse(BlockScope.java:1293)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.correlateTrackingVarsIfElse(BlockScope.java:1293)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:146)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:141)
	at org.eclipse.jdt.internal.compiler.ast.Block.analyseCode(Block.java:50)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.analyseCode(TryStatement.java:339)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:129)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:956)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:304)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:136)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:908)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:575)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at com.ibm.ws.jsp.translator.compiler.JDTCompiler.compile(JDTCompiler.java:177)
```

**Comment by volosied** [comment]
If I'm looking at this line 1257 right, then either `elseFlowInfo` or `trackingVar` is null, but, based on the previous `if` statement, `trackingVar`  cannot be null.  `elseFlowInfo` is the culprit. 

<img width="877" alt="image" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/5934310/76ab1fed-b750-425e-baaa-2d2aa642fe55">
