### ISSUE TITLE
AnnotationProcessingCompilerToolTest fails on Windows since I20230621-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1178]
See
- https://download.eclipse.org/eclipse/downloads/drops4/I20230621-1800/testResults.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20230621-1800/testresults/html/org.eclipse.jdt.apt.tests_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

Looks line new line difference (Win/Unix) is the problem:
```
--------- Difference is ----------
expected:<...]\n
in jar:file:C:[\Users\genie.releng\AppData\Local\Temp\]org.eclipse.jdt.apt....> but was:<...]\n
in jar:file:C:[/Users/genie.releng/AppData/Local/Temp/]org.eclipse.jdt.apt....>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractBatchCompilerTest.runTest(AbstractBatchCompilerTest.java:611)
at org.eclipse.jdt.apt.tests.AnnotationProcessingCompilerToolTest.runTest(AnnotationProcessingCompilerToolTest.java:212)
at org.eclipse.jdt.apt.tests.AnnotationProcessingCompilerToolTest.test_github844(AnnotationProcessingCompilerToolTest.java:63)
```

This is the new test added in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/845.

@guw : could you please take a look?

**Comment by guw** [comment]
@iloveeclipse Can you assign this to me please?
