### ISSUE TITLE
MethodHandle::invokeExact infers wrong return type

### ISSUE THREAD

**Issue by stevenschlansker** [eclipse-jdt/eclipse.jdt.core#1267]
The following code runs OK (no exception thrown) in openjdk Red_Hat-20.0.1.0.9-2.rolling.fc38
In Eclipse, it fails with a `WrongMethodTypeException`. The method reference `mh::invokeExact` should take the `void` return type from the implemented interface, but ends up with `Object` instead.

```java
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.function.BiConsumer;

public class TestWrongMethodType {
    public static void main(final String[] args) throws Exception {
        final var mh = MethodHandles.lookup()
                .findVirtual(TestWrongMethodType.class, "setProp", MethodType.methodType(TestWrongMethodType.class, String.class))
                .asType(MethodType.methodType(void.class, Object.class, Object.class));
        uncheckedBiConsumer(mh::invokeExact).accept(new TestWrongMethodType(), "42");
    }

    public TestWrongMethodType setProp(final String value) {
        return this;
    }

    public static <X, Y> BiConsumer<X, Y> uncheckedBiConsumer(final CheckedBiConsumer<X, Y> checkedBiConsumer) {
        return (x, y) -> {
            try {
                checkedBiConsumer.accept(x, y);
            } catch (final Throwable t) {
                throw new RuntimeException(t);
            }
        };
    }

    public interface CheckedBiConsumer<X, Y> {
        void accept(X x, Y y) throws Throwable;
    }
}
```

In Eclipse JDT 3.19.100.v20230605-0440, this fails:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.invoke.WrongMethodTypeException: expected (Object,Object)void but found (Object,Object)Object
	at org.jdbi.v3.core.mapper.TestWrongMethodType.lambda$1(TestWrongMethodType.java:37)
	at org.jdbi.v3.core.mapper.TestWrongMethodType.main(TestWrongMethodType.java:25)
Caused by: java.lang.invoke.WrongMethodTypeException: expected (Object,Object)void but found (Object,Object)Object
	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:523)
	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:532)
	at org.jdbi.v3.core.mapper.TestWrongMethodType.lambda$1(TestWrongMethodType.java:35)
	... 1 more
```

**Comment by srikanth-sankaran** [comment]
> The following code runs OK (no exception thrown) in openjdk Red_Hat-20.0.1.0.9-2.rolling.fc38
> In Eclipse, it fails with a `WrongMethodTypeException`. The method reference `mh::invokeExact` should take the `void` return type from the implemented interface, but ends up with `Object` instead.

JLS 15.12:

The compile-time parameter types and compile-time result are determined as
follows:
• If the compile-time declaration for the method invocation is not a signature
polymorphic method, then:
– The compile-time parameter types are the types of the formal parameters of
the compile-time declaration.
– The compile-time result is the result of the invocation type of the compiletime
declaration (§15.12.2.6).
• If the compile-time declaration for the method invocation is a signature
polymorphic method, then:
– The compile-time parameter types are the types of the actual argument
expressions. An argument expression which is the null literal null (§3.10.8)
is treated as having the type Void.
– The compile-time result is determined as follows:
› If the signature polymorphic method is either void or has a return type other
than Object, the compile-time result is the result of the invocation type of
the compile-time declaration (§15.12.2.6).
› Otherwise, if the method invocation expression is an expression statement,
the compile-time result is void.
› Otherwise, if the method invocation expression is the operand of a cast
expression (§15.16), the compile-time result is the erasure of the type of the
cast expression (§4.6).
› Otherwise, the compile-time result is the signature polymorphic method's
return type, Object.

**Comment by srikanth-sankaran** [comment]
@stephan-herrmann per my reading, this doesn't call for return type to be picked up from invocation context treating the declared return type Object as a polymorphic place holder - for parameter types, it is clear just not for return type: do you agree ??
