### ISSUE TITLE
Nasty Log output for xml file on classpath: java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by mguillem** [eclipse-jdt/eclipse.jdt.core#1274]
If a XML file is present on the classpath ecj 3.31+ (including 3.34.0) produces some annoying output on the console (compilation is done correctly).

Example:
```
Failed to init Classpath for jar file test.xml
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
        at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
        at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
        at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
        at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
        at org.eclipse.jdt.internal.compiler.batch.Main.main(Main.java:1521)
```

The problem can be easily reproduced:
```
cat << EOF > Test.java
class Test {}
EOF

cat << EOF > test.xml
<x></x>
EOF

java -jar ecj-3.31.0.jar -cp test.xml Test.java
Failed to init Classpath for jar file test.xml
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
        at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
        at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
        at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
        at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
        at org.eclipse.jdt.internal.compiler.batch.Main.main(Main.java:1521)
```

No console output is generated with version 3.30.

**Comment by iloveeclipse** [comment]
May I ask **why** do you put xml file on compiler classpath?

**Comment by mguillem** [comment]
In a old huge maven project we have a dependency of type pom (which has itself normal dependencies) what causes maven to put the pom.xml in the compile classpath.
Btw: javac doesn't complain.

**Comment by iloveeclipse** [comment]
So is this a maven bug or maven configuration issue? I don't think a pom.xml file from maven is a supported way to add some classpath dependencies to Java compiler. I would expect list of resolved libraries / paths added instead.

I tend to close this issue as invalid.

**Comment by mguillem** [comment]
I think that this is definitely a regression in ecj as the behaviour was ok before 3.31 and javac doesn't complain either.

For standard sdk tools, the documentation says that such files are ignored:
```
Class path entries that are neither directories nor archives (.zip or JAR files) nor the asterisk (*) wildcard character are ignored.
```
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1578
