### ISSUE TITLE
java.lang.IllegalArgumentException: "L;" at 0

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1289]
logged during org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests.testCompleteMethodParameter_DeepInTwoNestedClasses()

**Comment by jukzi** [comment]
```
java.lang.IllegalArgumentException: "L;" at 0
	at org.eclipse.jdt.core.Signature.newIllegalArgumentException(Signature.java:3017)
	at org.eclipse.jdt.core.Signature.appendClassTypeSignature(Signature.java:608)
	at org.eclipse.jdt.core.Signature.appendTypeSignature(Signature.java:931)
	at org.eclipse.jdt.core.Signature.appendTypeSignature(Signature.java:875)
	at org.eclipse.jdt.core.Signature.toCharArray(Signature.java:2753)
	at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.getDeclaringType(CompletionProposalCollector.java:639)
	at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.accept(CompletionProposalCollector.java:281)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findFields(CompletionEngine.java:7354)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findFields(CompletionEngine.java:7491)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findVariablesAndMethods(CompletionEngine.java:13457)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnSingleNameReference(CompletionEngine.java:4031)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2018)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2615)
	at org.eclipse.jdt.internal.core.SourceType.codeComplete(SourceType.java:142)
	at org.eclipse.jdt.internal.core.SourceType.codeComplete(SourceType.java:101)
	at org.eclipse.jdt.internal.core.SourceType.codeComplete(SourceType.java:87)
	at org.eclipse.jdt.internal.debug.ui.contentassist.JavaDebugContentAssistProcessor.computeCompletionProposals(JavaDebugContentAssistProcessor.java:164)
	at org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests$2.call(SyntheticVariableTests.java:132)
	at org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests$2.call(SyntheticVariableTests.java:1)
	at org.eclipse.jdt.debug.tests.ui.AbstractDebugUiTests.lambda$6(AbstractDebugUiTests.java:228)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.jdt.debug.tests.ui.AbstractDebugUiTests.sync(AbstractDebugUiTests.java:226)
	at org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests.computeCompletionProposals(SyntheticVariableTests.java:126)
	at org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests.testCompleteMethodParameter_DeepInTwoNestedClasses(SyntheticVariableTests.java:111)

```

**Comment by stephan-herrmann** [comment]
To avoid going in circles, let's collect some context:

The exception is thrown below
```
	at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.getDeclaringType(CompletionProposalCollector.java:639)
	at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.accept(CompletionProposalCollector.java:281)
```
That call to `getDeclaringType()` was added via https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/541 . Given that the return value is ignored I assume that @jjohnstn added it for the sole purpose of raising this exact `IAE`. I further assume that this was done to trigger the exception from within a suitable try-catch, to avoid the same to happen later during processing of the same proposal (https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/239). Right?

Is class `Signature` supposed to handle anonymous classes, and if so, how? 
* `Signature.appendClassTypeSignature()` can recognize the binary form using a digit as the type name.
* This is the only mentioning of "anonymous" within that class.
* Typically, signatures are used as a memento representation of types, that can be used by a client to reconstruct the type.
  * An empty name is useless for that purpose.
* Perhaps the code around `InternalCompletionProposal.setDeclarationSignature(char[])` should refuse to assign the signature of an anonymous type (or CompletionEngine itself should avoid such calls)?
  * => Perhaps this is where the exception should have been thrown and caught?

How would  clients of `CompletionProposal.getDeclarationSignature()` handle a signature with empty type name?
* Could they make actual use of it? I don't think so.
* Would they throw exceptions or otherwise misbehave? 
  * From a quick glance I found nothing conclusive within JDT sources, but obviously *any* plug-in could use this API with certain assumptions.
  * Changing `IAE` to returning an empty name would be an API change, that could possibly stir up more dust downstream.
* Note that `CompletionProposal.getDeclarationSignature()` declares that `null` is a legal return value
  * Would `null` be a better vehicle for such information than throwing?

**Comment by jukzi** [comment]
Thanks Stephan, for rapid feedback!

> That call to `getDeclaringType()` was added via [eclipse-jdt/eclipse.jdt.ui#541](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/541) .

see https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/239#issuecomment-1516608263
the call was there before - within isFiltered(). It was only added back because if the the exception is not catched that early it will later fail when sorting the resulting proposals. But if there is no exception it does not need to be eager catched :-)

The IAE was not intentional it was only catched & logged with https://bugs.eclipse.org/bugs/show_bug.cgi?id=84657

My suggestion with this patch is that the IAE is not used for control flow of an expected behavior.
Both tests pass with it:
org.eclipse.jdt.debug.tests.eval.SyntheticVariableTests.testCompleteMethodParameter_DeepInTwoNestedClasses()
org.eclipse.jdt.text.tests.contentassist.MethodInsertCompletionTest.testIssue417()

@jjohnstn With fixing the underlying IAE it would be even possible to remove the superfluous `getDeclaringType(proposal)` again.

I don't have any deeper clue how Signature should handle anonymous classes, it just worked naturally for JDT's related usecases.

**Comment by stephan-herrmann** [comment]
> My suggestion with this patch is that the IAE is not used for control flow of an expected behavior.

And I think, that asking the signature of an anonymous type ("what's the name of the unnamed?") is outside the contract, and therefor _must_ raise an exception.

@jarthana could you think of any reasons for working with signatures of anonymous types?

Given that class `Signature` is API, and the given method is indirectly called from public methods, we need to be quite careful with any semantic changes.

Perhaps, jdt.debug is better served with an additional API to ask if a type "has a valid signature", or such. This would allow them to avoid the questionable invocation in the first place.

**Comment by jukzi** [comment]
> > My suggestion with this patch is that the IAE is not used for control flow of an expected behavior.
> 
> And I think, that asking the signature of an anonymous type ("what's the name of the unnamed?") is outside the contract, and therefor _must_ raise an exception.
> 
> @jarthana could you think of any reasons for working with signatures of anonymous types?
> 
> Given that class `Signature` is API, and the given method is indirectly called from public methods, we need to be quite careful with any semantic changes.
> 
> Perhaps, jdt.ui is better served with an additional API to ask if a type "has a valid signature", or such. This would allow them to avoid the questionable invocation in the first place.

An alternative is to not create proposals that would lead to this exception:
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1381
