### ISSUE TITLE
NullAnnotationsRewriteOperations: OutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1294]
according to the stacktrace this was logged when Hovering org.eclipse.egit.ui.internal.ValidationUtils line 41
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/38186a72-e895-43f5-80c8-374bb852807a)

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.eclipse.jdt.core.dom.ASTNode$NodeList.get(ASTNode.java:1583)
	at org.eclipse.jdt.internal.corext.fix.NullAnnotationsRewriteOperations$ParameterAnnotationRewriteOperation.<init>(NullAnnotationsRewriteOperations.java:278)
	at org.eclipse.jdt.internal.corext.fix.NullAnnotationsRewriteOperations$ParameterAnnotationRewriteOperation.<init>(NullAnnotationsRewriteOperations.java:272)
	at org.eclipse.jdt.internal.corext.fix.NullAnnotationsRewriteOperations$Builder.createAddAnnotationOperation(NullAnnotationsRewriteOperations.java:621)
	at org.eclipse.jdt.internal.corext.fix.NullAnnotationsRewriteOperations$Builder.createAddAnnotationOperation(NullAnnotationsRewriteOperations.java:507)
	at org.eclipse.jdt.internal.corext.fix.NullAnnotationsFix.createNullAnnotationInSignatureFix(NullAnnotationsFix.java:142)
	at org.eclipse.jdt.internal.ui.text.correction.NullAnnotationsCorrectionProcessor.addNullAnnotationInSignatureProposal(NullAnnotationsCorrectionProcessor.java:76)
	at org.eclipse.jdt.internal.ui.text.correction.NullAnnotationsCorrectionProcessor.addReturnAndArgumentTypeProposal(NullAnnotationsCorrectionProcessor.java:71)
	at org.eclipse.jdt.internal.ui.text.correction.QuickFixProcessor.process(QuickFixProcessor.java:826)
	at org.eclipse.jdt.internal.ui.text.correction.QuickFixProcessor.getCorrections(QuickFixProcessor.java:361)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor$SafeCorrectionCollector.safeRun(JavaCorrectionProcessor.java:381)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor$SafeCorrectionProcessorAccess.run(JavaCorrectionProcessor.java:341)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor$SafeCorrectionProcessorAccess.process(JavaCorrectionProcessor.java:336)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor.collectCorrections(JavaCorrectionProcessor.java:465)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.getJavaAnnotationFixes(ProblemHover.java:115)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.computeCompletionProposals(ProblemHover.java:89)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.<init>(ProblemHover.java:74)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover.createAnnotationInfo(ProblemHover.java:178)
	at org.eclipse.jdt.internal.ui.text.java.hover.AbstractAnnotationHover.getHoverInfo2(AbstractAnnotationHover.java:755)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)

```

```
eclipse.buildId=4.29.0.I20230815-1800
java.version=17.0.8
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product -data file:/C:/Users/jkubitz/egit-2023-08-16/ws/

```
@jjohnstn don't knw if this is a core or ui problem

**Comment by jukzi** [comment]
@stephan-herrmann looks like you wrote the code

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann looks like you wrote the code

Indeed so. :)

Thanks for the hint and for reproducing steps!

**Comment by stephan-herrmann** [comment]
> @jjohnstn don't know if this is a core or ui problem

The bug is in jdt.ui. Does github support moving an issue to a different component?

Obviously linking to the PR didn't work, here it is: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/724

**Comment by iloveeclipse** [comment]
> Does github support moving an issue to a different component?

Yes. See the box on the upper right side of the ticket: 
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/4b4ce816-f5c9-45b9-9c96-bbc53a1e8548)

**Comment by iloveeclipse** [comment]
If you click on it and select repo you will see following screen:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/e00ef1a5-d505-4d47-b735-a87daaa108de)
