### ISSUE TITLE
"Error checking whether PackageFragmentRoot is on module path!"

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1318]
Right after OOmphing workspace with https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md
many errors are logged like

```
!SESSION 2023-08-28 07:24:05.201 -----------------------------------------------
eclipse.buildId=4.29.0.I20230827-1800
java.version=17.0.8
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\jkubitz\platform-2023-08-28\ws

This is a continuation of log file C:\Users\jkubitz\platform-2023-08-28\ws\.metadata\.bak_0.log
Created Time: 2023-08-28 07:38:44.245

!ENTRY org.eclipse.jdt.core 4 1006 2023-08-28 07:38:44.246
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.core.runtime_3.29.0.v20230726-0617.jar is not on its project's build path

!ENTRY org.eclipse.jdt.core 4 4 2023-08-28 07:38:44.246
!MESSAGE Error checking whether PackageFragmentRoot is on module path!
!STACK 1
Java Model Exception: Error in Java Model (code 1006): C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.core.runtime_3.29.0.v20230726-0617.jar is not on its project's build path
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getRawClasspathEntry(PackageFragmentRoot.java:613)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeModuleFor(JavaSearchNameEnvironment.java:610)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.mapToClassPathLocation(JavaSearchNameEnvironment.java:300)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:213)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:187)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:95)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:166)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:117)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:680)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1294)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:527)
	at java.base/java.lang.Thread.run(Thread.java:833)
!SUBENTRY 1 org.eclipse.jdt.core 4 1006 2023-08-28 07:38:44.246
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.core.runtime_3.29.0.v20230726-0617.jar is not on its project's build path

!ENTRY org.eclipse.jdt.core 4 1006 2023-08-28 07:38:44.248
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.equinox.transforms.hook_1.3.300.v20230622-2056.jar is not on its project's build path

!ENTRY org.eclipse.jdt.core 4 4 2023-08-28 07:38:44.248
!MESSAGE Error checking whether PackageFragmentRoot is on module path!
!STACK 1
Java Model Exception: Error in Java Model (code 1006): C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.equinox.transforms.hook_1.3.300.v20230622-2056.jar is not on its project's build path
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getRawClasspathEntry(PackageFragmentRoot.java:613)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeModuleFor(JavaSearchNameEnvironment.java:610)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.mapToClassPathLocation(JavaSearchNameEnvironment.java:300)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:213)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:187)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:95)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:166)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:117)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:680)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1294)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:527)
	at java.base/java.lang.Thread.run(Thread.java:833)
!SUBENTRY 1 org.eclipse.jdt.core 4 1006 2023-08-28 07:38:44.248
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.equinox.transforms.hook_1.3.300.v20230622-2056.jar is not on its project's build path

!ENTRY org.eclipse.jdt.core 4 1006 2023-08-28 07:38:44.249
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.jface.text_3.24.100.v20230727-0604.jar is not on its project's build path

!ENTRY org.eclipse.jdt.core 4 4 2023-08-28 07:38:44.250
!MESSAGE Error checking whether PackageFragmentRoot is on module path!
!STACK 1
Java Model Exception: Error in Java Model (code 1006): C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.jface.text_3.24.100.v20230727-0604.jar is not on its project's build path
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getRawClasspathEntry(PackageFragmentRoot.java:613)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeModuleFor(JavaSearchNameEnvironment.java:610)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.mapToClassPathLocation(JavaSearchNameEnvironment.java:300)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:213)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:187)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:95)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:166)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:117)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:680)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1294)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:527)
	at java.base/java.lang.Thread.run(Thread.java:833)
!SUBENTRY 1 org.eclipse.jdt.core 4 1006 2023-08-28 07:38:44.250
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.jface.text_3.24.100.v20230727-0604.jar is not on its project's build path
```
...
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/bd8f7a2f-e990-498e-b4ff-313a9a16bd17)

**Comment by jukzi** [comment]
@trancexpress @iloveeclipse the stacktrace points to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/746

I don't know what the error is trying to tell me.

**Comment by jukzi** [comment]
those files are from target platform:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/dc8decbf-3d43-4081-922d-0feb06edcaad)

**Comment by jukzi** [comment]
did not happen again. not planned to fix
