### ISSUE TITLE
Test failure - testCreateResourceIncludedPackage

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1333]
testCreateResourceIncludedPackage

```
nexpected deltas. ----------- Expected ------------ P[*]: {CHILDREN}\n src[*]: {CHILDREN}\n p[+]: {} ------------ but was ------------ P[*]: {CHILDREN | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n p[+]: {}\n ResourceDelta(/P/.classpath)[*] --------- Difference is ---------- expected:<P[*]: {CHILDREN[}\n src[*]: {CHILDREN}\n p[+]: {}]> but was:<P[*]: {CHILDREN[ | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n p[+]: {}\n ResourceDelta(/P/.classpath)[*]]>
```

https://download.eclipse.org/eclipse/downloads/drops4/I20230830-2200/testresults/html/org.eclipse.jdt.core.tests.model_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

```
junit.framework.ComparisonFailure: Unexpected deltas.
----------- Expected ------------
P[*]: {CHILDREN}\n
src[*]: {CHILDREN}\n
p[+]: {}
------------ but was ------------
P[*]: {CHILDREN | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n
src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n
p[+]: {}\n
ResourceDelta(/P/.classpath)[*]
--------- Difference is ----------
expected:<P[*]: {CHILDREN[}\n
src[*]: {CHILDREN}\n
p[+]: {}]> but was:<P[*]: {CHILDREN[ | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n
src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n
p[+]: {}\n
ResourceDelta(/P/.classpath)[*]]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertDeltas(AbstractJavaModelTests.java:1416)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertDeltas(AbstractJavaModelTests.java:1406)
at org.eclipse.jdt.core.tests.model.InclusionPatternsTests.testCreateResourceIncludedPackage(InclusionPatternsTests.java:328)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:983)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
```

**Comment by iloveeclipse** [comment]
Looks like testCreateResourceIncludedPackage and testCreateResourceIncludedPackage**2** are failing sporadically, 


**testCreateResourceIncludedPackage2**
* https://download.eclipse.org/eclipse/downloads/drops4/I20231017-1140/testresults/html/org.eclipse.jdt.core.tests.model_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
* https://download.eclipse.org/eclipse/downloads/drops4/I20231018-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
```
Unexpected deltas. ----------- Expected ------------ P[*]: {CHILDREN}\n src[*]: {CHILDREN | CONTENT}\n p1.p2.p3[+]: {}\n ResourceDelta(/P/src/p1)[*] ------------ but was ------------ P[*]: {CHILDREN}\n src[*]: {CHILDREN | CONTENT}\n p1.p2.p3[+]: {}\n ResourceDelta(/P/src/p1)[+] ---------------------- ---------- expected:<...rceDelta(/P/src/p1)[[*]]> but was:<...rceDelta(/P/src/p1)[[+]]>

junit.framework.ComparisonFailure: Unexpected deltas.
----------- Expected ------------
P[*]: {CHILDREN}\n
src[*]: {CHILDREN | CONTENT}\n
p1.p2.p3[+]: {}\n
ResourceDelta(/P/src/p1)[*]
------------ but was ------------
P[*]: {CHILDREN}\n
src[*]: {CHILDREN | CONTENT}\n
p1.p2.p3[+]: {}\n
ResourceDelta(/P/src/p1)[+]
---------------------- ----------
expected:<...rceDelta(/P/src/p1)[[*]]> but was:<...rceDelta(/P/src/p1)[[+]]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertDeltas(AbstractJavaModelTests.java:1444)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertDeltas(AbstractJavaModelTests.java:1434)
at org.eclipse.jdt.core.tests.model.InclusionPatternsTests.testCreateResourceIncludedPackage2(InclusionPatternsTests.java:358)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:975)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:98)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:86)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:95)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**testCreateResourceIncludedPackage**

* https://download.eclipse.org/eclipse/downloads/drops4/I20231018-0110/testresults/html/org.eclipse.jdt.core.tests.model_ep430I-unit-win32-java17_win32.win32.x86_64_17.html
* https://download.eclipse.org/eclipse/downloads/drops4/I20231016-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
```
Unexpected deltas. ----------- Expected ------------ P[*]: {CHILDREN}\n src[*]: {CHILDREN}\n p[+]: {} ------------ but was ------------ P[*]: {CHILDREN | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n p[+]: {}\n ResourceDelta(/P/.classpath)[*] ---------------------- ---------- expected:<P[*]: {CHILDREN[}\n src[*]: {CHILDREN}\n p[+]: {}]> but was:<P[*]: {CHILDREN[ | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n p[+]: {}\n ResourceDelta(/P/.classpath)[*]]>

junit.framework.ComparisonFailure: Unexpected deltas.
----------- Expected ------------
P[*]: {CHILDREN}\n
src[*]: {CHILDREN}\n
p[+]: {}
------------ but was ------------
P[*]: {CHILDREN | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n
src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n
p[+]: {}\n
ResourceDelta(/P/.classpath)[*]
---------------------- ----------
expected:<P[*]: {CHILDREN[}\n
src[*]: {CHILDREN}\n
p[+]: {}]> but was:<P[*]: {CHILDREN[ | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}\n
src[*]: {CHILDREN | ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}\n
p[+]: {}\n
ResourceDelta(/P/.classpath)[*]]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertDeltas(AbstractJavaModelTests.java:1444)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertDeltas(AbstractJavaModelTests.java:1434)
at org.eclipse.jdt.core.tests.model.InclusionPatternsTests.testCreateResourceIncludedPackage(InclusionPatternsTests.java:328)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:975)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:98)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:86)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:95)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by jukzi** [comment]
i can reproduce locally [windows] that testCreateIncludedPackage() is failing randomly

**Comment by jukzi** [comment]
The test is designed to print error details to stdErr. In case of failing it logs for example async event **"Worker-3: Refreshing workspace"** - i.e. that async refresh should be avoided during test:

```
java.lang.Throwable: Refreshing workspace [Worker-3: Refreshing workspace] Caller of IElementChangedListener#elementChanged with delta Java Model[*]: {CHILDREN}
	P[*]: {CHILDREN | CONTENT | RAW CLASSPATH CHANGED | RESOLVED CLASSPATH CHANGED}
		src[*]: {ADDED TO CLASSPATH | REMOVED FROM CLASSPATH}
		ResourceDelta(/P/.classpath)[*]
	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests$DeltaListener.elementChanged(AbstractJavaModelTests.java:385)
	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1760)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1748)
	at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1581)
	at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1557)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyAndFire(DeltaProcessor.java:2278)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2168)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:503)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:458)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1586)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:50)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```
