### ISSUE TITLE
UnsupportedOperationException: remove in DetectVMInstallationsJob

### ISSUE THREAD

**Issue by guw** [eclipse-jdt/eclipse.jdt.core#1337]
I noticed the following in the log of JDTLS. Not sure if this is caused by JDTLS or a problem in JDT. However, the collection trying to be modified does not support `removeIf`. But the code changed. Perhaps it's no longer a problem.

```
!ENTRY org.eclipse.core.jobs 4 2 2023-09-01 14:10:08.170
!MESSAGE An internal error occurred during: "Look up for installed JVMs".
!STACK 0
java.lang.UnsupportedOperationException: remove
	at java.base/java.util.Iterator.remove(Unknown Source)
	at java.base/java.util.Collection.removeIf(Unknown Source)
	at org.eclipse.jdt.internal.launching.DetectVMInstallationsJob.run(DetectVMInstallationsJob.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by jjohnstn** [comment]
This was fixed by: https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/292
