### ISSUE TITLE
[21] Record type inference fails when 'var' and <> mixed

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1361]
The following code is rejected by the ECJ:

```
record Record<T>(T a) {}
public class X {
	static void test(Object m) {
		if (m instanceof Record(var x)) {
			var wrapped = new Record<>(x);
			Record<Object> r = wrapped; // Type mismatch: cannot convert from Record<capture#2-of ?> to Record<Object>
		}
	}
}
```
Of course, if I use explicit types in either of the 'var', the code compiles. Javac is able to infer the type correctly.

**Comment by mpalat** [comment]
@jarthana After reading (and experimenting with) specs and pointers from @stephan-herrmann  in the PR #4719 , the conclusion is that ECJ is correct in finding the type of v as "Record\<capture#2-of ?\>". This is not assignable to "Record\<Object\>".   This should be a bug in javac implementation.
@stephan-herrmann : Please chime in

**Comment by stephan-herrmann** [comment]
> ECJ is correct in finding the type of v as "Record<capture#2-of ?>". This is not assignable to "Record"

Did you mean to write `Record<Object>` rather than `Record`? (pitfalls of markdown editing?) 

Please also clarify: do we speak about subtyping or about assignability? The latter is more lenient than the former.

**Comment by stephan-herrmann** [comment]
I extended the program with
* some more details to make `Record` and `X` more interesting
* an unchecked cast to make it compilable
* a main program that shows that the program now has a type error

```java
import java.util.function.Consumer;

record Record<T>(Consumer<T> cons) {
	void m(T t) {
		cons.accept(t);
	}
}
public class X {
	void n() {
		System.out.println("n");
	}
	static void test(Object o) {
		if (o instanceof Record(var x)) {
			var v = new Record<>(x);
			Record<Object> r = (Record<Object>) v;
			r.m(new Object());
		}
	}
	public static void main(String[] args) {
		Record<? extends X> rs = new Record<>(s -> s.n()); 
		test(rs);
	}
}
```

Result:
```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Object cannot be cast to class X (java.lang.Object is in module java.base of loader 'bootstrap'; X is in unnamed module of loader 'app')
	at Record.m(X.java:5)
	at X.test(X.java:16)
	at X.main(X.java:21)
```

If, btw, I remove the case again, also javac detects the bug:
```
X.java:15: error: incompatible types: Record<CAP#1> cannot be converted to Record<Object>
                        Record<Object> r = v;
                                           ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ?
1 error
```

Ergo, I and both compilers agree :)

**Comment by mpalat** [comment]
> > ECJ is correct in finding the type of v as "Record<capture#2-of ?>". This is not assignable to "Record"
> 
> Did you mean to write `Record<Object>` rather than `Record`? (pitfalls of markdown editing?)

Oops..Markdown swallowed my "<". Thanks for flagging it !
> 
> Please also clarify: do we speak about subtyping or about assignability? The latter is more lenient than the former.

Thanks @stephan-herrmann for the hint - right, "Record\<capture#2-of ?\>" is not a subtype of "Record\<Object\>", given that generics is invariant despite α \<: Object. And hence not assignable.
