### ISSUE TITLE
Enum.values() throws NullPointerException if switch statement exists

### ISSUE THREAD

**Issue by loetifuss** [eclipse-jdt/eclipse.jdt.core#1450]
Following class will compile but throws an error when calling the "values()" method on the enum class.
With source level 1.8 this works but source level > 1.8 will throw

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local0>" is null
	at test_bug/test.FooEnum.values(FooEnum.java:1)
	at test_bug/test.Foo.$SWITCH_TABLE$test$FooEnum(FooEnum.java:15)
	at test_bug/test.Foo.<clinit>(FooEnum.java:15)
```

```
public enum FooEnum implements Foo {

	A, B;

	public static void main(String[] args) {
		FooEnum.values();
		System.out.println("Works");
	}
}

interface Foo {

	// random field breaks byte code
	String RANDOM_STRING = "bar";

	// unused switch
	default String breaksCompilation(FooEnum enumValue) {
		switch (enumValue) {
			case A:
				return "A";
			default :
				return "";
		}
	}
}
```
The error can only be reproduced as long as interface "Foo" contains a switch statement AND a field. If "RANDOM_STRING" or the switch statement is removed the error will disappear.

Tested with ECJ version 3.31

**Comment by iloveeclipse** [comment]
> Tested with ECJ version 3.31

Current master version is 3.36, released 3.35. Can you please test with latest you can use?
See for example ecj from https://download.eclipse.org/eclipse/downloads/drops4/S-4.30M1-202309271800/

**Comment by loetifuss** [comment]
> > Tested with ECJ version 3.31
> 
> Current master version is 3.36, released 3.35. Can you please test with latest you can use? See for example ecj from https://download.eclipse.org/eclipse/downloads/drops4/S-4.30M1-202309271800/

Tested with latest release 3.35, same error. With "javac" the code compiles and executes fine.

**Comment by iloveeclipse** [comment]
Thanks. I've checked master, same error.

**Comment by stephan-herrmann** [comment]
For a brief period of time in the past this worked:
```
$ java -jar ecj-4.7.2.jar -proc:none -9 FooEnum.java
$ java FooEnum 
Works
$ java -jar ecj-4.7.3.jar -proc:none -9 FooEnum.java
$ java FooEnum 
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local0>" is null
        at FooEnum.values(FooEnum.java:1)
        at Foo.$SWITCH_TABLE$FooEnum(FooEnum.java:11)
        at Foo.<clinit>(FooEnum.java:11)
$ java -jar ecj-4.7.3.jar -proc:none -version
Eclipse Compiler for Java(TM) v20180215-0725, 3.13.101, Copyright IBM Corp 2000, 2015. All rights reserved.
```

Ergo: a regression in 4.7.3 aka 3.13.101.
OK, the relevant logic was thoroughly rewritten in https://bugs.eclipse.org/bugs/show_bug.cgi?id=526911

**Comment by srikanth-sankaran** [comment]
See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2264
