### ISSUE TITLE
[21][pattern switch] IndexOutOfBoundsException regression against preview 4

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#1466]
Relates to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/587.

This was working fine in ECJ 3.35.0 (Java 20), but leads to problems in 3.36.0-SNAPSHOT (Java 21)
```java
public class SwitchPatternPreview4OK {
  public static void main(String[] args) {
    constantLabelMustAppearBeforePatternInteger(-1);
    constantLabelMustAppearBeforePatternInteger(0);
    constantLabelMustAppearBeforePatternInteger(42);
    constantLabelMustAppearBeforePatternInteger(-99);
    constantLabelMustAppearBeforePatternInteger(Integer.valueOf(123));
    constantLabelMustAppearBeforePatternInteger(null);
  }

  static String constantLabelMustAppearBeforePatternInteger(Integer i) {
    switch (i) {
      case null -> System.out.println("value unavailable: " + i);
      case -1, 1 -> System.out.println("absolute value 1: " + i);
      case Integer value when value > 0 -> System.out.println("positive integer: " + i);
      default -> System.out.println("other integer: " + i);
    }
    return i == null ? "null" : i.toString();
  }
}
```

### JDK 20 and ECJ 3.35.0

```text
XXX> java -jar ecj-3.35.0.jar -20 --enable-preview SwitchPatternPreview4OK.java
----------
1. WARNING in XXX\SwitchPatternPreview4OK.java (at line 13)
        case null -> System.out.println("value unavailable: " + i);
             ^^^^
You are using a preview language feature that may or may not be supported in a future release
----------
2. WARNING in XXX\SwitchPatternPreview4OK.java (at line 15)
        case Integer value when value > 0 -> System.out.println("positive integer: " + i);
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You are using a preview language feature that may or may not be supported in a future release
----------
2 problems (2 warnings)

XXX> "c:\Program Files\Java\jdk-20\bin\java.exe" --enable-preview SwitchPatternPreview4OK
absolute value 1: -1
other integer: 0
positive integer: 42
other integer: -99
positive integer: 123
value unavailable: null
```

### JDK 21 and Javac

```text
XXX> javac SwitchPatternPreview4OK.java

XXX> java SwitchPatternPreview4OK
absolute value 1: -1
other integer: 0
positive integer: 42
other integer: -99
positive integer: 123
value unavailable: null
```

### JDK 21 and ECJ 3.36.0-SNAPSHOT

```text
XXX> java -jar ecj-3.36.0-20231005.001952-71.jar -21 SwitchPatternPreview4OK.java

XXX> java SwitchPatternPreview4OK
absolute value 1: -1
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at SwitchPatternPreview4OK.constantLabelMustAppearBeforePatternInteger(SwitchPatternPreview4OK.java:12)
        at SwitchPatternPreview4OK.main(SwitchPatternPreview4OK.java:4)
```

You see, I used a snapshot from today. Please fix the problem. Thank you.

**Comment by kriegaex** [comment]
Note to myself: Reactivate code commented out it in
  * `features1921/java21/SwitchPatternPreview3Aspect.aj`,
  * `features1921/java21/SwitchPatternPreview4OK.java`

after this has been fixed and merged the AspectJ fork of JDT Core.

**Comment by kriegaex** [comment]
Sorry, this does not seem to be fixed. The `switch` seems to enter the wrong branches, The test output should be, as quoted above in the Javac-compiled output:

```text
absolute value 1: -1
other integer: 0
positive integer: 42
other integer: -99
positive integer: 123
value unavailable: null
```

But actually, it is:

```text
absolute value 1: -1
positive integer: 0
positive integer: 42
positive integer: -99
positive integer: 123
value unavailable: null
```

Neither 0 nor -99 are positive integers.

Your test is even [asserting on the wrong values](https://github.com/mpalat/eclipse.jdt.core/blob/432509d81c5d73f5765d9f395dd10a93d4a515c3/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/SwitchPatternTest.java#L6961-L6966).

Please reopen.

**Comment by mpalat** [comment]
will take a look

**Comment by kriegaex** [comment]
The corresponding tests in AspectJ also work now. Thanks for fixing the fix. 😉
