### ISSUE TITLE
NPE in ASTRewriteFlattener as return value of GuardedPattern.getPattern() is null

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.core#1483]
```
package ppp;

public class ZZ {
	public void foo(Integer n) {
		
		switch (n) { //[1]
		case Integer x when x.equals(10) -> {
		}
		case Comparable<?> y -> {
		}
		}
		;
	}
}

```

In the above code, press Ctrl+1 at "switch" on line [1]. See Error Log view. NPE is logged. The same happens when we try to apply the proposed quick fix at [1] to convert the switch to if-else.

Here' the stacktrace:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.dom.Pattern.accept(org.eclipse.jdt.core.dom.ASTVisitor)" because the return value of "org.eclipse.jdt.core.dom.GuardedPattern.getPattern()" is null
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFlattener.visit(ASTRewriteFlattener.java:582)
	at org.eclipse.jdt.core.dom.GuardedPattern.accept0(GuardedPattern.java:139)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFlattener.visit(ASTRewriteFlattener.java:627)
	at org.eclipse.jdt.core.dom.InfixExpression.accept0(InfixExpression.java:353)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFlattener.visit(ASTRewriteFlattener.java:592)
	at org.eclipse.jdt.core.dom.IfStatement.accept0(IfStatement.java:178)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.getFormattedResult(ASTRewriteFormatter.java:178)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextInsert(ASTRewriteAnalyzer.java:1453)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:792)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:823)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteParagraphList(ASTRewriteAnalyzer.java:1253)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2263)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:307)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:296)
	at org.eclipse.jdt.ui.text.java.correction.ASTRewriteCorrectionProposalCore.addEdits(ASTRewriteCorrectionProposalCore.java:84)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.createTextChange(CUCorrectionProposalCore.java:188)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.createChange(CUCorrectionProposalCore.java:195)
	at org.eclipse.jdt.core.manipulation.ChangeCorrectionProposalCore.getChange(ChangeCorrectionProposalCore.java:152)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.getTextChange(CUCorrectionProposalCore.java:206)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.getAdditionalProposalInfo(CUCorrectionProposalCore.java:133)
	at org.eclipse.jdt.ui.text.java.correction.CUCorrectionProposal.getAdditionalProposalInfo(CUCorrectionProposal.java:193)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$2$1.run(AdditionalInfoController.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by subyssurendran666** [comment]
@subyssurendran666

**Comment by subyssurendran666** [comment]
I will work on this task.

**Comment by subyssurendran666** [comment]
@noopur2507 Since the suggestion from the Quick assist proposal, who will handle this ? JDT.Core or JDT.UI ?
Also the conditions in the **case** are not a valid one,  so what's your view on that.

**Comment by noopur2507** [comment]
`org.eclipse.jdt.core.dom.GuardedPattern.getPattern()` is returning null causing NPE. It needs to be checked if returning null by this API is valid, and if so, it needs to be handled at the caller sites. This issue will most likely be handled in JDT.Core.

The code may not be a valid code but it shouldn't result in NPE.

**Comment by subyssurendran666** [comment]
Thanks @noopur2507 for the detailed explanation? We will work accordingly.
