### ISSUE TITLE
 JRTUtil.getJrtSystem(...) permanently consumes a large amount of memory

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#1526]
If one calls `JRTUtil.getJrtSystem(...)` it consumes about 180MB of persistent memory.
Even worse, if one passes the release flag, it consumes another 180MB, so calling the method with multiple release options can easily exhaust the memory of the JVM.

I think the following should be investigated:

1. Check if techniques like _Memory-Mapped File_ could be used to access things instead of holding everything in memory.
2. Check if loading for another release data can be shared with the previously loaded one
3. Check if maybe a Soft or at least Weak References can be used to allow the JVM to clear out some of the data in question

This was discovered here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3885#note_1266412 but can easily affect the IDE as well.

**Comment by laeubi** [comment]
Another source of high memory usage seems

```
17:35:37  Exception in thread "Java indexing" java.lang.OutOfMemoryError: Java heap space
17:35:37  	at java.base/java.nio.file.Files.read(Files.java:3238)
17:35:37  	at java.base/java.nio.file.Files.readAllBytes(Files.java:3295)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JRTUtil.safeReadBytes(JRTUtil.java:323)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.lambda$1(JRTUtil.java:669)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$$Lambda$3646/0x00007f4c44c26000.apply(Unknown Source)
17:35:37  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.getFileBytes(JRTUtil.java:667)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.getClassfileContent(JRTUtil.java:648)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getClassfileContent(JRTUtil.java:268)
17:35:37  	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex$JrtIndexer.visitFile(AddJrtToIndex.java:143)
17:35:37  	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex$JrtTraverser.visitFile(AddJrtToIndex.java:1)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$2.visitFile(JRTUtil.java:781)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$2.visitFile(JRTUtil.java:1)
17:35:37  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
17:35:37  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(JRTUtil.java:750)
17:35:37  	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:244)
17:35:37  	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex.execute(AddJrtToIndex.java:275)
17:35:37  	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:543)
17:35:37  	at org.eclipse.jdt.internal.core.search.processing.JobManager$$Lambda$3594/0x00007f4c44c9e1d0.run(Unknown Source)
17:35:37  	at java.base/java.lang.Thread.run(Thread.java:840)
17:35:37  [INFO] API Analysis finished in 15 s.
```

**Comment by laeubi** [comment]
It seems a lot of space is retained by the classes cache:

![grafik](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1331477/ca8a7c98-9957-488b-b22f-9eb5b5ade5ab)

**Comment by iloveeclipse** [comment]
> would this potentially fix things like [eclipse-jdt/eclipse.jdt.debug#283](https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/283) ?

Most likely no, see [last comment](https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/283#issuecomment-1633867133) from Mickael.

**Comment by laeubi** [comment]
@rgrunber the easiest way to try is setting system properties for the process that goes OOM:

```
-Dorg.eclipse.jdt.disable_JRT_cache=true
-Dorg.eclipse.jdt.disable_CTSYM_cache=true
```

also it you can take a headump it would be good way to verify. I also asked in another context if indexing can be disabled but this seems not the case.

And of cause as always there is not only one thing in OOM and strange things can happen, so you most probably get an unlucky combination of JDT and Maven see:
- https://issues.apache.org/jira/projects/MNG/issues/MNG-7592

**Comment by rgrunber** [comment]
Thanks for the hints! Those 2 flags seem to be have a positive impact for my use case locally (running a bunch of project imports for some fairly dependency heavy maven projects under tycho-surefire), but not when run on a build machine, so I may need to keep looking :

**normal**
![quarkus-jdt-ext-tests2](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1417342/e916b9d4-95ac-48f3-8298-fc2f7959329e)

**-Dorg.eclipse.jdt.disable_JRT_cache=true -Dorg.eclipse.jdt.disable_CTSYM_cache=true**
![quarkus-jdt-ext-tests-caches-disabled2](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1417342/5392a95e-ee65-481d-9bff-e4b815313743)

**Comment by laeubi** [comment]
Then at least the change will have an impact, for your CI machine you probably need then use more RAM an/or configure maven to use more RAM (see for example https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3896)
