### ISSUE TITLE
Dozens of failures in DebugEvaluationTest

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1559]
This is happening with the latest build. Could be a transient one as I don't see them in my local setup. But then I run a windows where the failures are with Linux.

The failures are reported here: https://download.eclipse.org/eclipse/downloads/drops4/I20231105-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

And most of the reported error is like this:

```Value display string expected:<class A35> but was:<100>

junit.framework.AssertionFailedError: Value display string expected:<class A35> but was:<100>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.jdt.core.tests.eval.EvaluationTest.failNotEquals(EvaluationTest.java:469)
at org.eclipse.jdt.core.tests.eval.EvaluationTest.assertEquals(EvaluationTest.java:161)
at org.eclipse.jdt.core.tests.eval.EvaluationTest.evaluateWithExpectedDisplayString(EvaluationTest.java:242)
at org.eclipse.jdt.core.tests.eval.JDIStackFrame.getDebuggedThread(JDIStackFrame.java:119)
at org.eclipse.jdt.core.tests.eval.JDIStackFrame.<init>(JDIStackFrame.java:89)
at org.eclipse.jdt.core.tests.eval.JDIStackFrame.<init>(JDIStackFrame.java:69)
at org.eclipse.jdt.core.tests.eval.DebugEvaluationTest.test035(DebugEvaluationTest.java:1631)

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1071
