### ISSUE TITLE
[19] Class Cast exception with Record pattern example in editor

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.core#157]
public class RecordPattern2 {
	public static void printLowerRight(Rectangle r) {
			    int res = switch(r) {
			       case Rectangle(ColoredPoint(Point(int x, int y), Color c),
			                               ColoredPoint lr) r1  -> {
			        		yield 1;  
			        } 
			        default -> 0;
			    };System.out.println(res);

	}

	public static void main(String[] args) {
			    printLowerRight(new Rectangle(new ColoredPoint(new Point(15, 5), Color.BLUE), 
			        new ColoredPoint(new Point(30, 10), Color.RED)));
			  }
}
record Point(int x, int y) {
}

enum Color {
	RED, GREEN, BLUE
}

record ColoredPoint(Point p, Color c) {
}

record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) {
}

This gave this :
java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding cannot be cast to class org.eclipse.jdt.internal.compiler.lookup.ArrayBinding (org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding and org.eclipse.jdt.internal.compiler.lookup.ArrayBinding are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7ca08b44)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:544)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:282)
	at org.eclipse.jdt.internal.compiler.ast.TypePattern.resolveType(TypePattern.java:136)
	at org.eclipse.jdt.internal.compiler.ast.RecordPattern.resolveType(RecordPattern.java:137)
	at org.eclipse.jdt.internal.compiler.ast.Pattern.resolveType(Pattern.java:42)
	at org.eclipse.jdt.internal.compiler.ast.RecordPattern.collectPatternVariablesToScope(RecordPattern.java:58)
	at org.eclipse.jdt.internal.compiler.ast.CaseStatement.collectPatternVariablesToScope(CaseStatement.java:383)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.resolve(SwitchStatement.java:906)
	at org.eclipse.jdt.internal.compiler.ast.SwitchExpression.resolveTypeInternal(SwitchExpression.java:480)
	at org.eclipse.jdt.internal.compiler.ast.SwitchExpression.resolveType(SwitchExpression.java:459)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1503)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1628)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:905)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:833)

Blocks #85

**Comment by jarthana** [comment]
This only happens when the record and record pattern using that record are in two different CUs. The reason a record binding is being considered an array because of a silly error in _BinaryTypeBinding#components()_ that adds the _AreRecordComponentsComplete_ to _tagBits_ instead of _extendedTagBits_. Note, _AreRecordComponentsComplete_ and _IsArrayType_ use the same bit value and will cause trouble if they are stored in the same place.
