### ISSUE TITLE
ecj spams the console with irrelevant zip exceptions

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1578]
Caused by [this change](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/239/files#diff-c0b06f7f0bde6fd19dd40c4dfdb8cf81916f21156eae057b0d2f54865fa1f66f)  from #239:

When compiling on JRE 1.8, the compiler spits out tons of exceptions like this:
```
Failed to init Classpath for jar file /somepath/j2sdk/linux/1.8.0_111/jre/lib/fontconfig.SuSE.10.properties.src
java.util.zip.ZipException: zip END header not found
	at
java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at
java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at
java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at
java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at
java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at
org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
	at
org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
	at
org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3504)
	at
org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4750)
	at
org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
	at
org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(JDTCompiler.java:370)
```

It does so for every file in that `jre/lib` directory.

I admit, that the strategy to detect zip files is a bit crude, but it looks like no reliable positive specification of zip file names was available when that code was written.

Hence the `ZipException` is perfectly legal in this situation, and silently catching it with an `// ignore` comment was by full intention.

Can we please get rid of this particular console logging?

**Comment by laeubi** [comment]
Should one not better fix that a step before and look if the file has a zip magic header at all ?

**Comment by stephan-herrmann** [comment]
> Should one not better fix that a step before and look if the file has a zip magic header at all ?

If that can be done without performance impact (accessing the file twice?), be my guest! :)

Just the combination of expected exception and console logging is wrong, to be resolved one way or other.

**Comment by laeubi** [comment]
Maybe you can set a breakpoint in `ClasspathJar` constructor to see where this originates, but usually this is printed if a jar has a classpath manifest header that is invalid/not found so it is not that useless at all, so I assume it comes from `org.eclipse.jdt.internal.compiler.batch.ClasspathJar.fetchLinkedJars(ClasspathSectionProblemReporter)` where it already checked if it is an existing file.

The problem is that here "something" seems to reference resource files as class-path, so a cheap check might be to check if it is actually a file ending in jar and do further investigation if it is at least a zip file, not sure if reading two bytes from a file is assumed a large performance problem here.

**Comment by stephan-herrmann** [comment]
My link in the description already points to the exact code location in `FileSystem`. 

I think I saw the list of files collected in `Main.getLibraryFiles()`, where a preliminary check by file extension is already performed. That's the location that I commented above saying
> I admit, that the strategy to detect zip files is a bit crude, but it looks like no reliable positive specification of zip file names was available when that code was written.

**Comment by laeubi** [comment]
Hm... then I'm maybe on the wrong track here but it then seems a bit strange that this is reported as a module...

**Comment by stephan-herrmann** [comment]
> ... but it then seems a bit strange that this is reported as a module...

Who speaks of module?

**Comment by stephan-herrmann** [comment]
> Is it possible that the stacktrace is not from the latest ecj compiler?

Yes, line number may likely differ from HEAD.

**Comment by jukzi** [comment]
@iloveeclipse  i suggest to 
1. do not log stacktrace for ZipException - only log filename
2. be totally silent if the filename does not end with ".jar"

**Comment by iloveeclipse** [comment]
> When compiling on JRE 1.8, the compiler spits out tons of exceptions
> It does so for every file in that jre/lib directory

Stephan, could you please explain what do you mean by "compiling on JRE 1.8"? I believe we require Java 17 minimum in ecj? Do you mean *by specifying 1.8 JRE as dependency* maybe? How exactly do you specify that? Or are you running older ecj version on 1.8? In that case, updating to new ecj should fix the problem without any change, as 1.8 is not supported platform to run ecj on anymore.

> be totally silent if the filename does not end with ".jar"

I'm not a friend of hiding exceptions, and assuming only jar files are "valid" libraries is also not right thing to do, there are multiple file formats that can be used as "libraries".

> do not log stacktrace for ZipException - only log filename

I would be fine with that, assuming we produce error messages distinct enough to identify the exact place in compiler code that produces it.

**Comment by jukzi** [comment]
> I'm not a friend of hiding exceptions, and assuming only jar files are "valid" libraries is also not right thing to do, there are multiple file formats that can be used as "libraries".

May be it's more safe to assume that a "*.properties.src" file is not meant to contain class files? Then it could be excluded from logging.
@stephan-herrmann is it only that file name that makes a problem?

**Comment by laeubi** [comment]
I agree with @iloveeclipse that hiding the exception does not help much, Exceptions are .. exceptional and indicate there is a problem in the handling of classpathes, they key to solve this would be

1. latest ECJ so one can see where the exception exactly happens (code already recently changed/improved over time)
2. Give a reference to the JVM to one can check why this file is on the classpath and what it contains (maybe ECJ should indeed handle the file somehow instead of ignore it)

**Comment by stephan-herrmann** [comment]
Sorry for bogus line numbers and imprecise description of the problem.

Here's a simple reproducer using ecj-4.30RC1.jar:

```
$ echo "public class X {}" > X.java
$ java -jar ecj-4.30RC1.jar -1.8 -bootclasspath /home/java/jdk1.8.0/jre/lib/rt.jar -endorseddirs  /home/java/jdk1.8.0/jre/lib X.java
openjdk 20 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
Failed to init Classpath for jar file /home/java/jdk1.8.0/jre/lib/fontconfig.RedHat.5.properties.src
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1489)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1497)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1335)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1298)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
        at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
        at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3504)
        at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4750)
        at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
        at org.eclipse.jdt.internal.compiler.batch.Main.main(Main.java:1521)
Failed to init Classpath for jar file /home/java/jdk1.8.0/jre/lib/hijrah-config-umalqura.properties
java.util.zip.ZipException: zip END header not found
...
many more of those
...
```

In the original case I believe it was tycho adding either `-endorseddirs` or `-extdirs`. That perhaps was a result of using toolchains, but that shouldn't matter.

File extensions encountered: `.src`, `.properties`, `.bfc`, `.data`, `.dat`, `.txt`, `.ja`.

**Comment by stephan-herrmann** [comment]
> Exceptions are .. exceptional and indicate there is a problem in the handling of classpathes

These exceptions are expected. Catching those is necessary until someone comes up with a reliable replacement that detects zipfiles without trying to access them. At least for `-endorseddirs` and `-extdirs` there is no use in logging those exceptions, pretty please.

**Comment by laeubi** [comment]
>> Exceptions are .. exceptional and indicate there is a problem in the handling of classpathes
> At least for -endorseddirs and -extdirs there is no use in logging those exceptions, pretty please.

I'm not sure if it is feasible to assume that these directories contain anything that is **not** named `.jar` but is a jar for the classpath ... so I think the simplest solution here would be to filter all files not ending with `.jar` this also would prevent to access these files at all.

If one things that not enough, one could have a "blacklist" for `-endorseddirs` and `-extdirs` that e.g. do not try the knwon not jar extensions you listed above...

**Comment by stephan-herrmann** [comment]
> I'm not sure if it is feasible to assume ...

The compiler should generally not "assume" anything other than what's specified in JLS. Unfortunately I'm not aware of a specification that tells us that all archives of .class files on the classpath must end with `.jar`.

Other than that it's impossible to know if any users out in the huge Java universe rely on the fact that ecj is able to read classes from an oddly named archive. Even if such use cases doesn't make sense to you and me, I don't want to take responsibility for causing potential breakage out there for little benefit on our end.

**Comment by laeubi** [comment]
Of course not all jars must end with jar, that is correct,If I look for example at `javac` option for `extdirs` it says:
> Each JAR file in the specified directories is searched for class files. All JAR files found become part of the class path.

So it seems mandatory to check each file in the directory if it is a jar file before passing it further down as classpath entry to any internal code in the compiler.

Of course not all jars must end with jar, that is correct, so either the part that parses the `-endorseddirs` and `-extdirs` need to enhanced or one might think about making the classpath code more "smart" e.g. lets assume I'm that "power user" and have a jar that is corrupted and I name it `my.lib` now I put it on the classpath and get no message at all but of course something does not work, so I would want the compiler to tell me something is wrong with it (that's what the exception currently offers, a way to tell: Hey there _might_ be something wrong but I don't know for sure) because otherwise I might be frustrated and think its a bug in JDT.

If we now want to extend this to that *any* file (not only jars) can be passed as classpath and this is assumed to be valid, then the I see the following options:

1.  **assume the best** - try reading as a jar and if that fails read the first bytes of the file and if they indicate a zip/jar header report it as an error, otherwise ignore the exception
2. **assume the worst** - never try to read it as jar if we not before have read the first bytes and they indicate a zip/jar header

but _always_ assume (and you said compiler should never assume anything) that any exception means we can ignore that and not report anything to the user just to silence such cases where non jar/class files are passed as classpath seems wrong.

**Comment by jukzi** [comment]
Did anybody try how javac treats JARs that have non normal file names - i.e. not named ".zip" or ".jar"?

**Comment by laeubi** [comment]
> Did anybody try how javac treats JARs that have non normal file names - i.e. not named ".zip" or ".jar"?

As mentioned above javac documents on the extdir:

>> **Each JAR file** in the specified directories is searched for class files. All JAR files found become part of the class path

And [Jar Specification says](https://docs.oracle.com/en/java/javase/20/docs/specs/jar/jar.html)

>> A JAR file is essentially a zip file that contains an optional META-INF directory. [...]. There is no restriction on the name of a JAR file, **it can be any legal file name** on a particular platform.

So if one combines those two it can be any name but must be a zip and maybe contains a manifest...

**Comment by jukzi** [comment]
`search for jar/zip only` [1]

https://github.com/openjdk/jdk/blob/f2a4ed680b54e644ae83f8898a4e66a0c45c9cf4/test/langtools/tools/javac/Paths/MineField.java#L49

`javac -endorseddirs "C:\Program Files\Java\jdk1.8.0_202\jre\lib" -bootclasspath c:\ -source 8 -target 8 A.java`
does not output any warning, see also BatchCompilerTest.test017b

**Comment by wilx** [comment]
> > Exceptions are .. exceptional and indicate there is a problem in the handling of classpathes
> 
> These exceptions are expected. Catching those is necessary until someone comes up with a reliable replacement that detects zipfiles without trying to access them. At least for `-endorseddirs` and `-extdirs` there is no use in logging those exceptions, pretty please.

Can't we use the magic numbers? <https://en.wikipedia.org/wiki/List_of_file_signatures> All we need is first 4 bytes.

**Comment by mmosconi1** [comment]
Actually in a Tycho build (as of 2025-03 / Tycho 4.0.12) the files in question are explicitly given to ecj via the "-bootclasspath" argument:
```
[DEBUG] JDT compiler args: [...
 -bootclasspath,
 C:\install\Java\jdk_1.8\jre\lib\accessibility.properties;C:\install\Java\jdk_1.8\jre\lib\calendars.properties;C:\install\Java\jdk_1.8\jre\lib\charsets.jar;C:\install\Java\jdk_1.8\jre\lib\classlist;C:\install\Java\jdk_1.8\jre\lib\content-types.properties;C:\install\Java\jdk_1.8\jre\lib\currency.data;C:\install\Java\jdk_1.8\jre\lib\ext\access-bridge-64.jar;C:\install\Java\jdk_1.8\jre\lib\ext\cldrdata.jar;C:\install\Java\jdk_1.8\jre\lib\ext\dnsns.jar;C:\install\Java\jdk_1.8\jre\lib\ext\jaccess.jar;C:\install\Java\jdk_1.8\jre\lib\ext\localedata.jar;C:\install\Java\jdk_1.8\jre\lib\ext\meta-index;C:\install\Java\jdk_1.8\jre\lib\ext\nashorn.jar;C:\install\Java\jdk_1.8\jre\lib\ext\sunec.jar;C:\install\Java\jdk_1.8\jre\lib\ext\sunjce_provider.jar;C:\install\Java\jdk_1.8\jre\lib\ext\sunmscapi.jar;C:\install\Java\jdk_1.8\jre\lib\ext\sunpkcs11.jar;C:\install\Java\jdk_1.8\jre\lib\ext\zipfs.jar;C:\install\Java\jdk_1.8\jre\lib\flavormap.properties;C:\install\Java\jdk_1.8\jre\lib\fontconfig.bfc;C:\install\Java\jdk_1.8\jre\lib\fontconfig.properties.src;C:\install\Java\jdk_1.8\jre\lib\hijrah-config-umalqura.properties;C:\install\Java\jdk_1.8\jre\lib\jce.jar;C:\install\Java\jdk_1.8\jre\lib\jfr.jar;C:\install\Java\jdk_1.8\jre\lib\jsse.jar;C:\install\Java\jdk_1.8\jre\lib\jvm.hprof.txt;C:\install\Java\jdk_1.8\jre\lib\logging.properties;C:\install\Java\jdk_1.8\jre\lib\management-agent.jar;C:\install\Java\jdk_1.8\jre\lib\meta-index;C:\install\Java\jdk_1.8\jre\lib\net.properties;C:\install\Java\jdk_1.8\jre\lib\psfont.properties.ja;C:\install\Java\jdk_1.8\jre\lib\psfontj2d.properties;C:\install\Java\jdk_1.8\jre\lib\resources.jar;C:\install\Java\jdk_1.8\jre\lib\rt.jar;C:\install\Java\jdk_1.8\jre\lib\sound.properties;C:\install\Java\jdk_1.8\jre\lib\tzdb.dat;C:\install\Java\jdk_1.8\jre\lib\tzmappings,
...]
```
I don't know who constructs this list - Tycho? Maybe it should already be filtered for "relevant" files there?
Independently, I also think ecj should simply stop logging this with a stack trace.

**Comment by demonfiddler** [comment]
I've been hitting *intermittent* problems with this for two years in VS Code with the Microsoft Extension Pack for Java, which includes 'Language support for Java ™ for Visual Studio Code' and 'Gradle for Java' extensions, one or both of which evidently use various Eclipse JDT components under the hood. It seems that this problem could potentially manifest in any Gradle or Maven project that has a POM-type dependency anywhere in its class-path.

This is an absolute show-stopper, and has literally wasted many days of my time trying to work around it, and goodness only knows how many people are impacted by this. I'm staggered that getting on for three years later it remains unfixed! As an Eclipse plug-in developer of many years standing myself, I can't see what's wrong with the solution proposed several times in this thread: if a class-path entry starts with the magic ZIP file signature bytes 50 4B 03 04, attempt to read it as a ZIP file and log any errors, otherwise silently ignore it. Responsibility for processing POM files and adding any libraries referenced therefrom to the resolved class-path lies elsewhere in the Maven/Gradle integrations.

Please consider resolving this issue as a matter of urgency. Thanks!

**Comment by stephan-herrmann** [comment]
Here's a proposal that shouldn't impact normal use too much and still helps to detect some unexpected situations:
* no additional checks up-front, just try to open the jar/zip
* catch ZipException, when caught check:
  * if file name is (ignoring case)  .jar or .zip log the error
  * otherwise if the file starts with zip magic numbers log the error
  * otherwise keep quiet as there is no indication that this file was intended for supplying .class files.

Here the magic number scan would still penalize all those files that currently trigger the exception. If that's too much, we could probably still omit that step.

**Comment by wilx** [comment]
What about adding an opt-in switch for us to use like this https://github.com/eclipse-jdt/eclipse.jdt.core/pull/5185?

**Comment by stephan-herrmann** [comment]
> What about adding an opt-in switch for us to use like this [#5185](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/5185)?

What is the expected benefit in comparison to [my proposal](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1578#issuecomment-4927999373)?

Ideally, *everybody* should see fewer exceptions logged, no?

**Comment by wilx** [comment]
The reason for making it opt-in is that the discussion has two competing use cases:

1. For -extdirs / -endorseddirs / Tycho-generated Java 8 runtime lists, these exceptions are expected noise and should disappear.
2. For an explicit classpath entry, silently ignoring a non-ZIP file can hide a real configuration problem. That concern came up earlier: if a build accidentally puts something like a POM, text file, or corrupted oddly named archive on the classpath, some users expect ECJ to report that something is wrong.

Your proposal improves the default for everybody, but it still changes default diagnostics: non-.jar/.zip files without ZIP magic become quiet even when explicitly supplied. The opt-in switch lets affected build integrations choose that behavior without taking diagnostics away from users who want ECJ to complain about suspicious classpath entries.

**Comment by stephan-herrmann** [comment]
I'm still striving for a solution without an additional switch, because not everybody annoyed by the exception logging will have the time and energy to discover that option.

> That concern came up earlier: if a build accidentally puts something like a POM, text file, or corrupted oddly named archive on the classpath, some users expect ECJ to report that something is wrong.

In that branch of discussion we already have this tentative agreement from above:

>> @jukzi:
>>  do not log stacktrace for ZipException - only log filename
>
> @iloveeclipse:
> I would be fine with that, assuming we produce error messages distinct enough to identify the exact place in compiler code that produces it.

If we replace exception stacktraces with simple, useful messages, that might be all that's needed? E.g.:
```
File on classpath is not a valid jar file: /com/foo/pom.xml
```
In the original situation this would (on my system) amount to 25 lines of output instead of 404 lines. I think 25 lines are tolerable.

As a bonus feature we'd try to print which parameter pulled in the file (e.g, -classpath vs. -endorseddirs).

**Comment by demonfiddler** [comment]
@stephan-herrmann, I like your [counter-proposal](#issuecomment-4927999373), as it defers the cost of reading the four magic bytes to the exception handler.

I think it's worth pointing out that I'm getting *actual build failures* in VS Code (as distinct from pure noise in logs) on account of [JDT code attempting to read POMs as ZIPs](/redhat-developer/vscode-java/issues/3555), the corresponding JDT issue being variously identified as [#1274](/eclipse-jdt/eclipse.jdt.core/issues/1274) (now closed as 'not planned') and this one. It looked to me that the JDT exception handler code responsible for logging stack traces was also wrapping and re-throwing the exception, which presumably could lead to the kind of build failure I'm seeing from calling code in the VS Code extension.

**Comment by stephan-herrmann** [comment]
Interested parties: please see my minimal fix in #5189 

In particular:
> ... I'm getting actual build failures ...

In HEAD those ZipExceptions never mark compilation as failed. So how are tools influenced by such printout?

See also my note on different err channels in  #5189.

**Comment by demonfiddler** [comment]
@stephan-herrmann, to your question:
> In HEAD those ZipExceptions never mark compilation as failed. So how are tools influenced by such printout?

I honestly don't know and unfortunately right now I'm too preoccupied with other concerns to do a deep dive on this one. Sorry I can't be more helpful.

**Comment by stephan-herrmann** [comment]
From the PR:
> In order to make this testable, I also redirect the printout via Main.err (since plain System.err.println() almost never is a good idea to begin with).
> 
> This comes with the risk, that some build tools will only now begin to "see" these messages, and ecj cannot know, how those tools will interpret this (perhaps this will cause them to mark a compilation as failed).

As I have just merged those changes, interested parties should then test how this surfaces in builds of their build tool of choice. You might use the next nightly, or wait for M2 (due next week).
