### ISSUE TITLE
Too many compiler regression tests on Java 21 SDK build

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1605]
Compiler regression tests run very long & generate HUGE test results (~20MB html produced from 26 MB xml) that some browser fail to show (e.g. Chrome on Linux just crashes, Chrome on Android freezes), and even Jenkins instances (if not equipped with enough memory) fail to complete SDK builds as happened today.

https://ci.eclipse.org/releng/job/AutomatedTests/job/ep430I-unit-cen64-gtk3-java21/101/
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep430I-unit-cen64-gtk3-java21/100/

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.FileInputStream.close(FileInputStream.java:373)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.close(XMLEntityManager.java:3144)
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.close(UTF8Reader.java:675)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.closeReaders(XMLEntityManager.java:1452)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.cleanup(XML11Configuration.java:803)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:844)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:186)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:390)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:320)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:262)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:248)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:226)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:179)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:180)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 896054cf-6969-47c6-93a1-0c8bb7d585d3
Caused: java.io.IOException: Remote call on JNLP4-connect connection from 10.40.62.175/10.40.62.175:55628 failed
```

This issue is not a new one, it appeared few times in different variations since we run one SDK build on Java 21, I just had no time to check that in detail. It is not directly Java 21 related, it seem to be the problem of **ever increasing** test matrix that we build for different JLS levels, from 1.3 JSL to latest supported Java 21. The compiler tests run parameterized for every JLS, and that means on Java 21 build they have to test more. However, this "more" is a bit too much, so I wonder if the test matrix is somehow broken.

Here is the difference in test number/test time:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/7e4b1f95-49b4-45a1-9e47-c44af453e708)

Looking into details
* https://download.eclipse.org/eclipse/downloads/drops4/I20231114-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
* https://download.eclipse.org/eclipse/downloads/drops4/I20231114-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep430I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Notice that compiler regression tests number **explodes** - it increases from **43362** to **181583**!
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/3d2f90a5-7cc5-4834-bd37-e970d26eb525)

This doesn't sound right, it is **4 times** more tests! 
Looking into xml files I see that for example `testNullCase` is executed in Java 17 build with JLS 1.8, 16, 17 (4 times), and in Java 21 build it is executed **19 times** starting with 1.4 up to 21. Similar with `test427728a` - 4 times on Java 17, **17 times** on Java 21 (starting now with 1.5 upwards) etc.

Note: on Jenkins builds (started on github PR's), we run with **1.4,1.8,17,19,21** JLS.

I've found an old bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=563458 and looking into commit bfac82b5863b9e9d73291c8000780642ba0b0746 and current code I see that we most likely missed to update that after moving tests to Java 21:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/1222d1baedff28bf78f417a8d459807de3a1dfd0/org.eclipse.jdt.core.tests.compiler/test.xml#L60

So I would propose to change 
- `compliance.jre.17` from `1.8,11,16,17` to `1.3,1.8,11,17` (adding 1.3 and omitting 16). (will run on all platforms)
- `compliance.jre.21` to `1.8,11,17,18,19,20,21` (from "undefined" that we have today, which results in tests for `1.3,1.4,1.5,1.6,1.7,1.8,9,10,11,12,13,14,15,16,17,18,19,20,21`). (Will run on Java 21 Linux build only).

Additionally we discussed with Srikanth if we still need to run all tests with 1.3 JLS (if specified), or only those that are actually testing something 1.3 specific.

I will push a PR for the `compliance.jre` argument in a moment.

**Comment by akurtakov** [comment]
I would even propose that compliance.jre.21 doesn't have to test 18 and 19 for sure . Even 20 could be removed when Java 21 is fully implemented.

**Comment by iloveeclipse** [comment]
> I would even propose that compliance.jre.21 doesn't have to test 18 and 19 for sure

See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1606

**Comment by iloveeclipse** [comment]
@jarthana , @srikanth-sankaran, @mpalat, @stephan-herrmann : any objections?

**Comment by stephan-herrmann** [comment]
> So I would propose to change
> * compliance.jre.17 from 1.8,11,16,17 to 1.3,1.8,11,17 (adding 1.3 and omitting 16). (will run on all platforms)

Omitting 16 sounds good. I think we can identify a better pre-1.8 candidate. See below.

> * compliance.jre.21 to 1.8,11,17,18,19,20,21 (from "undefined" that we have today, which results in tests for 1.3,1.4,1.5,1.6,1.7,1.8,9,10,11,12,13,14,15,16,17,18,19,20,21). (Will run on Java 21 Linux build only).
 
:+1: 

Question going forward: what would be the point in time to drop testing 18,19,20? Right when 22 is added?

Previous criteria for selecting "representative" versions, e.g.:
* 1.4 is the highest version without generics etc.
* 1.7 is the highest version without lambdas, new type inference etc.
* 1.8 is the highest version without JPMS support

I.e., we selected the most mature version _before_ the next huge change, motivated by the idea that users facing a bug affecting e.g., 1.5 should be able to migrate to 1.7 without much hassle, whereas 1.8 might be perceived as a barrier. Etc.

After 9 we never had such a huge change again, so its only fair to switch from "streams before a huge change" to "streams towards an LTS release" (like considering 12-17 a stream with final release = 17). 

Still, with this in mind I suggest that testing 1.7 has more relevance than 1.3.

**Comment by iloveeclipse** [comment]
> Question going forward: what would be the point in time to drop testing 18,19,20? Right when 22 is added?

I would assume we only run test for the **last** "non-LTS" Java version that precedes latest released one.

> I suggest that testing 1.7 has more relevance than 1.3.

OK, I will update  PR

**Comment by jarthana** [comment]
> @jarthana , @srikanth-sankaran, @mpalat, @stephan-herrmann : any objections?

None from me.

**Comment by srikanth-sankaran** [comment]
> > @jarthana , @srikanth-sankaran, @mpalat, @stephan-herrmann : any objections?
> 
> None from me.

No objection. 

At some point, we can explore identifying the smallest subset of tests that must be run at any compliance level and extract them into separate suites. These would be the tests that exercise the code blocks of the form

```
if (compilerOptions().complianceLevel operator ClassFileConstants.JDK_XYZ) // operator one of != == > >= < <= ...
```
