### ISSUE TITLE
Unexpected compile error for sealed-interface without permits inside record

### ISSUE THREAD

**Issue by lukeu** [eclipse-jdt/eclipse.jdt.core#1641]
Given the following, which `javac` accepts...

		record InterfaceInRecord() {
		    sealed interface I {
		        enum Empty implements I {
		            INSTANCE;
		        }
		        record Single(double value) implements I {
		        }
		    }
		}

... Eclipse issues 2 compiler errors on the lines containing `implements I`

Here are 2 modifications that (independently) resolve the errors:

 - Change the outer `record` into a `class`; or
 - Following `sealed interface I` insert `permits I.Empty, I.Single`   _(A useful workaround)_

Based on this evidence (nb: without reading the language spec) I'm inclined to think the Eclipse compiler is wrong in this case.

**Tested using:**

- Eclipse Version: 2023-12 (4.30 RC2) - Build id: I20231123-1700
- Running on Java Temurin: jdk-21.0.0.35-hotspot
- Trying both "Compiler Compliance Level" 17 and 21

**Comment by mpalat** [comment]
Thanks @lukeu for providing the test case and investigating further - will take a look

**Comment by lukeu** [comment]
Hi, thanks for looking into this. I played around with the fix and I believe similar bugs remain when the sealed interface is inside an `enum` rather than a `record`. Here is another test case:

    enum InterfaceInEnum {
        INSTANCE;
        sealed interface I  {
            final class C implements I {}
        }
        final class D implements I {}
    }

Similarly, Eclipse reports 2x compiler errors here, whereas `javac` reports none. 

*However,* when attempting to test the workaround, a crash occurs. Specifically, this is thrown after typing: `permits I.`

    java.lang.NullPointerException: Cannot read the array length because "superPermittedTypes" is null
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkPermitsAndAdd(SourceTypeBinding.java:1342)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkPermitsInType(SourceTypeBinding.java:1203)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkPermitsInType(SourceTypeBinding.java:1210)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkPermitsInType(SourceTypeBinding.java:1210)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1112)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:603)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1314)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:790)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1242)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1120)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5812)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1120)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:189)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)

This also appears to be to do with permitted types in the AST, so maybe another side of the same coin?

--------

Adding a further line creates a different variant of the test case above. (With this it does not seem to trigger the crash):

	    final class E implements InterfaceInEnum.I {}

* Observed: 3 compile errors
* Expected: No compile errors - the same as if the user had explicitly written `sealed interface I permits I.C, D, E`

**Comment by mpalat** [comment]
Thanks @lukeu for the variants - will check

**Comment by lukeu** [comment]
> which workaround are you referring to?

I mean that after: `sealed interface I` I began typing `permits I.C, D, E` and as soon as I typed the `'.'` I saw that stack-trace.

As for my environment, I am debugging Eclipse from Eclipse [as described here](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1561#issuecomment-1830915344).

**Comment by mpalat** [comment]
> 
> I mean that after: `sealed interface I` I began typing `permits I.C, D, E` and as soon as I typed the `'.'` I saw that stack-trace.
> 
Ah, I see. Thanks for the immediate response. able to reproduce this - the pr fixes it though its a different issue.  -will see whether a fix can be  piggybacked with this pr. Thanks

**Comment by mpalat** [comment]
> > I mean that after: `sealed interface I` I began typing `permits I.C, D, E` and as soon as I typed the `'.'` I saw that stack-trace.
> 
> Ah, I see. Thanks for the immediate response. able to reproduce this - the pr fixes it though its a different issue. -will see whether a fix can be piggybacked with this pr. Thanks

@lukeu I've merged the fix for enums also last week via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1739 - Please let me know whether you see any further issues in your setup. closing this now.
