### ISSUE TITLE
Failure of org.eclipse.jdt.core.tests.compiler.regression.TryWithResourcesStatementTest.testBug533187

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-jdt/eclipse.jdt.core#1689]
Failed here https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1687/checks?check_run_id=19325502794 (#1687)

```java
junit.framework.ComparisonFailure: 
Unexpected error running resulting class file for Stuck.java:
--[START]--
---[END]---
.
----------- Expected ------------
java.lang.RuntimeException\n
	at Stuck.raise(Stuck.java:19)\n
	at Stuck.snippet1(Stuck.java:15)\n
	at Stuck.main(Stuck.java:3)\n

------------ but was ------------

---------------------- ----------
 expected:<[java.lang.RuntimeException\n
	at Stuck.raise(Stuck.java:19)\n
	at Stuck.snippet1(Stuck.java:15)\n
	at Stuck.main(Stuck.java:3)\n
]> but was:<[]>
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3601)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3252)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:3831)
	at org.eclipse.jdt.core.tests.compiler.regression.TryWithResourcesStatementTest.testBug533187(TryWithResourcesStatementTest.java:4249)
...
```

**Comment by fedejeanne** [comment]
I'm not planning on working on this one any time soon. Could someone add the "help wanted" label here? (I don't have the proper permissions to do it myself).
Thank you.
