### ISSUE TITLE
Infinite loop on Java 1.8 compilation when use of lot of Generics

### ISSUE THREAD

**Issue by Greg34170** [eclipse-jdt/eclipse.jdt.core#177]
One of my project compile correctly with Eclipse 4.9. I try to migrate to eclipse 4.24.0. An infinite loop seems to appears when try to compile the same project and editor freeze when we try to use completion. (The same bug in eclipse 4.21).
Please find an part of the code that generate the bug.

[GenericProject.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/8999794/GenericProject.zip)

Regards.

**Comment by trancexpress** [comment]
Stack trace after importing the reproducer project:

```
"Compiler Processing Task" #128 daemon prio=5 os_prio=0 cpu=24981.53ms elapsed=25.06s tid=0x00007f2ad018c3c0 nid=0x6bb3 runnable  [0x00007f2c8cfba000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1068)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.isProperType(ParameterizedTypeBinding.java:1069)
        at org.eclipse.jdt.internal.compiler.lookup.TypeVariableBinding.isProperType(TypeVariableBinding.java:629)
        at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.resolve(ReturnStatement.java:349)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1506)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:905)
        at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
        at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)
```
