### ISSUE TITLE
Internal compiler error when yielding inside of try-catch.

### ISSUE THREAD

**Issue by DaRealTurtyWurty** [eclipse-jdt/eclipse.jdt.core#180]
`
Internal compiler error: java.lang.NullPointerException: Cannot read field "id" because "typeBinding" is null at org.eclipse.jdt.internal.compiler.codegen.CodeStream.popInvokeTypeBinding(CodeStream.java:4682)`

This error occurs when having a try-catch inside of a switch expression where you then attempt to yield a value.

An example piece of code that should compile but doesn't:
```java
public enum Numbers {
    FLOAT, INTEGER, DOUBLE;
    
    public static double parse(Numbers numbers, String str) {
            return switch (numbers) {
                case FLOAT -> {
                    try {
                        yield Float.parseFloat(str);
                    } catch (final NumberFormatException exception) {
                        yield Float.NaN;
                    }
                }
                case INTEGER -> {
                    try {
                        yield Integer.parseInt(str);
                    } catch (final NumberFormatException exception) {
                        yield Float.NaN;
                    }
                }
                case DOUBLE -> {
                    try {
                        yield Double.parseDouble(str);
                    } catch (final NumberFormatException exception) {
                        yield Float.NaN;
                    }
                }
                default -> throw new IllegalArgumentException("Unexpected value: " + enumm);
            };
    }
}

**Comment by iloveeclipse** [comment]
Can reproduce on head, stack from master:
```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.popInvokeTypeBinding(CodeStream.java:4682)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.invoke18(CodeStream.java:4718)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.invoke(CodeStream.java:4673)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.invoke(CodeStream.java:4667)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.invokeJavaLangEnumvalueOf(CodeStream.java:5050)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.generateSyntheticBodyForEnumValueOf(CodeStream.java:2766)
	at org.eclipse.jdt.internal.compiler.ClassFile.addSyntheticEnumValueOfMethod(ClassFile.java:1370)
	at org.eclipse.jdt.internal.compiler.ClassFile.addSpecialMethods(ClassFile.java:1121)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:765)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:831)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:916)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The code in question is coming from https://bugs.eclipse.org/bugs/show_bug.cgi?id=571929, see https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/177802/8/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/codegen/CodeStream.java#4653

Note, org.eclipse.jdt.internal.compiler.codegen.CodeStream.popTypeBinding() can return null, but it is dereferenced without null check.
