### ISSUE TITLE
"Error indexing package names!"

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1828]
After a fresh OOmphed Platform workspace eclipse starts with 6 times this error in the log (i have not seen those before):
```
Java Model Exception: Error in Java Model (code 969): C:\Users\jkubitz\platform-2024-01-10\git\eclipse.pde\apitools\org.eclipse.pde.api.tools.annotations\ does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:559)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:254)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:572)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:303)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:289)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:244)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.indexPackageNames(JavaSearchNameEnvironment.java:231)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:220)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:189)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:97)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:167)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:117)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:681)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1292)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:542)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
```
eclipse.buildId=4.31.0.I20240109-1800
java.version=21.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\jkubitz\platform-2024-01-10\ws

This is a continuation of log file C:\Users\jkubitz\platform-2024-01-10\ws\.metadata\.bak_0.log
Created Time: 2024-01-10 09:44:24.207
```
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/6d6129f7-9ae0-4fe7-8572-0b8450d4588c)

**Comment by iloveeclipse** [comment]
So `C:\Users\jkubitz\platform-2024-01-10\git\eclipse.pde\apitools\org.eclipse.pde.api.tools.annotations\` is referenced by some project and missing? Why is this a JDT bug?

**Comment by jukzi** [comment]
i wonder: the folder does exist:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/155d1cdc-23da-4576-9ebd-15a2ae9c2140)

**Comment by iloveeclipse** [comment]
Can it be the project moved?

**Comment by jukzi** [comment]
It was a fresh installation, there should be no move!
