### ISSUE TITLE
[17] Compilation problem when running in parallel with Java 17

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#183]
We currently discovered [a problem in Tycho](https://github.com/eclipse/tycho/issues/1099) that makes compilation failing on Java 17 with error:

`The type java.lang.Object cannot be resolved`

Current reproducer:

- git clone https://github.com/eclipse/tycho.git
- cd tycho
- Make sure java -version shows 17
- mvn clean package **-T1** -DskipTests -> **succeds**
- mvn clean package **-T16** -DskipTests -> **fails** (but not always at the same step)

Using java 11 the build succeeds!

Failure message include:

- String cannot be resolved to a type
- The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
- The import java.util cannot be resolved
- Implicit super constructor Object() is undefined for default constructor. Must define an explicit constructor

**Comment by laeubi** [comment]
It might be necessary to configure a Java 11 JDK in the `<userhome>/.m2/toolchains.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<toolchains>
	<toolchain>
		<type>jdk</type>
		<provides>
			<id>JavaSE-11</id>
			<version>11</version>
		</provides>
		<configuration>
			<jdkHome>/path/to/jdk-11</jdkHome>
		</configuration>
	</toolchain>
	<toolchain>
		<type>jdk</type>
		<provides>
			<id>JavaSE-17</id>
			<version>17</version>
		</provides>
		<configuration>
			<jdkHome>/path/to/jdk-17</jdkHome>
		</configuration>
	</toolchain>
</toolchains>
```

**Comment by stephan-herrmann** [comment]
What options does tycho pass into ecj? Is `--release` included? For which target version?

**Comment by laeubi** [comment]
We are calling the compiler with the follwoing arguments:
```
-properties <projectdir>/.settings/org.eclipse.jdt.core.prefs
 -s <classes output dir>generated-sources/annotations
 -d <classes output dir>
 -classpath <classpath>
<classes output dir>
<a java file>
 -g
 -nowarn
 -target 11
 -source 11
 --release 11
 -encoding UTF-8
```
It might be an issue in how tycho is calling the compiler, but strange enough it reliable fails when using JDK17 but works with JDK11 and I'm not familiar enough with EJC to tell if it is a Tycho or JDT issue, so any hint would be appreciated!

**Comment by laeubi** [comment]
What I noticed when capturing the compiler options: it seems that the additional debug output is enough sometimes to make the build succeed (e.g. print to console).

**Comment by iloveeclipse** [comment]
@laeubi : could you just for fun add this option: `-Dorg.eclipse.jdt.disable_CTSYM_cache=true` ? I don't see if there is a MT issue with related code, but who knows? The build will be probably considerably slower.

**Comment by styken** [comment]
I've seen the same error; not finding String or Object etc; in the IDE. The workaround we use is to choose another JDK, rebuild and switch back to normal JDK. Seem like it might be a similar issue with some cache that is not populated properly.

**Comment by laeubi** [comment]
> I've seen the same error; not finding String or Object etc; in the IDE.

Any chance you can share a stacktrace or error log of this?

**Comment by styken** [comment]
It's been a while it now, for me it happens once every other week so no recent "incident". I can't remember I saw anything in the error log. It just failed to recognize standard code.

**Comment by stephan-herrmann** [comment]
Scribbling down some hypotheses:
* Each compiler invocation uses a fresh `new Main(..)` so any instance fields should be isolated between threads.
* `org.eclipse.jdt.internal.compiler.util.JRTUtil.images` is a static map, providing one global instance of JrtFileSystem per (JAVA_HOME x release).
* with `--release` we use a `JrtFileSystemWithOlderRelease`
* due to sharing via map `images`, access to all instance fields of `JrtFileSystemWithOlderRelease` must be thread-safe
* the fact that `--release 11` on JDK 11 works, suggests that `JrtFileSystem` doesn't have the problem ( ? )
* the difference between both classes isn't huge, only few fields are added
  * `ctSym` is only ever accessed during construction ( ?? )
  * `releaseRoots` is assigned during construction, and afterwards only read, not modified
* ignoring the `...WithOlderRelease` part, `org.eclipse.jdt.internal.compiler.util.JrtFileSystem.cachePackage(String, String)` looks like a candidate needing synchronization, concerning `packageToModule` and `packageToModules` - *and it already is synchronized :)*
* due to the logical dependency between `packageToModule` and `packageToModules` I could imagine that `getModules()` and `getModulesDeclaringPackage()` could use synchronization, too, to avoid reading inconsistent state? But that doesn't sound like it could cause the devastating breakdown reported here.

I don't see a really hot track here. `org.eclipse.jdt.internal.compiler.util.JRTUtil.ctSymFiles` could use some similar scrutiny.

**Comment by laeubi** [comment]
> * Each compiler invocation uses a fresh `new Main(..)` so any instance fields should be isolated between threads.

Tycho already uses

`Main compiler = new Main(new PrintWriter(out), new PrintWriter(err), false, null, null);`

> * `org.eclipse.jdt.internal.compiler.util.JRTUtil.images` is a static map, providing one global instance of JrtFileSystem per (JAVA_HOME x release).

But uses concurrent maps, that seems "save", but it has `JRTUtil.MODULE_TO_LOAD` that is non final (claimed for test purpose only) and is written in `org.eclipse.jdt.internal.compiler.util.JrtFileSystem.initialize(File)` so should it not be a property of `JrtFileSystem`?

> * But that doesn't sound like it could cause the devastating breakdown reported here.

As it is quite reproducible (about 9/10 builds fail) I could try to add some breakpoints or even try use modified versions of the compiler if it helps.

**Comment by laeubi** [comment]
I'd like to propose some smaller refactoring to clarify code and reduce the chance of having race conditions, thus I started with:
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/187

would be good if someone could review this.

**Comment by iloveeclipse** [comment]
@laeubi : would you be able to recompile jdt core with this patch on top (https://github.com/eclipse-jdt/eclipse.jdt.core/pull/192) , add  `-Dorg.eclipse.jdt.propagate_io_errors=true` option and check if that reveals any (suppressed) error, or might be even helps? See PR description for explanation.

**Comment by laeubi** [comment]
@iloveeclipse sorry it seems I have missed that request! As it is already merged, do I need to recompile or can I download the compiler part or is there even a SNPASHOT deploy to a maven repository?
Beside that I have opened
- https://github.com/eclipse/tycho/issues/1135

for using a custom build of JDT.

**Comment by iloveeclipse** [comment]
@laeubi : no problem. 
**If** you can configure your build to use ecj jar, [here it is](https://download.eclipse.org/eclipse/downloads/drops4/I20220712-1800/download.php?dropFile=ecj-I20220712-1800.jar). It is always provided on every nightly build page, [like here](https://download.eclipse.org/eclipse/downloads/drops4/I20220712-1800/), just scroll down to "JDT Core Batch Compiler".

Note: the build is unlikely to fix your issue, but watch for unexpected errors/error printouts, might be we could get some new insights from them. You can try first without `-Dorg.eclipse.jdt.propagate_io_errors=true` and later with that flag. In first case we only report unexpected IO issues to std error, in later we propagate them up to compiler.

**Comment by laeubi** [comment]
Yeah I think we need to poke around a bit to get an idea  whats going on, similar my approach at https://github.com/eclipse-jdt/eclipse.jdt.core/pull/187 would be good to have this as well if there are no concerns.

**Comment by laeubi** [comment]
I think I got it working (is there an option to print the EJC compiler version to verify this?) but adding the flag do not reveal any additional errors.

**Comment by laeubi** [comment]
Okay I finally got it working to use a local compile ecj with Tycho, any place where I can print some useful info?

**Comment by laeubi** [comment]
Remote debugging also works, so if someone has a hint where to put a breakpoint....

**Comment by iloveeclipse** [comment]
@laeubi : if you can build ecj now, could you try to rebase this patch on master and check if anything changes: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/194

This is again unlikely fixes your issue, but who knows?

Can you provide a "simple" setup that reproduces your issue and allows to configure ecj build for fully stupid maven users? Or, even better: if you can reverse engineer what maven does, could you provide exact commands triggered by maven, so one could skip all that maven machinery and run a simple MT Java main class that triggers N compiler threads? Would also allow to write a unit test. 

I can't guarantee, but might be someone else could find time to look at this bug given a simple setup.

**Comment by laeubi** [comment]
I have now created an example project, and getting the following exception:

```
StdErr: java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:104)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247Jdk12.initialize(ClasspathJep247Jdk12.java:132)
	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:229)
	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
	at runner.RunCompiler.doCompile(RunCompiler.java:60)
	at runner.RunCompiler.lambda$0(RunCompiler.java:40)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Its yet unclear for me why I was not able to capture this inside Tycho, but the compile errors are the same. Interestingly the errors only occur in those threads that do *not* have this exception ...

The test case is here [ecj.compile.problem.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9108458/ecj.compile.problem.zip)

it contains of two parts:

1. **project** : a simple java project to compile
2. **runner** : a plain java main that runs many compiles of the project in parallel

The runner needs the path to the example project, optionally one can specify the number of threads, while 16 seem to work on my machine to reproduce the problem always.

.

**Comment by laeubi** [comment]
I have proposed a patch for the FileSystem init here: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/213 sadly the compile now still fails but without any additional error...

**Comment by laeubi** [comment]
> if you can build ecj now, could you try to rebase this patch on master and check if anything changes: #194

The test-case still fails with this patch, but might be not surprising as `--release 11` is used on Java 17 JVM, so maybe do not make any difference here?

**Comment by laeubi** [comment]
I tried to track why a package is not found and observed the following:

If I put a break-point at `org.eclipse.jdt.internal.compiler.lookup.PackageBinding.addPackage(PackageBinding, ModuleBinding)` all threads halt at `package ecj.compile` but has **different** call sites!

```
Thread [Compile-Thread-00] (Suspended (breakpoint at line 93 in PackageBinding))	
	PlainPackageBinding(PackageBinding).addPackage(PackageBinding, ModuleBinding) line: 93	
	ModuleBinding$UnNamedModule(ModuleBinding).getOrCreateDeclaredPackage(char[][]) line: 336	
	ModuleBinding$UnNamedModule(ModuleBinding).getOrCreateDeclaredPackage(char[][]) line: 334	
	ModuleBinding$UnNamedModule.getDeclaredPackage(char[]) line: 104	
	LookupEnvironment.createPlainPackage(char[][]) line: 1095	
	CompilationUnitScope.buildTypeBindings(AccessRestriction) line: 135	
	LookupEnvironment.buildTypeBindings(CompilationUnitDeclaration, AccessRestriction) line: 475	
	Compiler.internalBeginToCompile(ICompilationUnit[], int) line: 856	
	Compiler.beginToCompile(ICompilationUnit[]) line: 394	
	Compiler.compile(ICompilationUnit[], boolean) line: 448	
	Compiler.compile(ICompilationUnit[]) line: 426	
	Main.performCompilation() line: 4781	
	Main.compile(String[]) line: 1802	
	RunCompiler.doCompile(String, CountDownLatch) line: 75	
	RunCompiler.lambda$0(String, CountDownLatch, Map, String, CountDownLatch) line: 47	
	0x0000000800c061e8.run() line: not available	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1136	
	ThreadPoolExecutor$Worker.run() line: 635	
	Thread.run() line: 833	
```

and

```
Thread [Compile-Thread-01] (Suspended (breakpoint at line 93 in PackageBinding))	
	PlainPackageBinding(PackageBinding).addPackage(PackageBinding, ModuleBinding) line: 93	
	LookupEnvironment.createPlainPackage(char[][]) line: 1150	
	CompilationUnitScope.buildTypeBindings(AccessRestriction) line: 135	
	LookupEnvironment.buildTypeBindings(CompilationUnitDeclaration, AccessRestriction) line: 475	
	Compiler.internalBeginToCompile(ICompilationUnit[], int) line: 856	
	Compiler.beginToCompile(ICompilationUnit[]) line: 394	
	Compiler.compile(ICompilationUnit[], boolean) line: 448	
	Compiler.compile(ICompilationUnit[]) line: 426	
	Main.performCompilation() line: 4781	
	Main.compile(String[]) line: 1802	
	RunCompiler.doCompile(String, CountDownLatch) line: 75	
	RunCompiler.lambda$0(String, CountDownLatch, Map, String, CountDownLatch) line: 47	
	0x0000000800c061e8.run() line: not available	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1136	
	ThreadPoolExecutor$Worker.run() line: 635	
	Thread.run() line: 833	
```

It seems that `org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage(char[][], char[])` (what then calls `org.eclipse.jdt.internal.compiler.batch.FileSystem.getModulesDeclaringPackage(char[][], char[])`) returns different results.

I added some debug print out and got the following:

### All compile fail with 16 Threads
```
[Thread[Compile-Thread-01,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1142816013, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1018878487
[Thread[Compile-Thread-11,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@2091583325, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@299035309
[Thread[Compile-Thread-13,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1220691567, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1491777957
[Thread[Compile-Thread-15,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@697222521, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1948400314
[Thread[Compile-Thread-12,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@640992083, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@2082503624
[Thread[Compile-Thread-10,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@241414398, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@804974725
[Thread[Compile-Thread-06,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1860200233, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1294604046
[Thread[Compile-Thread-02,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1268584243, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@2037698132
[Thread[Compile-Thread-07,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@341249738, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@2039646093
[Thread[Compile-Thread-03,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@2094992518, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@497709186
[Thread[Compile-Thread-08,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1300236674, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1700905975
[Thread[Compile-Thread-04,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1293388526, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1514677805
[Thread[Compile-Thread-09,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1331856764, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@2077290705
[Thread[Compile-Thread-00,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1048455186, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1538374675
[Thread[Compile-Thread-05,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@2044440792, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@325922405
[Thread[Compile-Thread-14,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1147989414, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@651479730
```

### One succeeds and one fails with 2 Threads

```
[Thread[Compile-Thread-01,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@344069850, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1712086287
[Thread[Compile-Thread-00,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1554711604, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1358557472
===Compile-Thread-00===
true
===Compile-Thread-01===
false
```

### With one thread succeeds:
```
[Thread[Compile-Thread-00,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1926933262, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1574998161
===Compile-Thread-00===
true
```

**Comment by laeubi** [comment]
Strange thing is that if I put a breakpoint at the FileSystem constructor and let run each thread after the other, then I get similar output but successful compilation:

```
[Thread[Compile-Thread-01,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=null, this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@405455212, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@2019072368
[Thread[Compile-Thread-00,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1940291447, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1328259325
===Compile-Thread-00===
true
===Compile-Thread-01===
true
```

So there seems some shared state I have not found yet to make this still succeed, but its really confusing that two instance return different results for the same "thing" (only difference is the compiler output directory here)

**Comment by laeubi** [comment]
I added some more debug to trace when this is called and what it returns:
```
[Thread[Compile-Thread-01,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@1451649822, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@2110444715
[Thread[Compile-Thread-00,5,main]][] flatName=ecj.compile.problem, nameForLookup=, declaringModuleNames=[,], this=org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule@111424790, moduleEnv=org.eclipse.jdt.internal.compiler.batch.FileSystem@1934940532
===Compile-Thread-00===
false
	[11128891101635][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem returned [,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding$UnNamedModule.getDeclaredPackage, LookupEnvironment.createPlainPackage, CompilationUnitScope.buildTypeBindings, LookupEnvironment.buildTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128895816225][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj returned [,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getTopLevelPackage, LookupEnvironment.getTopLevelPackage, LookupEnvironment.createPlainPackage, CompilationUnitScope.buildTypeBindings, LookupEnvironment.buildTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128916554684][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem/HelloWorld returned null [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getVisiblePackage, PackageBinding.findPackage, PackageBinding.getPackage, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128917795145][org.eclipse.jdt.internal.compiler.batch.FileSystem]java returned [java.base,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.net.http,java.prefs,java.rmi,java.sql,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getTopLevelPackage, LookupEnvironment.getTopLevelPackage, CompilationUnitScope.getDefaultImports, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128923812558][org.eclipse.jdt.internal.compiler.batch.FileSystem]java returned [java.base,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.net.http,java.prefs,java.rmi,java.sql,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, LookupEnvironment.computePackageFrom, LookupEnvironment.createMissingType, CompilationUnitScope.getDefaultImports, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128924233663][org.eclipse.jdt.internal.compiler.batch.FileSystem]java/lang returned [java.base,java.instrument,java.management,] [FileSystem.getModulesDeclaringPackage, LookupEnvironment.computePackageFrom, LookupEnvironment.createMissingType, CompilationUnitScope.getDefaultImports, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128925173741][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem/ExampleEnum returned null [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getVisiblePackage, PackageBinding.findPackage, PackageBinding.getPackage, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
===Compile-Thread-01===
true
	[11128891061183][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem returned [,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding$UnNamedModule.getDeclaredPackage, LookupEnvironment.createPlainPackage, CompilationUnitScope.buildTypeBindings, LookupEnvironment.buildTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128891814942][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj returned [,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getTopLevelPackage, LookupEnvironment.getTopLevelPackage, LookupEnvironment.createPlainPackage, CompilationUnitScope.buildTypeBindings, LookupEnvironment.buildTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128908047934][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem/HelloWorld returned null [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getVisiblePackage, PackageBinding.findPackage, PackageBinding.getPackage, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128908446290][org.eclipse.jdt.internal.compiler.batch.FileSystem]java returned [java.base,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.net.http,java.prefs,java.rmi,java.sql,] [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getTopLevelPackage, LookupEnvironment.getTopLevelPackage, CompilationUnitScope.getDefaultImports, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128942169737][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem/ExampleEnum returned null [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getVisiblePackage, PackageBinding.findPackage, PackageBinding.getPackage, CompilationUnitScope.checkAndSetImports, LookupEnvironment.completeTypeBindings, Compiler.internalBeginToCompile, Compiler.beginToCompile, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]
	[11128961207232][org.eclipse.jdt.internal.compiler.batch.FileSystem]ecj/compile/problem/String returned null [FileSystem.getModulesDeclaringPackage, IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage, ModuleBinding.getVisiblePackage, ModuleBinding.getVisiblePackage, PackageBinding.findPackage, PackageBinding.getTypeOrPackage, Scope.getTypeOrPackage, Scope.getType, ArrayTypeReference.getTypeBinding, TypeReference.internalResolveType, ArrayTypeReference.internalResolveType, TypeReference.resolveType, TypeReference.resolveType, SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy, SourceTypeBinding.resolveTypesFor, AnnotationDiscoveryVisitor.visit, Argument.traverse, AnnotationDiscoveryVisitor.visit, MethodDeclaration.traverse, TypeDeclaration.traverse, CompilationUnitDeclaration.traverse, CompilationUnitDeclaration.traverse, RoundEnvImpl.<init>, BaseAnnotationProcessorManager.processAnnotations, Compiler.processAnnotations, Compiler.compile, Compiler.compile, Main.performCompilation, Main.compile]

```

**Comment by iloveeclipse** [comment]
@laeubi : I had a quick look into your example (great!), I can reproduce the problem with JDK 14, 15, 17 but not with 11. Amazing. I hope to find some time to debug next week.

**Comment by iloveeclipse** [comment]
> `org.eclipse.jdt.internal.core.builder.ClasspathJrt.ModulesCache` seem also to be not MT safe...

I was so close ... It's the copy in `org.eclipse.jdt.internal.compiler.**batch**.ClasspathJrt.ModulesCache`

**Comment by laeubi** [comment]
Great that we have a solution, @akurtakov given we have a fix in master, would it be possible to release the `ecj.jar` to maven central as a RC1 or something? See also #209 as this currently prevents parallel execution and as platform has recently moved to Java 17 build jdks (see https://github.com/eclipse-platform/eclipse.platform/runs/7368496301?check_suite_focus=true for example), this current forces to use slower single-threaded builds. The alternative would be to add workarounds (e.g. synchronization) to Tycho but would also affect users of other java versions or we need to add special code to detect the issue, what not seems so nice.

**Comment by akurtakov** [comment]
I would redirect the question to @sravanlakkimsetti . We have released some new artifacts for this release so technically there is no blocker to do it. Let's be sure that jdt devs are fine with some build and publish.

**Comment by iloveeclipse** [comment]
> This must only be **properly** fixed.

I've merged the fix now, leave this open for:

1) confirmation that this fixes the maven compile - there can be other issues still
2) to fix similar code in `org.eclipse.jdt.internal.core.builder.ClasspathJrt` & Co (IDE part)

**Comment by laeubi** [comment]
I can confirm that building a larger project that fails with the previous version of EJC now runs fine in parallel mode using `I20220717`

@sravanlakkimsetti any chance to deploy the `ecj.jar` eg as version `3.30.I20220717` to maven central?

**Comment by iloveeclipse** [comment]
@laeubi : thanks for validation.
I think we plan to release 4.25 M2 on 29 Juli (in ~10 days). 
Would it be OK to wait till M2?

**Comment by iloveeclipse** [comment]
> If M2 will be available to maven ... :-)

Please create dedicate ticket and ask someone (Sravan?) who deployed the packages to maven to do that, we don't need to discuss release things on this ticket.

**Comment by laeubi** [comment]
Done, I think this can be assumed fixed then.
