### ISSUE TITLE
NPE during "Refreshing Workspace" - IFileStore.getFileSystem()" is null - often when switching between git branches 

### ISSUE THREAD

**Issue by synesty-cr** [eclipse-jdt/eclipse.jdt.core#1886]
I recently noticed the following exception quite often when switching between git branches (using external Github Desktop git client... not Eclipse itself)
Probably because the underlying filesystem has changed. But maybe the NPE can be handled. 

## Exception

An internal error occurred during: "Refreshing workspace".

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileSystem.getScheme()" because the return value of "org.eclipse.core.filesystem.IFileStore.getFileSystem()" is null
	at org.eclipse.core.internal.filesystem.FileStoreUtil.compareFileStore(FileStoreUtil.java:138)
	at org.eclipse.core.filesystem.IFileStore.compareTo(IFileStore.java:583)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:344)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at org.eclipse.core.internal.resources.AliasManager$LocationMap.matchingResourcesDo(AliasManager.java:203)
	at org.eclipse.core.internal.resources.AliasManager.internalComputeAliases(AliasManager.java:545)
	at org.eclipse.core.internal.resources.AliasManager.computeAliases(AliasManager.java:430)
	at org.eclipse.core.internal.localstore.RefreshLocalAliasVisitor.deleteResource(RefreshLocalAliasVisitor.java:53)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.synchronizeExistence(RefreshLocalVisitor.java:195)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:302)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:119)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:1025)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:1008)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1610)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:228)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

## Environment 

```
eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product -keyring /Users/christoph/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.committers.product -keyring ....

This is a continuation of log file .../.metadata/.bak_5.log
Created Time: 2024-01-19 09:05:25.246

```

**Comment by jukzi** [comment]
getFileSystem() should never return null. org.eclipse.core.internal.filesystem.local.LocalFileSystem.instance is neither final nor synchronized. That may be a concurrency problem. 
or if you use another filesystem - do you find logentries like "No file system is defined for scheme: {0}" in Error View?

**Comment by mpalat** [comment]
[Note: Thanks Jörg for taking a look at this - @synesty-cr - want to note that this issue has been raised against jdt.core - this is a platform issue ]

**Comment by jukzi** [comment]
@synesty-cr please open a copy of issue at https://github.com/eclipse-platform/eclipse.platform/issues
