### ISSUE TITLE
NPE in CompilationUnitResolver.getSourceClassPaths(IJavaProject) since https://bugs.eclipse.org/578928

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#19]
I'm getting NPE in this call stack:

```
java.lang.NullPointerException
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.getSourceClassPaths(CompilationUnitResolver.java:381)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:343)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1272)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:166)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:151)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Steps:
* create a general project, no Java nature
* in that project create a .java file with a minimal class declaration
* in the (java) editor select the class name

This seems to be caused by https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/?id=f4c79a0498a4c3902c619d4dc7a24fa37364e908 on behalf of https://bugs.eclipse.org/578928.

I can see that the offending block existed in a different class before, but looking at the flow this looks just plain wrong:

```
		IClasspathEntry[] resolvedClasspath = null;
		try {
			resolvedClasspath = project.getResolvedClasspath(true);
		} catch (JavaModelException e) {
			//do nothing
		}

		for (IClasspathEntry entry : resolvedClasspath) {
```

Someone was literally asking for NPE on the last line shown, notably when JavaModelException actually occurs, as will be the case when `!project.exists()` (i.e., we're attempting to read a non-java project as a java project).

**Comment by vik-chand** [comment]
I am looking at this issue.
