### ISSUE TITLE
org.eclipse.jdt.internal.core.util.Util.getSignature() throwing exception for NameQualifiedType

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#1980]
When Util.getSignature() receives a NameQualifiedType as input, it crashes with
```
java.lang.IllegalArgumentException: 
	at org.eclipse.jdt.core.Signature.createCharArrayTypeSignature(Signature.java:1105)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1305)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1332)
	at org.eclipse.jdt.internal.core.util.Util.getSignature(Util.java:1215)
```

The cause is org.eclipse.jdt.internal.core.util.Util.getFullyQualifiedName() is missing support for NameQualifiedType and returns an empty name; which is later rejected.

**Comment by mickaelistria** [comment]
While I've detected it using API, I think trying to use some wizard to create/move a method of type `void foo(java.util.@NonNull String)` will exhibit the errors to users.
