### ISSUE TITLE
ASTParser.createAST silently stop in the middle of a batch of compilation units

### ISSUE THREAD

**Issue by alban-auzeill** [eclipse-jdt/eclipse.jdt.core#2050]
Context:
When I'm using ASTParser.createAST `org.eclipse.jdt:org.eclipse.jdt.core:3.36.0` (instead of `3.35.0`).

Problem:
The parser fails at handling missing types, this is the first issue. it could be related to #1915.
But this first issue highlights a second issue with a bigger impact:
The analysis of a batch of compilation units in `ASTParser.createAST` silently stops in the middle of a batch.
So the ASTParser does not call back the FileASTRequestor for the file having the missing type, and does not call back all the remaining files in the batch.

[This GitHub repository](https://github.com/alban-auzeill/jdt-core-ast-for-batch-of-compilation-units-bug) is a reproducer for this problem. It's `README.md` file explains how to reproduce.

**Comment by jukzi** [comment]
it would help if you find the commit that broke your usecase and provide a Juni test that shows your problem.

**Comment by alban-auzeill** [comment]
@jukzi I tried to provide a Junit test that breaks my use-case. Unfortunately, I failed to make all tests pass using the simplified `Oomph` method described (here)[https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/Code-Setup-Using-Oomph]. Then my use-case is not an easy single snippet of Java code to integrate as a string in one unit test. It requires a simple Java code that depends on a binary `.class` file, that depends on a missing other `.class` in the classpath.

About finding the commit, is there a maven repository that I can use ( like the one for the snapshots https://repo.eclipse.org/content/repositories/eclipse-snapshots/ ) instead of building `org.eclipse.jdt.core` again and again for each commit?

**Comment by alban-auzeill** [comment]
@jukzi the first issue about `fails at handling missing types` has been introduced by 6138ac397f
A `ProblemReporter` has an unexpected null `referenceContext` which throws the following exception:
```
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(700) The class file Module1<String> contains a signature '(Lorg/example/Module1<Ljava/lang/String;>.Inner;)V' ill-formed at position 42
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:161)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2671)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2734)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.corruptedSignature(ProblemReporter.java:1839)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:2062)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:1058)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:1212)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:612)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1062)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1043)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:307)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:353)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3557)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3264)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:60)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:528)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:631)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:627)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.resolveType(AllocationExpression.java:360)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1157)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:668)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:576)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1504)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1630)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:669)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:904)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1119)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:739)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1049)
	at org.example.ParserTest.getParsedFileNames(ParserTest.java:69)
	at org.example.ParserTest.check_accept_files_with_missing_semantic(ParserTest.java:39)
```

This exception is not caught and the stack gets back to this call:
```
at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1119)
```
And exit the following loop, which means no other `astRequestor.acceptAST(...)` calls will be possibly done for the remaining  compilation units. This is the second issue.
```java
			// process all units (some more could be injected in the loop by the lookup environment)
			for (int i = 0; i < this.totalUnits; i++) {
```
Note: The second issue can only be discovered thanks to the first issue.

**Comment by jukzi** [comment]
> issue about `fails at handling missing types` has been introduced by [6138ac3](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/6138ac397fca4323d50f47aae4b83895c170a361)

@stephan-herrmann

**Comment by stephan-herrmann** [comment]
> @jukzi the first issue about `fails at handling missing types` has been introduced by [6138ac3](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/6138ac397fca4323d50f47aae4b83895c170a361)
> A `ProblemReporter` has an unexpected null `referenceContext` which throws the following exception:

It is not totally unexpected as the explicit throwing of `AbortCompilation` signals. ProblemHandler is normally invoked via the idiom `scope.problemReporter().reportSomeError()`, where the method `problemReporter()` sets the `referenceContext`. Obviously, when the error is detected while handling a binary .class file, there is no scope and no referenceContext.

As for the impact of 6138ac39 _it could be_, that prior to that commit, a stale reference to a referenceContext was still set from some totally unrelated operation, and reporting against that compilation unit would have been plain wrong.

Also I don't think there's any guarantee that the compiler will continue in a meaningful way, if binaries are corrupt, missing etc.

We could, however, check if `AbortCompilation` could be caught at a location where the compiler could resume work in a meaningful way. 

And at least the problem must be reported to the user in all such scenarios. But when a client invokes the ASTParser, only the client can know which channels can be used to inform the user, as ASTParser has no channel to the user.

So please check, if the result from ASTParser contained some indication of the error.
