### ISSUE TITLE
New transient test failures in CompletionTests18

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2056]
There are 15 tests failing in the latest I build on Mac and JRE 17. These are not reproducible locally (but I only have access to a Windows machine, though). 

https://download.eclipse.org/eclipse/downloads/drops4/I20240221-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep431I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

This is not the first time, though. I have seen this happening in the past once and then the failures disappear in the subsequent builds.

**Comment by jukzi** [comment]
happened again in 
https://download.eclipse.org/eclipse/downloads/drops4/I20240516-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep432I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
Exactly 15 random failures on mac

**Comment by jukzi** [comment]
for example

```
junit.framework.ComparisonFailure:
----------- Expected ------------
StringBufferInputStream[TYPE_REF]{java.io.StringBufferInputStream, java.io, Ljava.io.StringBufferInputStream;, null, null, null, null, [147, 159], 49}\n
StringBuffer[TYPE_REF]{StringBuffer, java.lang, Ljava.lang.StringBuffer;, null, null, null, null, [147, 159], 56}
------------ but was ------------

---------------------- ----------
expected:<[StringBufferInputStream[TYPE_REF]{java.io.StringBufferInputStream, java.io, Ljava.io.StringBufferInputStream;, null, null, null, null, [147, 159], 49}\n
StringBuffer[TYPE_REF]{StringBuffer, java.lang, Ljava.lang.StringBuffer;, null, null, null, null, [147, 159], 56}]> but was:<[]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:239)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelCompletionTests.assertResults(AbstractJavaModelCompletionTests.java:215)
at org.eclipse.jdt.core.tests.model.CompletionTests18.test473008a(CompletionTests18.java:2864)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:98)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:86)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:95)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

```

**Comment by jukzi** [comment]
The CompletionTests18 now fails frequently on i-builds for java17_macosx.cocoa.aarch64_17.
