### ISSUE TITLE
[Switch Expression] NPE in StackMapFrameCodeStream.recordExpressionType

### ISSUE THREAD

**Issue by rfcom** [eclipse-jdt/eclipse.jdt.core#2072]
```
java.lang.NullPointerException: Cannot read field "id" because "typeBinding" is null
	at org.eclipse.jdt.internal.compiler.codegen.StackMapFrameCodeStream.recordExpressionType(StackMapFrameCodeStream.java:175)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.generateCode(SwitchStatement.java:933)
	at org.eclipse.jdt.internal.compiler.ast.SwitchExpression.generateCode(SwitchExpression.java:331)
	at org.eclipse.jdt.internal.compiler.ast.Statement.generateArguments(Statement.java:443)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.generateCode(AllocationExpression.java:217)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:214)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:358)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:292)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:759)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:803)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.generateCode(QualifiedAllocationExpression.java:250)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:214)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:358)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:292)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:759)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:829)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:414)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://git.eclipse.org/r/plugins/gitiles/jdt/eclipse.jdt.core/+/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/codegen/StackMapFrameCodeStream.java
```
	@Override
	public void recordExpressionType(TypeBinding typeBinding, int delta, boolean adjustStackDepth) {
		if (adjustStackDepth) {
			// optimized goto
			// the break label already adjusted the stack depth (-1 or -2 depending on the return type)
			// we need to adjust back to what it was
			switch (typeBinding.id) {
				case TypeIds.T_long:
				case TypeIds.T_double:
					this.stackDepth += 2;
					break;
				case TypeIds.T_void:
					break;
				default:
					this.stackDepth++;
					break;
			}
		}
	}
```

**Comment by srikanth-sankaran** [comment]
Stack trace is somewhat useful - but a reproducible test case will be very welcome.

**Comment by iloveeclipse** [comment]
@rfcom : could you please attach the source code that shows the problem?

@srikanth-sankaran : I assume something you will address anyway during switch refactoring work, right? The code in question that fails with NPE is very old, probably not a recent regression.

**Comment by srikanth-sankaran** [comment]
> @rfcom : could you please attach the source code that shows the problem?
> 
> @srikanth-sankaran : I assume something you will address anyway during switch refactoring work, right? The code in question that fails with NPE is very old, probably not a recent regression.

Yes, I will follow up.

**Comment by srikanth-sankaran** [comment]
`StackMapFrameCodeStream.recordExpressionType` is dead! Long live `StackMapFrameCodeStream.recordExpressionType`! 😀 

This was part of the ad-hoc stack size computation that https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2171 attempts to eliminate with a streamlined and structured stack size tracking across branch arcs.

The method where the NPE is reported doesn't exist anymore and so the problem has been incinerated.

Closing as fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2171
