### ISSUE TITLE
APT plugin does not use projects JDK for annotation processing

### ISSUE THREAD

**Issue by agentgt** [eclipse-jdt/eclipse.jdt.core#2137]
The APT plugin apparently uses the Eclipse VM (the VM running eclipse) to find annotation processors and if they are compiled to a newer version than it cannot load them despite the project having a newer JDK that is supported.

To reproduce run Eclipse with JDK 17 (which I think is still the default) but setup your project for JDK 21 and create an annotation processor.

Then create another project referencing that annotation processor using Maven or Gradle in the same eclipse. You will have to close the annotation processor project because of another long standing issue where annotation processor projects open in the same workbench will not load (this may have been fixed now).

Then you must run `-debug options`

Where options is a file with:

```
org.eclipse.jdt.apt.core/debug=true
```

The work around for this bug is to run Eclipse with the newer version of the JDK but this does not seem correct. Maybe its a limitation with the APT that it must run on the same JVM but that seems wrong?

Regardless it seems incredibly wrong that when this fails it is logged as `trace` thus requiring the special debug options.

Below is an example exception:

```
java.lang.UnsupportedClassVersionError: io/jstach/rainbowgum/apt/ConfigProcessor has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava6FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:458)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:952)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:449)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:411)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:342)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:286)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I can later on potentially provide a reproducible project.

**Comment by iloveeclipse** [comment]
> The APT plugin apparently uses the Eclipse VM

Well, it is Eclipse plugin so it runs in Eclipse VM :-)

> The work around for this bug is to run Eclipse with the newer version of the JDK but this does not seem correct

Why? If your toolchain uses Java 21 but your Eclipse is running on 17, wouldn't be only consistent to have all your tools running on same Java version?

There are no plans to run parts of Eclipse apt plugin in another JVM, so closing as won't fix.

**Comment by agentgt** [comment]
> Why? If your toolchain uses Java 21 but your Eclipse is running on 17, wouldn't be only consistent to have all your tools running on same Java version?

Eclipse will compile Java 21 code while running under 17. People install Eclipse all the time and do not to change their `-vm ` setting. **But yes I guess you do not need Java 21 code to compile obviously so I admit I was surprised even though I suppose it makes sense.**

That is why I was confused because I guess I just thought ECJ was forked. Forking would be slow so yeah I agree my complaint is not valid.


However I do think the error should have been propagated up the UI Problems instead of buried in a trace message (especially as you said it... *you are in the Eclipse VM*).

**Comment by agentgt** [comment]
Sorry for the brain fart. It was a long day... yes I feel very stupid thinking Eclipse forked on compile :)
