### ISSUE TITLE
Util.getSignature(type) crashing for UnionType (and probably intersection as well)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#2153]
Util.getSignature(type) doesn't support union type and fails with
```
java.lang.IllegalArgumentException: 
	at org.eclipse.jdt.core.Signature.createCharArrayTypeSignature(Signature.java:1105)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1305)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1332)
	at org.eclipse.jdt.internal.core.util.Util.getSignature(Util.java:1214)
...
```

**Comment by stephan-herrmann** [comment]
**CAVEAT:** Before using these signatures please carefully check https://bugs.eclipse.org/bugs/show_bug.cgi?id=551077 - otherwise the results might be the opposite from what you expect **!!!**

Sorry about the bad news - this confusion goes back to the implementation of Java 7 in 2011 and once this was implemented nobody dared to change it, in particular since the part in `Signature` is API.

Please check if it would be "less wrong" if the current PR would also swap union vs. intersection. 

Best way to achieve confidence would be to create a test that starts from a Type (UnionType/IntersectionType) then:
* resolve the type to an ITypeBinding
* convert to signature, then lookup the binding for that signature

The results must be equal.
