### ISSUE TITLE
[Java 22] HierarchicalASTVisitor must be updated to reflect a change in the ASTNode hierarchy

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2193]
The test `org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest` fails  [here](https://download.eclipse.org/eclipse/downloads/drops4/I20240320-0740/testresults/html/org.eclipse.jdt.ui.tests_ep432I-unit-win32-java17_win32.win32.x86_64_17.html)

with 

```
HierarchicalASTVisitor must be updated to reflect a change in the ASTNode hierarchy. No method visit(AbstractUnnamedTypeDeclaration) was found in HierarchicalASTVisitor.

java.lang.AssertionError: HierarchicalASTVisitor must be updated to reflect a change in the ASTNode hierarchy. No method visit(AbstractUnnamedTypeDeclaration) was found in HierarchicalASTVisitor.
at org.junit.Assert.fail(Assert.java:89)
at org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest.checkHierarchicalASTVisitorMethodExistsFor(HierarchicalASTVisitorTest.java:540)
at org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest.checkAllMethodsForHierarchyExist(HierarchicalASTVisitorTest.java:513)
at org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest.test(HierarchicalASTVisitorTest.java:489)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by srikanth-sankaran** [comment]
@jarthana thanks for following up. Mildly surprised to see this as a top level abstraction. Honestly haven't thought about it deeply myself.

**Comment by iloveeclipse** [comment]
Seem to be fixed in the meantime
