### ISSUE TITLE
[Switch-Expression] Assertion failure while compiling enum class that uses switch expression with try block

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2233]
Compiling the code below in the IDE results in `Internal compiler error: java.lang.AssertionError at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7743)`

Test case:

```
public enum X {
	PARAMETER, FIELD, METHOD;
	X() {
		System.out.println(switch (this) {
								default -> {
									try {
										yield 10;
									} finally {
										
									}
								}
							});			
	}

    public static void main(String [] args) {
        X x = PARAMETER;
        System.out.println(x);
    }
}
```

**Comment by srikanth-sankaran** [comment]
With https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2313 merged in the failure mode has changed. We now get `Internal compiler error: java.lang.AssertionError: Operand type is null at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7793)` 

in this call stack:
```
TypeAnnotationCodeStream(CodeStream).pushTypeBinding(TypeBinding) line: 7793	
TypeAnnotationCodeStream(CodeStream).pushTypeBinding(int) line: 7769	
TypeAnnotationCodeStream(CodeStream).aload_1() line: 358	
ExplicitConstructorCall.generateCode(BlockScope, CodeStream) line: 164	
ConstructorDeclaration.internalGenerateCode(ClassScope, ClassFile) line: 441	
ConstructorDeclaration.generateCode(ClassScope, ClassFile) line: 312	
TypeDeclaration.generateCode(ClassFile) line: 762	
TypeDeclaration.generateCode(CompilationUnitScope) line: 832	
CompilationUnitDeclaration.generateCode() line: 412	
```

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2317 addresses the compile time assertion failure. However the generated code now runs into https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2264 - which has a long history in bugzilla. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=533475 and friends
