### ISSUE TITLE
ClassCastException on class org.eclipse.jdt.internal.core.JavaNature

### ISSUE THREAD

**Issue by Kiiv** [eclipse-jdt/eclipse.jdt.core#2235]
Hi,

after upgrading to Eclipse 2024-03, i've got a lot of error of this kind :

```
Stacktrace :

java.lang.ClassCastException: class org.eclipse.jdt.internal.core.JavaNature cannot be cast to class org.eclipse.jdt.core.IJavaProject (org.eclipse.jdt.internal.core.JavaNature and org.eclipse.jdt.core.IJavaProject are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @69dcf047)
	at org.eclipse.jem.workbench.utility.JemProjectUtilities.getJavaProject(JemProjectUtilities.java:203)
	at org.eclipse.jst.j2ee.internal.validation.ProjectValidationHelper.getCachedOutputContainers(ProjectValidationHelper.java:44)
	at org.eclipse.jst.j2ee.internal.validation.ProjectValidationHelper.getOutputContainers(ProjectValidationHelper.java:63)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.checkIfValidSourceFile(ValidatorMetaData.java:344)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:315)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:306)
	at org.eclipse.wst.validation.internal.FilterUtil.filterOut(FilterUtil.java:339)
	at org.eclipse.wst.validation.internal.FilterUtil.filterOut(FilterUtil.java:376)
	at org.eclipse.wst.validation.internal.FilterUtil.filterOut(FilterUtil.java:433)
	at org.eclipse.wst.validation.internal.FilterUtil$2.visit(FilterUtil.java:631)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:66)
	at org.eclipse.wst.validation.internal.FilterUtil.loadDeltas(FilterUtil.java:647)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.loadFileDeltas(ValidationOperation.java:547)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.getFileDeltas(ValidationOperation.java:519)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.preValidate(ValidationOperation.java:791)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.run(ValidationOperation.java:653)
	at org.eclipse.wst.validation.internal.operations.ValidationBuilder.build(ValidationBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Session Data :
eclipse.buildId=4.31.0.20240307-1200
java.version=17.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

```

Any idea of the root cause ? Didn't install anything else between and I've keep my previous workspace.

**Comment by akurtakov** [comment]
The error happens in https://github.com/eclipse-jeetools/webtools.javaee (org.eclipse.jst/org.eclipse.jem packages) code so please report it there. There is nothing to be done here. If webtools idenfities some breakace in jdt's public API or some other bug in jdt someone should come with the details to us.
With the above said I'm closing it for now.

**Comment by Hirnfiedler** [comment]
Just as clarification for dummys like me:
Updating the 'webtools' (marketplace) fixed the problem problem for me.
