### ISSUE TITLE
[Switch-Expression] Bad code generation for switch expression inside enum constructor results in ExceptionInInitializerError

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2264]
The following program when compiled and run on master results in `ExceptionInInitializerError`:

```
public enum X {
					ONE;
					X() {
						System.out.println(switch(this) {
							default -> this;
						});
					}

				    public static void main(String [] args) {
				        X x = ONE;
				        System.out.println(x);
				    }
}
```

When run we get:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local0>" is null
	at X.values(X.java:1)
	at X.$SWITCH_TABLE$X(X.java:1)
	at X.<init>(X.java:4)
	at X.<clinit>(X.java:2)
```

**Comment by srikanth-sankaran** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=533475 and friends (search for `ExceptionInInitializerError` in bugzilla) - Each fix improves/enlarges the set of programs we can compile without completely addressing the problem

**Comment by srikanth-sankaran** [comment]
See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1450
