### ISSUE TITLE
"RuntimeException computing completion proposal for ..." (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse-jdt/eclipse.jdt.core#2276]
I just found this in the Eclipse IDE error logs:

```
RuntimeException computing completion proposal for ThroughputTest.java at offset 2603 line 68
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at org.eclipse.text.templates.TemplateStoreCore.internalAdd(TemplateStoreCore.java:185)
	at org.eclipse.ui.editors.text.templates.ContributionTemplateStore.loadContributedTemplates(ContributionTemplateStore.java:112)
	at org.eclipse.jface.text.templates.persistence.TemplateStore.load(TemplateStore.java:98)
	at org.eclipse.jdt.internal.ui.JavaPlugin.getTemplateStore(JavaPlugin.java:843)
	at org.eclipse.jdt.internal.ui.text.template.contentassist.TemplateEngine.complete(TemplateEngine.java:155)
	at org.eclipse.jdt.internal.ui.text.java.AbstractTemplateCompletionProposalComputer.computeCompletionProposals(AbstractTemplateCompletionProposalComputer.java:82)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:354)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:333)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

Looks like the `fTemplates` data structure in [TemplateStoreCore.java](https://github.com/eclipse-platform/eclipse.platform.ui/blob/3f6ffc2dcddec56fd54153ac1bcd86931d2926d2/bundles/org.eclipse.text/src/org/eclipse/text/templates/TemplateStoreCore.java) is accessed in a non-threadsafe way.

Using Eclipse IDE
Version: 2024-03 (4.31.0)
Build id: 20240307-1437
on macOS aarch64

**Comment by iloveeclipse** [comment]
@kohlschuetter: I assume you can't reproduce (it is a timing issue), but in case you can, please try with the build from https://download.eclipse.org/eclipse/downloads/drops4/I20240414-1800/ if the problem is fixed or just moved to some other place.

Background: async content assist spawns multiple threads and they were trying to concurrently compute some proposals, activating related bundles & singletons along the way. One place should hopefully be more safe now, but there are for sure other places to discover...
