### ISSUE TITLE
Eclipse compiler produces bytecode which do not pass ASM 9.6 verification 'Error at instruction 0: Incompatible stack heights '

### ISSUE THREAD

**Issue by robserm** [eclipse-jdt/eclipse.jdt.core#2356]
Recently I have discovered that some of the java sources in Eclipse  are compiled to possibly incorrect bytecode.
For example, if you compile the following snippet in Eclipse 2023-12 it does not pass ASM verification:

```
public class InvalidClass {

    public static Map<String, Properties> readLocations(InputStream cvgReportStream)
    {
        Map<String, Properties> locations = new HashMap<>();
        LocationsReader reader = new LocationsReader();
        Set<String> locationRefs = new HashSet<String>();
        locationRefs.forEach(locRef -> locations.put(locRef, reader.getStoredLocation(locRef)));
        return locations;
    }
    
    static class LocationsReader{
    	public Properties getStoredLocation(String locRef)
    	{
    		return new Properties();
    	}
    }
}
```

An important note is that it is invalid for ASM 9.6 or above. 
For older ASMs like 9.2 it passes verification flawlessly. To validate it use the following code snippet:
```
        InputStream resourceAsStream = getClass().getResourceAsStream("/InvalidClass.class");
        ClassReader reader = new ClassReader(resourceAsStream);
        reader.accept(new CheckClassAdapter(new ClassWriter(0)), 0);
```

and here is the error produced by the ASM verification:

```
java.lang.IllegalArgumentException: Error at instruction 0: Incompatible stack heights lambda$0(Ljava/util/Map;LInvalidClass$LocationsReader;Ljava/lang/String;)V
00000 R R R  : R  :    L0
00001 R R R  :  :     LINENUMBER 35 L0
00002 R R R  :  :     ALOAD 0
00003 R R R  : R  :     ALOAD 2
00004 R R R  : R R  :     ALOAD 1
00005 R R R  : R R R  :     ALOAD 2
00006 R R R  : R R R R  :     INVOKEVIRTUAL InvalidClass$LocationsReader.getStoredLocation (Ljava/lang/String;)Ljava/util/Properties;
00007 R R R  : R R R  :     INVOKEINTERFACE java/util/Map.put (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (itf)
00008 R R R  : R  :     RETURN
00009 ?        :    L1


	at org.objectweb.asm.util.CheckMethodAdapter$1.throwError(CheckMethodAdapter.java:489)
	at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(CheckMethodAdapter.java:475)
	at org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:796)
	at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(CheckMethodAdapter.java:1044)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1519)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:745)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
```

Another important note is that bytecode produced by 'javac' for the same sourcecode passes verification without any problems.

**Comment by iloveeclipse** [comment]
Could you please try latest Eclipse build: https://download.eclipse.org/eclipse/downloads/drops4/I20240417-1800/ ?

**Comment by srikanth-sankaran** [comment]
Please provide full test case with imports and such in future, thanks

> Recently I have discovered that some of the java sources in Eclipse are compiled to possibly incorrect bytecode. For example, if you compile the following snippet in Eclipse 2023-12 it does not pass ASM verification:

Does the VM complain about the class ? If not, it is more likely to be an ASM issue. The code produced by javac could be very different and may not add much to the picture.

**Comment by robserm** [comment]
the code snippet that verifies the bytecode updated, now it is a full junit test 

@iloveeclipse I verified the problem against the installation from the link and unfortunately, it gives the same result

@srikanth-sankaran it seems that VM is not complaining, but we are worried that such somehow invalid bytecode may lead to some serious issues. For example, now we are not able to verify the correctness of the instrumentation of such classes.

**Comment by robserm** [comment]
Hi there, 
I checked it and it passes verification on ASM 9.3, but on any higher version it does **not** pass (including 9.7 ASM)
I have attached a full miniproject on which you verify easily the issue.
