### ISSUE TITLE
NPE when doing a Reference search (Workspace) on a method

### ISSUE THREAD

**Issue by chrisrueger** [eclipse-jdt/eclipse.jdt.core#2381]
1. I have an inner class
`FieldTypeDefinition2.FieldTypeDefinitionBuilder2.build()`

e.g.

```
public class FieldTypeDefinition2 implements java.io.Serializable {

    public FieldTypeDefinition2(FieldTypeDefinitionBuilder2 fieldTypeDefinitionBuilder2) {
        // TODO Auto-generated constructor stub
    }

    public static class FieldTypeDefinitionBuilder2 {
         public FieldTypeDefinition2 build() {
            return new FieldTypeDefinition2(this);
        }
    }
}
```

2. When right-click on the `build()` method and a `Refeferences / Workspace`

I get: 

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.leafComponentType()" because "this.resolvedType" is null
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveAnnotations(TypeReference.java:715)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.updateWithAnnotations(TypeReference.java:675)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.updateWithAnnotations(SingleTypeReference.java:164)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.updateParameterizedTypeWithAnnotations(TypeReference.java:681)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.updateWithAnnotations(ParameterizedQualifiedTypeReference.java:547)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.updateWithAnnotations(TypeDeclaration.java:1919)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.updateSupertypesWithAnnotations(TypeDeclaration.java:1897)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.updateSupertypesWithAnnotations(TypeDeclaration.java:1911)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.updateSupertypesWithAnnotations(TypeDeclaration.java:1911)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.integrateAnnotationsInHierarchy(CompilationUnitScope.java:402)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment$CompleteTypeBindingsSteps.perform(LookupEnvironment.java:173)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:543)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1345)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.jdt.internal.ui.search.JavaSearchQuery.run(JavaSearchQuery.java:178)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Environment:** 

Version: 2023-12 (4.30.0)
Build id: 20231201-2043

```
eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=de_DE
```

**Comment by iloveeclipse** [comment]
Please try if this is still reproducible in latest 4.32 I-Build from https://download.eclipse.org/eclipse/downloads/
