### ISSUE TITLE
JDT Core throws NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.AnnotationBinding.getAnnotationType()" because "internalAnnotation" is null

### ISSUE THREAD

**Issue by r0texx** [eclipse-jdt/eclipse.jdt.core#2402]
Hello,

I'm trying to build a source, but JDT Core throws an exception when calling `ClassInstanceCreation.resolveConstructorBinding().getAnnotations()`:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.AnnotationBinding.getAnnotationType()" because "internalAnnotation" is null
	at org.eclipse.jdt.core.dom.MethodBinding.filterTypeAnnotations(MethodBinding.java:245)
	at org.eclipse.jdt.core.dom.MethodBinding.getAnnotations(MethodBinding.java:134)
	at main.PoCMain$1$1.visit(Main.java:112)
	at org.eclipse.jdt.core.dom.ClassInstanceCreation.accept0(ClassInstanceCreation.java:293)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:677)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:498)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
```

For the following test source (save it to a directory and change the `ROOT` variable):
```java
package test;

public class TestClass {
    @com.Missing
    public TestClass() {
        new test.TestClass();
    }
}

class com {
}
```

I use the following code to parse it using JDT Core:
```java
package main;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.jdt.core.dom.AST;
import org.eclipse.jdt.core.dom.ASTParser;
import org.eclipse.jdt.core.dom.FileASTRequestor;

public class PoCMain {
    private static final File ROOT = new File("PATH_WHERE_YOU_UNPACK_test.TestClass");
    
    public static void main(String[] args) throws Throwable {
        List<String> files = findSources(ROOT, ".java");
        getParser().createASTs(files.toArray(new String[files.size()]), null, new String[0], new FileASTRequestor() {
            @Override
            public void acceptAST(String sourceFilePath, CompilationUnit ast) {
                ast.accept(new ASTVisitor() {
                    @Override
                    public boolean visit(ClassInstanceCreation node) {
                        IMethodBinding binding = node.resolveConstructorBinding();
                        if (binding != null) {
                            binding.getAnnotations();
                        }
                        return true;
                    }
                });
            }
        }, null);
    }
    
    private static ASTParser getParser() {
        ASTParser astParser = ASTParser.newParser(AST.JLS21);
        astParser.setResolveBindings(true);
        astParser.setStatementsRecovery(true);
        astParser.setBindingsRecovery(true);
        astParser.setKind(ASTParser.K_COMPILATION_UNIT);
        astParser.setEnvironment(new String[0], new String[0], null, false);
        
        Map<String, String> options = JavaCore.getDefaultOptions();
        options.put(JavaCore.COMPILER_COMPLIANCE, JavaCore.VERSION_21);
        options.put(JavaCore.COMPILER_SOURCE, JavaCore.VERSION_21);
        options.put(JavaCore.COMPILER_CODEGEN_TARGET_PLATFORM, JavaCore.VERSION_21);
        astParser.setCompilerOptions(options);
        return astParser;
    }
    
    private static List<String> findSources(File dir, String ext) {
        List<String> paths = new ArrayList<>();
        for (File child : dir.listFiles()) {
            if (child.isFile()) {
                if (child.getName().endsWith(ext)) {
                    paths.add(child.getAbsolutePath());
                }
            } else {
                paths.addAll(findSources(child, ext));
            }
        }
        
        return paths;
    }
}
```

**Comment by jukzi** [comment]
@r0texx please contribute a junit test that shows the error. There are similar tests in org.eclipse.jdt.core.tests.dom.StandAloneASTParserTest

**Comment by r0texx** [comment]
Hey @jukzi,

For some reason, I don't see a way to send a PR from my fork. Do you mind adding it by yourself? My test is the following:
```java


	public void testBugGithub2402() throws JavaModelException {
	        String contents =
	                "package test;\n"
	                + "\n"
	                + "public class TestClass {\n"
	                + "    @com.Missing\n"
	                + "    public TestClass() {\n"
	                + "        new test.TestClass();\n"
	                + "    }\n"
	                + "}\n"
	                + "\n"
	                + "class com {\n"
	                + "}\n";
	
	        ASTParser parser = ASTParser.newParser(AST.JLS20);
	        parser.setResolveBindings(true);
	        parser.setStatementsRecovery(true);
	        parser.setBindingsRecovery(true);
	        parser.setKind(ASTParser.K_COMPILATION_UNIT);
	        parser.setEnvironment(new String[0], new String[0], null, false);
	        parser.setSource(contents.toCharArray());
	        parser.setUnitName("test.TestClass");
	        
	        Map<String, String> options = JavaCore.getDefaultOptions();
	        options.put(JavaCore.COMPILER_COMPLIANCE, JavaCore.VERSION_17);
	        options.put(JavaCore.COMPILER_SOURCE, JavaCore.VERSION_17);
	        options.put(JavaCore.COMPILER_CODEGEN_TARGET_PLATFORM, JavaCore.VERSION_17);
	        parser.setCompilerOptions(options);
	        ASTNode node = parser.createAST(null);
	        assertTrue("Should be a compilation unit", node instanceof CompilationUnit);
	        
	        CompilationUnit cu = (CompilationUnit) node;
	        TypeDeclaration type = (TypeDeclaration) cu.types().get(0);
	        MethodDeclaration method = (MethodDeclaration) type.bodyDeclarations().get(0);
	        ExpressionStatement stmt = (ExpressionStatement) method.getBody().statements().get(0);
	        ClassInstanceCreation expr = (ClassInstanceCreation) stmt.getExpression();
	        IMethodBinding ctorBinding = expr.resolveConstructorBinding();
	        assertNotNull(ctorBinding);
	        IAnnotationBinding[] annotations = ctorBinding.getAnnotations();
	        assertNotNull(annotations);
	}
```

**Comment by jukzi** [comment]
> For some reason, I don't see a way to send a PR from my fork.

There is a instruction on https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md how to build a PR. For copyright reasons it is not allowed to copy arbitrary source. You will need an ECA.

**Comment by r0texx** [comment]
@jukzi 
Is there a way to fix the bug without that bureaucracy stuff?

**Comment by jukzi** [comment]
You can hire someone to fix it or join the IDE workinggroup (even more bureaucracy).
We are short on resources, but this is open source and contributions are welcome.

**Comment by subyssurendran666** [comment]
@mpalat I can take-up this task. Could you please assign this ticket to me.

**Comment by subyssurendran666** [comment]
Since the issue has been fixed, closing it.
