### ISSUE TITLE
Fix MT issues in org.eclipse.jdt.internal.core.builder.ClasspathJrt & Co

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#242]
Follow up on #183 findings. Similar static caches that were found in unsafe code in `org.eclipse.jdt.internal.compiler.*batch*.ClasspathJrt` exist in `org.eclipse.jdt.internal.core.*builder*.ClasspathJrt` in the IDE related builder code.

We should fix that code before trying to rework same code in #238.

I plan to push a PR soon.

**Comment by iloveeclipse** [comment]
There is a regression, see
https://download.eclipse.org/eclipse/downloads/drops4/I20220718-1800/testresults/ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11/org.eclipse.jdt.debug.tests.AutomatedSuite.txt
```
!ENTRY org.eclipse.core.resources 4 2 2022-07-19 00:50:25.962
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1690)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrt.loadModules(ClasspathJrt.java:122)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.loadModules(ClasspathJrtWithReleaseOption.java:147)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:83)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:169)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.computeClasspathLocations(NameEnvironment.java:333)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.<init>(NameEnvironment.java:63)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:644)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:182)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by cdietrich** [comment]
we see all of our xtend tests fail cause of this 
https://github.com/eclipse/xtext-xtend/issues/1361

**Comment by iloveeclipse** [comment]
@cdietrich : sure, I'm on it.
