### ISSUE TITLE
[win] (random?) failing MultiProjectTests

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2446]
testCycle3() and testCycle4() failed in:

https://download.eclipse.org/eclipse/downloads/drops4/I20240514-1800/testresults/html/org.eclipse.jdt.core.tests.builder_ep432I-unit-win32-java17_win32.win32.x86_64_17.html

```
Java Model Exception: Error in Java Model (code 977): Build path contains duplicate entry: 'C:PROGRA~1/ECLIPS~1/jdk-17.0.5.8-hotspot/lib/jrt-fs.jar' for project 'P1'
at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:801)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3518)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3478)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3534)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.setClasspath(TestingEnvironment.java:1199)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addEntry(TestingEnvironment.java:365)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addExternalJars(TestingEnvironment.java:336)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addExternalJars(TestingEnvironment.java:324)
at org.eclipse.jdt.core.tests.builder.MultiProjectTests.testCycle3(MultiProjectTests.java:585)
```

can not reproduce locally, no related recent commits. 
the error meessage is from org.eclipse.jdt.internal.core.ClasspathEntry.validateClasspath(IJavaProject, IClasspathEntry[], IPath), the classpath is probably set in

```
Thread [main] (Suspended (breakpoint at line 2396 in JavaProject))	
	JavaProject.getRawClasspath() line: 2396	
	TestingEnvironment.getRawClasspath(IPath) line: 609	
	TestingEnvironment.addEntry(IPath, IClasspathEntry) line: 361	
	TestingEnvironment.addExternalJars(IPath, String[], boolean) line: 336	
	TestingEnvironment.addExternalJars(IPath, String[]) line: 324	
	MultiProjectTests.testCompileOnlyDependent() line: 52	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 77	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 568	
	MultiProjectTests(TestCase).runTest() line: 177	
	MultiProjectTests(TestCase).runTest() line: 972	
	MultiProjectTests(TestCase).runBare() line: 142	
	TestResult$1.protect() line: 122	
	TestResult.runProtected(Test, Protectable) line: 142	
	TestResult.run(TestCase) line: 125	
	MultiProjectTests(TestCase).run(TestResult) line: 130	
	OrderedTestSuite(TestSuite).runTest(Test, TestResult) line: 241	
	OrderedTestSuite(TestSuite).run(TestResult) line: 236	
	SuiteMethod(JUnit38ClassRunner).run(RunNotifier) line: 90	
	JUnit4TestReference.run(TestExecution) line: 93	
	TestExecution.run(ITestReference[]) line: 40	
	RemotePluginTestRunner(RemoteTestRunner).runTests(String[], String, TestExecution) line: 529	
	RemotePluginTestRunner(RemoteTestRunner).runTests(TestExecution) line: 757	
	RemotePluginTestRunner(RemoteTestRunner).run() line: 452	
	RemotePluginTestRunner.main(String[]) line: 83	
	CoreTestApplication.start(IApplicationContext) line: 28	
	EclipseAppHandle.run(Object) line: 208	
	EclipseAppLauncher.runApplication(Object) line: 143	
	EclipseAppLauncher.start(Object) line: 109	
	EclipseStarter.run(Object) line: 439	
	EclipseStarter.run(String[], Runnable) line: 271	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 77	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 568	
	Main.invokeFramework(String[], URL[]) line: 668	
	Main.basicRun(String[]) line: 605	
	Main.run(String[]) line: 1481	
	Main.main(String[]) line: 1454	
```

probably random fail

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3081
