### ISSUE TITLE
JEP 482: access to enclosing instance in anonyous type in preconstructor context not reported

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2464]
This program:
```
public class Test {
	String name = "Test";
	Test() {
		Runnable r = new Runnable() {
			@Override
			public void run() {
				System.out.println(Test.this);
				System.out.println(name);
			}
		};
		r.run();
		super();
	}
	public static void main(String[] args) {
		new Test();
	}
}
```
contains two violations of this from [8.1.3 Inner Classes and Enclosing Instances](https://cr.openjdk.org/~gbierman/jep447/jep447-20230927/specs/statements-before-super-jls.html#jls-8.1.3) :
> An instance of an anonymous class whose declaration occurs in a pre-construction context ([8.8.7.1](https://cr.openjdk.org/~gbierman/jep447/jep447-20230927/specs/statements-before-super-jls.html#jls-8.8.7.1)) has no immediately enclosing instance.

ecj fails to report these.

Interestingly, javac reports only one error at a time, to see the second error you have to comment the first error statement:
```
Test.java:7: error: no enclosing instance of type Test is in scope
                                System.out.println(Test.this);
                                                       ^
1 error
```
then
```
Test.java:8: error: no enclosing instance of type Test is in scope
                                System.out.println(name);
                                                   ^
1 error
```

But wait, that sentence is missing from https://cr.openjdk.org/~gbierman/jep482/jep482-20240514/specs/flexible-constructor-bodies-jls.html#jls-8.1.3 does that mean this will be legal going forward?

**Comment by stephan-herrmann** [comment]
> But wait, that sentence is missing from https://cr.openjdk.org/~gbierman/jep482/jep482-20240514/specs/flexible-constructor-bodies-jls.html#jls-8.1.3 does that mean this will be legal going forward?

@mpalat  do you have any information about such a change post Java 22?

**Comment by stephan-herrmann** [comment]
The obvious consequences of failing to report errors: the program can be executed producing this output:
```
null
Exception in thread "main" java.lang.NullPointerException: Cannot read field "name" because "this.this$0" is null
	at StatsBeforeSuper/test.Test$1.run(Test.java:11)
	at StatsBeforeSuper/test.Test.<init>(Test.java:16)
	at StatsBeforeSuper/test.Test.main(Test.java:21)
```
The explicit `Test.this` reference is `null`, and an implicit one throws NPE. Not nice :smile:

**Comment by stephan-herrmann** [comment]
>>  An instance of an anonymous class whose declaration occurs in a pre-construction context ([8.8.7.1](https://cr.openjdk.org/~gbierman/jep447/jep447-20230927/specs/statements-before-super-jls.html#jls-8.8.7.1)) has no immediately enclosing instance.
>
> But wait, that sentence is missing from https://cr.openjdk.org/~gbierman/jep482/jep482-20240514/specs/flexible-constructor-bodies-jls.html#jls-8.1.3 does that mean this will be legal going forward?

It seems this was just redundant vs. the following from 15.9.2:
> If C is an anonymous class, then:
> * If the class instance creation expression occurs in a static context or a pre-construction context, then i has no immediately enclosing instance.

But also this addition is missing in newer drafts. :thinking:

**Comment by stephan-herrmann** [comment]
According to [recent clarification](https://mail.openjdk.org/pipermail/amber-spec-experts/2024-May/004137.html) a change of strategy happened:
> The first step was to recognize that an early construction context is not the same thing as a static context. The next step was to allow enclosing instances for classes in early construction contexts. And the third step was to ensure that the restrictions on references from early construction contexts continue to apply appropriately inside nested classes.

This implies we need to apply these:
* for `Test.this`: §15.8.4 Qualified this
  *  It is a compile-time error if a qualified this expression occurs in an early construction context ([8.8.7.1](https://cr.openjdk.org/~gbierman/jep482/jep482-20240514/specs/flexible-constructor-bodies-jls.html#jls-8.8.7.1)) of the class named by TypeName.
* for `name`: §6.5.6.1 Simple Expression Names
  * following must be true, or a compile-time error occurs:
     * If the expression name appears in an early construction context of C ([8.8.7.1](https://cr.openjdk.org/~gbierman/jep482/jep482-20240514/specs/flexible-constructor-bodies-jls.html#jls-8.8.7.1)), then it is the left-hand operand of a simple assignment expression ([15.26](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-15.26)), ...

Indeed both these rules are violated by the given example. See that both rules specifically mention the class to which the restriction applies. Other enclosings may be unaffected.

**Comment by stephan-herrmann** [comment]
Revolved via #2685
