### ISSUE TITLE
new NPE with latest i-build

### ISSUE THREAD

**Issue by cdietrich** [eclipse-jdt/eclipse.jdt.core#247]
with the latest i-build we see this new NPE

```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.createHandle(MatchLocator.java:528)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2545)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3298)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3310)
	at org.eclipse.jdt.internal.core.search.matching.MemberDeclarationVisitor.visit(MemberDeclarationVisitor.java:330)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1714)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:693)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:390)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:437)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2586)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3298)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2862)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2037)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1310)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1390)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1532)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
```
any ida what could have caused this?

**Comment by iloveeclipse** [comment]
I assume this is side effect of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/242

**Comment by cdietrich** [comment]
unfortunately not. i was trying your patch

type is MapEntry (not open) [in HashBiMap$1$MapEntry.class [in com.google.common.collect [in /Users/cdietrich/.p2/pool/plugins/com.google.guava_30.1.0.v20210127-2300.jar]]]
and declaring type is null

**Comment by iloveeclipse** [comment]
Were tests OK with I20220718-0710 build? 
If yes, I only see #242 changes there, so if #245 doesn't help: how I can reproduce this NPE?

**Comment by cdietrich** [comment]
test was green with org.eclipse.jdt.core_3.30.100.v20220717-1600.jar 
we run tests only once a day against latest platform

here is that the test does

```
IJavaSearchScope searchScope = SearchEngine.createJavaSearchScope(new IJavaElement[] { javaProject });
			SearchRequestor searchRequestor = new SearchRequestor() {
				@Override
				public void acceptSearchMatch(SearchMatch match) throws CoreException {
					Object element = match.getElement();
					if (element instanceof IMethod) {
						IMethod constructor = (IMethod) element;
						allScopedElements.add(createScopedElement(constructor));	
					} else if (element instanceof IType) {
						allScopedElements.add(createScopedElement((IType)element));
					}
				}
			};
SearchPattern pattern = new ConstructorDeclarationPattern(null, null, SearchPattern.R_PREFIX_MATCH);
		new SearchEngine().search(pattern, SearchUtils.getDefaultSearchParticipants(), searchScope, searchRequestor, new NullProgressMonitor());
```

**Comment by iloveeclipse** [comment]
@cdietrich : could you try with the patch below on top of #245 ?
```
diff --git a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathJrtWithReleaseOption.java b/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathJrtWithReleaseOption.java
index 41f903c..943d1f0 100644
--- a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathJrtWithReleaseOption.java
+++ b/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathJrtWithReleaseOption.java
@@ -261,3 +261,3 @@
 	protected String getKey() {
-		return this.fs == null ? super.getKey() : this.modPathString;
+		return this.fs == null || this.modPathString == null ? super.getKey() : this.modPathString;
 	}
```

**Comment by cdietrich** [comment]
the 2nd patch wont help

**Comment by iloveeclipse** [comment]
@cdietrich : could at least add a pointer to the test code and test job? Or give a hint how one could run the test? You should also know on which JDK the code is executed?

**Comment by cdietrich** [comment]
@iloveeclipse you can clone https://github.com/eclipse/xtext-eclipse.git
and then import the org.eclipse.xtext.common.types.eclipse.tests project
and run JdtBasedConstructorScopeTest

**Comment by cdietrich** [comment]
will also test with older versions

**Comment by iloveeclipse** [comment]
@cdietrich : test is green for me, in IDE, with #245 and broken (with different NPE without the patch).

**Comment by iloveeclipse** [comment]
New IBuild is there: https://download.eclipse.org/eclipse/downloads/drops4/I20220719-0530/

**Comment by cdietrich** [comment]
[jdt-247.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9141260/jdt-247.zip)

can be reproduced:
install guava with sources from 
https://download.eclipse.org/tools/orbit/downloads/drops/R20220531185310/repository/

and do a constructor search with `*` in the project

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IType.getFullyQualifiedName()" because the return value of "org.eclipse.jdt.core.IType.getDeclaringType()" is null
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.createHandle(MatchLocator.java:528)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2545)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3298)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3310)
	at org.eclipse.jdt.internal.core.search.matching.MemberDeclarationVisitor.visit(MemberDeclarationVisitor.java:330)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1714)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:693)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:390)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:437)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2586)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3298)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2862)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2037)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1353)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1390)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1532)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.ui.search.JavaSearchQuery.run(JavaSearchQuery.java:178)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by iloveeclipse** [comment]
Short summary of what we've found so far: this is not caused by a regression in 4.25 JDT **code**, but in 4.25 **platform** that now JDT somehow "sees" guava **sources**. Adding guava sources to 4.24 target also breaks with same NPE.

The problem seem only appear in PDE based projects, we were unable to reproduce it with plain Java projects so far.

**Comment by iloveeclipse** [comment]
> update/correction, when source is properly attached, can also be reproduced with normal java project

Please attach updated project with "properly" attached sources (whatever is meant by that :-))

**Comment by cdietrich** [comment]
[jdt-247-pure.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9141953/jdt-247-pure.zip)

**Comment by cdietrich** [comment]
looks like https://github.com/eclipse-jdt/eclipse.jdt.core/pull/245 has fixed the problem in tycho. so the problem locally and in tycho seems to have been different

**Comment by iloveeclipse** [comment]
@cdietrich : I know this is lame, but I've simply added NP check in related code, see #248.

I believe the JDT model around anonymous types is not consistent (and was that long time), but I have no clue where and how to fix that, and I fear this is not trivial task anyway.

**Comment by cdietrich** [comment]
thx. i guess not crashing would be enhough anyway.

**Comment by iloveeclipse** [comment]
> thx. i guess not crashing would be enhough anyway.

Do the tests work for you with new platform build?

**Comment by cdietrich** [comment]
the integ tests on jenkins did not run yet. 
locally i just git pulled. will try to oomph now

**Comment by cdietrich** [comment]
looks good, locally and on jenkins.
=> we can close this as fixed
