### ISSUE TITLE
Java Indexing reads source files multiple times

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2501]
I put a `System.out.println(file);` into 
` org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(IFile, String)`
and looked on the output after pressing "rebuild Index"

In the platform workspace that immediately showed multiple reads of for example CoreException.java
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/2ad5e19f-96ac-4d1a-a2a2-1a8d5332d944)

**Comment by jukzi** [comment]
typical stacktrace:
```
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(Util.java:1202)
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(Util.java:1196)
	at org.eclipse.jdt.internal.core.util.ResourceCompilationUnit.getContents(ResourceCompilationUnit.java:60)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12950)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12922)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11306)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.accept(SourceIndexer.java:131)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:373)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:626)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:698)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:525)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:600)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:172)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:116)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:680)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1286)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:542)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by jukzi** [comment]
At least the source is intendet to be cached in ResourceCompilationUnit.getContents() but everytime a new ResourceCompilationUnit is constructed like

```
Thread [Java indexing] (Suspended (breakpoint at line 34 in ResourceCompilationUnit))	
	ResourceCompilationUnit.<init>(IFile, char[]) line: 34	
	ClasspathSourceDirectory.findClass(String, String, String, String) line: 123	
	ClasspathSourceDirectory.findClass(String, String, String, String, boolean, Predicate<String>) line: 114	
	JavaSearchNameEnvironment.findClass(String, char[], IModuleAwareNameEnvironment$LookupStrategy, String) line: 376	
	JavaSearchNameEnvironment.findType(char[], char[][], char[]) line: 461	
	LookupEnvironment.fromSplitPackageOrOracle(IModuleAwareNameEnvironment, ModuleBinding, PackageBinding, char[]) line: 463	
	LookupEnvironment.lambda$1(IModuleAwareNameEnvironment, PackageBinding, char[], ModuleBinding) line: 336	
	0x000002630192fdb8.apply(Object) line: not available	
	LookupEnvironment.askForTypeFromModules(ModuleBinding, ModuleBinding[], Function<ModuleBinding,NameEnvironmentAnswer>) line: 430	
	LookupEnvironment.askForType(PackageBinding, char[], ModuleBinding) line: 335	
	PlainPackageBinding(PackageBinding).getTypeOrPackage(char[], ModuleBinding, boolean) line: 276	
	CompilationUnitScope.findImport(char[][], int) line: 626	
	CompilationUnitScope.findSingleImport(char[][], int, boolean) line: 698	
	CompilationUnitScope.faultInImports() line: 525	
	CompilationUnitScope.faultInTypes() line: 600	
	SourceIndexer.resolveDocument() line: 172	
	JavaSearchParticipant.resolveDocument(SearchDocument) line: 116	
	IndexManager.indexResolvedDocument(SearchDocument, SearchParticipant, Index, IPath) line: 680	
	IndexManager$2.execute(IProgressMonitor) line: 1286	
	IndexManager(JobManager).indexerLoop() line: 542	
	0x000002630155ae80.run() line: not available	
	Thread.runWith(Object, Runnable) line: 1596	
	Thread.run() line: 1583	
```
