### ISSUE TITLE
NoSuchFileException jclMin1.3.jar

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2524]
logged during tests - should not test for1.3 anymore?

```
[2024-05-27T06:26:27.956Z] [2024-05-27 06:26:27 +0000] org.eclipse.jdt.core.tests.model.CompletionTests2#testBug151500c()
[2024-05-27T06:26:27.956Z] Failed to init Classpath for jar file /home/jenkins/agent/workspace/eclipse.jdt.core-Github_PR-2477/org.eclipse.jdt.core.tests.model/target/work/jclMin1.3.jar
[2024-05-27T06:26:27.956Z] java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/eclipse.jdt.core-Github_PR-2477/org.eclipse.jdt.core.tests.model/target/work/jclMin1.3.jar
[2024-05-27T06:26:27.956Z] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[2024-05-27T06:26:27.956Z] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[2024-05-27T06:26:27.956Z] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[2024-05-27T06:26:27.956Z] 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:56)
[2024-05-27T06:26:27.956Z] 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
[2024-05-27T06:26:27.956Z] 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[2024-05-27T06:26:27.956Z] 	at java.base/java.nio.file.Files.readAttributes(Files.java:1858)
[2024-05-27T06:26:27.956Z] 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1491)
[2024-05-27T06:26:27.956Z] 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
[2024-05-27T06:26:27.956Z] 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
[2024-05-27T06:26:27.956Z] 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
[2024-05-27T06:26:27.956Z] 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:194)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:197)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:205)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:189)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.util.Util.compile(Util.java:254)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.util.Util.createJar(Util.java:460)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.util.Util.createJar(Util.java:484)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.createJar(AbstractJavaModelTests.java:1724)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.model.CompletionTests2.testBug151500c(CompletionTests2.java:5146)
[2024-05-27T06:26:27.956Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-05-27T06:26:27.956Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestCase.runTest(TestCase.java:177)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestCase.runBare(TestCase.java:142)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestResult.run(TestResult.java:125)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestCase.run(TestCase.java:130)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestSuite.runTest(TestSuite.java:241)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestSuite.run(TestSuite.java:236)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:98)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:86)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:95)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestSuite.runTest(TestSuite.java:241)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestSuite.run(TestSuite.java:236)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestSuite.runTest(TestSuite.java:241)
[2024-05-27T06:26:27.956Z] 	at junit.framework.TestSuite.run(TestSuite.java:236)
[2024-05-27T06:26:27.956Z] 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.test.TracingSuite.runChild(TracingSuite.java:279)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2024-05-27T06:26:27.956Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
[2024-05-27T06:26:27.956Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-05-27T06:26:27.956Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
[2024-05-27T06:26:27.956Z] 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:140)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.start(HeadlessTestApplication.java:29)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
[2024-05-27T06:26:27.956Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-05-27T06:26:27.956Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
[2024-05-27T06:26:27.956Z] 	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
[2024-05-27T06:26:27.957Z] 	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```

https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2477/2/consoleText

**Comment by stephan-herrmann** [comment]
Interesting find :)

AFAICS the file `JCL/jclMin1.3.jar` never existed. And the test shown in the stack doesn't need it either.
