### ISSUE TITLE
[Sealed types] Completion fails within the body of a permitted class

### ISSUE THREAD

**Issue by rgrunber** [eclipse-jdt/eclipse.jdt.core#2540]
Version: 2024-06 (4.32)
Build id: I20240505-1800

Simply trigger completion within the body of `SqlStorage`.

**Storage.java**
```
package org.example;

public sealed class Storage permits SqlStorage {
}
```

**SqlStorage.java**
```
package org.example;

public final class SqlStorage extends Storage {

}

```

```
!ENTRY org.eclipse.jdt.ui 4 0 2024-06-07 11:58:01.714
!MESSAGE RuntimeException computing completion proposal for SqlStorage.java at offset 70 line 4 :
package org.example;

public final class SqlStorage extends Storage {
|
!STACK 0
java.lang.NullPointerException: Cannot read the array length because "superPermittedTypes" is null
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkPermitsAndAdd(SourceTypeBinding.java:1345)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkPermitsInType(SourceTypeBinding.java:1201)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1116)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:608)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2329)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:135)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:360)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:350)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalComputeCompletionProposals(JavaCompletionProposalComputer.java:256)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeCompletionProposals(JavaCompletionProposalComputer.java:218)
	at org.eclipse.jdt.internal.ui.text.java.JavaTypeCompletionProposalComputer.computeCompletionProposals(JavaTypeCompletionProposalComputer.java:65)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:354)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:332)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:288)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

This worked in 4.31, and the `superPermittedTypes` list did in fact contain the reference to `Storage`.

See https://github.com/redhat-developer/vscode-java/issues/3636 for original bug. A similar stacktrace at https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1641#issuecomment-1847710779 .

**Comment by srikanth-sankaran** [comment]
This appears fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2093 - I'll add a regression test and close this

**Comment by srikanth-sankaran** [comment]
> This is a big issue with eclipse 2024-06 (4.32), do you plan to deliver a fix for it ?

My understanding (@mpalat or @jarthana may correct me) is that with the frequent releases brought about by the 3 month cadence used by Eclipse lately, we will not have maintenance releases of past versions. So please consider upgrading to 4.33 versions when they available,

**Comment by Vale68** [comment]
Sure but, at least in my opinion, this issue prevents the usage of sealed classes/interfaces with eclipse so I hope you will give priority to its resolution.
Probably I can try to downgrade to the 4.31 version.

**Comment by srikanth-sankaran** [comment]
> Sure but, at least in my opinion, this issue prevents the usage of sealed classes/interfaces with eclipse so I hope you will give priority to its resolution. Probably I can try to downgrade to the 4.31 version.

Hello! The issue is resolved already and fix is pushed to master HEAD. You can grab a suitable I build or 4.33 M1 when it is declared. Thanks

**Comment by alienisty** [comment]
The issue is back

```
java.lang.NullPointerException: Cannot read the array length because "methods" is null
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.getResolvedSignature(CompletionEngine.java:6380)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.proposeConstructor(CompletionEngine.java:14260)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.proposeConstructor(CompletionEngine.java:14024)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.acceptConstructors(CompletionEngine.java:1053)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findTypesAndPackages(CompletionEngine.java:11789)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnSingleTypeReference(CompletionEngine.java:3991)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:1866)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2209)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:139)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:451)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:441)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalComputeCompletionProposals(JavaCompletionProposalComputer.java:256)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeCompletionProposals(JavaCompletionProposalComputer.java:218)
	at org.eclipse.jdt.internal.ui.text.java.JavaTypeCompletionProposalComputer.computeCompletionProposals(JavaTypeCompletionProposalComputer.java:63)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:353)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:332)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:288)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Throwable: Source line 81 :
-----
  }

  @Bean
  public SettingPropertySourceLoader settingPropertySourceLoader(SettingRepository settings,
                                                                 TransactionTemplate tx) {
    return new SettingPropertySourceLoader(settings, tx);
  }
  
  @Bean
  public FileLedgerCoordinator fileLedgerCoordinator() {
    return new File|
-----
		at org.eclipse.jdt.internal.ui.util.SelectionUtil.logException(SelectionUtil.java:157)
		at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:373)
		... 13 more
```

```
eclipse.buildId=4.36.0.I20250528-1830
java.version=21.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_AU
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```

**Comment by srikanth-sankaran** [comment]
> The issue is back

No, the stack traces are completely unrelated. Other than that both problems result in NPE I don't see any connection between these two.
