### ISSUE TITLE
mac: Random failing CopyMoveElementsTests.testCopyFieldForce

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2552]
failed in two MacOS builds:
```
junit.framework.AssertionFailedError: No delta found for class Y [in Y.java [in <default> [in src [in P]]]]
boolean foo
int foo#2, all deltas: [Java Model[*]: {CHILDREN}
P[*]: {CHILDREN}
src[*]: {CHILDREN}
<default>[*]: {CHILDREN}
Y.java[*]: {CONTENT | PRIMARY RESOURCE}]
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.jdt.core.tests.model.CopyMoveTests.copyPositive(CopyMoveTests.java:122)
at org.eclipse.jdt.core.tests.model.CopyMoveElementsTests.testCopyFieldForce(CopyMoveElementsTests.java:215)

```
both:
https://download.eclipse.org/eclipse/downloads/drops4/I20240611-0150/testresults/html/org.eclipse.jdt.core.tests.model_ep433I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20240611-0150/testresults/html/org.eclipse.jdt.core.tests.model_ep433I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

May relate to another random fail of CopyMoveElementsTests.testCopyConstructorInDifferentProject:
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1094

**Comment by srikanth-sankaran** [comment]
`testCopyFieldInDifferentProject` occasionally fails too

**Comment by srikanth-sankaran** [comment]
`org.eclipse.jdt.core.tests.model.CopyMoveElementsTests.testCopyField` occasionally fails too

**Comment by stephan-herrmann** [comment]
Look, what I found in the console when `testCopyField` failed:
```
[2024-06-22T20:10:28.199Z] java.lang.Throwable: Refreshing workspace [Worker-0: Refreshing workspace] Caller of IElementChangedListener#elementChanged with delta Java Model[*]: {CHILDREN}
[2024-06-22T20:10:28.199Z] 	P[*]: {CHILDREN}
[2024-06-22T20:10:28.199Z] 		src[*]: {CHILDREN}
[2024-06-22T20:10:28.199Z] 			<default>[*]: {CHILDREN}
[2024-06-22T20:10:28.199Z] 				Y.java[*]: {CONTENT | PRIMARY RESOURCE}
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests$DeltaListener.elementChanged(AbstractJavaModelTests.java:390)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1751)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1739)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1572)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1548)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyAndFire(DeltaProcessor.java:2259)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2151)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:501)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:459)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1587)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:50)
[2024-06-22T20:10:28.199Z] 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

What's more: I can reproduce locally (here it's happens consistently on `testCopyConstructor`)

**Comment by stephan-herrmann** [comment]
The only thing unusual in the above log output: normally `elementChanged()` is executed on thread `main`, but in the above logs it says `Refreshing workspace [Worker-0: Refreshing workspace]`!

So, here's a recipe for seeing it fail:
* breakpoint in CopyMoveTests.copyPositive(IJavaElement, IJavaElement, IJavaElement, String, boolean) on line 73 (invocation of `copy()`)
* breakpoint in org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(IProgressMonitor) first line
* launch headless debug session for `CopyMoveElementsTests`
* both breakpoints will be triggered in different threads (main resp. "Refreshing workspace")
* in main step over `copy()`
* resume thread "Refreshing workspace"
* continue in main will see the failure

I believe this happens, because running `AbstractJavaModelTests$DeltaListener.elementChanged()` in the refresh thread happens before main calls `waitForAutoBuild()`, and hence the delta notifications will be consume before they are fully built.

At face value, couldn't this be an actual bug, not a test-only issue? In real life, clients could rely on seeing the detailed delta, but when a workspace refresh kicks in at the unfortunate moment, the delta will be incomplete.

OTOH, the test could be made more robust by adding this line between `copy()` and `waitForAutoBuild()`:
`element.getJavaProject().getProject().build(IncrementalProjectBuilder.FULL_BUILD, null);`

This indicates, that all expected deltas will *eventually* be sent. Is the assumption wrong, that `waitForAutoBuild()` will ensure all deltas to be sent?

**Comment by stephan-herrmann** [comment]
Happened again during a PR build:
```
org.eclipse.jdt.core.tests.model.CopyMoveElementsTests.testCopyFieldForce

No delta found for class Y [in Y.java [in <default> [in src [in P]]]]
  boolean foo
  int foo#2, all deltas: [Java Model[*]: {CHILDREN}
 P[*]: {CHILDREN}
  src[*]: {CHILDREN}
   <default>[*]: {CHILDREN}
    Y.java[*]: {CONTENT | PRIMARY RESOURCE}]
```

**Comment by trancexpress** [comment]
Maybe related, `CopyMoveElementsTests.testCopyFieldsMultiStatus` failed here: https://download.eclipse.org/eclipse/downloads/drops4/I20260429-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep440I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

Diff between logged deltas when running the test from Eclipse (before) and in the failed build (after):

```
@@ -43,7 +43,7 @@
        kind: 4, resource: F/P/src
        kind: 1, resource: L/P/src/Y.java
 Logging resource change event
-thread: main
+thread: Worker-0: Refreshing workspace
 type: 1
 buildKind: 0
 resource: null
@@ -53,6 +53,10 @@
        kind: 4, resource: P/P
        kind: 4, resource: F/P/src
        kind: 4, resource: L/P/src/Y.java
+               "P[*]: {CHILDREN}\n" +
+               "       src[*]: {CHILDREN}\n" +
+               "               <default>[*]: {CHILDREN}\n" +
+               "                       Y.java[*]: {CONTENT | PRIMARY RESOURCE}"
 Logging resource change event
 thread: main
 type: 1
```

So maybe waiting on auto-refresh helps.

**Comment by trancexpress** [comment]
@stephan-herrmann anything against stabilizing the test (or at least trying to) and keeping the ticket open for looking into the potential production problem?

**Comment by stephan-herrmann** [comment]
> [@stephan-herrmann](https://github.com/stephan-herrmann) anything against stabilizing the test (or at least trying to) and keeping the ticket open for looking into the potential production problem?

What exactly do you propose? We're not sure to what degree #2629 improved the situation.

As for `CopyMoveElementsTests.testCopyFieldsMultiStatus()` this test doesn't benefit from #2629 as it calls `copy()` directly rather than through `CopyMoveTests.copyPositive()`. OTOH, a quick experiment using the recipe from [this comment](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2552#issuecomment-2184309320) brought up nothing because in this case I don't see the breakpoint in `RefreshJob` triggering.  Do you?

**Comment by trancexpress** [comment]
> What exactly do you propose?

I'll start adding waits for whichever parallel jobs process delta notifications, the first one would be the auto-refresh: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2552#issuecomment-4349970875

If there is more code to wait on, the verbose outputs in the logs should show which code that is.

This so far seems to be the most time efficient way to avoid the sporadic fails in JDT tests.

**Comment by stephan-herrmann** [comment]
> I'll start adding waits for whichever parallel jobs process delta notifications, the first one would be the auto-refresh: [#2552 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2552#issuecomment-4349970875)

Do you have indications that refresh has a finger in the pie with this test case? As mentioned I could not get a breakpoint on `RefreshJob.runInWorkspace()` to trigger during that test.

**Comment by trancexpress** [comment]
> Do you have indications that refresh has a finger in the pie with this test case? As mentioned I could not get a breakpoint on `RefreshJob.runInWorkspace()` to trigger during that test.

The verbose output diff listed here: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2552#issuecomment-4349970875

I'm guessing something has to be delayed for the refresh job to actually do a delta notification. I don't think debugging here until the race condition is explained is a good use of time, I've already tried debugging many of the sporadic fails in JDT. I resorted to verbose outputs in the logs because of debugging not getting me anywhere.

**Comment by stephan-herrmann** [comment]
> The verbose output diff listed here: [#2552 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2552#issuecomment-4349970875)

When first looking at that, I failed to see the part about "Worker-0: Refreshing workspace". Sorry.

With that I'm fine with trying the waiting approach also here.
