### ISSUE TITLE
Unhandled event loop exception : java.nio.file.InvalidPathException: Illegal char <<> at index 115:

### ISSUE THREAD

**Issue by btheu** [eclipse-jdt/eclipse.jdt.core#2562]
Building a simple project java maven with renjin dependencies makes eclipse UI error.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test-eclipse</groupId>
  <artifactId>test-eclipse</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <repositories>
  <repository>
  <id>beta</id>
  <url>https://nexus.bedatadriven.com/content/groups/public/</url>
  </repository>
  </repositories>
  <dependencies>
  <dependency>
    <groupId>org.renjin</groupId>
    <artifactId>renjin-core</artifactId>
    <version>3.5-beta75</version>
</dependency>
  </dependencies>
</project>
```

When using Eclipse UI action "Create a java class" nothing happen, here the Eclipse error:

```
java.nio.file.InvalidPathException: Illegal char <<> at index 115: C:\Users\test\.m2\repository\org\renjin\renjin-core\3.5-beta75\renjin-core-3.5-beta75.jar\org/renjin/base/[[<-.data.frame.RData
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at org.eclipse.jdt.internal.core.util.Util.getEntryName(Util.java:3364)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.computeChildren(JarPackageFragmentRoot.java:154)
	at org.eclipse.jdt.internal.core.JavaProjectElementInfo.initializePackageNames(JavaProjectElementInfo.java:276)
	at org.eclipse.jdt.internal.core.JavaProjectElementInfo.getProjectCache(JavaProjectElementInfo.java:244)
	at org.eclipse.jdt.internal.core.JavaProjectElementInfo.newNameLookup(JavaProjectElementInfo.java:313)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2799)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2793)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2811)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2803)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1704)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1605)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.setSuperClassType(NewTypeWizardPage.java:2681)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.typePageDialogFieldChanged(NewTypeWizardPage.java:1364)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage$TypeFieldsAdapter.dialogFieldChanged(NewTypeWizardPage.java:1265)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.DialogField.dialogFieldChanged(DialogField.java:78)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.StringDialogField.setText(StringDialogField.java:195)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.setSuperClass(NewTypeWizardPage.java:1660)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.initTypePage(NewTypeWizardPage.java:762)
	at org.eclipse.jdt.ui.wizards.NewClassWizardPage.init(NewClassWizardPage.java:92)
	at org.eclipse.jdt.internal.ui.wizards.NewClassCreationWizard.addPages(NewClassCreationWizard.java:56)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:634)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:98)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
```

Level: Critical
  This issue makes whole eclipse unusable as long one project in the workspace has this dependencies.

Broken versions:
  Eclipse-jee 2024-03 & 2024-06

Version not impacted:
  Eclipse-jee 2023-12

**Comment by iloveeclipse** [comment]
`Illegal char <<> at index 115: C:\Users\test\.m2\repository\org\renjin\renjin-core\3.5-beta75\renjin-core-3.5-beta75.jar\org/renjin/base/[[<-.data.frame.RData`

This path looks strange but it is in fact inside the jar file:
https://mvnrepository.com/artifact/org.renjin/renjin-core/3.5-beta75
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/f2fad790-b605-414e-a1da-f206cc624507)

This is a regression from fc75d8237441ae0011508f6e08e45e8123d441b3.
@jukzi : could you please check?

**Comment by jukzi** [comment]
The path is not a valid path in windows. you can not extract the jar on windows. what do you expect to happen?
The library is marked with several CVEs regarding specially crafted archive, so i don't care.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/2eca8184-6ee6-4a1b-928d-d18bff5197c2)

**Comment by iloveeclipse** [comment]
> you can not extract the jar on windows. what do you expect to happen?

It is not about user extracting anything, it is about JDT looking for types in a jar and failing now.

> The library is marked with several CVEs regarding specially crafted archive, so i don't care.

Sorry, this is totally wrong attitude. We cannot / should not assume anything about which libraries user wants to compile or use.

**Comment by btheu** [comment]
Indeed, this library is not the cleanest one. For context, I am not the final user of this library in my organization, but we need to support it and select tools that can handle it. I agree with @iloveeclipse we should not judge final user. About CVEs, I think this is security topic and not related with the current issue.

Is it possible to simply ignore such strange files in the jar to avoid sudden failures?

**Comment by stephan-herrmann** [comment]
I wonder about this segment:
```
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at org.eclipse.jdt.internal.core.util.Util.getEntryName(Util.java:3364)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.computeChildren(JarPackageFragmentRoot.java:154)
```

Does anything in the specification of jar files suggests the use of `java.nio.file.Path`?

If yes, then it seems that rejecting the file would be correct (and only the way the error is reported should be improved).

If no, then we should indeed improve the resilience and read from that jar just what we possibly can.

OTOH, if these bogus entries are indeed part of a vulnerability, it would be a great service if JDT could raise an alert of this exact fact.

**Comment by stephan-herrmann** [comment]
> About CVEs, I think this is security topic and not related with the current issue.

As an aside, and speaking only for myself as a voluntary committer, I may well decide not to invest my time into making it easier to create insecure, vulnerable software. If the entry in question is part of a vulnerability (is it?), then I believe normal work ethics give room for personal decisions on this topic. I wonder if @mbarbero has a comment on this.

**Comment by jukzi** [comment]
As far as i understand a dangerous (forbidden/broken/invalid/malcius?) entry would land in org.eclipse.jdt.internal.core.OpenableElementInfo.nonJavaResources and there is no guaranty that all Consumers are aware that it can be dangerous to use the name. For example
org.eclipse.jdt.ui.tests.refactoring.GenericRefactoringTest.tryDeletingAllNonJavaChildResources(IPackageFragmentRoot) would just try to delete a file that it should not access. And the calltree is just too big to check all usages. At best we could maybe ignore/skip such entries, like 7zip does during extract, but i don't know how such missing entry might affect the consumers.  A missing node in the package explorer for example?
I personally do not want to use malcious libraries at all.

**Comment by iloveeclipse** [comment]
> If the entry in question is part of a vulnerability (is it?)

It is not. All vulnerabilities in question are coming from the **dependencies** of the library, not from the library itself.

> I may well decide not to invest my time into making it easier to create insecure, vulnerable software

Sure. But the problem here is and the reason I've assigned that to @jukzi: 
1) generic one: a jar containing "unusual" characters in the name or path of some entries can't be used anymore
2) it is a regression from https://github.com/eclipse-jdt/eclipse.jdt.core/commit/fc75d8237441ae0011508f6e08e45e8123d441b3 authored by @jukzi. In my world author of the change is responsible to fix the regression caused by the change.

**Comment by mbarbero** [comment]
I think there might be a red herring here. The artifact is flagged with vulnerabilities due to its dependency on a vulnerable version of Apache Commons Compress, not because of the unusual-looking JAR entries.

It appears that the code designed to prevent zip slip vulnerabilities (which is a positive measure) is overly strict -at least on Windows-, leading to this issue. From my perspective, addressing the reported issue would not compromise JDT security nor would it endanger JDT users by exposing them to malicious packages. Naturally, any fix should continue to guard against zip slips.

Ultimately, the decision to address this is in your hands, project committers.

@stephan-herrmann, I hope this clarifies the situation.

**Comment by mbarbero** [comment]
(I should add, please tag @eclipse-jdt/eclipsefdn-security rather than individuals when you need our input. You never know who will be available to participate in similar discussions. Thanks!)

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann, I hope this clarifies the situation.

Case settled. Thanks a lot!

**Comment by jukzi** [comment]
Before anyone works on a solution we should agree on how to handle
1. invalid paths (OS dependend)
2. zip slip paths

a) reject the whole archive
b) reject/skip single entry
c) do no validate

**Comment by netomi** [comment]
to give my 2c on this topic:

Renjin is an interpreter for R (the statistical language). It contains in its jar file also R files that are binary compiled (these RDATA files). At first I thought these are obfuscated files but looking at the sourcecode (https://github.com/bedatadriven/renjin/tree/master/core/src/main/R/base) they look legitimate. I did not figure out why in some cases the files start with special characters, but that might be some mangling they need to do. In general, just because a certain filesystem does not allow such filenames does not mean that the processing of such a library should fail imho.

So if during the processing with jdt the files are extracted to the local filesystem for further processing then it might mean that you will not be able to handle such jar files unless you can change that in some way. If these are just resource files that will not be processed by jdt, it might not be necessary, but I am not familiar with the workings of jdt.

I used to maintain ProGuard which is an optimizer / obfuscator for jar files, and from this experience I can say that this is basic obfuscation technique to name class files in a way that would not be supported e.g. by the file system by still allowed by the JVM specification, so that is not a totally unrealistic usecase. If such jars should be processable by jdt is another topic ofc.

**Comment by jukzi** [comment]
I vote:

1. invalid paths (OS dependend) => b) reject/skip single entry
2. zip slip paths =a) reject the whole archive

as a compromise. any objections?

**Comment by iloveeclipse** [comment]
Could you please check what the code did **before** with paths found in exact this jar / a jar with "strange" entry names as shown above?

For me it looks like it would go to: 
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/3eb741f97331662b5e08ae988a6c124eed607d50/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JarPackageFragmentRoot.java#L348

and there just "ignore" non-Java package names and later do some work that seem to be **not needed at all**  (`children` array is local)???:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/3eb741f97331662b5e08ae988a6c124eed607d50/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JarPackageFragmentRoot.java#L387-L396

Beside this the proposal sounds OK.

**Comment by jukzi** [comment]
> and there just "ignore" non-Java package names and later do some work that seem to be **not needed at all** (`children` array is local)???:

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2562#issuecomment-2165159999 those nonjava entries can later be used.

**Comment by jukzi** [comment]
example package explorer did show the entries:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/4861e47a-33fc-408f-acd9-c89381bdd2d3)

**Comment by jukzi** [comment]
with the proposed change it would not show the entry in package explorer:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/0117b9d7-5b8c-4159-b962-2f1a68a75ec0)

**Comment by jukzi** [comment]
proposed behaviour for zipslip:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/210213ee-d976-402f-b72a-5e426e3c09d6)

**Comment by jukzi** [comment]
@btheu please test the new build
https://download.eclipse.org/eclipse/downloads/drops4/I20240618-1800/

**Comment by btheu** [comment]
@jukzi This update fixed the issue.

Thanks
