### ISSUE TITLE
Show declaration (F3) & Mouseover Popups not working

### ISSUE THREAD

**Issue by DanskerDave** [eclipse-jdt/eclipse.jdt.core#2571]
One line of code causes F3 & Mouseover popups in the Java Editor to stop working.

Here's an example.

```
package org.eclipse;

import java.util.function.Predicate;
import java.util.function.Supplier;

public class PopupKiller {

	public final Supplier<Predicate<String>> predicateSupplier = () -> new Predicate<>() {

		@SuppressWarnings("unused")
		public static boolean THIS_VARIABLE_KILLS_JAVADOC_POPUPS_AND_F3 = true;

		@Override
		public boolean test(final String record) {

			System.out.println("<-- try to Mouseover System.out.: nothing!");

			return true;
		}
	};
}

```

Version.: newly downloaded Eclipse 2024-06 RCP/RAP
OS.: Windows 11

**Comment by stephan-herrmann** [comment]
Thanks, I could observe the following exception, which is silently swallowed unless `SelectionEngine.DEBUG` is set:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 30
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.commit(AssistParser.java:2334)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.triggerRecoveryUponLambdaClosure(AssistParser.java:596)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.consumeFieldDeclaration(AssistParser.java:736)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7026)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12707)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12965)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.parse(SelectionParser.java:1910)
```
(I happened to be in a workspace with sources as of some time in April this year).

Scanner state at that point is
```
----------------Scanner--------------
package org.eclipse;

import java.util.function.Predicate;
import java.util.function.Supplier;

public class PopupKiller {

	public final Supplier<Predicate<String>> predicateSupplier = () -> new Predicate<>() {

		@SuppressWarnings("unused")
		public static final boolean THIS_VARIABLE_KILLS_JAVADOC_POPUPS_AND_F3 = true;

		
===============================
Starts here -->@<-- Ends here
===============================
Override
		public boolean test(final String record) {
...
```

@srikanth-sankaran `triggerRecoveryUponLambdaClosure()` seems to be confused by the field declaration inside the lambda body. My quick guess is, that while iterating over `elementStack` "outwards" we should stop the search for a potentially closed lambda when we see we are in fact inside a (anonymous) class declaration.

I'm sure you remember all details of this method which you wrote a mere 11 years ago, don't you ;-P

**Comment by stephan-herrmann** [comment]
```diff
	for (int i = this.elementPtr; i >= 0; --i) {
+		if (this.elementKindStack[i] == K_TYPE_DELIMITER)
+			break;
		if (this.elementKindStack[i] != K_LAMBDA_EXPRESSION_DELIMITER)
			continue;
		LambdaExpression expression = (LambdaExpression) this.elementObjectInfoStack[i];
```
Now the hover works :smile:

**Comment by DanskerDave** [comment]
Does this fix the F3 issue, or just the Mouseover ("hover")?

**Comment by stephan-herrmann** [comment]
> Does this fix the F3 issue, or just the Mouseover ("hover")?

it should fix both.

**Comment by DanskerDave** [comment]
ok,many thanks.
Greetings from the Odenwald.

**Comment by stephan-herrmann** [comment]
> Greetings from the Odenwald.

interesting :) I had assumed your user name hints towards Denmark ...

**Comment by DanskerDave** [comment]
> interesting :) I had assumed your user name hints towards Denmark ...

Yes, many, many years ago!
