### ISSUE TITLE
[code select] ClassCastException when hovering in switch case yield

### ISSUE THREAD

**Issue by Nightenom** [eclipse-jdt/eclipse.jdt.core#2572]
Running latest vscode, but this has been issue for at least last 6 months (just haven't got to report it yet) and clearly mentions jdt.core.

Use following code and try to hover over anything in `BarFoo` or `FooBar` case block, surprisingly `Bar` block is fine.
In more complex code hovering nor ctrl+clicking (follow to definition) does not work, however sometimes some deeply nested code (in case block) is working.

Code:
```java
public class Test
{
    public static void main(String[] args)
    {
        test(new Bar(0));
        test(new FooBar<>("0"));
    }

    public static void test(final Foo foo)
    {
        final String str = switch (foo)
        {
            case Bar(Number number) -> {
                yield number.toString();
            }
            case BarFoo(String data)  -> {
                yield data;
            }
            case final FooBar<?> fooBar -> {
                yield fooBar.object.toString();
            }
        };
        System.out.println(str);
    }

    private static sealed interface Foo
    {}

    private record Bar(Number number) implements Foo
    {}

    private record BarFoo(String data) implements Foo
    {}

    private record FooBar<T>(T object) implements Foo
    {}
}
```

Stacktrace:
```
java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.ast.CaseStatement cannot be cast to class org.eclipse.jdt.internal.compiler.ast.Expression (org.eclipse.jdt.internal.compiler.ast.CaseStatement and org.eclipse.jdt.internal.compiler.ast.Expression are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @203b844)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.buildMoreCompletionContext(SelectionParser.java:209)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.attachOrphanCompletionNode(SelectionParser.java:160)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.updateRecoveryState(SelectionParser.java:2021)
	at org.eclipse.jdt.internal.compiler.parser.Parser.resumeOnSyntaxError(Parser.java:14087)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12613)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:2107)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:1943)
	at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:350)
	at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:313)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1080)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:166)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:375)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:1042)
	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeHover(HoverInfoProvider.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.computeHover(HoverHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:43)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:654)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by srikanth-sankaran** [comment]
Reproduced, Thanks for the report. Investigating ...
