### ISSUE TITLE
BasicBuildTests.testCustomerCompilerFactoryWithAP fails since I20240620-0440

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2618]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240620-0440/testresults/html/org.eclipse.jdt.core.tests.builder_ep433I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Regression from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2497, visible after fixing https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2614.

```
../org.eclipse.jdt.core.tests.builder/resources/autoValueSnippet

java.nio.file.NoSuchFileException: ../org.eclipse.jdt.core.tests.builder/resources/autoValueSnippet
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
at java.base/java.nio.file.Files.copy(Files.java:1305)
at org.eclipse.jdt.core.tests.builder.BasicBuildTests.copyFiles(BasicBuildTests.java:841)
at org.eclipse.jdt.core.tests.builder.BasicBuildTests.testCustomerCompilerFactoryWithAP(BasicBuildTests.java:766)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

@testforstephen, @mickaelistria : please take a look.

**Comment by stephan-herrmann** [comment]
This looks pretty much like https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2497#discussion_r1644314668

**Comment by testforstephen** [comment]
We use the relative path to copy the local test sample project `autoValueSnippet`. It seems the relative path varies when the unit test is triggered from different plugin entry points. I'm not familiar with how the unit test run at the product build job. Any idea on how to reproduce this failure by myself? thanks.

**Comment by iloveeclipse** [comment]
Still fails, now because the resources folder is not deployed (build.properties entry missing?)
See https://download.eclipse.org/eclipse/downloads/drops4/I20240622-0130/testresults/html/org.eclipse.jdt.core.tests.builder_ep433I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

**Comment by jukzi** [comment]
still fails
```
java.io.IOException: File not found: resources
at org.eclipse.jdt.core.tests.builder.BasicBuildTests.getFileFromPlugin(BasicBuildTests.java:870)
at org.eclipse.jdt.core.tests.builder.BasicBuildTests.getSourceProjectDirectory(BasicBuildTests.java:859)
at org.eclipse.jdt.core.tests.builder.BasicBuildTests.copyFiles(BasicBuildTests.java:830)
at org.eclipse.jdt.core.tests.builder.BasicBuildTests.testCustomerCompilerFactoryWithAP(BasicBuildTests.java:771)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20240624-1800/testresults/html/org.eclipse.jdt.core.tests.builder_ep433I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

**Comment by testforstephen** [comment]
I just merged my change a few hours ago, not sure if this build includes my update. Is there any way to know what commits are taken by I20240624-1800?

**Comment by testforstephen** [comment]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240625-1800/testResults.php

Close it since no failure for test bundle `jdt.core.tests.builder` in the latest build.
