### ISSUE TITLE
JDT Core throws ClassCastException: NullTypeBinding cannot be cast to class ArrayBinding

### ISSUE THREAD

**Issue by r0texx** [eclipse-jdt/eclipse.jdt.core#2677]
Hello,

Paste the following code to Eclipse:
```java
package test;

public class Test {
    public float test(float[] arr) {
        return (arr != null ? arr : null)[0];
    }
}
```

JDT will throw the following exception:
```
Exception in thread "main" java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.lookup.NullTypeBinding cannot be cast to class org.eclipse.jdt.internal.compiler.lookup.ArrayBinding (org.eclipse.jdt.internal.compiler.lookup.NullTypeBinding and org.eclipse.jdt.internal.compiler.lookup.ArrayBinding are in unnamed module of loader 'app')
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.xaload(OperandStack.java:85)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.faload(CodeStream.java:1326)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.arrayAt(CodeStream.java:447)
	at org.eclipse.jdt.internal.compiler.ast.ArrayReference.generateCode(ArrayReference.java:113)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:234)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:324)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1127)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:740)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1055)
```

**Comment by srikanth-sankaran** [comment]
Thanks. I'll follow up.

**Comment by srikanth-sankaran** [comment]
I agree compiler should not crash - but I am trying to understand the code you have posted and having some trouble. Is this a simplified version of a complex code ? Why wouldn't one simply say `return arr[0]` ? How did you end up with this/such code ?

**Comment by r0texx** [comment]
Hey @srikanth-sankaran,

That's a simplified variant of the (incorrectly) decompiled code that crashed JDT

**Comment by srikanth-sankaran** [comment]
Flipping the condition is an easy work around:

```
public class Test {
    public float test(float[] arr) {
        return (arr == null ? null : arr)[0];
    }
}    
```

doesn't trigger the problem.
