### ISSUE TITLE
SourceTypeBinding.superInterfaces() returns missing type for "cyclic" static imports

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#269]
To reproduce, import project from attached archive: [TypeHierarchyBugReproducer.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9199404/TypeHierarchyBugReproducer.zip)

Then try to compute the type hierarchy of ```test.Test```, observe that ```test.internal.TestImpl``` is not on the hierarchy according to the view.

This is the case, due to this stack trace exiting early:

```
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.reportHierarchy(HierarchyResolver.java:607)
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.resolve(HierarchyResolver.java:894)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildForProject(IndexBasedHierarchyBuilder.java:265)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildFromPotentialSubtypes(IndexBasedHierarchyBuilder.java:376)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:166)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:323)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1319)
        - locked <0x00000001b44008c0> (a org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle.doHierarchyRefresh(TypeHierarchyLifeCycle.java:331)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle.doHierarchyRefreshBackground(TypeHierarchyLifeCycle.java:272)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle$1.run(TypeHierarchyLifeCycle.java:225)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
(stack trace is from 4.21, where we initially observed the problem)

```HierarchyResolver.subOrSuperOfFocus(ReferenceBinding)``` will return ```false``` here, due to ```HierarchyResolver.subTypeOfType(ReferenceBinding, ReferenceBinding)``` having this code:

```
			if (superInterface.isHierarchyInconsistent()) return false;
````

Replacing either of the used static imports with qualified method calls will "fix" the bug.

From what I debugged, the interface super type is ``````

Seen with:

```
Eclipse SDK
Version: 2022-06 (4.25)
Build id: I20220718-1800
```

**Comment by trancexpress** [comment]
We have the wrong ```org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.token``` during this stack trace:

```
"Worker-8: Computing type hierarchy of 'Test - test'..." #56 prio=5 os_prio=0 cpu=420.13ms elapsed=1107.10s tid=0x00007ffe2c001800 nid=0x116f7 runnable  [0x00007ffe4d7f8000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getPackage0(LookupEnvironment.java:1649)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTopLevelPackage(LookupEnvironment.java:1685)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3559)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3189)
        at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:634)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:630)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveSuperType(TypeReference.java:602)
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.findSupertype(ClassScope.java:1670)
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperInterfaces(ClassScope.java:1393)
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1455)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.findMemberType(Scope.java:1578)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3505)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3189)
        at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveLeafType(ParameterizedSingleTypeReference.java:200)
        at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveType(ParameterizedSingleTypeReference.java:174)
        at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.resolveType(ParameterizedSingleTypeReference.java:395)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:630)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveSuperType(TypeReference.java:602)
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.findSupertype(ClassScope.java:1670)
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperInterfaces(ClassScope.java:1393)
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1455)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:367)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:586)
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.accept(HierarchyResolver.java:209)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:342)
        at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:259)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:606)
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.resolve(HierarchyResolver.java:861)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildForProject(IndexBasedHierarchyBuilder.java:265)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildFromPotentialSubtypes(IndexBasedHierarchyBuilder.java:376)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:166)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:323)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1319)
        - locked <0x00000000f951c468> (a org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle.doHierarchyRefresh(TypeHierarchyLifeCycle.java:331)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle.doHierarchyRefreshBackground(TypeHierarchyLifeCycle.java:272)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle$1.run(TypeHierarchyLifeCycle.java:225)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

So the package is not found, which results in a ```MissingTypeBinding``` being created.

Maybe the static import results in the bad token, I'll have to check. I'm not too familiar with this.

**Comment by trancexpress** [comment]
OK, I think I understand the cause now.

Looks like resolving the static imports results in a recursive attempt to resolve types:

```
"ModalContext" #127 prio=6 os_prio=0 cpu=13.36ms elapsed=245.52s tid=0x00007ffff2c86800 nid=0x3feb runnable  [0x00007ffe493f7000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getType0(PackageBinding.java:222)
        at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:249)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:259)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:585)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.accept(Engine.java:141)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.accept(SelectionEngine.java:375)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:342)
        at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:259)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:585)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1074)
        at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

So essentially, the code is not done initializing everything on ```CompilationUnitDeclaration.scope```, see the first call to ```CompilationUnitScope.checkAndSetImports()``` on the stack trace above. Then, the code tries to resolve the first static import. In the type that is statically imported, there is again a static import to resolve. This 2nd resolve tries to use the original scope, that is not fully initialized yet (it has no imports yet, its still computing those). Which results in missing imports and being unable to resolve the type of the implemented interface. Which later on results in a badly computed hierarchy.

**Comment by trancexpress** [comment]
Looks like now some problems that exist in test snippets are no longer detected.

I'll try a different fix in ```org.eclipse.jdt.internal.codeassist.SelectionEngine.accept(ISourceType[], PackageBinding, AccessRestriction)```. When I was writing the test, I noticed that the hierarchy was being computed fine until I invoked ```org.eclipse.jdt.core.ICodeAssist.codeSelect(int, int)```. So maybe the problem is only there.
