### ISSUE TITLE
ArrayIndexOutOfBoundsException in org.eclipse.jdt.internal.compiler.parser.Scanner.internalScanIdentifierOrKeyword

### ISSUE THREAD

**Issue by sratz** [eclipse-jdt/eclipse.jdt.core#2703]
Since https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2660 I am getting the following exceptions for pretty much every project:

```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at org.eclipse.jdt.internal.compiler.parser.Scanner.internalScanIdentifierOrKeyword(Scanner.java:3438)
	at org.eclipse.jdt.internal.compiler.parser.Scanner.scanIdentifierOrKeywordWithBoundCheck(Scanner.java:3034)
	at org.eclipse.jdt.internal.compiler.parser.Scanner.scanIdentifier(Scanner.java:1176)
	at org.eclipse.jdt.core.JavaConventions.scannedIdentifier(JavaConventions.java:133)
	at org.eclipse.jdt.core.JavaConventions.scannedIdentifier(JavaConventions.java:115)
	at org.eclipse.jdt.core.JavaConventions.validateIdentifier(JavaConventions.java:387)
	at org.eclipse.jdt.internal.core.util.Util.isValidFolderNameForPackage(Util.java:1773)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.initRawPackageInfo(JarPackageFragmentRoot.java:377)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.computeChildren(JarPackageFragmentRoot.java:168)
	at org.eclipse.jdt.internal.core.JavaProjectElementInfo.initializePackageNames(JavaProjectElementInfo.java:276)
	at org.eclipse.jdt.internal.core.JavaProjectElementInfo.getProjectCache(JavaProjectElementInfo.java:244)
	at org.eclipse.jdt.internal.core.JavaProject.getProjectCache(JavaProject.java:2388)
	at org.eclipse.jdt.internal.core.JavaProjectElementInfo.newNameLookup(JavaProjectElementInfo.java:332)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2799)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2793)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2811)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2803)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1704)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1605)
	at org.eclipse.pde.internal.core.util.PDEJavaHelper.isOnClasspath(PDEJavaHelper.java:111)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateJavaAttribute(ExtensionsErrorReporter.java:616)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateExtensionAttribute(ExtensionsErrorReporter.java:394)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateExistingExtensionAttributes(ExtensionsErrorReporter.java:384)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateElement(ExtensionsErrorReporter.java:239)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateElement(ExtensionsErrorReporter.java:256)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateExtension(ExtensionsErrorReporter.java:169)
	at org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validate(ExtensionsErrorReporter.java:124)
	at org.eclipse.pde.internal.core.builders.XMLErrorReporter.validateContent(XMLErrorReporter.java:379)
	at org.eclipse.pde.internal.core.builders.ManifestConsistencyChecker.validateFiles(ManifestConsistencyChecker.java:349)
	at org.eclipse.pde.internal.core.builders.ManifestConsistencyChecker.validateProject(ManifestConsistencyChecker.java:268)
	at org.eclipse.pde.internal.core.builders.ManifestConsistencyChecker.build(ManifestConsistencyChecker.java:194)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by srikanth-sankaran** [comment]
Never mind, I manage to reproduce it. I'll post a fix soon

**Comment by srikanth-sankaran** [comment]
> > Since #2660 I am getting the following exceptions for pretty much every project:
> 
> Will take a look. Can you provide a small test case ? This change passes the full test suite and is able to build the entire SDK, so need to know what is special about your environment - Thanks in advance

Basically problem happens with the scanner being queried for various Java naming conventions - in this case if "non" is a valid package name. So a package by name "non" is needed to reproduce the problem

**Comment by sratz** [comment]
Thanks for the quick fix! With that my workspace is error-free again.

**Comment by srikanth-sankaran** [comment]
> Thanks for the quick fix! With that my workspace is error-free again.

Thanks for the validation - sorry about the breakage.
