### ISSUE TITLE
org.eclipse.jdt.compiler.apt.tests.Java9ElementsTests has failing tests when run on Java 23

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#2735]
One failing assertion is 
```
expected:<[succeeded]> but was:<[incorrect no of uses, expected 36 but was 35
 at org.eclipse.jdt.compiler.apt.tests.processors.elements.Java9ElementProcessor.reportError(Java9ElementProcessor.java:1229)
 at org.eclipse.jdt.compiler.apt.tests.processors.elements.Java9ElementProcessor.assertEquals(Java9ElementProcessor.java:1316)
 at org.eclipse.jdt.compiler.apt.tests.processors.elements.Java9ElementProcessor.testModuleJavaBase4(Java9ElementProcessor.java:519)
 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
 at java.base/java.lang.reflect.Method.invoke(Method.java:580)
 at org.eclipse.jdt.compiler.apt.tests.processors.elements.Java9ElementProcessor.invokeTestMethods(Java9ElementProcessor.java:165)
 at org.eclipse.jdt.compiler.apt.tests.processors.elements.Java9ElementProcessor.process(Java9ElementProcessor.java:140)
 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:141)
 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:123)
 at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
 at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:952)
 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:449)
 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)]>
```

**Comment by akurtakov** [comment]
This is due to  [Removal of Module jdk.random](https://bugs.openjdk.org/browse/JDK-83300050
