### ISSUE TITLE
Update default set of root modules for unnamed modules

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2786]
ECJ should implement https://bugs.openjdk.org/browse/JDK-8205169 (which erroneously was declared with scope JDK, but should be scope SE).

**Comment by akurtakov** [comment]
Fix for this caused a failure in jdt.debug tests https://download.eclipse.org/eclipse/downloads/drops4/I20250118-1800/testresults/html/org.eclipse.jdt.debug.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html :
```
Unknown set of default modules java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.smartcardio,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.accessibility,jdk.attach,jdk.compiler,jdk.dynalink,jdk.httpserver,jdk.incubator.vector,jdk.jartool,jdk.javadoc,jdk.jconsole,jdk.jdi,jdk.jfr,jdk.jshell,jdk.jsobject,jdk.management,jdk.management.jfr,jdk.net,jdk.nio.mapmode,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom

junit.framework.AssertionFailedError: Unknown set of default modules java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.smartcardio,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.accessibility,jdk.attach,jdk.compiler,jdk.dynalink,jdk.httpserver,jdk.incubator.vector,jdk.jartool,jdk.javadoc,jdk.jconsole,jdk.jdi,jdk.jfr,jdk.jshell,jdk.jsobject,jdk.management,jdk.management.jfr,jdk.net,jdk.nio.mapmode,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.jdt.debug.tests.core.ModuleOptionsTests.testLimitModules1(ModuleOptionsTests.java:325)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2776)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)
at java.base/java.lang.Thread.run(Thread.java:1583) 
```

**Comment by stephan-herrmann** [comment]
> Fix for this caused a failure in jdt.debug tests https://download.eclipse.org/eclipse/downloads/drops4/I20250118-1800/testresults/html/org.eclipse.jdt.debug.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html :

Thanks. I kind-of expected this ripple, but of course the changes in jdt.core had to be merged before I could address this in jdt.debug.

I'm updating those tests via https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/597

**Comment by stephan-herrmann** [comment]
> > Fix for this caused a failure in jdt.debug tests https://download.eclipse.org/eclipse/downloads/drops4/I20250118-1800/testresults/html/org.eclipse.jdt.debug.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html :
> 
> Thanks. I kind-of expected this ripple, but of course the changes in jdt.core had to be merged before I could address this in jdt.debug.
> 
> I'm updating those tests via [eclipse-jdt/eclipse.jdt.debug#597](https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/597)

Done.
