### ISSUE TITLE
win: 24 failing compiler.regression.TestAll since I20240805-1800 "being used by another process"

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2812]
https://download.eclipse.org/eclipse/downloads/drops4/I20240805-1800/testResults.php

most look like:

C:\Users\genie.releng\AppData\Local\Temp\comptest\run.1722912180274\lib\lib8.jar: The process cannot access the file because it is being used by another process

```
java.nio.file.FileSystemException: C:\Users\genie.releng\AppData\Local\Temp\comptest\run.1722912180274\lib\lib8.jar: The process cannot access the file because it is being used by another process
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
at org.eclipse.jdt.core.tests.util.Util.zip(Util.java:1477)
at org.eclipse.jdt.core.tests.util.Util.createJar(Util.java:474)
at org.eclipse.jdt.core.tests.util.Util.createJar(Util.java:489)
at org.eclipse.jdt.core.tests.util.Util.createJar(Util.java:486)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractBatchCompilerTest.createCascadedJars(AbstractBatchCompilerTest.java:295)
at org.eclipse.jdt.core.tests.compiler.regression.BatchCompilerTest.test246_jar_ref_in_jar(BatchCompilerTest.java:8924)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.util.CompilerTestSetup.run(CompilerTestSetup.java:59)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by iloveeclipse** [comment]
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2766
