### ISSUE TITLE
ASTRewrite.rewriteAST fails with AssertionFailedException for records when it contains inner class

### ISSUE THREAD

**Issue by helospark** [eclipse-jdt/eclipse.jdt.core#2835]
Given the following `record`:

```java
record Test(String name, String address) {

    public static Builder builder() {
    }

    public static final class Builder {
    }
}
```

trying to remove the first inner node using `rewriteAST` results in the following exception:

```
org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.text.edits.TextEdit.<init>(TextEdit.java:153)
	at org.eclipse.text.edits.DeleteEdit.<init>(DeleteEdit.java:36)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextRemove(ASTRewriteAnalyzer.java:409)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:752)
...
```

The exception happens because `len` in DeleteEdit is negative.

However the same code works properly if the Test is a class instead of a record:
```java
class Test {
```

also works if the inner class and the method is in the opposite order.

Minimum reproducible example:
```java

    @Test
    public void minimumRepro() throws IOException, URISyntaxException, JavaModelException {
        String input = ""
                + "record Test(String name, String address) {\n"
                + "\n"
                + "    public static Builder builder() {\n"
                + "    }\n"
                + "\n"
                + "    public static final class Builder {\n"
                + "    }\n"
                + "\n"
                + "}";
        CompilationUnit result = getCompilationUnit(input);
        AbstractTypeDeclaration mainType = (AbstractTypeDeclaration) result.types().get(0);

        AST ast = result.getAST();
        ASTRewrite rewriter = ASTRewrite.create(ast);
        ListRewrite listRewriter = rewriter.getListRewrite(mainType, mainType.getBodyDeclarationsProperty());

        listRewriter.remove((ASTNode) mainType.bodyDeclarations().get(0), null); // remove builder() type

        Document document = new Document(input);
        TextEdit edits = rewriter.rewriteAST(document, null); // commit code change
    }

    private CompilationUnit getCompilationUnit(String input) throws IOException, URISyntaxException {
        ASTParser parser = ASTParser.newParser(JlsVersionProvider.getLatestJlsVersion());
        parser.setSource(input.toCharArray());
        Map options = JavaCore.getOptions();
        JavaCore.setComplianceOptions(JavaCore.VERSION_17, options);
        parser.setCompilerOptions(options);
        CompilationUnit result = (CompilationUnit) parser.createAST(null);
        return result;
    }
```

Issue is present in the latest (2024-06) Eclipse (jdt.core 3.38).

Root cause seems to be, that in case of RecordDeclaration the order of the bodyDeclarations() is in the wrong order, opposite of the actual declaration.

**Comment by subyssurendran666** [comment]
@mpalat could you please assign this ticket to me ?

**Comment by subyssurendran666** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3002 is merged with master, so closing the issue.

**Comment by subyssurendran666** [comment]
@mpalat could you please close this issue, since I don't have access.
