### ISSUE TITLE
NPE in BinaryModuleBinding.create() during incremental compile

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#284]
When using Eclipse 4.25, we ran into the following NPE (once):

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.env.IModule.isAutomatic()" because "module" is null
	at org.eclipse.jdt.internal.compiler.lookup.BinaryModuleBinding.create(BinaryModuleBinding.java:99)
	at org.eclipse.jdt.internal.compiler.impl.ITypeRequestor.accept(ITypeRequestor.java:65)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getModuleFromAnswer(LookupEnvironment.java:437)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:374)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:236)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:114)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:249)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:252)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:623)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:452)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:525)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:898)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

To my knowledge we have no module definitions.

**Comment by iloveeclipse** [comment]
Looking at the code in `org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getModuleFromAnswer(NameEnvironmentAnswer)`, there is a try/catch/re-throw added for https://bugs.eclipse.org/bugs/show_bug.cgi?id=529367

@stephan-herrmann : any clue why do we still observe that NPE?

@trancexpress : steps to reproduce?

**Comment by trancexpress** [comment]
> @trancexpress : steps to reproduce?

I believe I ran into the NPE when using the new 4.25 build we use as IDE. I don't remember doing anything particular, just starting Eclipse and seeing the exception during the build.

**Comment by stephan-herrmann** [comment]
> Looking at the code in `org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getModuleFromAnswer(NameEnvironmentAnswer)`, there is a try/catch/re-throw added for https://bugs.eclipse.org/bugs/show_bug.cgi?id=529367
> 
> @stephan-herrmann : any clue why do we still observe that NPE?

Did you see the re-throw? That block is only in order to spit out debug info to the console from where Eclipse was launched.

@trancexpress Should you ever see this again, please have a console at hand, where you can look for print out from
```
System.err.println("Bug 529367: moduleName: " + new String(moduleName) + "iModule null" +  //$NON-NLS-1$ //$NON-NLS-2$
			(iModule == null ? "true" : "false")); //$NON-NLS-1$ //$NON-NLS-2$]
```
