### ISSUE TITLE
ClasspathTests.testCycleReport failed on latest integration build

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#2840]
See:

https://download.eclipse.org/eclipse/downloads/drops4/I20240820-1800/testResults.php
https://download.eclipse.org/eclipse/downloads/drops4/I20240820-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep433I-unit-win32-java17_win32.win32.x86_64_17.html

```
Unexpected number of projects involved in a classpath cycle expected:<3> but was:<0>

junit.framework.AssertionFailedError: Unexpected number of projects involved in a classpath cycle expected:<3> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.core.tests.model.ClasspathTests.testCycleReport(ClasspathTests.java:2624)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:116)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:99)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:87)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:96)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```

No idea if its a known sporadic fail.

**Comment by jukzi** [comment]
same error again in
https://download.eclipse.org/eclipse/downloads/drops4/I20250203-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html
