### ISSUE TITLE
AIOOBE in ProblemReporter.invalidType()

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#286]
Most recent SDK build as of today (but can be reproduced on 4.21 too).
Right click `org.eclipse.jdt.internal.compiler.batch.ClasspathJar.file` field and say "Open Call Hierarchy".
"Call Hierarchy" view will be empty but an error will be reported to the log.

Opening call hierarchy on **other** fields in same class seem to work fine.

```
eclipse.buildId=4.25.0.I20220801-1800
java.version=17.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /data/4x_platform_workspace -os linux -ws gtk -arch x86_64

org.eclipse.jdt.ui
Error
Tue Aug 02 14:30:26 CEST 2022
Internal Error

java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.invalidType(ProblemReporter.java:4915)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.reportInvalidType(TypeReference.java:593)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.internalResolveLeafType(ParameterizedQualifiedTypeReference.java:223)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.internalResolveType(ParameterizedQualifiedTypeReference.java:206)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.resolveType(ParameterizedQualifiedTypeReference.java:472)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2803)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2705)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:2276)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getMethods(SourceTypeBinding.java:1914)
	at org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.getMethods(ReferenceBinding.java:1159)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod0(Scope.java:1696)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod(Scope.java:1658)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getImplicitMethod(Scope.java:2624)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:802)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:131)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolveIfStatement(IfStatement.java:291)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:317)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1503)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1628)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2030)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1360)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1397)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1539)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
	at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
	at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
	at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by trancexpress** [comment]
The code that throws:

```
		if (type instanceof ReferenceBinding) {
			char[][] name = ((ReferenceBinding) type).compoundName;
			end = (int) ref.sourcePositions[name.length - 1];
		}
```

The values that I see when the AIOOBE is (about to be) thrown:

```type``` is:

```
ProblemType:[compoundName=java.nio.file.DirectoryStream][problemID=ProblemReasons.Ambiguous][closestMatch=public interface java.nio.file.DirectoryStream<T extends java.lang.Object>
	extends java.lang.Object
	implements : java.io.Closeable, Iterable<T>
/*   methods   */
[unresolved] public abstract Iterator<T> iterator() 
/*   members   */
public static interface Filter#RAW
	extends NULL TYPENULL SUPERINTERFACES
	enclosing type : java.nio.file.DirectoryStream<T>NULL FIELDSNULL METHODS
]
```

```ref``` is:

```
DirectoryStream.Filter<? super Path>
```

```ref.sourcePositions``` is:

```
[59283433600505, 59352153077248]
```

**Comment by trancexpress** [comment]
See this index check, added quite a while near the same code: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/cf7db1b07f7da2723bd250cc64a7e16bec1c504d#diff-fd23cf7032143d2ba23d68639ebe308a164cc8d86477e7e4598bca7291dfd71bR3322
