### ISSUE TITLE
Failure in org.eclipse.jdt.core.tests.model.JavaSearchBugsTests. testBug339891

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2876]
ref: https://download.eclipse.org/eclipse/downloads/drops4/I20240828-1820/testresults/html/org.eclipse.jdt.core.tests.model_ep433I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
Unexpected search results. ----------- Expected ------------ Test.java void Test.foo(Ref) [foo()] EXACT_MATCH ------------ but was ------------ ---------------------- ---------- expected:<[Test.java void Test.foo(Ref) [foo()] EXACT_MATCH]> but was:<[]>

junit.framework.ComparisonFailure: Unexpected search results.
----------- Expected ------------
Test.java void Test.foo(Ref) [foo()] EXACT_MATCH
------------ but was ------------

---------------------- ----------
expected:<[Test.java void Test.foo(Ref) [foo()] EXACT_MATCH]> but was:<[]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:948)
at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:906)
at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:903)
at org.eclipse.jdt.core.tests.model.JavaSearchBugsTests.testBug339891(JavaSearchBugsTests.java:12939)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:116)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:99)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:87)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:96)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by subyssurendran666** [comment]
Also reported here [here](https://download.eclipse.org/eclipse/downloads/drops4/I20241031-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-macosx-aarch64-java17_macosx.cocoa.aarch64_17.html).

**Comment by trancexpress** [comment]
Failed again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260310-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

```
Unexpected search results. ----------- Expected ------------ Test.java void Test.foo(Ref) [foo()] EXACT_MATCH ------------ but was ------------ ---------------------- ---------- expected:<[Test.java void Test.foo(Ref) [foo()] EXACT_MATCH]> but was:<[]>

junit.framework.ComparisonFailure: Unexpected search results.
----------- Expected ------------
Test.java void Test.foo(Ref) [foo()] EXACT_MATCH
------------ but was ------------

---------------------- ----------
expected:<[Test.java void Test.foo(Ref) [foo()] EXACT_MATCH]> but was:<[]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:952)
at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:910)
at org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests.assertSearchResults(AbstractJavaSearchTests.java:907)
at org.eclipse.jdt.core.tests.model.JavaSearchBugsTests.testBug339891(JavaSearchBugsTests.java:12908)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```

Workspace log has nothing interesting:

https://download.eclipse.org/eclipse/downloads/drops4/I20260310-1800/testresults/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

```
00:54:57.246 SETUP JavaSearchBugsTests.testBug339891
Classpath variable 'JCL14_LIB', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin14.jar', file size: 23930
Classpath variable 'JCL14_SRC', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin14src.zip', file size: 15214
Classpath variable 'JCL18_LIB', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin1.8.jar', file size: 14941
Classpath variable 'JCL18_SRC', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin1.8src.zip', file size: 9405
Classpath variable 'JCL19_LIB', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin9.jar', file size: 14071
Classpath variable 'JCL19_SRC', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin9src.zip', file size: 9298
Classpath variable 'JCL_17_LIB', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin17.jar', file size: 20760
Classpath variable 'JCL_17_SRC', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin17src.zip', file size: 16168
Classpath variable 'JCL_21_LIB', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin21.jar', file size: 27542
Classpath variable 'JCL_21_SRC', path: '/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260310-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin21src.zip', file size: 20544
Classpath variable 'JCL_SRCROOT', path: 'src', file size: 0
testBug339891 got no result!
00:54:57.270 TDOWN JavaSearchBugsTests.testBug339891
```
