### ISSUE TITLE
[build][test] EvaluationContextWrapperTest.testBug573589_StaticImport fails on Linux since I20240919-1230

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2998]
Fails on all Linux platforms (Java 17 , 21 and 23) with different target JLS

Example stack from 
https://download.eclipse.org/eclipse/downloads/drops4/I20240923-0040/testresults/html/org.eclipse.jdt.core.tests.compiler_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html
```
Evaluation should not have problems : Bug573589 cannot be resolved to a type

junit.framework.AssertionFailedError: Evaluation should not have problems : Bug573589 cannot be resolved to a type
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.core.tests.eval.EvaluationContextWrapperTest.testBug573589_StaticImport(EvaluationContextWrapperTest.java:111)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:972)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.util.CompilerTestSetup.run(CompilerTestSetup.java:59)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
 ```

**Comment by iloveeclipse** [comment]
I could not reproduce locally on RHEL 9.2 with all 3 JDK's in question.

I've created https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2999 to cleanup test se we can see what's **really** wrong with it.

**Comment by iloveeclipse** [comment]
Still in https://download.eclipse.org/eclipse/downloads/drops4/I20241005-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep434I-unit-cen64-gtk3-java23_linux.gtk.x86_64_23.html

```
org.eclipse.jdt.core.tests.eval.EvaluationContextWrapperTest	testBug573589_StaticImport - 11	Failure	Evaluation should not have problems : Bug573589 cannot be resolved to a type

junit.framework.AssertionFailedError: Evaluation should not have problems : Bug573589 cannot be resolved to a type
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.core.tests.eval.EvaluationContextWrapperTest.testBug573589_StaticImport(EvaluationContextWrapperTest.java:109)
```

```
org.eclipse.jdt.core.tests.eval.EvaluationContextWrapperTest	testBug573589_StaticImport - 13	Failure	Evaluation should not have problems : Bug573589 cannot be resolved to a type

junit.framework.AssertionFailedError: Evaluation should not have problems : Bug573589 cannot be resolved to a type
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.core.tests.eval.EvaluationContextWrapperTest.testBug573589_StaticImport(EvaluationContextWrapperTest.java:109)
```

However not in I20241006-1800 and not in previous few days.

So the fail seem to be random...
