### ISSUE TITLE
Reduce WinNTFileSystem.getBooleanAttributes calls during classpath resolution

### ISSUE THREAD

**Issue by in-fke** [eclipse-jdt/eclipse.jdt.core#303]
Referring to https://bugs.eclipse.org/bugs/show_bug.cgi?id=460072

getting really bad hangs where Eclipse UI is busy in stacks like the following
```
"main" #1 prio=6 os_prio=0 cpu=242343.75ms elapsed=1584.37s tid=0x00000129b3906000 nid=0x5c88 runnable  [0x00000021f12fc000]
   java.lang.Thread.State: RUNNABLE
	at java.io.WinNTFileSystem.getBooleanAttributes(java.base@11.0.12/Native Method)
	at java.io.File.isFile(java.base@11.0.12/File.java:894)
	at org.eclipse.jdt.internal.core.JavaModel.isExternalFile(JavaModel.java:418)
	at org.eclipse.jdt.internal.core.JavaModel.getExternalTarget(JavaModel.java:378)
	at org.eclipse.jdt.internal.core.JavaModel.getTarget(JavaModel.java:338)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:767)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1103)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1048)
	at org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1870)
	at org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1861)
	at org.eclipse.jdt.internal.core.JavaProject.findPackageFragmentRoot0(JavaProject.java:1638)
	at org.eclipse.jdt.internal.core.JavaProject.findPackageFragmentRoot(JavaProject.java:1630)
	at org.eclipse.jdt.ui.StandardJavaElementContentProvider.getFolderContent(StandardJavaElementContentProvider.java:403)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getFolderContent(PackageExplorerContentProvider.java:278)
	at org.eclipse.jdt.ui.StandardJavaElementContentProvider.getChildren(StandardJavaElementContentProvider.java:190)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getChildren(PackageExplorerContentProvider.java:309)
	at org.eclipse.jdt.internal.ui.packageview.WorkingSetAwareContentProvider.getChildren(WorkingSetAwareContentProvider.java:79)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1445)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.hasFilteredChildren(ProblemTreeViewer.java:245)
	at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.isExpandable(ProblemTreeViewer.java:234)
	at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2214)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updatePlus(AbstractTreeViewer.java:2897)
	at org.eclipse.jface.viewers.TreeViewer.updatePlus(TreeViewer.java:801)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2789)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1971)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1977)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1977)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1977)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1977)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1977)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1977)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1947)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1904)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart$PackageExplorerProblemTreeViewer.internalRefresh(PackageExplorerPart.java:271)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$3(StructuredViewer.java:1482)
	at org.eclipse.jface.viewers.StructuredViewer$$Lambda$649/0x00000001009f5840.run(Unknown Source)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1482)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:538)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.lambda$1(PackageExplorerContentProvider.java:955)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider$$Lambda$1468/0x0000000101767040.run(Unknown Source)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.runUpdates(PackageExplorerContentProvider.java:210)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.runPendingUpdates(PackageExplorerContentProvider.java:202)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider$1.runInUIThread(PackageExplorerContentProvider.java:180)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.ui.progress.UIJob$$Lambda$931/0x0000000100edc440.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	- locked <0x00000000a5e79fd0> (a org.eclipse.swt.widgets.RunnableLock)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.ui.internal.Workbench$$Lambda$304/0x0000000100580440.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)

```
I think what also is the problem that
ProblemTreeViewer.hasFilteredChildren()
is doing something expensive in the first place.

But maybe also this approach for minimalistic change would be more realistic?
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/f2e62adf8a978a714a377b7dd04df4470e30bbd3/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModel.java#L418

It's one line!

```
418c418
<       boolean isFile = path.toFile().isFile();
---
>       boolean isFile = Files.exists(path.toFile().toPath(), LinkOption.NOFOLLOW_LINKS);
```

**Comment by jarthana** [comment]
> It's one line!
> 
> ```
> 418c418
> <       boolean isFile = path.toFile().isFile();
> ---
> >       boolean isFile = Files.exists(path.toFile().toPath(), LinkOption.NOFOLLOW_LINKS);
> ```

@jukzi I remember you ran some tests for my earlier patch. Can you try this again with this and let us know if this helps.

**Comment by iloveeclipse** [comment]
> It's one line!

Not all one-liners are equivalent to each other :-)
Note: in this case the code needs to know if this is a **file**, not if some **file or directory** exists on file system.

**Comment by jarthana** [comment]
> > It's one line!
> 
> Not all one-liners are equivalent to each other :-) Note: in this case the code needs to know if this is a **file**, not if some **file or directory** exists on file system.

Ouch. Sorry, missed that completely!

**Comment by jukzi** [comment]
according to my comment in https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/183464/4#message-23c5c4754ed90763fd2126549e69e44dfe472047
it does not matter if you call File.exists or file.isFile. Its both a slow system call.
There is already a cache in JavaModelManager.getJavaModelManager().isExternalFile() but it only remembers when isFile=true. A solution could be to cache the result for both true/false

**Comment by jukzi** [comment]
> Not all one-liners are equivalent to each other :-)

interestlingly ExternalFoldersManager.isExternalFolderPath() used Files.isRegularFile() for the same purpose.

**Comment by in-fke** [comment]
> it does not matter if you call File.exists or file.isFile. Its both a slow system call

But the existing call (in JavaModel) is `java.io.File.isFile()` and the suggested one is `java.nio.file.Files.isRegularFile()`

**Comment by in-fke** [comment]
So I have no proof, but I thought I have read somewhere that the NIO call is faster than the IO call.
NIO seems to boil down to this
https://github.com/openjdk/jdk/blob/cb37282a12698ae66c27889db9251a5b278624b0/src/java.base/windows/classes/sun/nio/fs/WindowsFileAttributes.java#L296
IO seems to boil down to this
https://github.com/openjdk/jdk/blob/cb37282a12698ae66c27889db9251a5b278624b0/src/java.base/windows/classes/java/io/WinNTFileSystem.java#L585
And I think that I read somewhere that this call is expensive due to this "Blocker" thingy.
Can we at least give NIO a try?
I guess I could also try to write a Unit Test for that (I am bit baffled that I cannot find anything quickly by googling this).

**Comment by jukzi** [comment]
according to my comment in https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/183464/4#message-23c5c4754ed90763fd2126549e69e44dfe472047
it does not matter if you call File.exists or Files.isRegularFile.

the code to test that was
```
package benchmarks.file;

import java.io.IOException;
import java.nio.file.Files;

import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.RunnerException;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;

@BenchmarkMode(org.openjdk.jmh.annotations.Mode.AverageTime)
@OutputTimeUnit(java.util.concurrent.TimeUnit.MICROSECONDS)
@State(org.openjdk.jmh.annotations.Scope.Thread)
@Fork(value = 1, jvmArgsAppend = { "-Dsun.io.useCanonPrefixCache=false", "-Dsun.io.useCanonCaches=false", "-ea" })
@Warmup(time = 50, timeUnit = java.util.concurrent.TimeUnit.MILLISECONDS)
@Measurement(time = 50, timeUnit = java.util.concurrent.TimeUnit.MILLISECONDS, iterations = 10)
public class FilesAttributes {
	String fileName = "100b.txt";
	String dirName = "resources/";

	java.io.File file;
	java.io.File dir;


	@Setup
	public void setup() throws IOException {
		file = new java.io.File(dirName + fileName).getCanonicalFile();
		dir = new java.io.File(dirName).getCanonicalFile();
		assert file.exists() : "file not found:" + file;
	}

	@Benchmark
	public boolean fileExists() throws IOException {//
		return file.exists();
	}
	@Benchmark
	public boolean fileIsFile() throws IOException {//
		return file.isFile();
	}
	@Benchmark
	public boolean filesExists() throws IOException {//
		return Files.exists(file.toPath());
	}
	@Benchmark
	public boolean filesIsRegularFile() throws IOException {//
		return Files.isRegularFile(file.toPath());
	}


	public static void main(String[] args) throws RunnerException {
		Options opt = new OptionsBuilder().include(FilesAttributes.class.getSimpleName()).shouldFailOnError(true).build();

		new Runner(opt).run();
	}
}

```

result:

```
Benchmark                           Mode  Cnt   Score   Error  Units
FilesAttributes.fileExists          avgt   10  19,616 ± 2,529  us/op
FilesAttributes.fileIsFile          avgt   10  19,442 ± 3,258  us/op
FilesAttributes.filesExists         avgt   10  22,150 ± 0,344  us/op
FilesAttributes.filesIsRegularFile  avgt   10  20,089 ± 4,087  us/op
```

**Comment by jukzi** [comment]
> So I have no proof, but I thought I have read somewhere that the NIO call is faster than the IO call.

the faster thing in NIO is the better API. if you use
`
		BasicFileAttributes attrs = java.nio.file.Files.readAttributes(file.toPath(), BasicFileAttributes.class);
`
it takes also 20us but gives you all file attributes you can need. while io would do a separate system call for each attribute

**Comment by in-fke** [comment]
> the code to test that was

Thank you for providing this. I now did a similar benchmark, because I want to try it on different machines (suspecting that a realtime virus protection is making it even slower).

**So maybe we should be looking at this problem on a higher level, e.g. `ProblemTreeViewer.isExpandable` (see stack trace).**

Should we open another issue for that?

**Comment by in-fke** [comment]
@jukzi thanks for followin up on this. So has your commit
https://github.com/jukzi/eclipse.jdt.core/commit/c00eff4c98da8c21a76dc3959f9b7f4b4fc9df14
been pulled to any release yet? I am having trouble to track where this commit went to.
Thanks!

**Comment by jukzi** [comment]
JDT teams seems to have lack of resources to process pull request.

**Comment by in-fke** [comment]
> JDT teams seems to have lack of resources to process pull requests.

Ok, well thanks for the quick update! Hopefully, this will go through at some point.
I still cannot wrap my around the fact that `File.isFile()` is so slow!

**Comment by in-fke** [comment]
> @in-fke can you test if [eclipse-jdt/eclipse.jdt.ui#796](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/796) solves your performance problem? It should reduce number of file accesses instead of caching the result.

Hello Jörg, thanks for getting back to me - as for now, I won't have the time to test this from source build. I would have to rely on some release.

**Comment by jukzi** [comment]
@in-fke please test with I20230919-1800

**Comment by in-fke** [comment]
> @in-fke please test with I20230919-1800

Sorry, I'm lost - I found https://download.eclipse.org/equinox/drops/I20230919-1800/index.php - but where is the "PDE Core"?
It does not seem to be in the "All of Equinox" Repo?

**Comment by in-fke** [comment]
> @in-fke download from here: https://download.eclipse.org/eclipse/downloads/drops4/I20230919-1800/

Ok, I guess I now have it in place, we'll see how it goes

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/73228413/a31debb7-f634-4b0f-8cae-8d24dfe4b5d8)

**Comment by jukzi** [comment]
@in-fke  the main change for your problem was in jdt.ui - not pde!

**Comment by in-fke** [comment]
> @in-fke the main change for your problem was in jdt.ui - not pde!

Ok, thanks for the heads up. Got that update as well.

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/73228413/a78cfa35-ec03-452e-9eb3-33b2408da847)

**Comment by jukzi** [comment]
As far as i understand the sourcecode the issue can only happen if
* the javaprojects classpath refers to library inside the workspace (for example path="/TypeHierarchy/lib.jar")
* the eclipse workspace is not aware that such file exists in workspace, because
 a) the llib does not exists at all or 
 b) the file was just externally created and the workspace not yet refreshed 
 c) the file exists for long time but the project was just created/opened and is not yet loaded.
Happens for example during TypeHierarchyTests.testExternalFolder() when the setUpSuite() calls setUpJavaProject("TypeHierarchy")

**Comment by in-fke** [comment]
> the javaprojects classpath refers to library inside the workspace

Without knowing the source code, I can say for my scenario, `.classpath` has a lot of entries with *Classpath Variable* `M2_REPO` - if that matters. After the from `I20230919-1800` it works way better though.

**Comment by jukzi** [comment]
that was https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/796 - can we close this issue?

**Comment by in-fke** [comment]
> can we close this issue?

Thanks for asking - as far as I can judge you can close this issue. Thanks!

**Comment by jukzi** [comment]
@in-fke can you try this: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1971 if it helps even more?
