### ISSUE TITLE
[build][test] MultiProjectTests.testCycle* are unstable

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3081]
In I Build tests [this link may vanish later]: https://download.eclipse.org/eclipse/downloads/drops4/I20241014-0530/testresults/html/org.eclipse.jdt.core.tests.builder_ep434I-unit-win32-java17_win32.win32.x86_64_17.html

(1) 
org.eclipse.jdt.core.tests.builder.MultiProjectTests | testCycle7| Error

Build path contains duplicate entry: 'src' for project 'P1'

Java Model Exception: Error in Java Model (code 977): Build path contains duplicate entry: 'src' for project 'P1'
at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:812)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3494)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3454)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3510)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.setClasspath(TestingEnvironment.java:1179)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addEntry(TestingEnvironment.java:365)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addPackageFragmentRoot(TestingEnvironment.java:191)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addPackageFragmentRoot(TestingEnvironment.java:169)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addPackageFragmentRoot(TestingEnvironment.java:165)
at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addPackageFragmentRoot(TestingEnvironment.java:152)
at org.eclipse.jdt.core.tests.builder.MultiProjectTests.testCycle7(MultiProjectTests.java:1100)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

(2)

org.eclipse.jdt.core.tests.builder.MultiProjectTests | testCycle8 | Error | 

Build path contains duplicate entry: 'P2' for project 'P1'Java Model Exception: Error in Java Model (code 977): Build path contains duplicate entry: 'P2' for project 'P1'at 

org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:812)at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3494)at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3454)at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3510)at org.eclipse.jdt.core.tests.builder.TestingEnvironment.setClasspath(TestingEnvironment.java:1179)at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addEntry(TestingEnvironment.java:365)at org.eclipse.jdt.core.tests.builder.TestingEnvironment.addRequiredProject(TestingEnvironment.java:296)at org.eclipse.jdt.core.tests.builder.MultiProjectTests.testCycle8(MultiProjectTests.java:1210)at java.base/java.lang.reflect.Method.invoke(Method.java:568)at junit.framework.TestCase.runTest(TestCase.java:177)at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)at junit.framework.TestCase.runBare(TestCase.java:142)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)
-- | -- | -- | --

Please take a look at similar issues from bugzilla:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=412484
https://bugs.eclipse.org/bugs/show_bug.cgi?id=531897
https://bugs.eclipse.org/bugs/show_bug.cgi?id=505822
https://bugs.eclipse.org/bugs/show_bug.cgi?id=162054

**Comment by jukzi** [comment]
May relate to logged errors like

```
!ENTRY org.eclipse.jdt.core 4 4 2024-10-30 02:56:33.285
!MESSAGE Could not touch project P1
!STACK 1
org.eclipse.core.internal.resources.ResourceException(/P1)[368]: java.lang.Exception: Resource '/P1' does not exist.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:364)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:238)
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:183)
	at org.eclipse.core.internal.resources.Resource.checkAccessibleAndLocal(Resource.java:244)
	at org.eclipse.core.internal.resources.Resource.touch(Resource.java:1796)
	at org.eclipse.core.internal.resources.Project.touch(Project.java:1403)
	at org.eclipse.jdt.internal.core.JavaModelManager$TouchJob.lambda$0(JavaModelManager.java:377)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at org.eclipse.jdt.internal.core.JavaModelManager$TouchJob.runInWorkspace(JavaModelManager.java:369)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.core.resources 4 368 2024-10-30 02:56:33.297

```

or

```
WARNING in test: org.eclipse.jdt.core.tests.builder.ParticipantBuildTests - tearDown
	- problems occured while deleting resource P/Project
	- stack trace:
		-> org.eclipse.jdt.core.tests.util.Util.waitUntilResourceDeleted(Util.java:1425)
		-> org.eclipse.jdt.core.tests.util.Util.delete(Util.java:571)
		-> org.eclipse.jdt.core.tests.builder.TestingEnvironment.deleteResource(TestingEnvironment.java:523)
		-> org.eclipse.jdt.core.tests.builder.TestingEnvironment.removeProject(TestingEnvironment.java:1017)
		-> org.eclipse.jdt.core.tests.builder.TestingEnvironment.resetWorkspace(TestingEnvironment.java:1034)
		-> org.eclipse.jdt.core.tests.builder.BuilderTests.tearDown(BuilderTests.java:489)
		-> org.eclipse.jdt.core.tests.builder.ParticipantBuildTests.tearDown(ParticipantBuildTests.java:76)
...
	!!! ERROR: P/Project was never deleted even after having waited 10000ms!!!
```

https://download.eclipse.org/eclipse/downloads/drops4/I20241029-1800/testresults/ep434I-unit-win32-x86_64-java17_win32.win32.x86_64_17/org.eclipse.jdt.core.tests.builder.BuilderTests.txt
