### ISSUE TITLE
[build][test] TypeHierarchyNotificationTests.testAddCompilationUnit2 fails with message: Should receive change

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3104]
org.eclipse.jdt.core.tests.model.TypeHierarchyNotificationTests | testAddCompilationUnit2 | Failure
-- | -- | --

Failure at: https://download.eclipse.org/eclipse/downloads/drops4/I20241016-0020/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

Should receive change

junit.framework.AssertionFailedError: Should receive change
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.core.tests.model.TypeHierarchyNotificationTests.assertOneChange(TypeHierarchyNotificationTests.java:55)
at org.eclipse.jdt.core.tests.model.TypeHierarchyNotificationTests.testAddCompilationUnit2(TypeHierarchyNotificationTests.java:221)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by mpalat** [comment]
Locally this is running - this looks like a time out issue. would close this now. To reopen and investigate further if required.

**Comment by HannesWell** [comment]
This occurred again in https://download.eclipse.org/eclipse/downloads/drops4/I20241101-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-linux-x86_64-java23_linux.gtk.x86_64_23.html.

**Comment by jukzi** [comment]
happend again:
https://download.eclipse.org/eclipse/downloads/drops4/I20241211-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-aarch64-java17_macosx.cocoa.aarch64_17.html

**Comment by subyssurendran666** [comment]
Failed again https://download.eclipse.org/eclipse/downloads/drops4/I20250211-0520/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by subyssurendran666** [comment]
`TypeHierarchyNotificationTests.testAddExtendsSourceType3` is failing in https://download.eclipse.org/eclipse/downloads/drops4/I20250221-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by mpalat** [comment]
yet another failure at: https://download.eclipse.org/eclipse/downloads/drops4/I20250521-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by subyssurendran666** [comment]
`TypeHierarchyNotificationTests.testAddCompilationUnit2` failed in
https://download.eclipse.org/eclipse/downloads/drops4/I20250521-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by subyssurendran666** [comment]
[**`TypeHierarchyNotificationTests.testAddAnonymousInRegion`** | **Failure**](https://download.eclipse.org/eclipse/downloads/drops4/I20250614-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep437I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html)

```
Should receive change

junit.framework.AssertionFailedError: Should receive change
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.core.tests.model.TypeHierarchyNotificationTests.assertOneChange(TypeHierarchyNotificationTests.java:55)
at org.eclipse.jdt.core.tests.model.TypeHierarchyNotificationTests.testAddAnonymousInRegion(TypeHierarchyNotificationTests.java:153)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by jarthana** [comment]
Failed again in the last build: https://download.eclipse.org/eclipse/downloads/drops4/I20260221-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep439I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html
