### ISSUE TITLE
Errors reported while updating working sets

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#3125]
I have workspace with ~20 working sets containing most of SDK projects.
Starting latest IBuild I see random errors logged during startup, refresh, pull operations (all that involve workspace operations like build or refresh etc).
```
java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.core.IJavaModel.getNonJavaResources()" is null
	at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater.updateElements(OthersWorkingSetUpdater.java:196)
	at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater$ResourceChangeListener.resourceChanged(OthersWorkingSetUpdater.java:70)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:465)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1593)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2471)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.egit.core.internal.ResourceRefreshHandler.refreshRepository(ResourceRefreshHandler.java:170)
	at org.eclipse.egit.core.internal.ResourceRefreshHandler.onWorkingTreeModified(ResourceRefreshHandler.java:83)
	at org.eclipse.jgit.events.WorkingTreeModifiedEvent.dispatch(WorkingTreeModifiedEvent.java:97)
	at org.eclipse.jgit.events.WorkingTreeModifiedEvent.dispatch(WorkingTreeModifiedEvent.java:1)
	at org.eclipse.jgit.events.ListenerList.dispatch(ListenerList.java:102)
	at org.eclipse.egit.core.RepositoryCache.lambda$3(RepositoryCache.java:107)
	at org.eclipse.jgit.events.WorkingTreeModifiedEvent.dispatch(WorkingTreeModifiedEvent.java:97)
	at org.eclipse.jgit.events.WorkingTreeModifiedEvent.dispatch(WorkingTreeModifiedEvent.java:1)
	at org.eclipse.jgit.events.ListenerList.dispatch(ListenerList.java:102)
	at org.eclipse.jgit.lib.Repository.fireEvent(Repository.java:172)
	at org.eclipse.egit.core.RepositoryHandle.fireEvent(RepositoryHandle.java:149)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:496)
	at org.eclipse.jgit.api.RebaseCommand.checkoutCommit(RebaseCommand.java:1497)
	at org.eclipse.jgit.api.RebaseCommand.initFilesAndRewind(RebaseCommand.java:1165)
	at org.eclipse.jgit.api.RebaseCommand.call(RebaseCommand.java:290)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:366)
	at org.eclipse.egit.core.op.PullOperation$PullJob.run(PullOperation.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.core.IJavaModel.getNonJavaResources()" is null
	at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater.updateElements(OthersWorkingSetUpdater.java:196)
	at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater$ResourceChangeListener.resourceChanged(OthersWorkingSetUpdater.java:70)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:465)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1593)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2471)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:821)
	at org.eclipse.jdt.core.JavaCore.setClasspathContainer(JavaCore.java:6237)
	at org.eclipse.pde.internal.core.PluginModelManager$UpdateClasspathsJob.run(PluginModelManager.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.core.IJavaModel.getNonJavaResources()" is null
	at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater.updateElements(OthersWorkingSetUpdater.java:196)
	at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater$ResourceChangeListener.resourceChanged(OthersWorkingSetUpdater.java:70)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:465)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1593)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2471)
	at org.eclipse.core.internal.events.NotificationManager$NotifyJob.run(NotificationManager.java:60)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The root cause is the recent code change that violated the API contract of `org.eclipse.jdt.core.IJavaModel.getNonJavaResources()` by returning `null` array.

This is regression from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3117.

I would propose to revert this change completely.

**Comment by iloveeclipse** [comment]
Note, we have 4 PDE test failures also caused by the same issue, since https://download.eclipse.org/eclipse/downloads/drops4/I20241019-0120/testResults.php

Example from https://download.eclipse.org/eclipse/downloads/drops4/I20241020-1800/testresults/html/org.eclipse.pde.ui.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
!STACK 0 java.lang.NullPointerException: Cannot read the array length because "a2" is null at org.eclipse.jdt.ui.StandardJavaElementContentProvider.concatenate(StandardJavaElementContentProvider.java:559) at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.getChildren(PackageExplorerContentProvider.java:297) at org.eclipse.jdt.ui.StandardJavaElementContentProvider.getElements(StandardJavaElementContentProvider.java:163) at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:941) at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:702) at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1456) at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:352) at org.eclipse.jdt.internal.ui.viewsupport.ProblemTreeViewer.getFilteredChildren(ProblemTreeViewer.java:251) at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1025) at org.eclipse.jface.viewers.ColumnViewer.getSortedChildren(ColumnViewer.java:821) at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:690) at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2896) at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:2031) at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684) at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:2004) at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1954) at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart$PackageExplorerProblemTreeViewer.internalRefresh(PackageExplorerPart.java:272) at org.eclipse.jface.viewers.StructuredViewer.lambda$3(StructuredViewer.java:1486) at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1392) at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:367) at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1353) at
```

**Comment by iloveeclipse** [comment]
For the record: on the console Eclipse reported this stack:
```
org.eclipse.core.internal.resources.ResourceException(null)[380]: java.lang.Exception: The resource tree is locked for modifications.
        at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
        at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
        at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
        at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2407)
        at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1595)
        at org.eclipse.jdt.internal.core.JavaModelInfo.computeNonJavaResources(JavaModelInfo.java:36)
        at org.eclipse.jdt.internal.core.JavaModelInfo.getNonJavaResources(JavaModelInfo.java:67)
        at org.eclipse.jdt.internal.core.JavaModel.getNonJavaResources(JavaModel.java:233)
        at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater.updateElements(OthersWorkingSetUpdater.java:196)
        at org.eclipse.jdt.internal.ui.workingsets.OthersWorkingSetUpdater$ResourceChangeListener.resourceChanged(OthersWorkingSetUpdater.java:70)
        at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
        at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
        at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:465)
        at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1593)
        at org.eclipse.core.internal.resources.Workspace.createMultiple(Workspace.java:2881)
        at org.eclipse.core.internal.resources.Workspace.write(Workspace.java:2832)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.flushBatch(BatchImageBuilder.java:433)
        at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:646)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:496)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:447)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:441)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:250)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:118)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:314)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:233)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
