### ISSUE TITLE
IllegalArgumentException for ParenthesizedExpression on Assignment LHS

### ISSUE THREAD

**Issue by lucach** [eclipse-jdt/eclipse.jdt.core#316]
The following exception is thrown with the latest version of `org.eclipse.jdt.core` (3.30.0) when requesting to create an AST containing a ParenthesizedExpression in the left-hand side of an Assignment.

```
Status ERROR: org.eclipse.jdt.core code=4 Exception occurred during compilation unit conversion:
----------------------------------- SOURCE BEGIN -------------------------------------
class C {
    void m() { (1+2) = 3; }
}

----------------------------------- SOURCE END ------------------------------------- java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.InfixExpression.setOperator(InfixExpression.java:383)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1287)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2047)
	at org.eclipse.jdt.core.dom.ASTConverter.convertToParenthesizedExpression(ASTConverter.java:3853)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1953)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1204)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1990)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3095)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:751)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:208)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3390)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1534)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1136)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:739)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1049)
```

**Comment by iloveeclipse** [comment]
Is this a recent  regression? Could you bisect to the commit caused this?

**Comment by lucach** [comment]
I can't easily bisect to the commit as I'm fetching this as a maven dependency in an external project, but I've tried to find the first version that introduces the problem.

Up to **3.21.0** I correctly get "The left-hand side of an assignment must be a variable".
Starting from **3.22.0**, it throws an IllegalArgumentException.

**Comment by iloveeclipse** [comment]
See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/317

**Comment by jukzi** [comment]
@jarthana 
this was a regression from https://github.com/eclipse-jdt/eclipse.jdt.core/commit/9295bf84c9dbff60af20ec946d9d9cb0c37008df#diff-ef63a9e47d7749fd5654358b0f66887df86d8ed7821efed9a8d87981017d3188R109

Whereafter the bits of "reference lhs" and "operator" in ASTNode overlapp.

**Comment by jukzi** [comment]
fixed.
