### ISSUE TITLE
[23][Preview][Primitive Patterns] NPE when a record component is null in a record pattern

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#3182]
This code compiles as expected, but throws an NPE when run:

```
record Circle(Integer radius) {}
public class X {
	public static int foo(Circle c) {
		if (c instanceof Circle(int r)) {
			return r;
		}
		return 0;
	}
	public static void main(String[] args) {
		System.out.println(foo(new Circle(null)));
	}
}
```

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "Circle.radius()" is null
	at X.foo(X.java:4)
	at X.main(X.java:10)
```

**Comment by srikanth-sankaran** [comment]
Any primitive-reference mismatch between declared record component and the record pattern's component means it is JEP 455 related. So reassigning to @stephan-herrmann - Thanks for taking a look Stephan.

**Comment by srikanth-sankaran** [comment]
(Feel free to adjust milestone set by me while triaging)

**Comment by stephan-herrmann** [comment]
I can reproduce with 4.34, but compiled with ecj 4.35M1 or later the program prints "0". The same when compiled with javac.

I can't, however, say which exact change fixed this.
