### ISSUE TITLE
ClassCastException when ctrl+hover over a 'case' literal

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#3220]
```java
public class Hover {

	void do2() {
		record R(int i, long l) {}

		R r = new R(1, 1);
		switch (r) {
			case R(_, long l) -> {}
			case R r2 -> {}
		}
	}
}
```
Hold <kbd>Ctrl</kbd> and hover over the second `case` literal. The `case` will become clickable as if it's a method or parameter, which is wrong. Then, while still holding <kbd>Ctrl</kbd>, move the mouse to the first case label. A bunch of these errors will be thrown:
```
Unhandled event loop exception

java.lang.ClassCastException: class org.eclipse.jdt.core.dom.VariableDeclarationFragment cannot be cast to class org.eclipse.jdt.core.dom.SingleVariableDeclaration (org.eclipse.jdt.core.dom.VariableDeclarationFragment and org.eclipse.jdt.core.dom.SingleVariableDeclaration are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @17a0846)
	at org.eclipse.jdt.core.dom.TypePattern.getPatternVariable(TypePattern.java:242)
	at org.eclipse.jdt.internal.corext.dom.ASTFlattener.visit(ASTFlattener.java:2021)
	at org.eclipse.jdt.internal.corext.dom.ASTFlattener.visitPattern(ASTFlattener.java:1451)
	at org.eclipse.jdt.internal.corext.dom.ASTFlattener.visit(ASTFlattener.java:1427)
	at org.eclipse.jdt.core.dom.RecordPattern.accept0(RecordPattern.java:231)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.corext.dom.ASTFlattener.visit(ASTFlattener.java:1669)
	at org.eclipse.jdt.core.dom.SwitchCase.accept0(SwitchCase.java:212)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.corext.dom.ASTNodes.asString(ASTNodes.java:366)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.findSwitchCaseTarget(JavaElementHyperlinkDetector.java:290)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinksCached(JavaElementHyperlinkDetector.java:116)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.lambda$0(JavaElementHyperlinkDetector.java:84)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5694)
	at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5683)
	at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6150)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinks(JavaElementHyperlinkDetector.java:84)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:229)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4368)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1173)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4166)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:663)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:570)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:178)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
```
From the stack trace, I'm not sure if this is a bug in jdt.core or jdt.ui, but the exception itself happens in core.

eclipse.buildId=4.34.0.I20241101-1800
java.version=22
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US

**Comment by srikanth-sankaran** [comment]
@subyssurendran666 would you like to work on this ?

**Comment by subyssurendran666** [comment]
With pleasure! Could you please assign this to me?

> @subyssurendran666 would you like to work on this ?

**Comment by subyssurendran666** [comment]
I believe this issue is related to JDT.UI

In Java 22, a new feature called [unnamed variables and patterns](https://openjdk.org/jeps/456) has been introduced. To accommodate this, certain changes have been incorporated into JDT.Core. For example, in a case literal like `case R(_, long l) -> {}`, the first parameter of the record is an unnamed pattern (_). In JDT.Core DOM, unnamed patterns are handled by TypePattern. Here, the PatternVariable of the TypePattern is a VariableDeclarationFragment (since it has no type). However, the visit method in [ASTFlattener](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java#L2019) attempts to cast the patternVariable to SingleVariableDeclaration through getPatternVariable(), which is applicable only for Java version below 22.

<img width="563" alt="Screenshot 2024-11-03 at 11 52 29 PM" src="https://github.com/user-attachments/assets/17aa23e9-3a14-487f-a8ee-79470e421fab">

This issue has been addressed by implementing a new method called getPatternVariable2(). I believe the code below, or a similar approach, should resolve the issue.

```
 public boolean visit(TypePattern node) {
		if (ASTHelper.isPatternSupported(node.getAST())) {
                         if (node.getAST().apiLevel() < ASTHelper.JLS22) {
			    node.getPatternVariable().accept(this);
                         } else {
                              node.getPatternVariable2().accept(this);
                         }
		}
		return false;
}
```

**Comment by nlisker** [comment]
So should this be transferred to jdt.ui?

**Comment by srikanth-sankaran** [comment]
@subyssurendran666 - the code you cite is in jdt-core, no ?

**Comment by subyssurendran666** [comment]
No @srikanth-sankaran, the [ASTFlattener](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/corext/dom/ASTFlattener.java#L2019)(which is in JDT.UI)  is calling the `getPatternVariable()` API from the DOM.
