### ISSUE TITLE
[build][test] CompletionTests16_2.test002 fails with Assertion error

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3230]
In https://download.eclipse.org/eclipse/downloads/drops4/I20241030-1630/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

----------- Expected ------------ Enum[TYPE_REF]{Enum, java.lang, Ljava.lang.Enum;, null, null, 44}\n enum[KEYWORD]{enum, null, null, enum, null, 49} ------------ but was ------------ enum[KEYWORD]{enum, null, null, enum, null, 49} ---------------------- ---------- expected:<[Enum[TYPE_REF]{Enum, java.lang, Ljava.lang.Enum;, null, null, 44}\n ]enum[KEYWORD]{enum, ...> but was:<[]enum[KEYWORD]{enum, ...>

junit.framework.ComparisonFailure:
----------- Expected ------------
Enum[TYPE_REF]{Enum, java.lang, Ljava.lang.Enum;, null, null, 44}\n
enum[KEYWORD]{enum, null, null, enum, null, 49}
------------ but was ------------
enum[KEYWORD]{enum, null, null, enum, null, 49}
---------------------- ----------
expected:<[Enum[TYPE_REF]{Enum, java.lang, Ljava.lang.Enum;, null, null, 44}\n
]enum[KEYWORD]{enum, ...> but was:<[]enum[KEYWORD]{enum, ...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelCompletionTests.assertResults(AbstractJavaModelCompletionTests.java:223)
at org.eclipse.jdt.core.tests.model.CompletionTests16_2.test002(CompletionTests16_2.java:77)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by trancexpress** [comment]
Another fail in the test case here: https://download.eclipse.org/eclipse/downloads/drops4/I20260320-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html

```
	----------- Expected ------------ Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52} ------------ but was ------------ record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52} ---------------------- ---------- expected:<[Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n ]record[LOCAL_VARIABL...> but was:<[]record[LOCAL_VARIABL...>

junit.framework.ComparisonFailure:
----------- Expected ------------
Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}
------------ but was ------------
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}
---------------------- ----------
expected:<[Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n
]record[LOCAL_VARIABL...> but was:<[]record[LOCAL_VARIABL...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelCompletionTests.assertResults(AbstractJavaModelCompletionTests.java:227)
at org.eclipse.jdt.core.tests.model.CompletionTests16.testBug564828_2(CompletionTests16.java:384) 
```

Nothing in the workspace log: https://download.eclipse.org/eclipse/downloads/drops4/I20260320-1800/testresults/ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

```
01:18:06.680 SETUP CompletionTests16.testBug564828_2
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}

01:18:06.682 TDOWN CompletionTests16.testBug564828_2
```

**Comment by trancexpress** [comment]
`testBug564828_2` continues to fail, e.g.: https://download.eclipse.org/eclipse/downloads/drops4/I20260826-2300/testresults/html/org.eclipse.jdt.core.tests.model_ep441I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html

```
----------- Expected ------------ Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52} ------------ but was ------------ record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52} ---------------------- ---------- expected:<[Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n ]record[LOCAL_VARIABL...> but was:<[]record[LOCAL_VARIABL...>

junit.framework.ComparisonFailure:
----------- Expected ------------
Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}
------------ but was ------------
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}
---------------------- ----------
expected:<[Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n
]record[LOCAL_VARIABL...> but was:<[]record[LOCAL_VARIABL...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelCompletionTests.assertResults(AbstractJavaModelCompletionTests.java:227)
at org.eclipse.jdt.core.tests.model.CompletionTests16.testBug564828_2(CompletionTests16.java:384)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```

Lets enable JDT core verbose mode for the test, maybe it helps understanding the issue.

**Comment by mpalat** [comment]
same failure at https://download.eclipse.org/eclipse/downloads/drops4/I20260826-2300/testresults/html/org.eclipse.jdt.core.tests.model_ep441I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html for testBug564828_2  - updating here for reference

**Comment by trancexpress** [comment]
The `testBug564828_2` fail occurred again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260916-2300/testresults/html/org.eclipse.jdt.core.tests.model_ep442I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html

```
	----------- Expected ------------ Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52} ------------ but was ------------ record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52} ---------------------- ---------- expected:<[Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n ]record[LOCAL_VARIABL...> but was:<[]record[LOCAL_VARIABL...>

junit.framework.ComparisonFailure:
----------- Expected ------------
Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}
------------ but was ------------
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}
---------------------- ----------
expected:<[Record[TYPE_REF]{Record, java.lang, Ljava.lang.Record;, null, null, 44}\n
]record[LOCAL_VARIABL...> but was:<[]record[LOCAL_VARIABL...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelCompletionTests.assertResults(AbstractJavaModelCompletionTests.java:227)
at org.eclipse.jdt.core.tests.model.CompletionTests16.testBug564828_2(CompletionTests16.java:392)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```

Workspace log: https://download.eclipse.org/eclipse/downloads/drops4/I20260916-2300/testresults/ep442I-unit-linux-x86_64-java26_linux.gtk.x86_64_26/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

```
02:37:10.760 SETUP CompletionTests16.testBug564828_2
| main | 2026-09-17 02:37:10.761 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 1981 | COMPLETION IN /Completion/src/Point.java AT POSITION 70 |
| main | 2026-09-17 02:37:10.761 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 1982 | COMPLETION - Source :public class Point {
private void method(){
int record;
{
 /*here*/rec
}
}
} |
| main | 2026-09-17 02:37:10.761 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2003 | COMPLETION - Diet AST : |
| main | 2026-09-17 02:37:10.761 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2004 | public class Point {
  public Point() {
  }
  private void method() {
  }
}
 |
| main | 2026-09-17 02:37:10.762 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2210 | COMPLETION - AST : |
| main | 2026-09-17 02:37:10.762 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2211 | public class Point {
  public Point() {
  }
  private void method() {
    int record;
    {
      <CompleteOnName:rec>;
    }
  }
}
 |
| main | 2026-09-17 02:37:10.762 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2220 | COMPLETION - Completion node : <CompleteOnName:rec> |
| main | 2026-09-17 02:37:10.762 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | buildContext | 1754 | org.eclipse.jdt.internal.codeassist.InternalCompletionContext@368260d1 |
| main | 2026-09-17 02:37:10.762 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | printDebug | 13935 | COMPLETION - LOCAL_VARIABLE_REF{
	Completion[record]
	DeclarationSignature[null]
	DeclarationKey[null]
	Signature[I]
	Key[null]
	Name[record]
	Flags[]
	CompletionLocation[69]
	ReplaceStart[67]-ReplaceEnd[70]
	TokenStart[67]-TokenEnd[70]
	ReplacedText[rec]
	TokenStart[67]-TokenEnd[70]
	Relevance[52]
}
 |
record[LOCAL_VARIABLE_REF]{record, null, I, record, null, 52}

02:37:10.763 TDOWN CompletionTests16.testBug564828_2
```

If I run the test from Eclipse, the output is:

```
10:55:44.770 SETUP CompletionTests16.testBug564828_2
| main | 2026-09-17 10:55:44.773 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 1981 | COMPLETION IN /Completion/src/Point.java AT POSITION 70 |
| main | 2026-09-17 10:55:44.774 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 1982 | COMPLETION - Source :public class Point {
private void method(){
int record;
{
 /*here*/rec
}
}
} |
| main | 2026-09-17 10:55:44.775 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2003 | COMPLETION - Diet AST : |
| main | 2026-09-17 10:55:44.775 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2004 | public class Point {
  public Point() {
  }
  private void method() {
  }
}
 |
| main | 2026-09-17 10:55:44.777 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2210 | COMPLETION - AST : |
| main | 2026-09-17 10:55:44.777 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2211 | public class Point {
  public Point() {
  }
  private void method() {
    int record;
    {
      <CompleteOnName:rec>;
    }
  }
}
 |
| main | 2026-09-17 10:55:44.777 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | complete | 2220 | COMPLETION - Completion node : <CompleteOnName:rec> |
| main | 2026-09-17 10:55:44.778 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | buildContext | 1754 | org.eclipse.jdt.internal.codeassist.InternalCompletionContext@7bdb4f17 |
| main | 2026-09-17 10:55:44.779 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | printDebug | 13935 | COMPLETION - LOCAL_VARIABLE_REF{
	Completion[record]
	DeclarationSignature[null]
	DeclarationKey[null]
	Signature[I]
	Key[null]
	Name[record]
	Flags[]
	CompletionLocation[69]
	ReplaceStart[67]-ReplaceEnd[70]
	TokenStart[67]-TokenEnd[70]
	ReplacedText[rec]
	TokenStart[67]-TokenEnd[70]
	Relevance[52]
}
 |
| main | 2026-09-17 10:55:44.782 | org.eclipse.jdt.core | /debug | org.eclipse.jdt.internal.codeassist.CompletionEngine | printDebug | 13935 | COMPLETION - TYPE_REF{
	Completion[Record]
	DeclarationSignature[java.lang]
	DeclarationKey[null]
	Signature[Ljava.lang.Record;]
	Key[null]
	Name[null]
	Flags[public abstract synchronized]
	CompletionLocation[69]
	ReplaceStart[67]-ReplaceEnd[70]
	TokenStart[67]-TokenEnd[70]
	ReplacedText[rec]
	TokenStart[67]-TokenEnd[70]
	Relevance[44]
}
 |
10:55:44.783 TDOWN CompletionTests16.testBug564828_2
```

I'm not seeing anything useful in the current tracing.
