### ISSUE TITLE
[build][test] ClasspathTests.testDotDotLibraryEntry8 fails with Assertion error

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3231]
In https://download.eclipse.org/eclipse/downloads/drops4/I20241030-1630/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

```
----------- Expected ------------ /P[CPE_SOURCE][K_SOURCE][isExported:false]\n ../external.jar[CPE_LIBRARY][K_BINARY][isExported:false] ------------ but was ------------ /P[CPE_SOURCE][K_SOURCE][isExported:false]\n JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false] ---------------------- ---------- expected:<...isExported:false]\n [../external.jar[CPE_LIBRARY][K_BINARY]][isExported:false]> but was:<...isExported:false]\n [JCL18_LIB[CPE_VARIABLE][K_SOURCE]][isExported:false]>

junit.framework.ComparisonFailure:
----------- Expected ------------
/P[CPE_SOURCE][K_SOURCE][isExported:false]\n
../external.jar[CPE_LIBRARY][K_BINARY][isExported:false]
------------ but was ------------
/P[CPE_SOURCE][K_SOURCE][isExported:false]\n
JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false]
---------------------- ----------
expected:<...isExported:false]\n
[../external.jar[CPE_LIBRARY][K_BINARY]][isExported:false]> but was:<...isExported:false]\n
[JCL18_LIB[CPE_VARIABLE][K_SOURCE]][isExported:false]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertClasspathEquals(AbstractJavaModelTests.java:1300)
at org.eclipse.jdt.core.tests.model.ClasspathTests.testDotDotLibraryEntry8(ClasspathTests.java:2847)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by subyssurendran666** [comment]
Faile Again in https://download.eclipse.org/eclipse/downloads/drops4/I20250126-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by subyssurendran666** [comment]
`ClasspathTests.testDotDotLibraryEntry8` failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250317-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

**Comment by subyssurendran666** [comment]
`ClasspathTests.testDotDotLibraryEntry8` failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250322-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by trancexpress** [comment]
See also here:

https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4886
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4886/checks?check_run_id=65387921355

**Comment by iloveeclipse** [comment]
Let assume it is fixed now. If not, we can always reopen.
