### ISSUE TITLE
ClasspathTests.testCycleDetection fails with message: Invalid cycle detection after setting classpath for: P2

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3232]
in https://download.eclipse.org/eclipse/downloads/drops4/I20241031-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

Invalid cycle detection after setting classpath for: P2. ----------- Expected ------------ {P1, P2} ------------ but was ------------ {} ---------------------- ---------- expected:<{[P1, P2]}> but was:<{[]}>

junit.framework.ComparisonFailure: Invalid cycle detection after setting classpath for: P2.
----------- Expected ------------
{P1, P2}
------------ but was ------------
{}
---------------------- ----------
expected:<{[P1, P2]}> but was:<{[]}>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.model.ClasspathTests.assertCycleMarkers(ClasspathTests.java:133)
at org.eclipse.jdt.core.tests.model.ClasspathTests.testCycleDetection(ClasspathTests.java:4478)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by subyssurendran666** [comment]
`ClasspathTests.testCycleDetection` Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250320-0640/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`ClasspathTests.testCycleDetection` Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250321-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html
