### ISSUE TITLE
ClasspathTests.testCombineAccessRules5 fails with Assertion error

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3234]
In https://download.eclipse.org/eclipse/downloads/drops4/I20241102-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-win32-x86_64-java17_win32.win32.x86_64_17.html

----------- Expected ------------ /P2/src[CPE_SOURCE][K_SOURCE][isExported:false] ------------ but was ------------ /P2[CPE_SOURCE][K_SOURCE][isExported:false]\n JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false] ---------------------- ---------- expected:</P2[/src[CPE_SOURC]E][K_SOURCE][isExpor...> but was:</P2[[CPE_SOURCE][K_SOURCE][isExported:false]\n JCL18_LIB[CPE_VARIABL]E][K_SOURCE][isExpor...>

junit.framework.ComparisonFailure:
----------- Expected ------------
/P2/src[CPE_SOURCE][K_SOURCE][isExported:false]
------------ but was ------------
/P2[CPE_SOURCE][K_SOURCE][isExported:false]\n
JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false]
---------------------- ----------
expected:</P2[/src[CPE_SOURC]E][K_SOURCE][isExpor...> but was:</P2[[CPE_SOURCE][K_SOURCE][isExported:false]\n
JCL18_LIB[CPE_VARIABL]E][K_SOURCE][isExpor...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertClasspathEquals(AbstractJavaModelTests.java:1300)
at org.eclipse.jdt.core.tests.model.ClasspathTests.testCombineAccessRules5(ClasspathTests.java:4423)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by trancexpress** [comment]
Seen again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260305-1800/reports.html#tests

```
org.eclipse.jdt.core.tests.model.ClasspathTests	testCombineAccessRules5	Failure	----------- Expected ------------ /P2/src[CPE_SOURCE][K_SOURCE][isExported:false] ------------ but was ------------ /P2[CPE_SOURCE][K_SOURCE][isExported:false]\n JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false] ---------------------- ---------- expected:</P2[/src[CPE_SOURC]E][K_SOURCE][isExpor...> but was:</P2[[CPE_SOURCE][K_SOURCE][isExported:false]\n JCL18_LIB[CPE_VARIABL]E][K_SOURCE][isExpor...>

junit.framework.ComparisonFailure:
----------- Expected ------------
/P2/src[CPE_SOURCE][K_SOURCE][isExported:false]
------------ but was ------------
/P2[CPE_SOURCE][K_SOURCE][isExported:false]\n
JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false]
---------------------- ----------
expected:</P2[/src[CPE_SOURC]E][K_SOURCE][isExpor...> but was:</P2[[CPE_SOURCE][K_SOURCE][isExported:false]\n
JCL18_LIB[CPE_VARIABL]E][K_SOURCE][isExpor...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:237)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertClasspathEquals(AbstractJavaModelTests.java:1317)
at org.eclipse.jdt.core.tests.model.ClasspathTests.testCombineAccessRules5(ClasspathTests.java:4434)
```

Workspace log:

https://download.eclipse.org/eclipse/downloads/drops4/I20260305-1800/testresults/ep440I-unit-win32-x86_64-java21_win32.win32.x86_64_21/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

```
03:26:56.659 SETUP ClasspathTests.testCombineAccessRules5
Classpath variable 'JCL10_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin10.jar', file size: 14041
Classpath variable 'JCL10_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin10src.zip', file size: 9293
Classpath variable 'JCL11_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin11.jar', file size: 14093
Classpath variable 'JCL11_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin11src.zip', file size: 9293
Classpath variable 'JCL13_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin13.jar', file size: 14499
Classpath variable 'JCL13_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin13src.zip', file size: 9875
Classpath variable 'JCL14_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin14.jar', file size: 23930
Classpath variable 'JCL14_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin14src.zip', file size: 15214
Classpath variable 'JCL18_FULL', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclFull1.8.jar', file size: 621002
Classpath variable 'JCL18_FULL_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclFull1.8src.zip', file size: 10862
Classpath variable 'JCL18_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin1.8.jar', file size: 14941
Classpath variable 'JCL18_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin1.8src.zip', file size: 9405
Classpath variable 'JCL19_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin9.jar', file size: 14071
Classpath variable 'JCL19_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin9src.zip', file size: 9298
Classpath variable 'JCL_17_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin17.jar', file size: 20760
Classpath variable 'JCL_17_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin17src.zip', file size: 16559
Classpath variable 'JCL_21_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin21.jar', file size: 27542
Classpath variable 'JCL_21_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin21src.zip', file size: 20544
Classpath variable 'JCL_23_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin23.jar', file size: 31479
Classpath variable 'JCL_23_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin23src.zip', file size: 22822
Classpath variable 'JCL_24_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin24.jar', file size: 28685
Classpath variable 'JCL_24_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin24src.zip', file size: 21757
Classpath variable 'JCL_25_LIB', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin25.jar', file size: 25061
Classpath variable 'JCL_25_SRC', path: 'C:/Users/genie.releng/workspace/AutomatedTests/ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/test-eclipse/eclipse/jdt_model_folder/jclMin25src.zip', file size: 18857
Classpath variable 'JCL_SRCROOT', path: 'src', file size: 0
		"/P2[CPE_SOURCE][K_SOURCE][isExported:false]\n" + 
		"JCL18_LIB[CPE_VARIABLE][K_SOURCE][isExported:false]"03:26:56.768 TDOWN ClasspathTests.testCombineAccessRules5
```

Console log:

https://download.eclipse.org/eclipse/downloads/drops4/I20260305-1800/testresults/consolelogs/ep440I-unit-win32-x86_64-java21_win32.win32.x86_64_21_consolelog.txt

```

java-test:
     [echo] Running org.eclipse.jdt.core.tests.model.AllJavaModelTests. Result file: C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21/workarea/I20260305-1800/eclipse-testing/results/ep440I-unit-win32-x86_64-java21_win32.win32.x86_64_21/org.eclipse.jdt.core.tests.model.AllJavaModelTests.xml
     [echo] timout property: 7200000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m -Djava.io.tmpdir=C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21\tmp
     [echo] vmargs: -XX:CompileCommand=exclude,org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer::getExtendedRange -Xmx800M -XX:+HeapDumpOnOutOfMemoryError -DDetectVMInstallationsJob.disabled=true -DstoreMemory=jdtcoremodel_mem_trace,dir=C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21\workarea\I20260305-1800\eclipse-testing\test-eclipse\eclipse/../.. -Djdt.default.test.compliance=1.8
     [echo] extraVMargs: 
     [echo] frameworkperfargs: 
     [echo] crash loglocationarg (if any): ${loglocationarg}
     [echo] crash loglocation (if not default): 
     [java] Mar 06, 2026 3:21:21 AM org.apache.aries.spifly.BaseActivator log
     [java] INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
     [java] INFO: timeoutScreenOutputDir: C:\Users\genie.releng\workspace\AutomatedTests\ep440I-unit-win32-x86_64-java21\workarea\I20260305-1800\eclipse-testing\results\ep440I-unit-win32-x86_64-java21_win32.win32.x86_64_21/timeoutScreens
     [java] INFO: timeout: 7200000
     [java] ClasspathTests#testInvalidClasspath1() may generate an expected Fatal Error...
     [java] [Fatal Error] :3:43: Element type "classpathentry" must be followed by either attribute specifications, ">" or "/>".
     [java] Test testModuleCaching requires a JRE [9,11)
     [java] ----------
     [java] 1. ERROR in a\enum\b\NonCompliant.java (at line 1)
     [java] 	package a.enum.b;
     [java] 	          ^^^^
     [java] Syntax error on token "enum", Identifier expected
     [java] ----------
     [java] ----------
     [java] 1. ERROR in lib\External.java (at line 2)
     [java] 	import a.enum.b.NonCompliant;
     [java] 	         ^^^^
     [java] Syntax error on token "enum", Identifier expected
     [java] ----------
     [java] 2. ERROR in lib\External.java (at line 4)
     [java] 	public NonCompliant setNonCompliant(NonCompliant x) {
     [java] 	       ^^^^^^^^^^^^
     [java] NonCompliant cannot be resolved to a type
     [java] ----------
     [java] 3. ERROR in lib\External.java (at line 4)
     [java] 	public NonCompliant setNonCompliant(NonCompliant x) {
     [java] 	                                    ^^^^^^^^^^^^
     [java] NonCompliant cannot be resolved to a type
     [java] ----------
     [java] ----------
     [java] 1. ERROR in a\enum\b\NonCompliant.java (at line 1)
     [java] 	package a.enum.b;
     [java] 	          ^^^^
     [java] Syntax error on token "enum", Identifier expected
     [java] ----------
     [java] ----------
     [java] 1. ERROR in lib\External.java (at line 2)
     [java] 	import a.enum.b.NonCompliant;
     [java] 	         ^^^^
     [java] Syntax error on token "enum", Identifier expected
     [java] ----------
     [java] 2. ERROR in lib\External.java (at line 4)
     [java] 	public NonCompliant setNonCompliant(NonCompliant x) {
     [java] 	       ^^^^^^^^^^^^
     [java] NonCompliant cannot be resolved to a type
     [java] ----------
     [java] 3. ERROR in lib\External.java (at line 4)
     [java] 	public NonCompliant setNonCompliant(NonCompliant x) {
     [java] 	                                    ^^^^^^^^^^^^
     [java] NonCompliant cannot be resolved to a type
     [java] ----------
     [java] Java Result: 1
```

**Comment by trancexpress** [comment]
I think we'll have to understand why this test fails. I've seen this pattern over multiple days now, looking at sporadically failing JDT core tests:

```
public void testCombineAccessRules5() throws CoreException {
	try {
		IJavaProject project = createJavaProject("P2");
		editFile(
			"/P2/.classpath",
			"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
			"<classpath>\n" +
			"	<classpathentry kind=\"src\" path=\"src\"/>\n" +
			"	<classpathentry kind=\"output\" path=\"bin\"/>\n" +
			"</classpath>\n"
		);
		assertClasspathEquals(
			project.getRawClasspath(),
			"/P2/src[CPE_SOURCE][K_SOURCE][isExported:false]"
		);
	} finally {
		deleteProject("P2");
	}
}
```

```
protected IFile editFile(String path, String content) throws CoreException {
	IFile file = getFile(path);
	file.setContents(content.getBytes(), IResource.FORCE, null);
	return file;
}
```

Here we see the JDT model is outdated when the assertion runs... We'll have to understand what breaks the JDT model cache.

When I run the entire test case, I see this job removing a project info from the JDT model cache:

```
	at org.eclipse.jdt.internal.core.JavaModelManager$TouchJob.<init>(JavaModelManager.java:364)
	at org.eclipse.jdt.internal.core.JavaModelManager$TouchJob.<clinit>(JavaModelManager.java:360)
	at org.eclipse.jdt.internal.core.JavaModelManager.touchProjectsAsync(JavaModelManager.java:3401)
	at org.eclipse.jdt.internal.core.JavaModelManager$EclipsePreferencesListener.preferenceChange(JavaModelManager.java:1759)
	at org.eclipse.core.internal.preferences.EclipsePreferences.lambda$2(EclipsePreferences.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:833)
	at org.eclipse.core.internal.preferences.EclipsePreferences.put(EclipsePreferences.java:845)
	at org.eclipse.jdt.internal.core.JavaModelManager.storePreference(JavaModelManager.java:5308)
	at org.eclipse.jdt.internal.core.JavaModelManager.setOptions(JavaModelManager.java:5360)
	at org.eclipse.jdt.core.JavaCore.setOptions(JavaCore.java:6482)
	at org.eclipse.jdt.core.tests.model.ClasspathTests.testClasspathValidation27_Bug159325_project(ClasspathTests.java:1956)
```

It should be waited on on project creation in the test:

```
"main" #1 [109003] prio=6 os_prio=0 cpu=3102.15ms elapsed=73.09s tid=0x00007fb0c801bd00 nid=109003 in Object.wait()  [0x00007fb0ce1fc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.10/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@21.0.10/Object.java:366)
        at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1158)
        - locked <0x000000071e7be5d0> (a java.util.Collections$SynchronizedSet)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.waitForManualRefresh(AbstractJavaModelTests.java:4099)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.createJavaProject(AbstractJavaModelTests.java:2375)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.createJavaProject(AbstractJavaModelTests.java:2004)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.createJavaProject(AbstractJavaModelTests.java:1969)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.createJavaProject(AbstractJavaModelTests.java:1765)
        at org.eclipse.jdt.core.tests.model.ClasspathTests.testClasspathValidation27_Bug159325_project(ClasspathTests.java:1957)
```

And on tear down:

```
"main" #1 [109003] prio=6 os_prio=0 cpu=4069.63ms elapsed=167.50s tid=0x00007fb0c801bd00 nid=109003 in Object.wait()  [0x00007fb0ce1fc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.10/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@21.0.10/Object.java:366)
        at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1158)
        - locked <0x00000007225b1840> (a java.util.Collections$SynchronizedSet)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.waitForManualRefresh(AbstractJavaModelTests.java:4099)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.tearDown(AbstractJavaModelTests.java:4032)
        at org.eclipse.jdt.core.tests.model.ClasspathTests.tearDown(ClasspathTests.java:101)
```

Due to:

```
		@Override
		public boolean belongsTo(Object family) {
			return ResourcesPlugin.FAMILY_MANUAL_REFRESH == family || JavaModelManager.class == family;
		}
```

I'm also not sure if deleting the project info can cause the problem here... Since then retrieving the classpath would re-create it and it would have the correct contents. So maybe something else.

If it could run in parallel, the touch job could set the classpath to something else:

```
"Worker-1: Synchronizing projects" #65 [113490] prio=5 os_prio=0 cpu=32.58ms elapsed=92.60s tid=0x00007efe51c4d880 nid=113490 at breakpoint [0x00007efd2964e000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo.setClasspath(JavaModelManager.java:1401)
        at org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo.setRawClasspath(JavaModelManager.java:1430)
        - locked <0x000000071d28eb88> (a org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo)
        at org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo.readAndCacheClasspath(JavaModelManager.java:1500)
        - locked <0x000000071d28eb88> (a org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo)
        at org.eclipse.jdt.internal.core.DeltaProcessor.readRawClasspath(DeltaProcessor.java:638)
        at org.eclipse.jdt.internal.core.DeltaProcessor.checkProjectsAndClasspathChanges(DeltaProcessor.java:417)
        at org.eclipse.jdt.internal.core.DeltaProcessor.checkProjectsAndClasspathChanges(DeltaProcessor.java:595)
        at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2104)
        at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:490)
        at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:342)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:331)
        at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:185)
        at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:473)
        at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1619)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:51)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by trancexpress** [comment]
Another parallel job that can set the classpath:

```
"Worker-2: Decoration Calculation" #67 [126744] prio=5 os_prio=0 cpu=30.67ms elapsed=164.35s tid=0x00007f4e14009c60 nid=126744 at breakpoint [0x00007f4e6d309000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo.setResolvedClasspath(JavaModelManager.java:1444)
        at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3345)
        at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2453)
        at org.eclipse.jdt.internal.core.JavaProject.findContainingClasspathEntry(JavaProject.java:2740)
        at org.eclipse.jdt.internal.core.JavaProject.isOnClasspath(JavaProject.java:2724)
        at org.eclipse.jdt.internal.ui.BuildpathIndicatorLabelDecorator.getOverlay(BuildpathIndicatorLabelDecorator.java:49)
        at org.eclipse.jdt.internal.ui.BuildpathIndicatorLabelDecorator.decorate(BuildpathIndicatorLabelDecorator.java:35)
        at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:254)
        at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:359)
        at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:345)
        at org.eclipse.ui.internal.decorators.DecorationScheduler$1.queue(DecorationScheduler.java:410)
        at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:388)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I can get this job to try to write an outdated classpath in parallel, but due to the mechanism using `PerProjectInfo.rawTimeStamp`, the outdated classpath is discarded before setting it.
