### ISSUE TITLE
ModelUtilTests.testElementsWithEclipseCompiler fails since I20241104-1800

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3247]
In https://download.eclipse.org/eclipse/downloads/drops4/I20241104-1800/testresults/html/org.eclipse.jdt.compiler.apt.tests_ep434I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

```
Compilation failed : Round 1: input files: {targets.model.pc.Deprecation,targets.model.pd.outer.OuterClass,targets.model.order.EnumInstances,targets.model.pd.test.Foo,targets.model.pc.Bug547185,targets.model.order.Ordered,targets.model.pd.Marker,targets.model.pc.AnnotatedWithManyTypes,package targets.model.pa,targets.model.pa.ExceptionA,targets.model.pc.AnnoX,targets.model.pc.AnnoY,targets.model.pa.AnnoZ,targets.model.pa.IA,targets.model.pb.IB,targets.model.pc.IAsMemberOf,targets.model.pb.IC,targets.model.pc.Overriding,targets.model.pc.IF,targets.model.pc.Constants,targets.model.pa.A,targets.model.pb.AB,targets.model.pb.D,targets.model.pb.AC,targets.model.enumfields.EnumWithFields,targets.model.pc.F,targets.model.pc.G,targets.model.pc.H,targets.model.pc.AsMemberOf,targets.model.pc.J,targets.model.pb.DChild,targets.model.pc.K,targets.model.pc.AsMemberOfSub,targets.model.pc.Bug261969,targets.model.pd.Outer} annotations: [org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayAnnoChar,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoEnumConst,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoBoolean,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoAnnoChar,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayEnumConst,targets.model.pd.Marker,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoDouble,targets.model.pc.AnnoX,targets.model.pc.AnnoY,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayInt,targets.model.pa.AnnoZ,java.lang.Override,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoInt,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoChar,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayString,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoFloat,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayType,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoShort,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoByte,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoLong,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoType,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoString,java.lang.annotation.Inherited,java.lang.SuppressWarnings,java.lang.Deprecated] last round: false ---------- 1. ERROR in /Users/genie.releng/workspace/AutomatedTests/ep434I-unit-macosx-x86_64-java17/tmp/eclipse-temp/src/targets/model/pa/package-info.java (at line 0) 
/ ******************************************************************************* ^ Internal compiler error: java.lang.Exception: java.lang.NoClassDefFoundError: javax/lang/model/util/Elements$DocCommentKind at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:170) ---------- 1 problem (1 error)

junit.framework.AssertionFailedError: Compilation failed : Round 1:
input files: {targets.model.pc.Deprecation,targets.model.pd.outer.OuterClass,targets.model.order.EnumInstances,targets.model.pd.test.Foo,targets.model.pc.Bug547185,targets.model.order.Ordered,targets.model.pd.Marker,targets.model.pc.AnnotatedWithManyTypes,package targets.model.pa,targets.model.pa.ExceptionA,targets.model.pc.AnnoX,targets.model.pc.AnnoY,targets.model.pa.AnnoZ,targets.model.pa.IA,targets.model.pb.IB,targets.model.pc.IAsMemberOf,targets.model.pb.IC,targets.model.pc.Overriding,targets.model.pc.IF,targets.model.pc.Constants,targets.model.pa.A,targets.model.pb.AB,targets.model.pb.D,targets.model.pb.AC,targets.model.enumfields.EnumWithFields,targets.model.pc.F,targets.model.pc.G,targets.model.pc.H,targets.model.pc.AsMemberOf,targets.model.pc.J,targets.model.pb.DChild,targets.model.pc.K,targets.model.pc.AsMemberOfSub,targets.model.pc.Bug261969,targets.model.pd.Outer}
annotations: [org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayAnnoChar,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoEnumConst,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoBoolean,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoAnnoChar,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayEnumConst,targets.model.pd.Marker,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoDouble,targets.model.pc.AnnoX,targets.model.pc.AnnoY,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayInt,targets.model.pa.AnnoZ,java.lang.Override,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoInt,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoChar,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayString,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoFloat,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoArrayType,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoShort,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoByte,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoLong,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoType,org.eclipse.jdt.compiler.apt.tests.annotations.TypedAnnos.AnnoString,java.lang.annotation.Inherited,java.lang.SuppressWarnings,java.lang.Deprecated]
last round: false
----------
1. ERROR in /Users/genie.releng/workspace/AutomatedTests/ep434I-unit-macosx-x86_64-java17/tmp/eclipse-temp/src/targets/model/pa/package-info.java (at line 0)

/ *******************************************************************************
^
Internal compiler error: java.lang.Exception: java.lang.NoClassDefFoundError: javax/lang/model/util/Elements$DocCommentKind at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:170)
----------
1 problem (1 error)

at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.compiler.apt.tests.BatchTestUtils.compileTree(BatchTestUtils.java:254)
at org.eclipse.jdt.compiler.apt.tests.BatchTestUtils.compileTree(BatchTestUtils.java:146)
at org.eclipse.jdt.compiler.apt.tests.BatchTestUtils.compileTree(BatchTestUtils.java:137)
at org.eclipse.jdt.compiler.apt.tests.ModelUtilTests.internalTest(ModelUtilTests.java:98)
at org.eclipse.jdt.compiler.apt.tests.ModelUtilTests.testElementsWithEclipseCompiler(ModelUtilTests.java:63)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by iloveeclipse** [comment]
@subyssurendran666 : hint: all stack traces / code could be better formatted as **code** by using \``` at the begin and end of the text block. This way one can read the failreas easier.

**Comment by iloveeclipse** [comment]
@jarthana : this is regression from 3a95dca35897fa636174d7a9d3f9427a14770ea6. Could you please check?

**Comment by subyssurendran666** [comment]
> @subyssurendran666 : hint: all stack traces / code could be better formatted as **code** by using ``` at the begin and end of the text block. This way one can read the failreas easier.

Sure. I'll update all the stack traces.

**Comment by iloveeclipse** [comment]
@jarthana : please note: the tests did not fail on Jenkins because since cb2ef5dadf6b20ffefc4d857d56d6ba438756276 we run tests on jenkins with Java 23 runtime. If you run same test with Java 17 or 21 you will see the fail...

**Comment by jarthana** [comment]
Since we don't have DocCommentKind before Java 23, these tests should not be run in those versions. Will add filters.

**Comment by jarthana** [comment]
> Since we don't have DocCommentKind before Java 23, these tests should not be run in those versions. Will add filters.

This wasn't correct. The issue was, there was a reference to the new (JLS 23 method) from an earlier API implementation. I have remove it. There's some code duplication, but I guess we will live with that.
