### ISSUE TITLE
JavaModelTests.testPreProcessingResourceChangedListener04 fails with message: Unexpected event type expected

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3249]
In https://download.eclipse.org/eclipse/downloads/drops4/I20241104-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep434I-unit-linux-x86_64-java17_linux.gtk.x86_64_17.html

Unexpected event type expected:<17> but was:<16>

junit.framework.AssertionFailedError: Unexpected event type expected:<17> but was:<16>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.core.tests.model.JavaModelTests.testPreProcessingResourceChangedListener04(JavaModelTests.java:670)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

**Comment by jukzi** [comment]
in https://download.eclipse.org/eclipse/downloads/drops4/I20250106-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html
it was testPreProcessingResourceChangedListener01 to fail with similar exception:
```
junit.framework.AssertionFailedError: Unexpected event type expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.core.tests.model.JavaModelTests.testPreProcessingResourceChangedListener01(JavaModelTests.java:625)
```

**Comment by jukzi** [comment]
again in
https://download.eclipse.org/eclipse/downloads/drops4/I20250109-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250113-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by jukzi** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/actions/runs/12868975269/job/35878098223

**Comment by subyssurendran666** [comment]
Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250205-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testPreProcessingResourceChangedListener01` Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250224-0600/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testPreProcessingResourceChangedListener04`
Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250305-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testPreProcessingResourceChangedListener01` Failed again in
https://download.eclipse.org/eclipse/downloads/drops4/I20250306-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testPreProcessingResourceChangedListener01` Failed again in 
https://download.eclipse.org/eclipse/downloads/drops4/I20250316-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testPreProcessingResourceChangedListener01` Failed again https://download.eclipse.org/eclipse/downloads/drops4/I20250319-0550/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testCreatePkgHandleInDifferentProject` failed in
https://download.eclipse.org/eclipse/downloads/drops4/I20250412-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-win32-x86_64-java21_win32.win32.x86_64_21.html

**Comment by subyssurendran666** [comment]
`JavaModelTests.testPreProcessingResourceChangedListener01` failed in https://download.eclipse.org/eclipse/downloads/drops4/I20250512-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep436I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by subyssurendran666** [comment]
`**JavaModelTests.testPreProcessingResourceChangedListener01**` failed in https://download.eclipse.org/eclipse/downloads/drops4/I20250920-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep438I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

**Comment by trancexpress** [comment]
Another fail here:

https://download.eclipse.org/eclipse/downloads/drops4/I20260227-1600/testresults/html/org.eclipse.jdt.core.tests.model_ep440I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

```
org.eclipse.jdt.core.tests.model.JavaModelTests	testPreProcessingResourceChangedListener01	Failure	Unexpected event type expected:<1> but was:<0>

junit.framework.AssertionFailedError: Unexpected event type expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.core.tests.model.JavaModelTests.testPreProcessingResourceChangedListener01(JavaModelTests.java:625)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```

Test is:

```
public void testPreProcessingResourceChangedListener01() throws CoreException {
	final int[] eventType = new int[] {0};
	IResourceChangeListener listener = new IResourceChangeListener(){
		public void resourceChanged(IResourceChangeEvent event) {
			eventType[0] |= event.getType();
		}
	};
	try {
		JavaCore.addPreProcessingResourceChangedListener(listener);
		createProject("Test");
		assertEquals("Unexpected event type", IResourceChangeEvent.POST_CHANGE, eventType[0]);
	} finally {
		JavaCore.removePreProcessingResourceChangedListener(listener);
		deleteProject("Test");
	}
}
```

I'm not seeing what can go wrong here... If some other operation would consume the delta, the listener added during the test would be notified. And `DeltaProcessingState.addPreResourceChangedListener(IResourceChangeListener, int)` resp. `DeltaProcessingState.removePreResourceChangedListener(IResourceChangeListener)` are `synchronized`. There shouldn't be any code that accidentally removes the test listener in parallel... If `JavaModelManager.deltaState` is set to something else anywhere, I don't find it.

The log file also shows no errors:

https://download.eclipse.org/eclipse/downloads/drops4/I20260227-1600/testresults/ep440I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

**Comment by trancexpress** [comment]
`testCreatePkgHandleInDifferentProject` failed again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260309-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep440I-unit-win32-x86_64-java21_win32.win32.x86_64_21.html

Opened https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4917 for this, it looks like a different issue than the fail in `testPreProcessingResourceChangedListener01`.

**Comment by trancexpress** [comment]
Failed again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260318-1800/reports.html#tests

https://download.eclipse.org/eclipse/downloads/drops4/I20260318-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep440I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

```
	Unexpected event type expected:<1> but was:<0>

junit.framework.AssertionFailedError: Unexpected event type expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.jdt.core.tests.model.JavaModelTests.testPreProcessingResourceChangedListener01(JavaModelTests.java:646)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```

Workspace log: https://download.eclipse.org/eclipse/downloads/drops4/I20260318-1800/testresults/ep440I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

```
Running test testPreProcessingResourceChangedListener01...
22:46:22.453 SETUP JavaModelTests.testPreProcessingResourceChangedListener01
22:46:22.457 Logging resource delta
	kind: 4, resource: R/
	kind: 1, resource: P/Test
	kind: 1, resource: L/Test/.project
	kind: 1, resource: F/Test/.settings
	kind: 1, resource: L/Test/.settings/org.eclipse.core.resources.prefs

| Worker-2: Periodic workspace save. | 2026-03-18 22:46:22.457 | org.eclipse.jdt.core | /debug | org.eclipse.core.internal.resources.SaveManager | executeLifecycle | 466 | Saved 5,810 bytes in variablesAndContainers.dat in 0ms |
22:46:22.460 Logging resource delta
	kind: 4, resource: R/
	kind: 2, resource: P/Test
	kind: 2, resource: L/Test/.project
	kind: 2, resource: F/Test/.settings
	kind: 2, resource: L/Test/.settings/org.eclipse.core.resources.prefs

| Worker-3: Periodic workspace save. | 2026-03-18 22:46:22.461 | org.eclipse.jdt.core | /debug | org.eclipse.core.internal.resources.SaveManager | executeLifecycle | 466 | Saved 5,810 bytes in variablesAndContainers.dat in 0ms |
22:46:22.461 TDOWN JavaModelTests.testPreProcessingResourceChangedListener01
```

When running the test from Eclipse:

```
09:56:47.344 SETUP JavaModelTests.testPreProcessingResourceChangedListener01
09:56:47.348 Logging resource delta
	kind: 4, resource: R/
	kind: 1, resource: P/Test
	kind: 1, resource: L/Test/.project
	kind: 1, resource: F/Test/.settings
	kind: 1, resource: L/Test/.settings/org.eclipse.core.resources.prefs

| Worker-3: Periodic workspace save. | 2026-03-19 09:56:47.349 | org.eclipse.jdt.core | /debug | org.eclipse.core.internal.resources.SaveManager | executeLifecycle | 466 | Saved 313 bytes in variablesAndContainers.dat in 0ms |
09:56:47.354 Logging resource delta
	kind: 4, resource: R/
	kind: 2, resource: P/Test
	kind: 2, resource: L/Test/.project
	kind: 2, resource: F/Test/.settings
	kind: 2, resource: L/Test/.settings/org.eclipse.core.resources.prefs

09:56:47.354 TDOWN JavaModelTests.testPreProcessingResourceChangedListener01
```

Only difference in the logging is the periodic workspace save. Potentially we still don't log enough.

The test does wait on the snapshot job, after project creation:

```
"main" #1 [37135] prio=6 os_prio=0 cpu=2762.17ms elapsed=101.58s tid=0x00007f380001beb0 nid=37135 in Object.wait()  [0x00007f3806ffb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.10/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@21.0.10/Object.java:366)
        at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1158)
        - locked <0x000000071e4dba68> (a java.util.Collections$SynchronizedSet)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.waitForSnapShot(AbstractJavaModelTests.java:4160)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.waitForManualRefresh(AbstractJavaModelTests.java:4119)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.createProject(AbstractJavaModelTests.java:2440)
        at org.eclipse.jdt.core.tests.model.JavaModelTests.testPreProcessingResourceChangedListener01(JavaModelTests.java:645)
```

Likely the 2nd snapshot job is due to the test project delete.
