### ISSUE TITLE
Many NPE when hover or refactor inside "instanceof" block

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#3263]
```
public class Test {
	{
		Map<String,Collection<Object>> binaryLocationsJars=new HashMap<>();
		if (null instanceof Object jar) {
				binaryLocationsJars.compute("", (pp,me // hover "me", or refactor "me"
						) ->{
					return me;
				});
		}
	}
}

```

for example

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.signableName()" because "binding.type" is null
	at org.eclipse.jdt.internal.core.SelectionRequestor.acceptLocalVariable(SelectionRequestor.java:418)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.selectFrom(SelectionEngine.java:1351)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1041)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:403)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:393)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugHover.resolveElement(JavaDebugHover.java:519)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugHover.getHoverInfo2(JavaDebugHover.java:302)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)

```

**Comment by srikanth-sankaran** [comment]
Thanks @jukzi - I'll take a look - Since this is tagged as a regression, do you know the last version where this worked ?

**Comment by jukzi** [comment]
Sorry, don't know. Don't even proofed it ever worked. "regression" is only a guess in this case because i can not remember to ever had a problem there.

**Comment by jukzi** [comment]
Still an issue! Refactoring (ALT+SHIFT+R) "me" became even worse, now logging tons of Exceptions:

![image](https://github.com/user-attachments/assets/f9b8f313-7015-4709-bb07-03cd04fd1cb0)

**Comment by srikanth-sankaran** [comment]
The recovered parse tree is:

```
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
public class Test {
  {
    Map<String, Collection<Object>> binaryLocationsJars;
    {
      <SelectionOnArgumentName:me>;
    }
  }
  public Test() {
  }
}
```

We don't even recognize `me` to be a lambda parameter. So the elided type of the local is unresolved and null resulting in NPE.

**Comment by srikanth-sankaran** [comment]
> Sorry, don't know. Don't even proofed it ever worked. "regression" is only a guess in this case because i can not remember to ever had a problem there.

A random pick of 4.20 shows we don't NPE there, so it is a regression although I don't know exactly since when

**Comment by srikanth-sankaran** [comment]
This is likely a bit involved, I will revisit when I have time ...

**Comment by phax** [comment]
Still an issue in 2026-03:

```
eclipse.buildId=4.39.0.20260305-0817
java.version=21.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=de_AT
Framework arguments:  -product org.eclipse.epp.package.committers.product -keyring /Users/philip/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.committers.product -keyring /Users/philip/.eclipse_keyring

org.eclipse.jdt.ui
Error
Thu Apr 23 12:46:36 CEST 2026
NullPointerException computing hyperlink in SchematronPreparer.java at offset 4215

java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.signableName()" because "binding.type" is null
	at org.eclipse.jdt.internal.core.SelectionRequestor.acceptLocalVariable(SelectionRequestor.java:422)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.selectFrom(SelectionEngine.java:1353)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1043)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:171)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:476)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:466)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinksCached(JavaElementHyperlinkDetector.java:127)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.lambda$0(JavaElementHyperlinkDetector.java:84)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5709)
	at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5698)
	at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6211)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinks(JavaElementHyperlinkDetector.java:84)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:83)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:294)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:264)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:474)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:254)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4671)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1657)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1680)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1665)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1394)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4438)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4014)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1051)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:684)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:583)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:185)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:219)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:615)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:563)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1415)
	Suppressed: java.lang.Throwable: Source line 86 :
-----
      {
        LOGGER.info ("Converting Schematron '" + source.toString () + "' to XSLT '" + target.toString () + "'");

        SchematronDebug.setDebugLog (true);
        final Document aXsltDoc = SchematronProviderXSLTFromSCH.createSchematronXSLT (new FileSystemResource (source),
                                                                                  new TransformerCustomizerSCH ());
        
        // Add all namespaces from XSLT document root
        final String sNSPrefix = XMLConstants.XMLNS_ATTRIBUTE + ":";
        final ICommonsMap <String, String> aMapFromXml = new CommonsLinkedHashMap <> ();
        XMLHelper.forAllAttributes (aXsltDoc.getDocumentElement (), (sAttrNam|e, sAttrValue) -> {
-----
		at org.eclipse.jdt.internal.ui.util.SelectionUtil.logException(SelectionUtil.java:157)
		at org.eclipse.jdt.internal.ui.javaeditor.JavaElementHyperlinkDetector.detectHyperlinksCached(JavaElementHyperlinkDetector.java:146)
		... 37 more

```
