### ISSUE TITLE
ClassCastException: org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding-> org.eclipse.jdt.internal.compiler.lookup.LocalTypeBinding

### ISSUE THREAD

**Issue by mebigfatguy** [eclipse-jdt/eclipse.jdt.core#329]
Linux Mint 20.1 (Ulyssa)
5.4.0-120-generic

Eclipse Version
Version: 2022-06 (4.24.0)
Build id: 20220609-1112

Get A compile error on one file pointing at the package xxx; line 1

Internal compiler error: java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding cannot be 
 cast to class org.eclipse.jdt.internal.compiler.lookup.LocalTypeBinding (org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding 
 and org.eclipse.jdt.internal.compiler.lookup.LocalTypeBinding are in unnamed module of loader org.eclipse.osgi.internal.loader.
 EquinoxClassLoader @53fb489d) at org.eclipse.jdt.internal.compiler.ast.LambdaExpression$LocalTypeSubstitutor.substitute
 (LambdaExpression.java:1490)

**Comment by mebigfatguy** [comment]
[FileEventActor.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9383371/FileEventActor.txt)

**Comment by iloveeclipse** [comment]
Could you please
1) attach full stack trace
2) try with 4.25 M3 (just released,  see https://download.eclipse.org/eclipse/downloads/drops4/S-4.25M3-202208171800/)
3) and if that error still appears,  attach the stack from 4.25

**Comment by mebigfatguy** [comment]
Java Model Exception: java.lang.ClassCastException
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:326)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:348)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:193)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1319)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)

**Comment by mebigfatguy** [comment]
i installed the development build, and the exception appears to be the same

**Comment by mebigfatguy** [comment]
I've widdled down the problem to a small  example, attached
[eclipse329.tar.gz](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9387979/eclipse329.tar.gz)

**Comment by stephan-herrmann** [comment]
> I've widdled down the problem to a small example, attached
> [eclipse329.tar.gz](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9387979/eclipse329.tar.gz)

Thanks, I can reproduce.

There are a few classes in kamon-core that quite confuse the compiler:
* `kamon.metric.Metric` - a toplevel interface
* `kamon.metric.Metric$` - a toplevel class
* `kamon.metric.Metric$Settings` - an inner interface of the `kamon.metric.Metric`
* `kamon.metric.Metric$Settings$` - an inner class of the `kamon.metric.Metric`
* `kamon.metric.Metric$Settings$ForDistributionInstrument` - inner class of `kamon.metric.Metric$Settings$`
* `kamon.metric.Metric$Settings$ForDistributionInstrument$` - inner class of `kamon.metric.Metric$Settings$`

According to Java rules, `kamon.metric.Metric$Settings$ForDistributionInstrument` should be inner class of `kamon.metric.Metric$Settings` (no trailing `$`), because the `$` is needed as the separator of name segments. Apparently the scala compiler, which produced these .class files, didn't pay attention to such rules. Given that the `InnerClasses` is the only manifestation of inner classes at the bytecode level, it is possible for a non-Java compiler to produce such .class files. 

What's more: `kamon.metric.Metric$Settings$` does not have a source name as seen in this bytecode attribute:
```
InnerClasses:
  public static #8= #2 of #7;             // =class kamon/metric/Metric$Settings$ of class kamon/metric/Metric
```
The source name would be the value of `#8`, i.e., the part before the `=`. I.e., we regard this type as an anonymous class.

In the Java world this means the type is anonymous, and hence no external reference to this type is possible. The compiler only has provisions for the source variant of anonymous classes, not for their binary counter part, as they are never relevant for compilation.

From this, `type.isLocalType()` is a sufficient guard for a cast to `LocalTypeBinding` - for legal .class files, i.e.

Still we find `Metric$Settings$` just by looking at public API: 
* `public static interface kamon.metric.Metric$Timer implements Metric<kamon.metric.Timer,kamon.metric.Metric$Settings$ForDistributionInstrument>`
* type argument `kamon.metric.Metric$Settings$ForDistributionInstrument` is inner class of `kamon.metric.Metric$Settings$`
* booom

To a java compiler this tells: here is a public interface that depends on an anonymous type. This is nonsense.


The scala compiler will have to make up its mind whether or not `kamon.metric.Metric$Settings$` is anonymous.

In JDT we could further protect this one cast, but we have a total of 64 callers of `isLocalType()`. Each would need to be thoroughly checked, which IMHO is way too much effort just to support non-Java .class files.

**Comment by mebigfatguy** [comment]
ok, i'll ask the kamon  folks, but point of note, the  normal oracle java  compiler  has no problems with it.

**Comment by stephan-herrmann** [comment]
> ok, i'll ask the kamon folks, but point of note, the normal oracle java compiler has no problems with it.

That could be pure coincidence, or perhaps the scala compiler was tested only to harmonize with javac. But if you are outside a specification just testing against one of two implementations is _weak_.

Looking at it from the opposite site: could you define rules how a java compiler should interpret the class files I mentioned? 
How could we possibly distinguish a "class without a name" from an anonymous class?

I only see one solution we could possibly apply on JDT side: given that .class files are only discovered by the compiler via external references, and given that anonymous classes cannot be referenced, we could override `isLocalType()` in `BinaryTypeBinding` as to always return false, no matter what garbage we find in any `InnerClasses` attribute. Such implementation would be wrong, but perhaps it might be possibly to argue that this is harmless nevertheless. We'd have to be really sure that such change will not have any effect on legal Java programs.

Can you help me argue why .class files of anonymous classes **can never be relevant for compilation, ever**?
