### ISSUE TITLE
Some tests fail silently due to now unsupported Java Version <8

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#3297]
for example
org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption2()

```
org.eclipse.core.runtime.CoreException: release 6 is not found in the system
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:101)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:175)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.computeClasspathLocations(NameEnvironment.java:360)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.<init>(NameEnvironment.java:90)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:692)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:213)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:668)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:604)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:642)
	at org.eclipse.core.internal.resources.Project.build(Project.java:154)
	at org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption2(ModuleBuilderTests.java:8356)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20241111-1800/testresults/ep434I-unit-linux-x86_64-java23_linux.gtk.x86_64_23/org.eclipse.jdt.core.tests.model.AllJavaModelTests.txt

**Comment by iloveeclipse** [comment]
This test `org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption2()` does not fail, it succeeds. The error reported is **expected** one, as the test checks whether passing wrong release version produces error marker, and exactly that is what happening after exception is thrown.
