### ISSUE TITLE
"Missing System Library" exception in ASTParser

### ISSUE THREAD

**Issue by ptziegler** [eclipse-jdt/eclipse.jdt.core#3298]
This seems to be a regression introduced by https://github.com/eclipse-jdt/eclipse.jdt.core/commit/74d062b38d3003638127127cc5358dd9f79df0f4

To reproduce: Make sure compiler compliance is set to > 1.8 and open a Java file from a project without Java nature.

![image](https://github.com/user-attachments/assets/5c8a6187-1d02-4534-832a-175b0b7bf02d)

Stack Trace:
```
java.lang.IllegalStateException: Missing system library
	at org.eclipse.jdt.core.dom.ASTParser.checkForSystemLibrary(ASTParser.java:311)
	at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:272)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1299)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$1(ASTParser.java:1178)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5694)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1178)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:918)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:189)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:167)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.lambda$0(SelectionListenerWithASTManager.java:149)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5694)
	at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5683)
	at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6150)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:149)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: Java Model Exception: Error in Java Model (code 969): TestProject does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:556)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:234)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:569)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:292)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:278)
	at org.eclipse.jdt.internal.core.JavaProject.getJavaProjectElementInfo(JavaProject.java:2040)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2775)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2769)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2787)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2779)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1681)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1582)
	at org.eclipse.jdt.core.dom.ASTParser.checkForSystemLibrary(ASTParser.java:304)
	... 19 more
```

**Comment by ptziegler** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3047 for context.

**Comment by ptziegler** [comment]
This check should probably only be done for proper Java projects?

**Comment by jukzi** [comment]
> This seems to be a regression introduced by [74d062b](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/74d062b38d3003638127127cc5358dd9f79df0f4)

@stephan-herrmann  can you take a look?

**Comment by jukzi** [comment]
This issue can still be reproduced. 

```
java.lang.IllegalStateException: Missing system library
	at org.eclipse.jdt.core.dom.ASTParser.checkForSystemLibrary(ASTParser.java:311)
	at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:272)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1299)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$1(ASTParser.java:1178)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5708)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1178)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:918)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:189)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:167)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.lambda$0(SelectionListenerWithASTManager.java:149)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5708)
	at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5697)
	at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6150)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:149)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: Java Model Exception: Error in Java Model (code 969): plain does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:556)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:234)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:569)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:292)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:278)
	at org.eclipse.jdt.internal.core.JavaProject.getJavaProjectElementInfo(JavaProject.java:2050)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2785)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2779)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2797)
	at org.eclipse.jdt.internal.core.JavaProject.newNameLookup(JavaProject.java:2789)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1691)
	at org.eclipse.jdt.internal.core.JavaProject.findType(JavaProject.java:1592)
	at org.eclipse.jdt.core.dom.ASTParser.checkForSystemLibrary(ASTParser.java:304)
	... 19 more
eclipse.buildId=4.35.0.I20250108-0430
java.version=22.0.2

```

> This check should probably only be done for proper Java projects?

@ptziegler can you propose such PR please?

**Comment by ptziegler** [comment]
There is a lot of stuff on my todo list right now, but think an initial draft is done fairly quickly. I'll try to come up with something during the weekend.

**Comment by ptziegler** [comment]
> This check should probably only be done for proper Java projects?


After a quick glance, I don't think adding an additional check in the AST parser is not the correct solution. Instead, I believe that the project being converted to a JavaProject is the real problem.

From the documentation:

> A Java project represents a view of a project resource in terms of Java elements such as package fragments, types, methods and fields. A project may contain several package roots, which contain package fragments. A package root corresponds to an underlying folder or JAR.

> Each Java project has a classpath, defining which folders contain source code and where required libraries are located. Each Java project also has an output location, defining where the builder writes .class files. A project that references packages in another project can access the packages by including the required project in a classpath entry. The Java model will present the source elements in the required project; when building, the compiler will use the corresponding generated class files from the required project's output location(s)). The classpath format is a sequence of classpath entries describing the location and contents of package fragment roots.

This is not the case, unless a project has the Java nature. And if the `JavaProject` field were to be null, this check would return early, without throwing an exception.

**Comment by stephan-herrmann** [comment]
> Instead, I believe that the project being converted to a JavaProject is the real problem.

Which code creates the `JavaProject` in your scenario?

**Comment by ptziegler** [comment]
> > Instead, I believe that the project being converted to a JavaProject is the real problem.
> 
> Which code creates the `JavaProject` in your scenario?

I believe the JavaProject is created by the CompilationUnitDocumentProvider when the Java editor is openend.. More specifically, by the JavaModelManager:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/2c5a057fc204307ea4a3db2f633b757ee7a124c4/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java#L964-L981

![image](https://github.com/user-attachments/assets/8ffafb2c-1566-41cc-86a2-627cdffc52eb)

However, I get the impression that there is no way around this, as the ICompilationUnit is created by an IPackageFragment, which in returns requires the JavaProject. 😦

**Comment by ptziegler** [comment]
I looked deeper into this issue and I believe the underlying problem is that the Java editor is always opened with the `RESOLVE_BINDING` bit set.

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/7ddead3f30ea50adc762d55ec6a32568427e692c/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ASTParser.java#L270-L272

If I add a check that clears this flag if the Java project doesn't have the Java nature, this exception isn't thrown. Meaning I now have two options: I can either fix it in the ASTParser class, where it would also handle all other combinations I haven't thought of, or in the UI classes for this specific use case.

Given that I'm not overly familiar with either classes, what would be the preferable approach? I'm personally leaning towards the latter option, because I think it's wrong to do a type binding when there are no types to bind with. Depending on that, I would push a PR either to this project or to JDT UI.

**Comment by ptziegler** [comment]
I've created https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3560 as a fix, after I noticed that this actively breaks our application, because we parse source code that isn't in a Java project. I therefore believe it's not sufficient to only fix this for the Java editor, as there are many more instances where this problem can and will occur.

**Comment by akurtakov** [comment]
@ptziegler You might consider adding such a test using ASTParser in non Java project to make sure it doesn't regress again in the future.

**Comment by ptziegler** [comment]
As a side note: The `IJavaProject` object is created quite frequently, even if the project is in-fact not a Java project. As far as I can tell, the deciding factor is only whether it has a Java nature or not.

**Comment by akurtakov** [comment]
What I've been thinking of a test without IJavaProject javaProject = JavaCore.create(project); and parser.setProject(javaProject); lines to ensure that ASTParser works in "plain" projects.

**Comment by ptziegler** [comment]
> What I've been thinking of a test without IJavaProject javaProject = JavaCore.create(project); and parser.setProject(javaProject); lines to ensure that ASTParser works in "plain" projects.

Ah, thanks for the clarification I've updated the test case to avoid using the `IJavaProject`, but I generally won't get around using some of the JDT API. In this case the `ICompilationUnit`.
