### ISSUE TITLE
Array out of bounds exception while parsing

### ISSUE THREAD

**Issue by jpAtOt** [eclipse-jdt/eclipse.jdt.core#3359]
I get this error when I try to parse the file  `src/main/java/org/owasp/webgoat/webwolf/FileServer.java` from Webgoat (https://github.com/WebGoat/WebGoat/releases/tag/v2023.8).  The parser throws an array out of bounds exception.

Stack trace:

````
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
    at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.sIsMoreSpecific(ReferenceExpression.java:1290) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.lookup.PolyTypeBinding.(PolyTypeBinding.java:84) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.lookup.Scope.mostSpecificMethodBinding(Scope.java:4609) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.lookup.Scope.findDefaultAbstractMethod(Scope.java:1295) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod0(Scope.java:1924) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod(Scope.java:1654) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.lookup.Scope.getMethod(Scope.java:3044) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.MessageSend.findMethodBinding(MessageSend.java:1014) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:835) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1503) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1628) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1240) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:712) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1245) ~[org.eclipse.jdt.core-3.28.0.jar:?]
    at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868) ~[org.eclipse.jdt.core-3.28.0.jar:?]
```

Is there some workaround on this?

**Comment by srikanth-sankaran** [comment]
Giving us an extracted test case that shows the problem will help investigate the problem. If I download a zip from there and import into my plain SDK installation workspace, I get tons of errors.

**Comment by jpAtOt** [comment]
> Giving us an extracted test case that shows the problem will help investigate the problem. If I download a zip from there and import into my plain SDK installation workspace, I get tons of errors.

My apologies! Here's the test case.

```java
import static java.util.Comparator.comparing;
import static org.springframework.http.MediaType.ALL_VALUE;

import jakarta.servlet.http.HttpServletRequest;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.attribute.FileTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.TimeZone;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.io.FileUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.view.RedirectView;

/** Controller for uploading a file */
@Controller
@Slf4j
public class FileServer {

  private static final DateTimeFormatter dateTimeFormatter =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

  @Value("${webwolf.fileserver.location}")
  private String fileLocation;

  @Value("${server.address}")
  private String server;

  @Value("${server.servlet.context-path}")
  private String contextPath;

  @Value("${server.port}")
  private int port;

  @GetMapping(value = "/files")
  public ModelAndView getFiles(
      HttpServletRequest request, Authentication authentication, TimeZone timezone) {
    String username = (null != authentication) ? authentication.getName() : "anonymous";
    File destinationDir = new File(fileLocation, username);

    ModelAndView modelAndView = new ModelAndView();
    record UploadedFile(String name, String size, String link, String creationTime) {}

    var uploadedFiles = new ArrayList<UploadedFile>();
    File[] files = destinationDir.listFiles(File::isFile);
    return modelAndView;
  }
}
```
