### ISSUE TITLE
[23] Random failing ASTRewritingModifying*Tests getStartPosition() because "range" is null

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#3385]
https://download.eclipse.org/eclipse/downloads/drops4/I20241203-0240/testresults/html/org.eclipse.jdt.core.tests.model_ep435I-unit-linux-x86_64-java23_linux.gtk.x86_64_23.html

```
Cannot invoke "org.eclipse.jdt.core.dom.rewrite.TargetSourceRangeComputer$SourceRange.getStartPosition()" because "range" is null

java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.dom.rewrite.TargetSourceRangeComputer$SourceRange.getStartPosition()" because "range" is null
at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.getExtendedEnd(ASTRewriteAnalyzer.java:264)
at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:420)
at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:457)
at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:451)
at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:464)
at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1830)
at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:249)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
at org.eclipse.jdt.core.dom.InternalASTRewrite.rewriteAST(InternalASTRewrite.java:100)
at org.eclipse.jdt.core.dom.AST.rewrite(AST.java:3897)
at org.eclipse.jdt.core.dom.CompilationUnit.rewrite(CompilationUnit.java:985)
at org.eclipse.jdt.core.tests.rewrite.modifying.ASTRewritingModifyingTest.evaluateRewrite(ASTRewritingModifyingTest.java:151)
at org.eclipse.jdt.core.tests.rewrite.modifying.ASTRewritingModifyingTest.evaluateRewrite(ASTRewritingModifyingTest.java:142)
at org.eclipse.jdt.core.tests.rewrite.modifying.ASTRewritingModifyingRemoveTest.test0004(ASTRewritingModifyingRemoveTest.java:156)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.runTest(SuiteOfTestCases.java:114)
at junit.framework.TestSuite.run(TestSuite.java:236)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.superRun(SuiteOfTestCases.java:97)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite$1.protect(SuiteOfTestCases.java:85)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at org.eclipse.jdt.core.tests.model.SuiteOfTestCases$Suite.run(SuiteOfTestCases.java:94)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by iloveeclipse** [comment]
Can't reproduce locally on Linux/Java 23.

**Comment by iloveeclipse** [comment]
The problem seem to be sporadic...

**Comment by jukzi** [comment]
Have not seen this test fail recently and can not reproduce locally (win) If it happens again reopen as random fail.

**Comment by jukzi** [comment]
Probably some bug in jdk-23+37 as the source looks like range can't be null at that position
```
[echoproperties] java.vendor.version=Temurin-23+37-202410121216
[echoproperties] java.version=23.0.1-beta
[echoproperties] java.version.date=2024-10-15
```

**Comment by jukzi** [comment]
A current version would be 23.0.2+7 @akurtakov can we upgrade jdk, please?

**Comment by akurtakov** [comment]
One has to open helpdesk issue like https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5179 for that . These are standard tools not managed by us.

**Comment by jukzi** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5603

**Comment by jukzi** [comment]
Issue still pops up with java.version=23.0.2 :-(

**Comment by jukzi** [comment]
> `-XX:CompileCommand=exclude,org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer::getExtendedRange`

May be a workaround, but i am more interested in a fix :-) @stephan-herrmann did you report the JIT bug? Any JDK Bug related?

**Comment by snjeza** [comment]
> @stephan-herrmann did you report the JIT bug?

Right.

> Any JDK Bug related?

- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5179
- https://bugs.openjdk.org/browse/JDK-8341872

**Comment by jukzi** [comment]
@snjeza those seem not to be related to the impossible NPE

**Comment by jukzi** [comment]
debugged: the "range" at that point should always be the  `new SourceRange(...)` from 
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/875f697721d804a7f0607afcec2eee152b6d4520/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/InternalASTRewrite.java#L90

**Comment by jukzi** [comment]
reported https://bugs.openjdk.org/browse/JDK-8349660

**Comment by jukzi** [comment]
The Java Team from oracle asks if we can run the build with : `-XX:-ReduceAllocationMerges` to find out if that helps to avoid the error. 
@rgrunber or @snjeza can you please try that instead of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3385#issuecomment-2631217214

**Comment by rgrunber** [comment]
Having run with this option for a little while, I don't think I've seen the failure appear in any of the builds with `-XX:-ReduceAllocationMerges` (`-XX:+UnlockDiagnosticVMOptions` was also needed). In those without it, I've seen the error in about 4 out of 14 builds. I'd say the option definitely helps.

**Comment by stephan-herrmann** [comment]
Not seeing any recent activity here, let's assume this has been worked around effectively by https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2954

According to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2142#issuecomment-2822504053 the workaround has to stay as along as Eclipse promises to run on JDK < 24.0.2+1-18
