### ISSUE TITLE
6 new compiler test errors on Java 17 builds since I20241203-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#3393]
https://download.eclipse.org/eclipse/downloads/drops4/I20241203-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep435I-unit-linux-x86_64-java17_linux.gtk.x86_64_17.html

```
testGH3278_missingAnnotations - 1.8	Failure	Invalid problem log . ----------- Expected ------------ ------------ but was ------------ ----------\n 1. ERROR in annotated\TestNotOwning.java (at line 23)\n for (Closeable closeable : toClose.reversed()) {\n ^^^^^^^^\n The method reversed() is undefined for the type List<Closeable>\n ----------\n ---------------------- ---------- expected:<[]> but was:<[----------\n 1. ERROR in annotated\TestNotOwning.java (at line 23)\n for (Closeable closeable : toClose.reversed()) {\n ^^^^^^^^\n The method reversed() is undefined for the type List<Closeable>\n ----------\n ]>

junit.framework.ComparisonFailure: Invalid problem log .
----------- Expected ------------

------------ but was ------------
----------\n
1. ERROR in annotated\TestNotOwning.java (at line 23)\n
for (Closeable closeable : toClose.reversed()) {\n
^^^^^^^^\n
The method reversed() is undefined for the type List<Closeable>\n
----------\n

---------------------- ----------
expected:<[]> but was:<[----------\n
1. ERROR in annotated\TestNotOwning.java (at line 23)\n
for (Closeable closeable : toClose.reversed()) {\n
^^^^^^^^\n
The method reversed() is undefined for the type List<Closeable>\n
----------\n
]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.checkCompilerLog(AbstractRegressionTest.java:1599)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3587)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3290)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runNegativeTest(AbstractRegressionTest.java:3052)
at 
org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakTests.runLeakTest(ResourceLeakTests.java:102)
at org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests.runLeakTestWithAnnotations(ResourceLeakAnnotatedTests.java:113)
at org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests.runLeakTestWithAnnotations(ResourceLeakAnnotatedTests.java:101)
at org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests.testGH3278_missingAnnotations(ResourceLeakAnnotatedTests.java:1767)
at
```

**Comment by iloveeclipse** [comment]
Probably related to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3374
@stephan-herrmann : could you please check?

**Comment by stephan-herrmann** [comment]
Reproduced, `List.reversed()` is `@since 21`. Luckily it's actually irrelevant for the test.

**Comment by jukzi** [comment]
still fails on windows with `character to be escaped is missing`
https://download.eclipse.org/eclipse/downloads/drops4/I20241207-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep435I-unit-win32-x86_64-java17_win32.win32.x86_64_17.html
@stephan-herrmann please take a look
