### ISSUE TITLE
[mac] AnnotationProcessorTests fails since I20241211-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#3442]
On both mac builds:
https://download.eclipse.org/eclipse/downloads/drops4/I20241211-1800/testresults/html/org.eclipse.jdt.compiler.apt.tests_ep435I-unit-macosx-aarch64-java17_macosx.cocoa.aarch64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20241211-1800/testresults/html/org.eclipse.jdt.compiler.apt.tests_ep435I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

```
junit.framework.AssertionFailedError: expected:<true> but was:<false>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:174)
at junit.framework.Assert.assertEquals(Assert.java:181)
at junit.framework.TestCase.assertEquals(TestCase.java:324)
at org.eclipse.jdt.compiler.apt.tests.AnnotationProcessorTests.testBug456986(AnnotationProcessorTests.java:97)

```

```
junit.framework.AssertionFailedError: Compilation failed : Recursive update

at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.compiler.apt.tests.BatchTestUtils.compileTree(BatchTestUtils.java:254)
at org.eclipse.jdt.compiler.apt.tests.BatchTestUtils.compileTree(BatchTestUtils.java:142)
at org.eclipse.jdt.compiler.apt.tests.AnnotationProcessorTests.testBug471995(AnnotationProcessorTests.java:177)

```

**Comment by jukzi** [comment]
reproducible fails on mac i-builds
