### ISSUE TITLE
TextBlockTest-23 fails CI since 2024-12-17

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#3469]
These two tests failed:
```
org.eclipse.jdt.core.tests.compiler.regression.TextBlockTest.test016b -23
org.eclipse.jdt.core.tests.compiler.regression.TextBlockTest.test023 -23
```
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3466/checks?check_run_id=34522421368

for example:
```
junit.framework.ComparisonFailure: 
Unexpected output running resulting class file for X.java:
--[START]--
---[END]---
.
----------- Expected ------------
<html>\n
    <body>\n
      <p>Hello, world</p>\n
    </body>\n
  </html>
------------ but was ------------

---------------------- ----------
 expected:<[<html>\n
    <body>\n
      <p>Hello, world</p>\n
    </body>\n
  </html>]> but was:<[]>
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:240)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3640)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3290)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:2083)
	at org.eclipse.jdt.core.tests.compiler.regression.TextBlockTest.runConformTest(TextBlockTest.java:44)
	at org.eclipse.jdt.core.tests.compiler.regression.TextBlockTest.test016b(TextBlockTest.java:1635)
```

**Comment by jukzi** [comment]
rebuild CI solved the failure -> random fail
