### ISSUE TITLE
Problem opening an editor

### ISSUE THREAD

**Issue by adidiot** [eclipse-jdt/eclipse.jdt.core#35]
Hello,
In that source file :
```
public class Test {
	
	private static final Map<String, Map<String, RErrorCode>> LOC_2_ERROR_CODES_MAP = new HashedMap<>();

	public static LabelProvider LABEL_PROVIDER = new LabelProvider() {
		public String getText(Object element) {
			return element instanceof RErrorCode ec ? ec.code() + " " + ec.text() : "?";
		};
	};
}
```
it causes errors when eg. I select the Test word with F3. If I put the static declaration of  LABEL_PROVIDER  in Comment
there is no error anymore.
See the error log in Eclipse
```
ava.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:230)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$26(ProgressManager.java:821)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.progress.ProgressManager.busyCursorWhile(ProgressManager.java:854)
	at org.eclipse.ui.internal.progress.ProgressManager.busyCursorWhile(ProgressManager.java:830)
	at org.eclipse.jdt.internal.ui.actions.SelectionConverter.performForkedCodeResolve(SelectionConverter.java:261)
	at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolveForked(SelectionConverter.java:173)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:164)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:278)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:252)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1937)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1519)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1546)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1568)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:928)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3993)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:921)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2414)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6834)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6210)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1565)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4578)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassCastException
Root exception:
java.lang.ClassCastException
```

Thanks for supporting
Best Regards,
Alexandre Didiot

**Comment by iloveeclipse** [comment]
@adidiot : could you please attach the stack from the root cause:
```
Caused by: java.lang.ClassCastException
Root exception:
java.lang.ClassCastException
```

**Comment by jukzi** [comment]
can reproduce:
![image](https://user-images.githubusercontent.com/51790620/164682299-13d0cf83-52a1-4794-801e-a0b4c565341e.png)

**Comment by jukzi** [comment]
Root exception:
java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.ast.LocalDeclaration cannot be cast to class org.eclipse.jdt.internal.compiler.ast.MethodDeclaration (org.eclipse.jdt.internal.compiler.ast.LocalDeclaration and org.eclipse.jdt.internal.compiler.ast.MethodDeclaration are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6ddc817f)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeMethodDeclaration(Parser.java:5255)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.consumeMethodDeclaration(AssistParser.java:747)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7153)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13038)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13293)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.parse(SelectionParser.java:1666)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13250)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11636)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.dietParse(SelectionParser.java:1490)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:994)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
	at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by jukzi** [comment]
minimal compiling example:
```
public class Test {
	public static Object X = new Object() {
		public String getText(Object element) {
			return element instanceof String m ? null:null;
		}
	};
}
```

needs [17]

**Comment by stephan-herrmann** [comment]
> minimal compiling example: ...

outch, looks like the selection parser completely misunderstands that snippet (whereas regular parsing succeeds).

You might want to turn on parser tracing via `org.eclipse.jdt.internal.compiler.parser.Parser#DEBUG` and/or `...DEBUG_AUTOMATON`, to find out what the heck caused the creation of a `LocalDeclaration`.

Perhaps @gayanper can help based on his experience with the CompletionParser.

**Comment by gayanper** [comment]
@jukzi and @adidiot can you reproduce this with latest ibuild ?

**Comment by jukzi** [comment]
i can't reproduce the same error with that version. however the same minimal example now has another bug:
![image](https://user-images.githubusercontent.com/51790620/187076098-bcf332cd-1dce-4b9b-bfd1-e1314223271e.png)

It keeps warning about "The method getText(Object) from the type new Object(){} is never used locally" and strg+1 keeps adding "unused" to @SuppressWarnings. why does it even warn that a public(!) method is not used?

**Comment by jukzi** [comment]
> now has another bug:

but i can not reproduce that behavior a 2nd time after deleting the class and adding it again.

**Comment by stephan-herrmann** [comment]
> however the same minimal example now has another bug:

which same example? Further up I see code with an anonymous class instantiation and the same is indicated by "the type new Object(){}", but the screenshot doesn't show likewise.

> why does it even warn that a public(!) method is not used?

Public methods of an anonymous class can only ever be accessed within that class or with the anonymous instantiation as the receiver. Nobody else is able to use that method as it doesn't have a globally useful (class-qualified) name.

**Comment by jukzi** [comment]
> Public methods of an anonymous class can only ever be accessed within that class or with the anonymous instantiation as the receiver. Nobody else is able to use that method as it doesn't have a globally useful (class-qualified) name.

That is why i changed to static and removed anonymous object. But the warning did not go away  - but since i can not reproduce that:  just do not bother.

**Comment by trancexpress** [comment]
> @jukzi and @adidiot can you reproduce this with latest ibuild ? like https://download.eclipse.org/eclipse/downloads/drops4/I20220827-1800/

Which PR is supposed to fix the bug? From what I can tell the bug here is fixed.

If the warning about an unused method is supposed to get fixed, please open another issue to track the bug. From my POV, the method is in an anonymous type. There is no way to call `getText()` from anywhere outside of the anonymous type definition for `X`. Since there is no call in the definition, it seems fair to assume no callers exist.

**Comment by Axidi** [comment]
I did the same test and it works now.

I use Eclipse SDK
Version: 2023-03 (4.27)
Build id: I20230302-0300
OS: Linux, v.5.19.0-38-generic, x86_64 / gtk 3.24.34
Java vendor: Oracle Corporation
Java runtime version: 20+36-2344
Java version: 20

**Comment by trancexpress** [comment]
OK, thanks for validating.

@jukzi please open a separate issue about the unused method, we can discuss there.
