### ISSUE TITLE
[BUG]: Misformatted diagnostics

### ISSUE THREAD

**Issue by ascopes** [eclipse-jdt/eclipse.jdt.core#3503]
Follow-up of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/958#issuecomment-2558170250 as requested by @stephan-herrmann.

Error 1311 / 8389919 `The package {0} does not exist or is empty` fails to bind due to missing parameters. 

This results in `Cannot bind message for problem (id: 1311) "The package {0} does not exist or is empty" with arguments: {}`.

```
[ForkJoinPool-1-worker-1] INFO io.github.ascopes.jct.compilers.impl.JctCompilationFactoryImpl - Starting compilation with ECJ (release = Java 17) (found 2 compilation units in approx 0ms)
[ForkJoinPool-1-worker-1] ERROR io.github.ascopes.jct.diagnostics.TracingDiagnosticListener - Cannot bind message for problem (id: 1311) "The package {0} does not exist or is empty" with arguments: {}
----------
1. ERROR in module-info.java (at line 22)
	exports com.example;
	        ^^^^^^^^^^^
The package com.example does not exist or is empty
----------
1 problem (1 error)
[ForkJoinPool-1-worker-1] INFO io.github.ascopes.jct.compilers.impl.JctCompilationFactoryImpl - Compilation with ECJ (release = Java 17) failed after approximately 93ms (roughly 21.51 classes/sec)
java.lang.AssertionError: Expected a successful compilation, but it failed.


Diagnostics:
[ERROR] 8389919
Cannot bind message for problem (id: 1311) "The package {0} does not exist or is empty" with arguments: {}

at io.github.ascopes.jct.integration.compilation.BasicModuleCompilationIntegrationTest.helloWorldRamDisk(BasicModuleCompilationIntegrationTest.java:51)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
```

**Comment by stephan-herrmann** [comment]
This should be fixed as part of #3446, no?

**Comment by ascopes** [comment]
Ah, wasn't aware of that being included in the fix as it seemed to be unrelated to the actual issue. Raised it as a separate issue as I thought you were including this in the remaining issues.

Happy to close if the error message was fixed as well.

**Comment by stephan-herrmann** [comment]
Closing as fixed via #3446 , see in particular https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3446/commits/de490a08a82ecc63aa7e25ed4b13b5b7f75eeeb4 :
> + fix arg passing in ProblemReporter.invalidPackageReference()
