### ISSUE TITLE
Eclipse compiler can generate bytecode that throws a NoClassDefFoundError

### ISSUE THREAD

**Issue by philwebb** [eclipse-jdt/eclipse.jdt.core#378]
## Overview

In certain situations bytecode produced by the Eclipse compiler can throw a `NoClassDefFoundError`, even though all signatures within the class use types that are on the classpath. This behavior is different to OpenJDK, where compiled classes do not throw such exceptions.

The following [sample application](https://github.com/philwebb/eclipse-jdt-issue-378) will reproduce the problem.

If you run the application from the command line with OpenJDK the build works and all tests pass.

If you import the project into Eclipse (Tested on 2022-03, 2022-08, 2022-06-RC1) and run `RunMeTest` you will see the following exception:

<details>
  <summary>java.lang.NoClassDefFoundError: com/example/optionallib/OptionalTalker</summary>

```
java.lang.NoClassDefFoundError: com/example/optionallib/OptionalTalker
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructors(Class.java:2060)
	at com.example.user.RunMe.main(RunMe.java:8)
	at com.example.user.RunMeTest.test(RunMeTest.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ClassNotFoundException: com.example.optionallib.OptionalTalker
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 75 more
```
</details>

## Sample Details

The sample application consists of the following four modules:

* `jdt-bug-lib` represents an library always on the classpath
* `jdt-bug-optional-lib` represents a library that uses `jdt-bug-lib` and is optional on the classpath
* `jdt-bug-framework` represents a framework that interacts with `jdt-bug-lib` and `jdt-bug-optional-lib`
* `jdt-bug-user` represents a user application that uses `jdt-bug-framework` but omits `jdt-bug-optional-lib`

The problem occurs in the `OptionalTalkerFactory` class:

```java
public class OptionalTalkerFactory {

	public Talker create(Type type) {
		if (type == null) {
			return null;
		}
		return Boolean.getBoolean("talker.mode") ? new FirstOptionalTalker()
				: new SecondOptionalTalker();
	}

	public static enum Type {

		DEFAULT, OPTIONAL;

	}

}
```

## Analysis

I believe that the problem is occurring with the following line:

```java
return Boolean.getBoolean("talker.mode") ? new FirstOptionalTalker()
		: new SecondOptionalTalker();
```

Both `FirstOptionalTalker` and `SecondOptionalTalker` have a common super type (`OptionalTalker`) which is not on the classpath. Note that the signature of `OptionalTalkerFactory` only exposes `Talker` which is always on the classpath.

Dissembling the bytecode for the Eclipse generated class using `javap -p -v -p -c com.example.framework.OptionalTalkerFactory` bytecode which include following:

```
StackMapTable: number_of_entries = 3
  frame_type = 6 /* same */
  frame_type = 17 /* same */
  frame_type = 70 /* same_locals_1_stack_item */
    stack = [ class com/example/optionallib/OptionalTalker ]
```

<details>
  <summary>Full javap output</summary>

```
Classfile /Volumes/Data/tmp/eclipse-bug/jdt-bug-framework/target/classes/com/example/framework/OptionalTalkerFactory.class
  Last modified Sep 8, 2022; size 980 bytes
  SHA-256 checksum 8b7fd2da22675fdafa7e89a3d5543773fe232662709019598d917cb04b2df679
  Compiled from "OptionalTalkerFactory.java"
public class com.example.framework.OptionalTalkerFactory
  minor version: 0
  major version: 61
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #1                          // com/example/framework/OptionalTalkerFactory
  super_class: #3                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 3
Constant pool:
   #1 = Class              #2             // com/example/framework/OptionalTalkerFactory
   #2 = Utf8               com/example/framework/OptionalTalkerFactory
   #3 = Class              #4             // java/lang/Object
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Utf8               Code
   #8 = Methodref          #3.#9          // java/lang/Object."<init>":()V
   #9 = NameAndType        #5:#6          // "<init>":()V
  #10 = Utf8               LineNumberTable
  #11 = Utf8               LocalVariableTable
  #12 = Utf8               this
  #13 = Utf8               Lcom/example/framework/OptionalTalkerFactory;
  #14 = Utf8               create
  #15 = Utf8               (Lcom/example/framework/OptionalTalkerFactory$Type;)Lcom/example/lib/Talker;
  #16 = String             #17            // talker.mode
  #17 = Utf8               talker.mode
  #18 = Methodref          #19.#21        // java/lang/Boolean.getBoolean:(Ljava/lang/String;)Z
  #19 = Class              #20            // java/lang/Boolean
  #20 = Utf8               java/lang/Boolean
  #21 = NameAndType        #22:#23        // getBoolean:(Ljava/lang/String;)Z
  #22 = Utf8               getBoolean
  #23 = Utf8               (Ljava/lang/String;)Z
  #24 = Class              #25            // com/example/optionallib/FirstOptionalTalker
  #25 = Utf8               com/example/optionallib/FirstOptionalTalker
  #26 = Methodref          #24.#9         // com/example/optionallib/FirstOptionalTalker."<init>":()V
  #27 = Class              #28            // com/example/optionallib/SecondOptionalTalker
  #28 = Utf8               com/example/optionallib/SecondOptionalTalker
  #29 = Methodref          #27.#9         // com/example/optionallib/SecondOptionalTalker."<init>":()V
  #30 = Utf8               type
  #31 = Utf8               Lcom/example/framework/OptionalTalkerFactory$Type;
  #32 = Utf8               StackMapTable
  #33 = Class              #34            // com/example/optionallib/OptionalTalker
  #34 = Utf8               com/example/optionallib/OptionalTalker
  #35 = Utf8               SourceFile
  #36 = Utf8               OptionalTalkerFactory.java
  #37 = Utf8               InnerClasses
  #38 = Class              #39            // com/example/framework/OptionalTalkerFactory$Type
  #39 = Utf8               com/example/framework/OptionalTalkerFactory$Type
  #40 = Utf8               Type
  #41 = Utf8               NestMembers
{
  public com.example.framework.OptionalTalkerFactory();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #8                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 7: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lcom/example/framework/OptionalTalkerFactory;

  public com.example.lib.Talker create(com.example.framework.OptionalTalkerFactory$Type);
    descriptor: (Lcom/example/framework/OptionalTalkerFactory$Type;)Lcom/example/lib/Talker;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_1
         1: ifnonnull     6
         4: aconst_null
         5: areturn
         6: ldc           #16                 // String talker.mode
         8: invokestatic  #18                 // Method java/lang/Boolean.getBoolean:(Ljava/lang/String;)Z
        11: ifeq          24
        14: new           #24                 // class com/example/optionallib/FirstOptionalTalker
        17: dup
        18: invokespecial #26                 // Method com/example/optionallib/FirstOptionalTalker."<init>":()V
        21: goto          31
        24: new           #27                 // class com/example/optionallib/SecondOptionalTalker
        27: dup
        28: invokespecial #29                 // Method com/example/optionallib/SecondOptionalTalker."<init>":()V
        31: areturn
      LineNumberTable:
        line 10: 0
        line 11: 4
        line 13: 6
        line 14: 24
        line 13: 31
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      32     0  this   Lcom/example/framework/OptionalTalkerFactory;
            0      32     1  type   Lcom/example/framework/OptionalTalkerFactory$Type;
      StackMapTable: number_of_entries = 3
        frame_type = 6 /* same */
        frame_type = 17 /* same */
        frame_type = 70 /* same_locals_1_stack_item */
          stack = [ class com/example/optionallib/OptionalTalker ]
}
SourceFile: "OptionalTalkerFactory.java"
InnerClasses:
  public static final #40= #38 of #1;     // Type=class com/example/framework/OptionalTalkerFactory$Type of class com/example/framework/OptionalTalkerFactory
NestMembers:
  com/example/framework/OptionalTalkerFactory$Type
```
</details>

Note that the `StackMapTable` includes a reference to `OptionalTalker` which is not on the classpath.

Running `mvn clean install` and repeating the process shows a different output produced by OpenJDK:

```
StackMapTable: number_of_entries = 3
  frame_type = 6 /* same */
  frame_type = 17 /* same */
  frame_type = 70 /* same_locals_1_stack_item */
    stack = [ class com/example/lib/Talker ]
```

<details>
  <summary>Full javap output</summary>

```
Classfile /Volumes/Data/tmp/eclipse-bug/jdt-bug-framework/target/classes/com/example/framework/OptionalTalkerFactory.class
  Last modified Sep 8, 2022; size 964 bytes
  SHA-256 checksum eb02098c1f23c01824f266278a6e1b2c0a113ef3d78744d238f16964435cf52f
  Compiled from "OptionalTalkerFactory.java"
public class com.example.framework.OptionalTalkerFactory
  minor version: 0
  major version: 61
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #21                         // com/example/framework/OptionalTalkerFactory
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 3
Constant pool:
   #1 = Methodref          #2.#3          // java/lang/Object."<init>":()V
   #2 = Class              #4             // java/lang/Object
   #3 = NameAndType        #5:#6          // "<init>":()V
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = String             #8             // talker.mode
   #8 = Utf8               talker.mode
   #9 = Methodref          #10.#11        // java/lang/Boolean.getBoolean:(Ljava/lang/String;)Z
  #10 = Class              #12            // java/lang/Boolean
  #11 = NameAndType        #13:#14        // getBoolean:(Ljava/lang/String;)Z
  #12 = Utf8               java/lang/Boolean
  #13 = Utf8               getBoolean
  #14 = Utf8               (Ljava/lang/String;)Z
  #15 = Class              #16            // com/example/optionallib/FirstOptionalTalker
  #16 = Utf8               com/example/optionallib/FirstOptionalTalker
  #17 = Methodref          #15.#3         // com/example/optionallib/FirstOptionalTalker."<init>":()V
  #18 = Class              #19            // com/example/optionallib/SecondOptionalTalker
  #19 = Utf8               com/example/optionallib/SecondOptionalTalker
  #20 = Methodref          #18.#3         // com/example/optionallib/SecondOptionalTalker."<init>":()V
  #21 = Class              #22            // com/example/framework/OptionalTalkerFactory
  #22 = Utf8               com/example/framework/OptionalTalkerFactory
  #23 = Utf8               Code
  #24 = Utf8               LineNumberTable
  #25 = Utf8               LocalVariableTable
  #26 = Utf8               this
  #27 = Utf8               Lcom/example/framework/OptionalTalkerFactory;
  #28 = Utf8               create
  #29 = Utf8               (Lcom/example/framework/OptionalTalkerFactory$Type;)Lcom/example/lib/Talker;
  #30 = Utf8               type
  #31 = Utf8               Lcom/example/framework/OptionalTalkerFactory$Type;
  #32 = Utf8               StackMapTable
  #33 = Class              #34            // com/example/lib/Talker
  #34 = Utf8               com/example/lib/Talker
  #35 = Utf8               SourceFile
  #36 = Utf8               OptionalTalkerFactory.java
  #37 = Utf8               NestMembers
  #38 = Class              #39            // com/example/framework/OptionalTalkerFactory$Type
  #39 = Utf8               com/example/framework/OptionalTalkerFactory$Type
  #40 = Utf8               InnerClasses
  #41 = Utf8               Type
{
  public com.example.framework.OptionalTalkerFactory();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 7: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lcom/example/framework/OptionalTalkerFactory;

  public com.example.lib.Talker create(com.example.framework.OptionalTalkerFactory$Type);
    descriptor: (Lcom/example/framework/OptionalTalkerFactory$Type;)Lcom/example/lib/Talker;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_1
         1: ifnonnull     6
         4: aconst_null
         5: areturn
         6: ldc           #7                  // String talker.mode
         8: invokestatic  #9                  // Method java/lang/Boolean.getBoolean:(Ljava/lang/String;)Z
        11: ifeq          24
        14: new           #15                 // class com/example/optionallib/FirstOptionalTalker
        17: dup
        18: invokespecial #17                 // Method com/example/optionallib/FirstOptionalTalker."<init>":()V
        21: goto          31
        24: new           #18                 // class com/example/optionallib/SecondOptionalTalker
        27: dup
        28: invokespecial #20                 // Method com/example/optionallib/SecondOptionalTalker."<init>":()V
        31: areturn
      LineNumberTable:
        line 10: 0
        line 11: 4
        line 13: 6
        line 14: 24
        line 13: 31
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      32     0  this   Lcom/example/framework/OptionalTalkerFactory;
            0      32     1  type   Lcom/example/framework/OptionalTalkerFactory$Type;
      StackMapTable: number_of_entries = 3
        frame_type = 6 /* same */
        frame_type = 17 /* same */
        frame_type = 70 /* same_locals_1_stack_item */
          stack = [ class com/example/lib/Talker ]
}
SourceFile: "OptionalTalkerFactory.java"
NestMembers:
  com/example/framework/OptionalTalkerFactory$Type
InnerClasses:
  public static final #41= #38 of #21;    // Type=class com/example/framework/OptionalTalkerFactory$Type of class com/example/framework/OptionalTalkerFactory
```
</details>

Note that in this case the `Talker` class is in the `StackMapTable` which will be always on the classpath.

I have found the problem can occur with `(!x) ? a : b` style expressions as well as with switch expressions. If code is rewritten to use a regular `if` then the problem often does away.

**Comment by stephan-herrmann** [comment]
From a quick look I would argue that mentioning `OptionalTalker` in StackMapTable is correct, because that is the "best type" for describing the ternary expression. I don't have a spec at hand to check if the least upper bound is to be used, or perhaps the target type indeed (which would also be the resolved type of the ternary).

But aren't we discussing only **at which point in time** the error will be raised? Without the super class you won't be able to run that code, right?

**Comment by philwebb** [comment]
The example above is somewhat contrived, but you can find a real example being fixed in https://github.com/spring-projects/spring-boot/commit/127d320636d6b372c06d51190fc6e16ae1437a6a.

> Without the super class you won't be able to run that code, right?

It should be possible to run `OptionalTalkerFactory` passing in a `null` and have it not fail because it won't attempt to load `FirstOptionalTalker`, `SecondOptionalTalker` or the common superclass. I believe that It should also be possible to use reflection on `OptionalTalkerFactory` without an exception being raised.

**Comment by stephan-herrmann** [comment]
To demonstrate that this is a bug in ECJ one would have to consult the specification and figure out what it requires to be put into StackMapTable in this specific case. From all I can see mentioning 'OptionalTalker` is correct.

**Comment by philwebb** [comment]
I'm not too familiar with the Java compiler specification, but if you can point me in the right direction I'm happy to try and take a look. Perhaps this is an area that's under specified?

Either way, the problem of not being able to use reflection on a class that has such an element in the StackMapTable does cause real problems and the behavior in ECJ does differ from OpenJDK. Of course, I can't say which is more correct, only report the issue that it causes.

**Comment by stephan-herrmann** [comment]
> I'm not too familiar with the Java compiler specification, but if you can point me in the right direction I'm happy to try and take a look. Perhaps this is an area that's under specified?

I had a look and probably the spec won't help us much here, as there is nothing about how the StackMapTable should be generated (JLS doesn't even mention it), but only how it is used for load-time type-checking:
* https://docs.oracle.com/javase/specs/jvms/se19/html/jvms-4.html#jvms-4.7.4
* https://docs.oracle.com/javase/specs/jvms/se19/html/jvms-4.html#jvms-4.10.1

I understand this as saying, it's the compiler's responsibility to produce any StackMapTable that will allow the JVM to verify type correctness of the code using the given prolog rules. IOW, as long as loading the class doesn't throw `VerifyError` the class file (code and stack map table) is good.

You may call this under-specified, as it doesn't define how the StackMapTable must be computed, but the acceptance criteria are clear and well defined. If the spec were more specific you might even call that over-specified :)

> Either way, the problem of not being able to use reflection on a class that has such an element in the StackMapTable does cause real problems 

Of course you can use reflection, but for that you need to provide on the classpath all those classes that were necessary to compile the class. I think that's a fair requirement.

> [...] and the behavior in ECJ does differ from OpenJDK. Of course, I can't say which is more correct, only report the issue that it causes.

I dare say that both are equally correct in this regard.

**Comment by stephan-herrmann** [comment]
Technically speaking, I see the following difference in strategies between compilers:

**javac** seems to leverage the target type of the ternary expression and concludes that the return value must have type `Talker`, so they put this type into the StackMapTable. The code passes verification. Fair enough. 

This can be observed by assigning the ternary to variables of different types:
```
interface I {}
class O implements I {}
class A extends O implements I {}
class B extends O implements I {}
public class T {
	I m1(boolean f) {
		I i = f ? new A() : new B();
		return i;
	}
	I m2(boolean f) {
		O i = f ? new A() : new B();
		return i;
	}
}
```

Method `m1` and `m2` produce exactly the same byte code, yet one mentions `I` in the StackMapTable, where the other mentions `O`. I.e., a purely internal change in the method body will thus decide which classes are needed during class loading. This doesn't sound like a very attractive contract if you ask me.


**ecj**, though, computes the StackMapTable based only on the byte code, where no target type is available. Here the type of the ternary is computed as the _least upper bound_ of the two branch types. The rules for _lub_ ensure that values from both branches can be assigned to the result type. In the above example both methods say `O`. This is simple and correct.


If it were a simple code change, we could perhaps still be persuaded to change strategy between correct and correct. But the current design in ecj doesn't have the information at hand that is necessary for javac's strategy. FWIW, here's the big change that introduced this design https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/150033/ 

I'm closing this issue, as it's not realistic to undo that big refactoring, sorry.

**Comment by philwebb** [comment]
No problem, I totally understand and thanks very much for digging into it. FWIW I think it's pretty unlikely that a typical application would hit the problem.
