### ISSUE TITLE
No search results for inner class constructor with first argument of outer type

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#401]
1) Part one: on **Java 11** I can't get any match trying to see **callers** or **references** of all inner class constructors inside `java.util.SplittableRandom` class, like
`java.util.SplittableRandom.RandomDoublesSpliterator.RandomDoublesSpliterator(SplittableRandom, long, long, double, double)`.
Neither call hierarchy nor search for references on the constructors show any match.
2) Part two: on **Java 17** (where the code in question is changed) I can't get any match trying to see **callers** (but I get references!) of all inner class constructors inside `java.util.SplittableRandom` class, like
`java.util.SplittableRandom.AbstractSplittableGeneratorProxy.AbstractSplittableGeneratorProxy(SplittableRandom)`.
Call hierarchy doesn't find, but search for references find the constructor.

The second part will be fixed with #333, but the first part not.
So this (part 1) seem to be different to #332 issue and need another fix.

**Comment by trancexpress** [comment]
Looks like the `SearchPattern` has `ConstructorPattern.parameterCount` set to 4, but the constructor has 5 arguments. So the calls to the constructor are ignored by the search. The argument count is decremented with this stack trace:

```
"Worker-11: Fetching children of RandomDoublesSpliterator" #97 prio=5 os_prio=0 cpu=38.88ms elapsed=158.86s tid=0x00007f8c9c001e90 nid=0x122b4 runnable  [0x00007f8cef5fe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.core.search.matching.ConstructorPattern.<init>(ConstructorPattern.java:334)
        at org.eclipse.jdt.internal.core.search.matching.ConstructorPattern.<init>(ConstructorPattern.java:366)
        at org.eclipse.jdt.core.search.SearchPattern.createPattern(SearchPattern.java:2209)
        at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:144)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
        at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Apparently the code assumes the first argument is synthetic, due to it being a parameter type that is the same as the outer type... That seems like a generous assumption...

Reproduction snippet:

```
package test.abc;

public final class TestInnerConstructor {

	public static void main(String[] args) {
		Banana b = Banana.foo();
		System.out.println(b);
	}

	private static final class Banana {
		Banana(TestInnerConstructor o, int i) {

		}
		static Banana foo() {
			return new Banana(null, 42);
		}
	}
}
```

For whatever reason, the snippet must be in a jar. If its a source file, the call hierarchy works fine. Will have to check what the difference between those 2 is and will have to add a test for source file and jar binary file.
