### ISSUE TITLE
 Cannot invoke "java.util.Map.keySet()" because "cache" is null

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#416]
When using -system with a java 11 JVM while running on a java 17 jvm compilation fails with:

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "cache" is null
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247Jdk12.loadModules(ClasspathJep247Jdk12.java:211)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJrt.initialize(ClasspathJrt.java:200)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247.initialize(ClasspathJep247.java:118)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247Jdk12.initialize(ClasspathJep247Jdk12.java:143)
	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
	at org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(JDTCompiler.java:372)
	at org.eclipse.tycho.compiler.jdt.JDTCompiler.performCompile(JDTCompiler.java:123)
	at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:414)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.doCompile(AbstractOsgiCompilerMojo.java:370)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:351)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "cache" is null
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247Jdk12.loadModules(ClasspathJep247Jdk12.java:211)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJrt.initialize(ClasspathJrt.java:200)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247.initialize(ClasspathJep247.java:118)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJep247Jdk12.initialize(ClasspathJep247Jdk12.java:143)
	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
	at org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(JDTCompiler.java:372)
	at org.eclipse.tycho.compiler.jdt.JDTCompiler.performCompile(JDTCompiler.java:123)
	at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:414)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.doCompile(AbstractOsgiCompilerMojo.java:370)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:351)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

see also https://github.com/eclipse-tycho/tycho/issues/1354

**Comment by iloveeclipse** [comment]
@laeubi : looks like "system" argument isn't supported with "release", and error above is just because lacking of proper argument validation :

```
// If release >= 9, the following are disallowed
// --system and --upgrade-module-path
```
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/6cc3c6a76d283e8d64a28f8fe7113159dd592e27/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/Main.java#L2700

**Comment by iloveeclipse** [comment]
`-target,` 11, -source, 11, --release, 11, -encoding, UTF-8, --system, /opt/tools/java/openjdk/jdk-11/latest`
https://github.com/eclipse-tycho/tycho/issues/1354#issuecomment-1250199240

Also below: https://github.com/eclipse-jdt/eclipse.jdt.core/blob/6cc3c6a76d283e8d64a28f8fe7113159dd592e27/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/Main.java#L2708
```
// -source and -target are disallowed for any --release
```

**Comment by laeubi** [comment]
So the fix would be to omit `--release` when using `--system`?
Strange enough it seems to work when I let point `JAVA_HOME = <system path>` ...

**Comment by iloveeclipse** [comment]
@laeubi : honestly speaking, I don't know what the spec says and what exactly "system" was good for. I assume we need to fix JDT to clearly fail on invalid arguments, but it requires a deeper understanding of all the consequences.

**Comment by iloveeclipse** [comment]
So yes, I wouldn't use "system" in tycho with Java > 9 as long as this one is open.

**Comment by laeubi** [comment]
Alright, currently Tycho uses:

`-bootclasspath / -extdirs / -endorseddirs`

for JVM <= 1.8, is `--system` the better approach here?

**Comment by laeubi** [comment]
> honestly speaking, I don't know what the spec says and what exactly "system" was good for

Interestingly it has worked so far to compile "higher" code (e.g. running in Java11 and then compile for java 17) and it seems there *is* an option in the JDT/Eclipse UI ...

**Comment by laeubi** [comment]
> looks like "system" argument isn't supported with "release", and error above is just because lacking of proper argument validation :

The usage section of the batch compiler claims:

```
 Module compilation options:\n\
   These options are meaningful only in Java 9 environment or later.\n\
    --module-source-path <directories separated by {0}>\n\
                       specify where to find source files for multiple modules\n\
    -p --module-path <directories separated by {0}>\n\
                       specify where to find application modules\n\
    --processor-module-path <directories separated by {0}>\n\
                       specify module path where annotation processors\n\
                       can be found\n\
    --system <jdk>     Override location of system modules\n\
```

so it seems `system` actually should be supported even with Java 9+....??
