### ISSUE TITLE
Search for reference not working for method reference in anonymous class

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#432]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=566435.

To reproduce, compute the call hierarchy of method `missingReference1` in the following snippet:

```
public class MissingReference2 {

	public static void main(String[] args) {
		new Runnable() {
			@Override
			public void run() {
				// here is the usage of the method
				Stream.empty().filter(MissingReference2::missingReference1).count();
			}
		}.run();
	}

	// Show references of this method says "0 references"
	public static boolean missingReference1(Object arg) {
		return true;
	}
}
```

Observe that there is nothing found.

This is a regression from the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=429279.

In particular, the entire body of `main` is removed by this call:

```
diff --git a/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/SourceIndexer.java b/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/SourceIndexer.java
index 39d388adb1..ac4820fc87 100644
--- a/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/SourceIndexer.java
+++ b/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/SourceIndexer.java
@@ -168,7 +168,7 @@ public class SourceIndexer extends AbstractIndexer implements ITypeRequestor, Su
                        // Use a non model name environment to avoid locks, monitors and such.
                        INameEnvironment nameEnvironment = IndexBasedJavaSearchEnvironment.create(Collections.singletonList((IJavaProject)javaProject), JavaModelManager.getJavaModelManager().getWorkingCopies(DefaultWorkingCopyOwner.PRIMARY, true/*add primary WCs*/));
                        this.lookupEnvironment = new LookupEnvironment(this, this.options, problemReporter, nameEnvironment);
-                       reduceParseTree(this.cud);
+                       //reduceParseTree(this.cud);
                        this.lookupEnvironment.buildTypeBindings(this.cud, null);
                        this.lookupEnvironment.completeTypeBindings();
                        this.cud.scope.faultInTypes();
```

When changing the snippet slightly, the problem is not seen:

```
public class MissingReference2 {

	public static void main(String[] args) {
		new Runnable() {
			@Override
			public void run() {
				// here is the usage of the method
				Stream.empty().filter(MissingReference2::missingReference1).count();
			}
		}.run();
		Stream.empty().filter(MissingReference2::missingReference1).count();
	}

	// Show references of this method says "0 references"
	public static boolean missingReference1(Object arg) {
		return true;
	}
}
```

I assume the code must check also member types defined in a method, before "purging" the method contents.

**Comment by iloveeclipse** [comment]
Test fails on windows build:
https://download.eclipse.org/eclipse/downloads/drops4/I20221027-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

```
junit.framework.AssertionFailedError: Expected search to find references of method: static boolean missingReference(Object) [in TestGh432 [in TestGh432.java [in p [in src [in gh432MethodReferencesSearchBug]]]]], in snippet:
package p;
public class TestGh432 {
private static void foo(Runnable r) {
r.run();
}
public static void main(String[] args) {
foo(() -> {
new Runnable() {
public void run() {
java.util.stream.Stream.empty().filter(TestGh432::missingReference).count();
}
};
});
}
public static boolean missingReference(Object arg) {
return true;
}
}
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertFalse(Assert.java:39)
at junit.framework.TestCase.assertFalse(TestCase.java:208)
at org.eclipse.jdt.core.tests.model.JavaSearchTests.testAnonymousTypeMethodReferenceSearchGh432(JavaSearchTests.java:4681)
```

**Comment by trancexpress** [comment]
> Test fails on windows build: https://download.eclipse.org/eclipse/downloads/drops4/I20221027-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

Opened: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/499

I don't have a Windows machine anymore so I can't validate.
