### ISSUE TITLE
Call hierarchy does not find some uses via method reference

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#438]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571913

To reproduce:

1. Create a new Java project, JRE is 11. No `module-info.java` file.
2. First paste this snippet into the project:
```
___ MethodRef.java ___
import java.util.ArrayList;
import java.util.List;

class MethodRef {
	List<User> users = new ArrayList<>();
	
	void printStuff() {
		doNames();
	}

	private void doNames() {
		users.forEach(User::printName);
	}
}
```
3. Then paste this snippet into the project:
```
___ User.java ___
class User {
	String name;

	void printName() {
		System.out.println(name);
	}
}
```
4. Compute the call hierarchy of `User.printName()`, observe that its empty.

When reversing the paste order, the call hierarchy is not empty.

**Comment by trancexpress** [comment]
When debugging, I see the following stack trace computes a `null` `MethodBinding` for the method reference. And so it doesn't add the method reference to the index:

```
"Java indexing" #61 daemon prio=5 os_prio=0 cpu=372.19ms elapsed=330.62s tid=0x00007ffff0bdd000 nid=0xdbef runnable  [0x00007fff5bdfc000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.indexResolvedDocument(SourceIndexer.java:280)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexResolvedDocument(JavaSearchParticipant.java:103)
        at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:677)
        at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1303)
        at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:478)
        at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)
```

Adding the missing source however does result in a re-compile of the source. I don't know why the indexer doesn't go over this code again to add the method reference once it can be resolved...
