### ISSUE TITLE
StackOverflowError in TypeBinding.getQualifiedName

### ISSUE THREAD

**Issue by guw** [eclipse-jdt/eclipse.jdt.core#440]
The following exception was reported while using `org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName`. I wonder if the code does need some recursive detection of if there is something else going on in the classpath, which could cause this.

```
java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeNode.findTreeNode(ConcurrentHashMap.java:2753)
	at java.base/java.util.concurrent.ConcurrentHashMap$TreeBin.find(ConcurrentHashMap.java:2905)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:944)
	at org.eclipse.jdt.core.dom.DefaultBindingResolver.internalGetTypeBinding(DefaultBindingResolver.java:424)
	at org.eclipse.jdt.core.dom.DefaultBindingResolver.getTypeBinding(DefaultBindingResolver.java:380)
	at org.eclipse.jdt.core.dom.TypeBinding.getBound(TypeBinding.java:197)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:739)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at org.eclipse.jdt.core.dom.TypeBinding.getQualifiedName(TypeBinding.java:748)
	at (hundrets more)
```

**Comment by srikanth-sankaran** [comment]
Please provide a test case. Thanks

**Comment by jukzi** [comment]
Closing as not enough information provided. Please reopen with reproducer if any.
