### ISSUE TITLE
Java build stuck with blazer persistence framework

### ISSUE THREAD

**Issue by bbobbettoS** [eclipse-jdt/eclipse.jdt.core#442]
When I try to build an existent maven java project where I have added the blaze framework in it, the build process stuck. 

My Steps to reproduce
In a fresh 2022.09 eclipse installation, 
- download the entityView maven archetype
'mvn archetype:generate "-DarchetypeGroupId=com.blazebit" "-DarchetypeArtifactId=blaze-persistence-archetype-entity-view-sample" "-DarchetypeVersion=1.6.7"'
- Imports as "Existing Maven Project"
- Disable "build automatically"
- Add jdk1.8 to "installed JREs" and sets as default
- Uncheck "Use compliance from execution..." and "Use default compliance settings" from "JDK Compliance"
- "Apply and Close" and rebuild

This steps are to reproduce the problem, in my case I am using jdk11 and I not have unchecked "Use compliance from execution..." and "Use default compliance settings", but after I added blaze libs and created a few Blaze interfaces, my project doesn't build anymore.
When I switch to the branch pre-blaze I can build without any problem

## What is the current bug behavior?
On the bottom Rebuilt is stuck at X% and I can only kill eclipse because all the other operation, closing included, will wait the rebuild process to finish.
On restart "Use compliance from execution..." and "Use default compliance settings" are checked, but every time I try to build the project, the build process stuck on 5%

## Priority

- [ ] Urgent
- [x] High
- [ ] Medium
- [ ] Low

## Severity

- [x] Blocker
- [ ] Major
- [ ] Normal
- [ ] Low

![eclipse](https://user-images.githubusercontent.com/114412356/192286595-dbccdd7c-b795-4636-96a1-48ae0081a885.gif)

**Comment by iloveeclipse** [comment]
Please create thread dump with `jstack -l` at the moment the build is suck and attach this dump here.

**Comment by iloveeclipse** [comment]
This hangs in `com.blazebit.persistence.view.processor.EntityViewAnnotationProcessor` code.
Please report the bug to the blazebit bug tracker.

```
"Worker-13: Building" #66 prio=5 os_prio=0 cpu=304,21ms elapsed=256,54s tid=0x00007ff3d22a42a0 nid=0x10cc waiting on condition  [0x00007ff338bfd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	- parking to wait for  <0x00000000a4a93dd0> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:211)
	at java.util.concurrent.FutureTask.awaitDone(java.base@17.0.4.1/FutureTask.java:447)
	at java.util.concurrent.FutureTask.get(java.base@17.0.4.1/FutureTask.java:190)
	at com.blazebit.persistence.view.processor.EntityViewAnnotationProcessor.await(EntityViewAnnotationProcessor.java:145)
	at com.blazebit.persistence.view.processor.EntityViewAnnotationProcessor.createMetaModelClasses(EntityViewAnnotationProcessor.java:234)
	at com.blazebit.persistence.view.processor.EntityViewAnnotationProcessor.execute(EntityViewAnnotationProcessor.java:125)
	at com.blazebit.persistence.view.processor.EntityViewAnnotationProcessor.process(EntityViewAnnotationProcessor.java:99)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:379)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:311)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:273)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:211)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
