### ISSUE TITLE
ConcurrentModificationException while downloading sources/javadoc

### ISSUE THREAD

**Issue by garretwilson** [eclipse-jdt/eclipse.jdt.core#447]
With Eclipse EE 2022-09 on Windows 10 I not infrequently get a `java.util.ConcurrentModificationException` when starting up or modifying projects. For example just now I started Eclipse and before I could do anything I get:

> Could not download sources or javadoc
> Unexpected internal Error occured
> java.util.ConcurrentModificationException

```
eclipse.buildId=4.25.0.I20220831-1800
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.m2e.core
Error
Sun Oct 02 06:41:45 PDT 2022
Unexpected internal Error occured

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$25(ProjectRegistryManager.java:1036)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.getMavenProject(ProjectRegistryManager.java:1036)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectFacade.getMavenProject(MavenProjectFacade.java:269)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.downloadMaven(DownloadSourcesJob.java:248)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.downloadFilesAndPopulateToUpdate(DownloadSourcesJob.java:220)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.lambda$0(DownloadSourcesJob.java:149)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.embedder.IMaven.execute(IMaven.java:270)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.run(DownloadSourcesJob.java:149)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
```
eclipse.buildId=4.25.0.I20220831-1800
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.m2e.jdt
Error
Sun Oct 02 06:41:45 PDT 2022
Could not download sources or javadoc
```

**Comment by iloveeclipse** [comment]
Please create bug at m2e project.

**Comment by garretwilson** [comment]
Thanks for pointing out this relates to m2e. Looks like it's a duplicate of eclipse-m2e/m2e-core#924
