### ISSUE TITLE
NPE in org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode

### ISSUE THREAD

**Issue by mfussenegger** [eclipse-jdt/eclipse.jdt.core#452]
Loading https://github.com/crate/crate using https://github.com/eclipse/eclipse.jdt.ls results in NPEs.
I can't tell if this is impacting the functionality much, I spotted this debugging another issue.
Afaik eclipse.jdt.ls is currently using the Eclipse 4.25 release

```
Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isStatic()" because "this.binding" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isStatic()" because "this.binding" is null
\tat org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:149)
\tat org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:236)
\tat org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:155)
\tat org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:959)
\tat org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:304)
\tat org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:136)
\tat org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:911)
\tat org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
\tat java.base/java.lang.Thread.run(Thread.java:833)
```

I'm not too familiar with the jdt.core code, but based on what I saw while stepping through it with a debugger, it appears to me it happens when evaluating the return type of an expression like this:

```
newInstance(
  source,
  Collectors.collectingAndThen(Collectors.summingLong(r -> (long) r.get(0)), sum -> Collections.singletonList(new Row1(sum))))
```

Here are the frames from the debugger view:

```
→ MessageSend.analyseCode(BlockScope,FlowContext,FlowInfo):149
  CastExpression.analyseCode(BlockScope,FlowContext,FlowInfo):80
  LambdaExpression.analyzeExceptions():565
  LambdaExpression.cachedResolvedCopy(TypeBinding,boolean,boolean,InferenceContext18,Scope):1017
  LambdaExpression.resolveExpressionExpecting(TypeBinding,Scope,InferenceContext18):1035
  ConstraintExpressionFormula.inputVariables(InferenceContext18):513
  InferenceContext18.lambda$1(ConstraintFormula):601
  0x00000008014175c0.perform():-1
  InferenceContext18.collectingInnerBounds(InferenceContext18$InferenceOperation):535
  InferenceContext18.addJDK_8153748ConstraintsFromFunctionalExpr(FunctionalExpression,TypeBinding,MethodBinding):601
  InferenceContext18.addJDK_8153748ConstraintsFromExpression(Expression,TypeBinding,MethodBinding,InferenceSubstitution):571
  InferenceContext18.addJDK_8153748ConstraintsFromInvocation(Expression[],MethodBinding,InferenceSubstitution):556
  InferenceContext18.addJDK_8153748ConstraintsFromExpression(Expression,TypeBinding,MethodBinding,InferenceSubstitution):578
  InferenceContext18.addJDK_8153748ConstraintsFromInvocation(Expression[],MethodBinding,InferenceSubstitution):556
  InferenceContext18.addJDK_8153748ConstraintsFromExpression(Expression,TypeBinding,MethodBinding,InferenceSubstitution):578
  InferenceContext18.addJDK_8153748ConstraintsFromInvocation(Expression[],MethodBinding,InferenceSubstitution):556
  InferenceContext18.inferInvocationType(TypeBinding,InvocationSite,MethodBinding):421
  ParameterizedGenericMethodBinding.computeCompatibleMethod18(MethodBinding,TypeBinding[],Scope,InvocationSite):271
  ParameterizedGenericMethodBinding.computeCompatibleMethod(MethodBinding,TypeBinding[],Scope,InvocationSite):92
  Scope.computeCompatibleMethod(MethodBinding,TypeBinding[],InvocationSite,boolean):841
  Scope.computeCompatibleMethod(MethodBinding,TypeBinding[],InvocationSite):798
  Scope.findMethod0(ReferenceBinding,char[],TypeBinding[],InvocationSite,boolean):1757
  Scope.findMethod(ReferenceBinding,char[],TypeBinding[],InvocationSite,boolean):1658
  Scope.getImplicitMethod(char[],TypeBinding[],InvocationSite):2624
  MessageSend.findMethodBinding(BlockScope):1019
  MessageSend.resolveType(BlockScope):835
  ReturnStatement.resolve(BlockScope):337
  AbstractMethodDeclaration.resolveStatements():662
  MethodDeclaration.resolveStatements():388
  AbstractMethodDeclaration.resolve(ClassScope):571
  TypeDeclaration.resolve():1503
  TypeDeclaration.resolve(CompilationUnitScope):1628
  CompilationUnitDeclaration.resolve():667
  Compiler.process(CompilationUnitDeclaration,int):905
  ProcessTaskManager.run():145
```

<details>
  <summary>And here are parts of the locals:</summary>

```
Local
  flowInfo: UnconditionalFlowInfo@6812 "FlowInfo<def: 768, pot: 768, reachable:true, no null info>"
    definiteInits: 768
    extra: null
    iNBit: 0
    iNNBit: 0
    maxFieldCount: 8
    nullBit1: 0
    nullBit2: 0
    nullBit3: 0
    nullBit4: 0
    potentialInits: 768
    tagBits: 0
  this: MessageSend@6809 "r.get(0)"
    actualReceiverType: InferenceVariable@17582
    argsContainCast: false
    argumentTypes: TypeBinding[0]@17584
    arguments: Expression[1]@17583
      0: IntLiteral@17610 "0"
    argumentsHaveErrors: false
    binding: null
    bits: -2147483648
    closeTracker: null
    constant: DoubleConstant@17585 "(Constant) NotAConstant"
    expectedType: null
    expressionContext: ExpressionContext$3@17586 "casting context"
    flowUpdateOnBooleanResult: null
    genericTypeArguments: null
    implicitConversion: 0
    inferenceContexts: null
    nameSourcePosition: 12824772348844
    outerInferenceContext: null
    patternVarsWhenFalse: null
    patternVarsWhenTrue: null
    receiver: SingleNameReference@17587 "r"
    receiverIsType: false
    resolvedType: null
    selector: char[3]@17588
    solutionsPerTargetType: null
    sourceEnd: 2991
    sourceStart: 2984
    statementEnd: -1
    syntheticAccessor: null
    typeArguments: null
    valueCast: null
  currentScope: MethodScope@6810 "\n--- Method Scope ---\n	locals:\n		T#1 r[pos: unused][id:1]\n	startIndex = 0\n	isConstructorCall = false\n	initializedField = null\n	lastVisibleFieldID = -1\n	referenceContext = (<no type> r) -> (long) r.get(0)"
    analysisIndex: 0
    blockStatement: null
    commonTypeBindings: null
    compilationUnitScope: CompilationUnitScope@17616
    definiteInits: long[4]@17617
    enclosingCase: null
    extraDefiniteInits: long[4][]@17618
    extraSyntheticArguments: null
    finallyInfo: null
    hasMissingSwitchDefault: false
    initializedField: null
    insideTypeAnnotation: false
    isCompactConstructorScope: false
    isConstructorCall: false
    isPropagatingInnerClassEmulation: false
    isStatic: true
    kind: 2
    lastIndex: 0
    lastVisibleFieldID: -1
    localIndex: 1
    locals: LocalVariableBinding[5]@17619
    maxOffset: 0
    nullDefaultRanges: null
    offset: 0
    parent: MethodScope@17569 "\n--- Method Scope ---\n	locals:\n		BatchIterator<io.crate.data.Row> source[pos: unused][id:0]\n	startIndex = 0\n	isConstructorCall = false\n	initializedField = null\n	lastVisibleFieldID = -1\n	referenceContext = /**\n */\npublic static BatchIterator<Row> summingLong(BatchIterator<Row> source) {\n  return newInstance(source, Collectors.collectingAndThen(Collectors.summingLong((<no type> r) -> (long) r.get(0)), (<no type> sum) -> Collections.singletonList(new Row1(sum))));\n}"
    referenceContext: LambdaExpression@17620 "(<no type> r) -> (long) r.get(0)"
```

</summary>

I saw the same error also with constructs like this:

```
return new AddColumnDefinition<>(
    mapper.apply(name),
    null,
    type == null ? null : type.map(mapper),
    Lists2.map(constraints, x -> x.map(mapper)),
    false,
    generatedExpression != null
);
```

**Comment by vrubezhny** [comment]
The issue s really annoying. Once in a while when a build operation occurs on a project it opens a modal dialog like the following: 

![Screenshot from 2022-11-25 17-04-58](https://user-images.githubusercontent.com/620781/204022563-702bde2f-c25d-4cea-a57b-691221954159.png)

So, it doesn't look like the exception is really caught in all the places where this code is invoked. 

In my case the stack trace looks a little bit different:
```
eclipse.buildId=4.25.0.I20220831-1800
java.version=19.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.wildwebdeveloper.product.branding.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.wildwebdeveloper.product.branding.product -data file:/home/jeremy/projects/workspace-wwd/

org.eclipse.jdt.core
Error
Fri Nov 25 15:54:05 CET 2022
Errors running builder 'Java Builder' on project 'org.eclipse.lsp4e'.

java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isStatic()" because "this.binding" is null
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:149)
	at org.eclipse.jdt.internal.compiler.ast.Block.analyseCode(Block.java:50)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:110)
	at org.eclipse.jdt.internal.compiler.ast.Block.analyseCode(Block.java:50)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:110)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:155)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:959)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:304)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:136)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:911)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by stephan-herrmann** [comment]
> In my case the stack trace looks a little bit different:

So that is a different situation: if no type inference is happening in the call stack, nor LambdaExpression visible in the vicinity, then null indicates a bug indeed.

Can you identify which code triggers this? Does it happen, when doing a full build? Or does the NPE depend on factors like: which files have been edited? Or after a git branch switch, etc.?

If you're able to attach the debugger to the IDE, then a breakpoint hit (against NPE in general, or at the line that throws, with a proper breakpoint condition) would reveal the code location in question (all stack frames from package o.e.j.i.c.ast would be interesting).

**Comment by vrubezhny** [comment]
> Can you identify which code triggers this?

Do you mean what source text causes the compiler to generate a wrong (null) `this.binding` in  `MessageSend`?
It's most likely the following statement in line 60 of https://github.com/eclipse/lsp4e/blob/master/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatHandler.java#L60:

```
				versionedEdits.edits().thenAcceptAsync(edits -> {
					if (!edits.isEmpty()) {
						shell.getDisplay().asyncExec(() -> {
							try {
								formatter.applyEdits(document, edits, versionedEdits.version());
							} catch (ConcurrentModificationException e) {
								ServerMessageHandler.showMessage(Messages.LSPFormatHandler_DiscardedFormat, //
										new MessageParams(MessageType.Error,
												Messages.LSPFormatHandler_DiscardedFormatResponse));
							}
						});
					}
				});
```
>  Does it happen, when doing a full build? Or does the NPE depend on factors like: which files have been edited? Or after a git branch switch, etc.?

This happens when editing a completely different java file from the same project. Actually it looks like in order to see this Modal Dialog there is no need to open editor at all - it appears right after the lsp4e project is imported as existing Maven project. So, firstly it could be triggered by the background build, then on rebuilding after some source file is edited.

**Comment by martinlippert** [comment]
I think this needs to be re-opened. The issue still exists in the latest builds (trying Eclipse 2023-12 M3 at the moment) and happens in a regular Eclipse as well, not just in jdtls land.

I haven't looked into which code exactly is causing this, but I can reproduce it when importing https://github.com/spring-projects/spring-integration into a fresh workspace using a vanilla Eclipse 2023-12 M3 (Java Package) build, using Buildship to import the projects (they use Gradle).

Please re-open this!

**Comment by iloveeclipse** [comment]
@martinlippert : please create new ticket with your steps to reproduce and your specific error stack.

**Comment by martinlippert** [comment]
> @martinlippert : please create new ticket with your steps to reproduce and your specific error stack.

Done: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1621

Thanks a lot for looking into this!!!

**Comment by stephan-herrmann** [comment]
For starters I tried to reproduce using lsp4e, but never saw this NPE (except in situations where it is caught in LambdaExpression.analyseExceptions()).

**Comment by martinlippert** [comment]
Janne found the line of code that causes this, will update #1621 with more details
