### ISSUE TITLE
Record patterns exhaustiveness check problems

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#455]
This might be related to #450 (not sure). The following code compiles fine with Javac:

```java
public class RecordPatternsJava19ExhaustivenessOK {
  static Pair<A> p1 = new Pair<>(new A(), new B());
  static Pair<I> p2 = new Pair<>(new C(), new D());

  public static void main(String[] args) {
    exhaustiveSwitch();
  }

  static void exhaustiveSwitch() {
    switch (p2) {
      case Pair<I>(I i,C c) -> System.out.println("x");
      case Pair<I>(I i,D d) -> System.out.println("y");
    }

    switch (p2) {
      case Pair<I>(C c,I i) -> System.out.println("a");
      case Pair<I>(D d,C c) -> System.out.println("b");
      case Pair<I>(D d1,D d2) -> System.out.println("c");
    }
  }

  static class A { }
  static class B extends A { }
  sealed interface I permits C, D { }
  static final class C implements I { }
  static final class D implements I { }
  record Pair<T>(T x, T y) { }

}
```

```text
$ javac -J-Duser.language=en --enable-preview --release 19 -nowarn -d target/classes src/main/java/RecordPatternsJava19ExhaustivenessOK.java
Note: src\main\java\RecordPatternsJava19ExhaustivenessOK.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.

$ java --enable-preview -cp target/classes RecordPatternsJava19ExhaustivenessOK
y
a
```

But with ECJ it says (from my AspectJ Maven build):

```text
[ERROR] RecordPatternsJava19ExhaustivenessOK.java:10:0::0 An enhanced switch statement should be exhaustive; a default label expected
[ERROR] error at switch (p2) {
[ERROR]
[ERROR] RecordPatternsJava19ExhaustivenessOK.java:15:0::0 An enhanced switch statement should be exhaustive; a default label expected
```

The negative test:

```java
public class RecordPatternsJava19ExhaustivenessError {
  static Pair<I> p2 = new Pair<>(new C(), new D());

  public static void main(String[] args) {
    exhaustiveSwitch();
  }

  static void exhaustiveSwitch() {
    switch (p2) {
      case Pair<I>(C fst, D snd) -> System.out.println("a");
      case Pair<I>(D fst, C snd) -> System.out.println("b");
      case Pair<I>(I fst, C snd) -> System.out.println("c");
    }
  }

  static class A { }
  static class B extends A { }
  sealed interface I permits C, D { }
  static final class C implements I { }
  static final class D implements I { }
  record Pair<T>(T x, T y) { }

}
```

```text
$ javac -J-Duser.language=en --enable-preview --release 19 -nowarn -d target/classes src/main/java/RecordPatternsJava19ExhaustivenessError.java
src\main\java\RecordPatternsJava19ExhaustivenessError.java:9: error: the switch statement does not cover all possible input values
    switch (p2) {
    ^
Note: src\main\java\RecordPatternsJava19ExhaustivenessError.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.
1 error
```

ECJ says:

```text
[ERROR] RecordPatternsJava19ExhaustivenessError.java:9:0::0 An enhanced switch statement should be exhaustive; a default label expected
[ERROR] error at switch (p2) {
```

I am not sure if ECJ gets it right by chance or accidentally. Better double-check, please. Ideally, the error message should be adjusted to be similar to Javac's, too.

**Comment by kriegaex** [comment]
I just re-tested with ECJ 4.26 RC2. The issue persists.

**Comment by kriegaex** [comment]
Here is an additional finding: When adding redundant `default -> System.out.println("z");` clauses to both `switch` statements in the sample code in order to make it compile with ECJ, this will cause a runtime error when trying to execute the compiled code:

```text
$ "/c/Program Files/Java/jdk-19/bin/java" -jar ecj-I20221220-1800.jar --release 19 --enable-preview -nowarn RecordPatternsJava19ExhaustivenessOK.java

$ "/c/Program Files/Java/jdk-19/bin/java" --enable-preview RecordPatternsJava19ExhaustivenessOK
Exception in thread "main" java.lang.NoSuchMethodError: 'RecordPatternsJava19ExhaustivenessOK$I RecordPatternsJava19ExhaustivenessOK$Pair.x()'
        at RecordPatternsJava19ExhaustivenessOK.exhaustiveSwitch(RecordPatternsJava19ExhaustivenessOK.java:11)
        at RecordPatternsJava19ExhaustivenessOK.main(RecordPatternsJava19ExhaustivenessOK.java:6)
```

As you can see, it compiles fine after adding the default clauses, but the byte code generated seems to be wrong. Please note that I tried the latest integration build I20221220-1800.

**Comment by kriegaex** [comment]
After the Java 20 merge into the main branch, the erroneous exhaustiveness check still persists and needs to be fixed. But at least the workaround of adding a redundant `default` clause, as described in the previous comment, now works and no longer generates faulty byte code.

**Comment by kriegaex** [comment]
This seems to be fixed, closing issue.
