### ISSUE TITLE
EncodingTests.test021() fails on win

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#462]
https://download.eclipse.org/eclipse/downloads/drops4/I20221010-1840/testresults/html/org.eclipse.jdt.core.tests.model_ep426I-unit-win32-java11_win32.win32.x86_64_11.html
```

junit.framework.ComparisonFailure: Encoded UTF-8 source should have been decoded the same way!.
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertSourceEquals(AbstractJavaModelTests.java:1131)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertSourceEquals(AbstractJavaModelTests.java:1111)
at org.eclipse.jdt.core.tests.model.EncodingTests.test021(EncodingTests.java:466)
```

**Comment by jukzi** [comment]
can only be reproduced locally when -Dfile.encoding is not set
![image](https://user-images.githubusercontent.com/51790620/195134492-5bd9971c-96c4-41b2-be5b-da3c4fb3c5a1.png)
