### ISSUE TITLE
[Compiler] VerifyError for record whose canonical constructor unconditionally throws exception

### ISSUE THREAD

**Issue by Marcono1234** [eclipse-jdt/eclipse.jdt.core#487]
### Version
Eclipse Compiler 3.31.0
(Maven: [`org.eclipse.jdt:ecj:3.31.0`](https://search.maven.org/artifact/org.eclipse.jdt/ecj/3.31.0/jar))

### Description
The Eclipse compiler seems to produce invalid byte code for a record class with at least one component whose canonical constructor unconditionally throws an exception:
```
Error: Unable to initialize main class RecordTest
Caused by: java.lang.VerifyError: Control flow falls through code end
Exception Details:
  Location:
    RecordTest.<init>(Ljava/lang/String;)V @17: <invalid>
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2ab7 000a bb00 0d59 b700 0fbf 2a2b b500
    0000010: 10
  Stackmap Table:
    full_frame(@12,{Object[#1],Object[#20]},{})
```
I am not very familiar with Java byte code, but I assume the issue is that the compiler generates unreachable default code which tries to assign the record component fields. `javap` output:
```
 0: aload_0
 1: invokespecial #10                 // Method java/lang/Record."<init>":()V
 4: new           #13                 // class java/lang/RuntimeException
 7: dup
 8: invokespecial #15                 // Method java/lang/RuntimeException."<init>":()V
11: athrow
12: aload_0
13: aload_1
14: putfield      #16                 // Field s:Ljava/lang/String;
```

This is a quite contrived case, but it should probably nonetheless produce valid Java byte code.
This issue also occurs when the `throw` statement is wrapped with `if (true) { ... }`.

### Reproduction steps
1. Create a file called `RecordTest.java` with the following content
    ```java
    record RecordTest(String s) {
        RecordTest {
            throw new RuntimeException();
        }
        
        public static void main(String... args) throws Exception {
            new RecordTest("");
        }
    }
    ```
2. Compile the class with the Eclipse compiler:
    ```
    java -jar ./ecj-3.31.0.jar -17 ./RecordTest.java
    ```
3. Try to run the compiled class
    ```java
    java RecordTest
    ```
    :x: Bug: It fails with a `VerifyError`

**Comment by trancexpress** [comment]
`javap -verbose` output for the `.class` compiled by `javac`

```
  RecordTest(java.lang.String);
    descriptor: (Ljava/lang/String;)V
    flags: (0x0000)
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Record."<init>":()V
         4: new           #7                  // class java/lang/RuntimeException
         7: dup
         8: invokespecial #9                  // Method java/lang/RuntimeException."<init>":()V
        11: athrow
```

And for the one from `ecj`:

```
  RecordTest(java.lang.String);
    descriptor: (Ljava/lang/String;)V
    flags: (0x0000)
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: invokespecial #10                 // Method java/lang/Record."<init>":()V
         4: new           #13                 // class java/lang/RuntimeException
         7: dup
         8: invokespecial #15                 // Method java/lang/RuntimeException."<init>":()V
        11: athrow
        12: aload_0
        13: aload_1
        14: putfield      #16                 // Field s:Ljava/lang/String;
```

Stack trace that generates the `putfield` after the `athrow`:

```
"Compiler Processing Task" #199 daemon prio=5 os_prio=0 cpu=1.52ms elapsed=35.86s tid=0x00007fbd9c2429e0 nid=0x611e at breakpoint [0x00007fbe66bfe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.ast.Reference.fieldStore(Reference.java:124)
        at org.eclipse.jdt.internal.compiler.ast.FieldReference.generateAssignment(FieldReference.java:227)
        at org.eclipse.jdt.internal.compiler.ast.Assignment.generateCode(Assignment.java:139)
        at org.eclipse.jdt.internal.compiler.ast.Expression.generateCode(Expression.java:767)
        at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.internalGenerateCode(ConstructorDeclaration.java:458)
        at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.generateCode(ConstructorDeclaration.java:310)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:761)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:831)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:413)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:916)
        at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
        at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)
```

On the stack trace, I see `codeStream.methodDeclaration` (of type `CompactConstructorDeclaration`) with contents (at `Expression.generateCode()`):

```
RecordTest(String s) {
  super();
  throw new RuntimeException();
  this.s = s;
}
```

`this.s = s` is appended with this stack trace:

```
"Compiler Processing Task" #239 daemon prio=5 os_prio=0 cpu=9.28ms elapsed=58.51s tid=0x00007fbdb412fba0 nid=0x6841 runnable  [0x00007fbe943da000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.ast.CompactConstructorDeclaration.checkAndGenerateFieldAssignment(CompactConstructorDeclaration.java:93)
        at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.analyseCode(ConstructorDeclaration.java:207)
        at org.eclipse.jdt.internal.compiler.ast.CompactConstructorDeclaration.analyseCode(CompactConstructorDeclaration.java:43)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:951)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:304)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:137)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:911)
        at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
        at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)
```

Possibly the fix is as simple as changing the addition order:

```
diff --git a/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CompactConstructorDeclaration.java b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CompactConstructorDeclaration.java
index 391b860990..e9c4eb35b2 100644
--- a/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CompactConstructorDeclaration.java
+++ b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CompactConstructorDeclaration.java
@@ -87,8 +87,8 @@ public class CompactConstructorDeclaration extends ConstructorDeclaration {
                int len = this.statements.length;
                int fLen = fa.length;
                Statement[] stmts = new Statement[len + fLen];
-               System.arraycopy(this.statements, 0, stmts, 0, len);
-               System.arraycopy(fa, 0, stmts, len, fLen);
+               System.arraycopy(fa, 0, stmts, 0, fLen);
+               System.arraycopy(this.statements, 0, stmts, fLen, len);
                this.statements = stmts;
        }
 }
\ No newline at end of file
```

**Comment by Marcono1234** [comment]
> Possibly the fix is as simple as changing the addition order

That would violate the [language specification](https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.10.4.2):
> After the last statement, if any, in the body of the compact constructor has completed normally ([§14.1](https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.1)), all component fields of the record class are implicitly initialized to the values of the corresponding formal parameters.

The question would be whether that difference is really noticeable, but there might be contrived cases, such as leaking `this` in the canonical constructor, where this difference might have an effect.

Either way, since you did not chose this approach for your pull request it does not matter much.
Also thanks for fixing this!

**Comment by trancexpress** [comment]
> That would probably violate the [language specification](https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.10.4.2)

Thanks for the hint!
