### ISSUE TITLE
ArrayIndexOutOfBoundsException during Java Search

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdt/eclipse.jdt.core#488]
revision: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/528dc7e08311c59735d33154cf7e532758b55bd8
Steps to reproduce:

- import https://github.com/redhat-developer/vscode-java/files/9708915/test.zip
- open PartBuilder.java
- right click acceptLine in line 22, select References>Workspace

You will get the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getOrCreateDeclaredPackage(ModuleBinding.java:338)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule.getDeclaredPackage(ModuleBinding.java:104)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.combineWithPackagesFromOtherRelevantModules(ModuleBinding.java:669)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getVisiblePackage(ModuleBinding.java:614)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getTopLevelPackage(ModuleBinding.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTopLevelPackage(LookupEnvironment.java:1686)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3557)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3187)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:60)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveTypeArgument(TypeReference.java:638)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveLeafType(ParameterizedSingleTypeReference.java:264)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveType(ParameterizedSingleTypeReference.java:174)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.resolveType(ParameterizedSingleTypeReference.java:390)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveTypeForQualifiedAllocationExpression(QualifiedAllocationExpression.java:377)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveType(QualifiedAllocationExpression.java:304)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.resolve(FieldDeclaration.java:294)
```

A potential path:
```
diff --git a/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java b/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java
index f30e61acd4..432ec2b6e9 100644
--- a/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java
+++ b/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java
@@ -96,7 +96,7 @@ public class ModuleBinding extends Binding implements IUpdatableModule {
                @Override
                PlainPackageBinding getDeclaredPackage(char[] flatName) {
                        PlainPackageBinding declaredPackage = super.getDeclaredPackage(flatName);
-                       if (declaredPackage == null && this.environment.useModuleSystem) {
+                       if (declaredPackage == null && flatName.length > 0 && this.environment.useModuleSystem) {
                                IModuleAwareNameEnvironment moduleEnv = (IModuleAwareNameEnvironment) this.environment.nameEnvironment;
                                char[][] compoundName = CharOperation.splitOn('.', flatName);
                                char[][] declaringModuleNames = moduleEnv.getUniqueModulesDeclaringPackage(compoundName, nameForLookup());
```

A related issue: https://github.com/redhat-developer/vscode-java/issues/2710

**Comment by kaspernielsen** [comment]
See also
https://bugs.eclipse.org/bugs/show_bug.cgi?id=552572
https://bugs.eclipse.org/bugs/show_bug.cgi?id=560812
https://bugs.eclipse.org/bugs/show_bug.cgi?id=550067

**Comment by snjeza** [comment]
A duplicate of #825
