### ISSUE TITLE
ExternalAnnotations18Test.testBug482242 failure in I20220427-0410

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#49]
We see this in Linux/11 build:
https://download.eclipse.org/eclipse/downloads/drops4/I20220427-0410/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
Unexpected problem Pb(983) Unsafe null type conversion (type annotations): The value of type 'Collector<@NonNull String,capture#of ?,Set<@NonNull String>>' is made accessible using the less-annotated type 'Collector<? super String,Object,Set<@NonNull String>>' at 11

junit.framework.AssertionFailedError: Unexpected problem Pb(983) Unsafe null type conversion (type annotations): The value of type 'Collector<@NonNull String,capture#of ?,Set<@NonNull String>>' is made accessible using the less-annotated type 'Collector<? super String,Object,Set<@NonNull String>>' at 11
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.jdt.core.tests.model.ExternalAnnotations18Test.assertProblems(ExternalAnnotations18Test.java:483)
at org.eclipse.jdt.core.tests.model.ExternalAnnotations18Test.testBug482242(ExternalAnnotations18Test.java:2726)
```

@stephan-herrmann : related to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/48 ?

**Comment by stephan-herrmann** [comment]
I can see various failures in that suite on specific platforms, but the above was not part of what I saw in recent builds. Did it happen more than once?

**Comment by iloveeclipse** [comment]
No, whatever it was it is gone now.
