### ISSUE TITLE
NPE in JRTUtil.walkModuleImage

### ISSUE THREAD

**Issue by guw** [eclipse-jdt/eclipse.jdt.core#493]
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(org.eclipse.jdt.internal.compiler.util.JRTUtil$JrtFileVisitor, int)" because the return value of "org.eclipse.jdt.internal.compiler.util.JRTUtil.getJrtSystem(java.io.File, String)" is null
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:246)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.lambda$0(ClasspathJrtWithReleaseOption.java:143)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.findPackagesInModules(ClasspathJrtWithReleaseOption.java:140)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.getModuleNames(ClasspathJrtWithReleaseOption.java:242)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.querySystemPackages(TargetPlatformHelper.java:418)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getPlatformProperties(TargetPlatformHelper.java:385)
	at org.eclipse.pde.internal.core.MinimalState.getProfilePlatformProperties(MinimalState.java:260)
	at org.eclipse.pde.internal.core.MinimalState.initializePlatformProperties(MinimalState.java:254)
	at org.eclipse.pde.internal.core.PDEState.<init>(PDEState.java:67)
	at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:616)
	at org.eclipse.pde.internal.core.PluginModelManager.findModel(PluginModelManager.java:1070)
	at org.eclipse.pde.internal.core.RequiredPluginsInitializer.initialize(RequiredPluginsInitializer.java:50)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3145)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:3029)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3091)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2088)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4578)
	at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This is on M1 MacBook with an Azul JDK 17 configured as installed JREs

**Comment by guw** [comment]
This might actually be triggered by the broken state in PDE. Opened https://github.com/eclipse-pde/eclipse.pde/issues/368

**Comment by guw** [comment]
Looks like it. Here is what I found on console:
```
Error: failed to create JrtFileSystem from /Library/Java/JavaVirtualMachines/sfdc-openjdk_17.0.4_17.36.14_aarch64.jdk/Contents/Home/lib/jrt-fs.jar
java.io.FileNotFoundException: /Library/Java/JavaVirtualMachines/openjdk_17.0.4_17.36.14_aarch64.jdk/Contents/Home/release (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at org.eclipse.jdt.internal.compiler.util.Jdk.readJdkReleaseFile(JRTUtil.java:461)
	at org.eclipse.jdt.internal.compiler.util.Jdk.lambda$0(JRTUtil.java:414)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
```

**Comment by guw** [comment]
@iloveeclipse Thanks for the pointer. Further investigation unveils a problem in my installation. Azul has the release file at its proper place.

**Comment by iloveeclipse** [comment]
> unveils a problem in my installation

Something you can share, so others could learn from it?

**Comment by guw** [comment]
Just a missing symlink target. 🤷‍♂️

**Comment by guw** [comment]
@iloveeclipse Actually JDT might want to improve the error message here. That detail together with some further text could have avoided the GitHub issue.
