### ISSUE TITLE
Cannot invoke "org.eclipse.jdt.internal.compiler.env.IModule.isAutomatic()" because "module" is null

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#610]
While importing a project with m2e I got:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.env.IModule.isAutomatic()" because "module" is null
	at org.eclipse.jdt.internal.compiler.lookup.BinaryModuleBinding.create(BinaryModuleBinding.java:99)
	at org.eclipse.jdt.internal.compiler.impl.ITypeRequestor.accept(ITypeRequestor.java:65)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getModuleFromAnswer(LookupEnvironment.java:440)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:377)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:239)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:116)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:249)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getType(PackageBinding.java:205)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findType(Scope.java:2025)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3500)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3187)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:60)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2753)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2705)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:2276)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.internalFaultInTypeForFieldsAndMethods(SourceTypeBinding.java:1518)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1113)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:560)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:898)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jarthana** [comment]
Can you please provide the steps, more specifically, share the project with the problem?

**Comment by laeubi** [comment]
1. Download Eclipse RCP/RAP Edition
2. clone `https://github.com/ops4j/org.ops4j.pax.jdbc`
3. Import all projects from the git

**Comment by basilevs** [comment]
Happened for me when switching before very different branches with eGit.

**Comment by ptziegler** [comment]
I'm currently getting the same error consistently in my workspace as well. What I noticed is that this seems to only show up because the execution of my projects are mixed. Some use Java 17, others Java 21. If I update all projects to use Java 21, the problem disappears.

<img width="1919" height="1034" alt="Image" src="https://github.com/user-attachments/assets/0da11c0b-86d5-42e1-8d54-8dc65b16fbd8" />

A quick debug session revealed that in the `ClasspathJrt`, the `modulesCache` contains several entries for Java 21 (e.g. `/usr/lib/jvm/java-21-openjdk-amd64/lib/jrt-fs.jar|9`, as well as a `/usr/lib/jvm/java-25-openjdk-amd64/lib/jrt-fs.jar`, but no `/usr/lib/jvm/java-21-openjdk-amd64/lib/jrt-fs.jar`, which is what's then producing the `null` module.

<img width="1444" height="738" alt="Image" src="https://github.com/user-attachments/assets/3b50a339-8297-4af5-a2ad-0d53c9c060bc" />

The Java 25 is likely there because that's what set in the preferences.

<img width="953" height="663" alt="Image" src="https://github.com/user-attachments/assets/2a3c889f-44a9-4a10-8879-7e0b39ce4a58" />

As a remark: Because of this configuration, the projects having Java 17 as their EE reference Java 21, while the projects having Java 21 reference Java 25. Possibly something gets mixed up here.

Given the area that is affected, this is possibly also related to [Bug 529367](https://bugs.eclipse.org/bugs/show_bug.cgi?id=529367) - [9] NPE in BinaryModuleBinding.create(...) during search

**Comment by ptziegler** [comment]
Removing the erroneous mapping from "JRE for JavaSE-21" to Java 25 also solved the issue.

I also just noticed that the same issue is also described in #284 and #3608. Would it make sense to only keep one and close the others as duplicate?
