### ISSUE TITLE
CCE in ModularClassFile.getModule

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#661]
Following was thrown in one of our automated tests based on 4.25 platform.
The code lines matches master state, so the problem is most likely still there.

If I interpret the stack right, we have a case where a module info returns "true" from `ModularClassFile.exists()` call but on next call to `ModularClassFile.getModule()` it finds itself from `getElementInfo()` that actually it is `ModularClassFile.notExists` and happily throws a stupid CCE.

*Probably* related to the Xtext build and multi-threading, may be in between there was a parallel call to the same object and that time it was really missing.

At least CCE should be fixed (and `newNotPresentException()` called), I will try to provide a patch.

Unfortunately we can't reproduce, seem to be a very rare (timing related) issue.

```
java.lang.ClassCastException: class org.eclipse.jdt.internal.core.JavaElementInfo cannot be cast to class org.eclipse.jdt.internal.core.ClassFileInfo (org.eclipse.jdt.internal.core.JavaElementInfo and org.eclipse.jdt.internal.core.ClassFileInfo are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3a62ef37)
    at org.eclipse.jdt.internal.core.ModularClassFile.getModule(ModularClassFile.java:301)
    at org.eclipse.jdt.internal.core.PackageFragmentRoot.getSourceModuleDescription(PackageFragmentRoot.java:928)
    at org.eclipse.jdt.internal.core.PackageFragmentRoot.getModuleDescription(PackageFragmentRoot.java:904)
    at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.getModuleDescription(JarPackageFragmentRoot.java:307)
    at org.eclipse.jdt.internal.core.SearchableEnvironment.<init>(SearchableEnvironment.java:126)
    at org.eclipse.jdt.internal.core.SearchableEnvironment.<init>(SearchableEnvironment.java:146)
    at org.eclipse.jdt.internal.core.CancelableNameEnvironment.<init>(CancelableNameEnvironment.java:32)
    at org.eclipse.jdt.internal.core.CancelableNameEnvironment.<init>(CancelableNameEnvironment.java:29)
    at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:679)
    at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:907)
    at org.eclipse.jdt.core.dom.ASTParser.createBindings(ASTParser.java:1112)
    at org.eclipse.xtext.common.types.access.jdt.JdtBasedTypeFactory.resolveBindings(JdtBasedTypeFactory.java:396)
    at org.eclipse.xtext.common.types.access.jdt.JdtBasedTypeFactory.createType(JdtBasedTypeFactory.java:319)
```

**Comment by iloveeclipse** [comment]
Looks like this is a side effect of the patch 5447c5ed96ac15bf9373e90935d968a92f09ad36.
