### ISSUE TITLE
org.eclipse.jdt.core.tests.compiler.parser.TestAll.test010 fails since I20230208-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#715]
https://download.eclipse.org/eclipse/downloads/drops4/I20230208-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep427I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
invalid selection unit-X.java. ----------- Expected ------------ public class X {\n enum Num {\n ONE(),\n TWO(),\n THREE(),\n <clinit>() {\n }\n Num() {\n }\n }\n public X() {\n }\n public static void foo(Num num_) {\n switch (num_) {\n case THREE ->\n {\n int i_j;\n System.out.println(<SelectOnName:i_j>);\n break;\n }\n }\n }\n }\n ------------ but was ------------ public class X {\n enum Num {\n ONE(),\n TWO(),\n THREE(),\n <clinit>() {\n }\n Num() {\n }\n }\n public X() {\n }\n public static void foo(Num num_) {\n {\n {\n int i_j;\n <SelectOnName:i_j>;\n }\n }\n }\n }\n --------- Difference is ---------- expected:<...o(Num num_) {\n [switch (num_) {\n case THREE ->\n {\n int i_j;\n System.out.println(<SelectOnName:i_j>);\n break;\n ] }\n }\n ...> but was:<...o(Num num_) {\n [{\n {\n int i_j;\n <SelectOnName:i_j>;\n ] }\n }\n ...>

junit.framework.ComparisonFailure: invalid selection unit-X.java.
----------- Expected ------------
public class X {\n
enum Num {\n
ONE(),\n
TWO(),\n
THREE(),\n
<clinit>() {\n
}\n
Num() {\n
}\n
}\n
public X() {\n
}\n
public static void foo(Num num_) {\n
switch (num_) {\n
case THREE ->\n
{\n
int i_j;\n
System.out.println(<SelectOnName:i_j>);\n
break;\n
}\n
}\n
}\n
}\n

------------ but was ------------
public class X {\n
enum Num {\n
ONE(),\n
TWO(),\n
THREE(),\n
<clinit>() {\n
}\n
Num() {\n
}\n
}\n
public X() {\n
}\n
public static void foo(Num num_) {\n
{\n
{\n
int i_j;\n
<SelectOnName:i_j>;\n
}\n
}\n
}\n
}\n

--------- Difference is ----------
expected:<...o(Num num_) {\n
[switch (num_) {\n
case THREE ->\n
{\n
int i_j;\n
System.out.println(<SelectOnName:i_j>);\n
break;\n
] }\n
}\n
...> but was:<...o(Num num_) {\n
[{\n
{\n
int i_j;\n
<SelectOnName:i_j>;\n
] }\n
}\n
...>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.compiler.parser.AbstractSelectionTest.checkMethodParse(AbstractSelectionTest.java:194)
at org.eclipse.jdt.core.tests.compiler.parser.AbstractSelectionTest.checkMethodParse(AbstractSelectionTest.java:256)
at org.eclipse.jdt.core.tests.compiler.parser.SelectionParserTest12.test010(SelectionParserTest12.java:519)
```

**Comment by iloveeclipse** [comment]
@jarthana : this is a regression from 446877a222bd34e9b1947e9bb61ab98cd7af96a2.
Could you please check?

**Comment by iloveeclipse** [comment]
Thanks @jarthana!
