### ISSUE TITLE
NPE when adding files without file extension to the classpath

### ISSUE THREAD

**Issue by ptziegler** [eclipse-jdt/eclipse.jdt.core#720]
The exception is thrown, the moment a file without any file extension is added to the classpath of a Java project.

Tested with org.eclipse.jdt.core - 3.31.0.v20220831-1439

```
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.eclipse.core.runtime.IPath.getFileExtension()" is null
	at org.eclipse.jdt.internal.core.JavaModel.isJmod(JavaModel.java:401)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:801)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1103)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1048)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1025)
	at org.eclipse.jdt.internal.core.JavaProject.buildStructure(JavaProject.java:538)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:266)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:328)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
	at org.eclipse.jdt.internal.core.JavaProject.isUnNamedModule(JavaProject.java:4001)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:793)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1103)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1048)
	at org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1870)
	at org.eclipse.jdt.internal.core.JavaProject.getAllPackageFragmentRoots(JavaProject.java:1861)
	at org.eclipse.jdt.internal.core.JavaProject.findPackageFragmentRoot0(JavaProject.java:1638)
	at org.eclipse.jdt.internal.core.JavaProject.findPackageFragmentRoot(JavaProject.java:1630)
	at org.eclipse.jdt.internal.corext.buildpath.ClasspathModifier.isArchive(ClasspathModifier.java:694)
	...
```

This is the problematic method:

```
public static boolean isJmod(File file) {
	IPath path = Path.fromOSString(file.getPath());
	if (path.getFileExtension().equalsIgnoreCase(SuffixConstants.EXTENSION_jmod)) {
		return true;
	}
	return false;
}
```

I think the operands simply need to be swapped, so that the constant is on the left side.

So instead of :
`path.getFileExtension().equalsIgnoreCase(SuffixConstants.EXTENSION_jmod)`
it should be:
`SuffixConstants.EXTENSION_jmod.equalsIgnoreCase(path.getFileExtension())`

**Comment by anandbibek** [comment]
Reference : https://github.com/redhat-developer/vscode-java/issues/2856
