### ISSUE TITLE
Call hierarchy empty for static method in Java 8 project called by Java 11 project

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#723]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=549003

To reproduce:

1. Add a JRE installation for Java 1.8 and Java 11.
2. Import the example projects from: [call_hierarchy.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10706651/call_hierarchy.zip)
3. Compute call hierarchy of `Test8.testLocale(Locale)`, observe nothing is shown.
4. Compute method references of `Test8.testLocale(Locale)`, observe the listed match is a potential match.

Essentially, the 2 sources look like this, each in the respective project:

```
public class Test8 {
    public static void testLocale(java.util.Locale l) { }
}
```
```
public class Test11 {
    public void test() {
        Test8.testLocale(null);
    }
}
```

The Java 11 project references the Java 8 project. The Java 11 project has JRE 11 on its module path. The Java 8 project has JRE 8 on its classpath.

There is no call hierarchy shown for `Test8.testLocale()`.

**Comment by trancexpress** [comment]
This problem doesn't occur with a Java 11 and Java 17 projects.

I see there are problems with the imports of `Collection` and `Locale` with the Java 11 / Java 8 projects:

```
"Worker-0: Fetching children of testLocale" #41 prio=5 os_prio=0 cpu=571.18ms elapsed=52.28s tid=0x00007ffff09497f0 nid=0xb675 runnable  [0x00007ffef3ffd000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:484)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:552)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2031)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1363)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1400)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1542)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
        at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
        at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

In this code:

```
if (importBinding instanceof SplitPackageBinding && !inJdtDebugCompileMode) {
    SplitPackageBinding splitPackage = (SplitPackageBinding) importBinding;
    int sourceEnd = (int)(importReference.sourcePositions[splitPackage.compoundName.length-1] & 0xFFFF);
    problemReporter().conflictingPackagesFromModules((SplitPackageBinding) importBinding, module(), importReference.sourceStart, sourceEnd);
    continue nextImport;
}
```

`splitPackage` being:

```
package java.util (from <unnamed>, java.base, java.prefs, java.logging)
```

This is a lot like https://github.com/eclipse-jdt/eclipse.jdt.core/issues/675... And if I move the Java 11 JRE to the classpath (delete the `module` attribute which is per default set to `true` for Java 9+ projects, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=522592).

I'm not sure this is good enough here though, since its very easy to recreate this situation. Also the code compiles just fine, which would not have been the case in #675, had the module library been on the module path. The JRE 11 is on the module path of the Java 11 project and the JRE 8 is not on the classpath of the Java 11 project... I'm not sure how the search environment manages to run into a package conflict.

**Comment by stephan-herrmann** [comment]
Do you want me to take a look at the resolution failure? In that case a JUnit would come in really handy :)

Otherwise, when you are in the situation of that split package mentioned above, what is that `from <unnamed>` slice of the split package? What does it contain? Who contributes it? Seeing `java.util` from both unnamed and named modules sure looks fishy.

**Comment by trancexpress** [comment]
> Do you want me to take a look at the resolution failure? In that case a JUnit would come in really handy :)

I'll try to add one, maybe its not too difficult.

> Otherwise, when you are in the situation of that split package mentioned above, what is that `from <unnamed>` slice of the split package? What does it contain? Who contributes it? Seeing `java.util` from both unnamed and named modules sure looks fishy.

I'm trying to look into that but its slow going. I believe the unnamed module is added to the `SplitPackageBinding` with this stack trace:

```
"Worker-14: Fetching children of testLocale" #86 prio=5 os_prio=0 cpu=471.05ms elapsed=1823.63s tid=0x00007ffe5007e3a0 nid=0xcdea at breakpoint [0x00007ffe5e8ee000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.add(SplitPackageBinding.java:80)
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.<init>(SplitPackageBinding.java:68)
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.combine(SplitPackageBinding.java:50)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.combineWithPackagesFromOtherRelevantModules(ModuleBinding.java:670)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getVisiblePackage(ModuleBinding.java:614)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getTopLevelPackage(ModuleBinding.java:551)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTopLevelPackage(LookupEnvironment.java:1687)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.getDefaultImports(CompilationUnitScope.java:712)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:241)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:517)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1338)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1400)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1542)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
        at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
        at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by stephan-herrmann** [comment]
> I believe the unnamed module is added to the SplitPackageBinding with this stack trace:...

when asking, who contributes it, I was more interested in which classpath entry and which content provides `java.util@unnamed` (content being a class that declares this package).

**Comment by trancexpress** [comment]
> > I believe the unnamed module is added to the SplitPackageBinding with this stack trace:...
> 
> when asking, who contributes it, I was more interested in which classpath entry and which content provides `java.util@unnamed` (content being a class that declares this package).

I've added a test: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/726

Aside from the JREs, there is no contribution of a package `java` in either project. The Java 8 project has JRE 8 on the classpath. The Java 11 project has JRE 11 on the module path and references the Java 8 project.

**Comment by trancexpress** [comment]
Well, in short, `JavaSearchNameEnvironment.getModulesDeclaringPackage(char[][], char[])` is called by `ModuleBinding.getVisiblePackage(PackageBinding, char[])` in this code block:

```
if (this.environment.useModuleSystem) {
			IModuleAwareNameEnvironment moduleEnv = (IModuleAwareNameEnvironment) this.environment.nameEnvironment;
			declaringModuleNames = moduleEnv.getUniqueModulesDeclaringPackage(subPkgCompoundName, nameForLookup());
			if (binding == null) {
				if (declaringModuleNames != null) {
					if (CharOperation.containsEqual(declaringModuleNames, this.moduleName)) {
						if (parent != null) {
							PackageBinding singleParent = parent.getIncarnation(this);
							if (singleParent != null && singleParent != parent) {
								// parent.getPackage0() may have been too shy, so drill into the split:
								binding = singleParent.getPackage0(name);
							}
						}
						if (binding == null) {
							// declared here, not yet known, so create it now:
							binding = this.createDeclaredPackage(subPkgCompoundName, parent);
						}
					} else {
						// visible but foreign (when current is unnamed or auto):
						for (char[] declaringModuleName : declaringModuleNames) {
							ModuleBinding declaringModule = this.environment.root.getModule(declaringModuleName);
							if (declaringModule != null) {
								PlainPackageBinding declaredPackage = declaringModule.getDeclaredPackage(fullFlatName);
								binding = SplitPackageBinding.combine(declaredPackage, binding, this);
							}
						}
					}
				}
			}
		}
```

`nameForLookup()` here is `ModuleBinding.ANY`, since the code is in: `ModuleBinding$UnNamedModule(ModuleBinding).getVisiblePackage(PackageBinding, char[]) line: 582`


The `JavaSearchNameEnvironment` is aware of the JRE 8 from the Java 8 project. During `getModulesDeclaringPackage()`, `nameForLookup()` being set to `ANY` means that the code ignores having no module info for the JRE 8 and just considers everything in the JRE to belong to the unnamed module. This later on causes the split package problem.

The `ANY` strategy ignoring the absence of module info is due to changes for: https://bugs.eclipse.org/bugs/show_bug.cgi?id=519674

It was apparently needed to fix compile problems.

I don't understand what the compiler does here to avoid the same problem as seen by the search environment... I guess that will be the next thing to check. From #675 debugging, the difference was: `JavaSearchNameEnvironment.getModulesDeclaringPackage(char[][], char[])` vs. `SearchableEnvironment.getModulesDeclaringPackage(char[][], char[])`

The 2 are quite different w.r.t. the `ANY` strategy... `SearchableEnvironment` seems to return the unnamed module only during the compile, i.e. this code always returns:

```
case Any:
	// if in pre-9 mode we may still search the unnamed module
	if (this.knownModuleLocations == null) {
		if ((this.owner != null && this.owner.isPackage(pkgName))
				|| this.nameLookup.isPackage(pkgName))
			return new char[][] { ModuleBinding.UNNAMED };
```

Another thing I noticed while debugging earlier, there comes a point during the call hierarchy computation when `Test8.java` is being compiled with a `LookupEnvironment` that has its `useModuleSystem` flag set. I believe `Test8` is being compiled in the scope of the Java 11 project at least during `MatchLocator.locateMatches()`. There are different `LookupEnvironment` objects for different phases of the search... the one in `MatchLocator` is the only one with `useModuleSystem=true`... There is no such thing during the compile, of course.

**Comment by trancexpress** [comment]
I've adjusted the test in #723 to not use a JRE type for the reproduction. Instead there is a:

1. A module library on the module path of  project `A`.
2. A library on the classpath of project `B`.
3. Project `B` is on the classpath of project `A`.
4. Both libraries define the same type `X`.
5. Project `B` defines a method with a parameter of type `X`:
```
public class TestB {
    public static void test(X x) {}
}
```
6. Project `A` has a call to this method:
```
public class TestA {
    public void myMethod() {
        TestB.test(null);
    }
}
```
7. Code compiles and runs without problems.
8. Call hierarchy of `TestB.test()` is empty.

As explained in my comment above, the fix for #675 doesn't seem to help here due to the `Any` strategy - the fact that there is no module info for the classpath library from step `2.` is ignored.

**Comment by stephan-herrmann** [comment]
> The JRE 11 is on the module path of the Java 11 project and the JRE 8 is not on the classpath (or module path) of the Java 11 project

I'm still looking from a distance, haven't debugged it, but I'd guess the difference between compile and search is: we compile each project in its own scope, and from that perspective we never have more than one JRE on the build path at the same time. If search uses a workspace scope, however, this might happen, and then the code is not prepared for handling this ambiguity. 

If that's the root cause here, then I imagine that the topic of modules is only one prominent symptom of a situation that could also cause other havoc: 

E.g., when a project with a recent JRE uses a feature that is not present in an older JRE that is also used in the workspace. In a non-modular context we'd have no means to handle different versions of the same JRE class side-by-side, so perhaps unhappy selection among equal JRE classes could cause references to that new feature go unresolvable. This latter part is speculation, we'd need to check how generally such "conflict" of JRE versions is handled during search, e.g., by a closer look at the various `LookupEnvironment` instances you observed.

**Comment by trancexpress** [comment]
> I'm still looking from a distance, haven't debugged it, but I'd guess the difference between compile and search is: we compile each project in its own scope, and from that perspective we never have more than one JRE on the build path at the same time (because no JRE is exported from the project using it). If search uses a workspace scope, however, this might happen, and then the code is not prepared for handling this ambiguity.

Meanwhile I've reproduced this with normal libraries, not using JRE types. See: #726 

I thought that maybe re-exporting would result in the same problem during compile, that is how I ran into #729. The Java editor definitely has problems, but the compiler is fine. It seems to be aware of what is on the classpath and what is on the module path in a way that is better than the search (this also makes sense, since the compile knows which project its compiling... the search not quite).

The search sees a module conflict that doesn't exist. In the JRE 8 and JRE 11 case (since that is more simple to talk about) it takes everything from JRE 8 and assumes its in the unnamed module. Even though, 1) as you said, the JRE is not  re-exported and 2) the JRE 8 is on the classpath. It doesn't do anything with modules. `JavaSearchNameEnvironment.getModulesDeclaringPackage()` ignores the JRE 8 having no module information (due to not being on the module path).

**Comment by trancexpress** [comment]
If I make a jar from the referenced project (on the classpath) and add the jar on the classpath, there is a module conflict reported in the IDE. But not by `ecj`/`javac`. Opened: #730

**Comment by trancexpress** [comment]
OK, while browsing the internet to try to understand what should be in the unnamed module and what are module conflicts, I learned that what I assumed was an `ecj` bug in #730 is actually a `javac` bug.

So the problem here must be that the search environment is created in a way to run into the module conflict. The module conflict itself is expected at that point.

**Comment by trancexpress** [comment]
Odd, this seems to introduce #747. I was on the branch for this bug while reproducing (since I thought #747 might be fixed along with this one). But on current `master` #747 / https://bugs.eclipse.org/bugs/show_bug.cgi?id=553519 works fine (the part about JDK parameters in methods at least).
