### ISSUE TITLE
ecj reports module conflict compile error, javac doesn't

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#730]
To reproduce:

1. Import project from attached archive: [EclipseCompilerModuleConflictBug.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10716031/EclipseCompilerModuleConflictBug.zip)
2. Observe compile error: `The package testpackage is accessible from more than one module: <unnamed>, TestLibraryWithModule`
![eclipse_ide_module_conflict_compile_bug](https://user-images.githubusercontent.com/24752155/218312817-432bece3-41b5-4598-b08f-e85d6f4bd2a6.png)
4. Copy the source and libraries from the project to a separate directory, creating a structure like this:
```
.
|--cp/
|    |--TestLibraryOnClasspath.jar
|    |--TestLibraryUnnamedModule.jar
|--mp/
|    |--TestLibraryWithModule.jar
|--test1/
     |--Test1.java
```
5. Use `javac` and `java`, observe the code compiles and runs fine:
```
$ /usr/lib/jvm/java-17-openjdk/bin/javac --module-path mp/TestLibraryWithModule.jar -classpath cp/TestLibraryUnnamedModule.jar:cp/TestLibraryOnClasspath.jar test1/Test1.java
$ /usr/lib/jvm/java-17-openjdk/bin/java --module-path mp/TestLibraryWithModule.jar -classpath cp/TestLibraryUnnamedModule.jar:cp/TestLibraryOnClasspath.jar:. test1/Test1    
test done
```
6. Use `ecj` and `java`, observe the code compiles and runs fine:
```
$ /usr/lib/jvm/java-17-openjdk/bin/java -jar /data/eclipses/ecj-4.27M1.jar --module-path mp/TestLibraryWithModule.jar -classpath cp/TestLibraryUnnamedModule.jar:cp/TestLibraryOnClasspath.jar test1/Test1.java
$ /usr/lib/jvm/java-17-openjdk/bin/java --module-path mp/TestLibraryWithModule.jar -classpath cp/TestLibraryUnnamedModule.jar:cp/TestLibraryOnClasspath.jar:. test1/Test1
```

**Comment by trancexpress** [comment]
From what I can tell, this stack trace determines that the package is accessible from 2 modules:

```
"org.eclipse.jdt.internal.ui.text.JavaReconciler" #82 daemon prio=1 os_prio=0 cpu=385.08ms elapsed=408.54s tid=0x00007efe8a4ce690 nid=0xb0d6 at breakpoint [0x00007efcb9ffd000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.<init>(SplitPackageBinding.java:68)
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.combine(SplitPackageBinding.java:50)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getVisiblePackage(ModuleBinding.java:603)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getTopLevelPackage(ModuleBinding.java:551)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTopLevelPackage(LookupEnvironment.java:1686)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.getDefaultImports(CompilationUnitScope.java:712)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:241)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:516)
        at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:881)
        at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
        at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1038)
        at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1111)
        at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:282)
        at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:348)
        at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:193)
        at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
        at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1325)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
        at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
        at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
        at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
        at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

**Comment by trancexpress** [comment]
OK, for whatever reason `source` and `target` are not 17 per default. So `javac` does compile the code:

```
/usr/lib/jvm/java-17-openjdk/bin/javac -source 17 -target 17 --module-path mp/TestLibraryWithModule.jar -classpath cp/TestLibraryUnnamedModule.jar:cp/TestLibraryOnClasspath.jar test1/Test1.java
```

But `ecj` runs into the same problem as the Eclipse IDE:

```
$ /usr/lib/jvm/java-17-openjdk/bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000 -jar /data/eclipses/ecj-4.27M1.jar -source 17 -target 17 --module-path mp/TestLibraryWithModule.jar -classpath cp/TestLibraryUnnamedModule.jar:cp/TestLibraryOnClasspath.jar test1/Test1.java
Listening for transport dt_socket at address: 8000
----------
1. ERROR in /data/bugs/testmodular/test1/Test1.java (at line 3)
        import testpackage.TestClass;
               ^^^^^^^^^^^
The package testpackage is accessible from more than one module: <unnamed>, TestLibraryWithModule
----------
2. ERROR in /data/bugs/testmodular/test1/Test1.java (at line 13)
        TestClass t = new TestClass();
        ^^^^^^^^^
TestClass cannot be resolved to a type
----------
3. ERROR in /data/bugs/testmodular/test1/Test1.java (at line 13)
        TestClass t = new TestClass();
                          ^^^^^^^^^
TestClass cannot be resolved to a type
----------
3 problems (3 errors)
```

So this looks like a `ecj` bug.

**Comment by trancexpress** [comment]
Opened #734 for `ecj` behaving differently when `-source 17` is specified.

**Comment by trancexpress** [comment]
Actually when I look into the `javac` case that results in a compile error (a module library and a library without modules on the `--module-path`), the error is not about a conflict. Its about not being able to reach code in the library without modules:

```
$ /usr/lib/jvm/java-17-openjdk/bin/javac --module-path TestLibraryWithModule.jar:TestLibraryUnnamedModule.jar TestConflict.java 
TestConflict.java:3: error: package testpackage is not visible
        new testpackage.TestClass().foo();
            ^
  (package testpackage is declared in module TestLibraryUnnamedModule, which is not in the module graph)
1 error
```

The same error is seen if the `--module-path` has only the non-modular library:

```
➜  testconflictbug /usr/lib/jvm/java-17-openjdk/bin/javac --module-path TestLibraryUnnamedModule.jar TestConflict.java
TestConflict.java:3: error: package testpackage is not visible
        new testpackage.TestClass().foo();
            ^
  (package testpackage is declared in module TestLibraryUnnamedModule, which is not in the module graph)
1 error
```

**Comment by trancexpress** [comment]
OK, browsing Eclipse bugs I noticed several comments:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=560635#c1
https://bugs.eclipse.org/bugs/show_bug.cgi?id=545621#c1

Which lead to this bug:

https://bugs.openjdk.org/browse/JDK-8215739

So apparently `ecj` is right to report the module conflict, `javac` has a bug and does not report it.

**Comment by stephan-herrmann** [comment]
FYI, if you are interested in the latest twist of that old issue, have a look at my second answer on SO: https://stackoverflow.com/a/74890645/4611488 which then links back here https://github.com/eclipse-jdt/eclipse.jdt.core/issues/415#issuecomment-1256956523

**Comment by trancexpress** [comment]
> FYI, if you are interested in the latest twist of that old issue, have a look at my second answer on SO: https://stackoverflow.com/a/74890645/4611488 which then links back here [#415 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/415#issuecomment-1256956523)

Thanks, the modules are still new to me. I did try to search about why `javac` had no problem with the situation but found nothing, I get it now.
