### ISSUE TITLE
ecj doesn't detect module conflict without specifying -source

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#734]
To reproduce:

1. Put the attached jars and the following snippet in a directory:  [module_conflict_bug_example.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10722210/module_conflict_bug_example.zip)
```
public class TestConflict {
    public static void main(String[] args) {
        System.out.println(new testpackage.TestClass());
    }
}
```
2. Run `ecj` and then run the produced program, observe compile and execution are successful:
```
$ /usr/lib/jvm/java-17-openjdk/bin/java -jar /data/eclipses/ecj-4.27M1.jar --module-path TestLibraryWithModule.jar:TestLibraryUnnamedModule.jar TestConflict.java
$ /usr/lib/jvm/java-17-openjdk/bin/java -classpath TestLibraryModule.jar:TestLibraryUnnamedModule.jar:. TestConflict
testpackage.TestClass@277c0f21
```
3.  Run `javac`, observe the program doesn't compile (as expected, there is a module conflict for the type defined in both jars):
```
$ /usr/lib/jvm/java-17-openjdk/bin/javac --module-path TestLibraryWithModule.jar:TestLibraryUnnamedModule.jar TestConflict.java
TestConflict.java:3: error: package testpackage is not visible
        System.out.println(new testpackage.TestClass());
                               ^
  (package testpackage is declared in module TestLibraryUnnamedModule, which is not in the module graph)
1 error
```
4. Run `ecj` with `-source`, observe `ecj` now also detects the module conflict:
```
$ /usr/lib/jvm/java-17-openjdk/bin/java -jar /data/eclipses/ecj-4.27M1.jar -source 17 --module-path TestLibraryWithModule.jar:TestLibraryUnnamedModule.jar TestConflict.java
----------
1. ERROR in /data/bugs/testconflictbug/TestConflict.java (at line 3)
        System.out.println(new testpackage.TestClass());
                               ^^^^^^^^^^^
The package testpackage is accessible from more than one module: TestLibraryUnnamedModule, TestLibraryWithModule
----------
1 problem (1 error)
```

**Comment by trancexpress** [comment]
Note that `ecj` produces class version 61 when it doesn't detect the module conflict:

```
➜  testconflictbug /usr/lib/jvm/java-11-openjdk/bin/java -classpath TestLibraryModule.jar:TestLibraryUnnamedModule.jar:. TestConflict
Exception in thread "main" java.lang.UnsupportedClassVersionError: testpackage/TestClass has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at TestConflict.main(TestConflict.java:3)
```

**Comment by trancexpress** [comment]
Maybe there is some default here? I see this `source` value during the compile:

```
org.eclipse.jdt.core.compiler.source=1.3
```

```
"main" #1 prio=5 os_prio=0 cpu=157.90ms elapsed=108.90s tid=0x00007f01e4014c60 nid=0x5f3b runnable  [0x00007f01e85fe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(CompilerOptions.java:874)
        at org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(CompilerOptions.java:869)
        at org.eclipse.jdt.internal.compiler.batch.Main.validateOptions(Main.java:5540)
        at org.eclipse.jdt.internal.compiler.batch.Main.configure(Main.java:3055)
        at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1781)
        at org.eclipse.jdt.internal.compiler.batch.Main.main(Main.java:1521)
```

**Comment by trancexpress** [comment]
Seems fine then. `-source 1.3` sounds quite outdated as a default, but its documented and changing it is maybe not the best idea.
