### ISSUE TITLE
Call Hierarchy and references search don't see obvious references

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#740]
I'm baffled seeing following, using I20230213-1800 build with latest master state of related projects.

Preconditions: workspace with `org.eclipse.swt` and `org.eclipse.ui.ide.application` projects checked out.

1) Try to open Call Hierarchy on `org.eclipse.swt.graphics.Resource.nonDisposedReporter` field: **zero matches**.
2) Try to open Call Hierarchy on `org.eclipse.swt.graphics.Resource.setNonDisposeHandler(Consumer<Error>)` method: **zero matches**.
3) Try to search for references on `org.eclipse.swt.graphics.Resource.nonDisposedReporter` field: : **zero matches**
4) Try to search for **write** references on `org.eclipse.swt.graphics.Resource.nonDisposedReporter` field: : **zero matches**
5) Try to search for references on `org.eclipse.swt.graphics.Resource.setNonDisposeHandler(Consumer<Error>)` method: two **potential** matches.

![image](https://user-images.githubusercontent.com/964108/218682322-c0d31af4-e7fd-4622-b37e-4432df19163f.png)

This is insane! Sure there are **direct** matches for both the field and method!

Just to be sure, I've rebuilt JDT index and recompiled projects in question - with no change.

**Updated steps to reproduce**

1) Create java project referencing Java 9+ **without** module info file.
2) Change .classpath to remove "modular" attribute from container, like
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```
3) Paste this to the source folder:
```
import java.util.function.Consumer;
public class Z {
	private static Consumer<Error> field;
	private static class Inner {
		static {
			setField(e -> {});
		}
	}
	public static void setField(Consumer<Error> c) {
		field = c;
	}
}
```
Try Call Hierarchy or references search on `field` or `setField()`.

**Comment by trancexpress** [comment]
I wonder if we (or someone else) broke something recently?

I do see a call hierarchy for `Resource.nonDisposedReporter` with `I20230207-1800`. But not with `I20230211-0330`...

**Comment by iloveeclipse** [comment]
I can see the problem disappears if I revert changes on `JavaSearchNameEnvironment` to the state before 241f72191b9b592bdb9e4ba2af7cf4531acba8a3.

**Comment by iloveeclipse** [comment]
We should either fix that or revert 241f72191b9b592bdb9e4ba2af7cf4531acba8a3 for 4.27 M3 (this Thursday).

**Comment by iloveeclipse** [comment]
Note: **in the debugger** workspace I **additionally** see NPE's while doing reference search:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.env.IModule.isAutomatic()" because "module" is null
	at org.eclipse.jdt.internal.compiler.lookup.BinaryModuleBinding.create(BinaryModuleBinding.java:101)
	at org.eclipse.jdt.internal.compiler.impl.ITypeRequestor.accept(ITypeRequestor.java:65)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getModuleFromAnswer(LookupEnvironment.java:440)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:377)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:239)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:116)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:251)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getType(PackageBinding.java:205)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findType(Scope.java:2025)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3500)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3187)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:60)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveTypeArgument(TypeReference.java:638)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveLeafType(ParameterizedSingleTypeReference.java:264)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveType(ParameterizedSingleTypeReference.java:174)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.resolveType(ParameterizedSingleTypeReference.java:390)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypeFor(SourceTypeBinding.java:2627)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.fields(SourceTypeBinding.java:1550)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.internalFaultInTypeForFieldsAndMethods(SourceTypeBinding.java:1517)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1113)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:560)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2031)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1363)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1400)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1519)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.ui.search.JavaSearchQuery.run(JavaSearchQuery.java:178)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by trancexpress** [comment]
> I can see the problem disappears if I revert changes on `JavaSearchNameEnvironment` to the state before [241f721](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/241f72191b9b592bdb9e4ba2af7cf4531acba8a3).

Lets revert then. Though are you sure? I went further back and still see the problem.

**Comment by trancexpress** [comment]
I think we should add a test case too, but lets first fix the bug.

**Comment by iloveeclipse** [comment]
Simple steps to reproduce:
1) Create java project referencing Java 9+ **without** module info file.
2) Change .classpath to remove "modular" attribute from container, like
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```
3) Paste this to the source folder:
```
import java.util.function.Consumer;
public class Z {
	private static Consumer<Error> field;
	private static class Inner {
		static {
			setField(e -> {});
		}
	}
	public static void setField(Consumer<Error> c) {
		field = c;
	}
}
```
Try Call Hierarchy or references search on `field` or `setField()`.

**Comment by trancexpress** [comment]
> Simple steps to reproduce:

Did you mean to add this to the description? Or you mean something else with the comment?

**Comment by iloveeclipse** [comment]
> Or you mean something else with the comment?

I mean to provide "Simple steps to reproduce". Nothing else. It is way easier as to checkout two different projects from different git repos.
