### ISSUE TITLE
Handle JRE container when adding module class path info in Java search

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#748]
See #740 and the fix #746. Due to the missing module attribute for the JRE container (despite the JRE container being on the module path), we are forced to assume every container is on the module path.

We should look into the special handling JDT does for the JRE container and how to make the fix in #746 apply only for such containers (that JDT adds to the module path without a module attribute).

**Comment by trancexpress** [comment]
The build path page decides the JRE is on the module path with this stack trace:

```
"main" #1 prio=6 os_prio=0 cpu=7618.77ms elapsed=2454.16s tid=0x00007f6560015440 nid=0x3e19 runnable  [0x00007f65647fc000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.addModuleNodes(CPListElement.java:214)
        at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.<init>(CPListElement.java:178)
        at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:772)
        at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:710)
        at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.getCPListElements(BuildPathsBlock.java:446)
        at org.eclipse.jdt.internal.ui.wizards.buildpaths.BuildPathsBlock.init(BuildPathsBlock.java:341)
        at org.eclipse.jdt.internal.ui.preferences.BuildPathsPropertyPage.createWithJava(BuildPathsPropertyPage.java:170)
        at org.eclipse.jdt.internal.ui.preferences.BuildPathsPropertyPage.createContents(BuildPathsPropertyPage.java:88)
        at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:244)
        at org.eclipse.jdt.internal.ui.preferences.BuildPathsPropertyPage.createControl(BuildPathsPropertyPage.java:99)
        at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1434)
        at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1197)
```

With this code:

```
IModuleDescription module= fragmentRoots[0].getModuleDescription();
if (module != null && module.isSystemModule())
    addChildren= true;
```
