### ISSUE TITLE
Call Hierarchy crashes with AIOOBE in QualifiedTypeReference.getTypeBinding()

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#790]
Initially I've found strange that Call Hierarchy called on `org.eclipse.osgi.internal.module.MappedList.internal` showed no results - even if the field is referenced in the same class.
Then I've realized the search silently crashed with this stack in the error log:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.getTypeBinding(QualifiedTypeReference.java:133)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:634)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:630)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveSuperType(TypeReference.java:602)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.findSupertype(ClassScope.java:1673)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperclass(ClassScope.java:1176)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1454)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectMemberTypes(ClassScope.java:1143)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1464)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:394)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:521)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1338)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1400)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1519)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
	at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
	at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
	at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
	at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Then I've tried to reproduce in the debugger and failed.
After some digging I could reproduce that error in a fresh workspace that has **two** JRE's configured - Java 8 and Java 17, and with two simple projects, each configured to use distinct JRE. 
- Add "Java 8" project to the classpath (or modulepath) of the "Java 17" project
- Put this code to the Java 8 project src directory: 
```
import java.util.HashMap;

public class X {
	protected final HashMap<?, ?> internal; // call hierarchy crashes (if field is protected)
	protected final HashMap<?, ?> map; // call hierarchy always works

	public X() {
		internal = new HashMap<>();
		map = internal;
	}
}
```
- Open Call Hierarchy on `internal` field => KABOOM.
- Interesting observation: the field name makes difference! Call Hierarchy on the same kind of field just called `map` works fine.
- In debugger one can see that we have again split package problem for the `java.lang` package!
- But we don't have **any** source defining that package in the workspace - both are defined in respective JRE's.

Workaround (not fixing the root cause which is to understand first):
```
diff --git a/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/QualifiedTypeReference.java b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/QualifiedTypeReference.java
index 856fe9c..d1e4e08 100644
--- a/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/QualifiedTypeReference.java
+++ b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/QualifiedTypeReference.java
@@ -132,3 +132,8 @@
 	    			SplitPackageBinding splitPackage = (SplitPackageBinding) uniquePackage;
-	    			scope.problemReporter().conflictingPackagesFromModules(splitPackage, scope.module(), this.sourceStart, (int)this.sourcePositions[typeStart-1]);
+	    			if(typeStart-1 >= this.sourcePositions.length) {
+	    				this.resolvedType = new ProblemReferenceBinding(this.tokens, null, ProblemReasons.Ambiguous);
+	    				return null;
+	    			}
+	    			int sourceEnd2 = (int)this.sourcePositions[typeStart-1];
+					scope.problemReporter().conflictingPackagesFromModules(splitPackage, scope.module(), this.sourceStart, sourceEnd2);
 	    			this.resolvedType = new ProblemReferenceBinding(this.tokens, null, ProblemReasons.Ambiguous);
```

**Comment by iloveeclipse** [comment]
Projects to play with: [issue_790_projects.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10827272/issue_790_projects.zip)

@trancexpress : FYI.

**Comment by trancexpress** [comment]
The `SplitPackageBinding` is created while indexing JRE classes in the Java 17 project. I'm not sure why its being indexed, as it shouldn't be on the search path. Possibly its due to the workspace scope for the search, as that scope includes also the Java 17 project. The stack trace for creating the `SplitPackageBinding` is:

```
"Worker-3: Fetching children of internal" #59 prio=5 os_prio=0 cpu=2112.62ms elapsed=527.31s tid=0x00007f0f88001670 nid=0x2b72 at breakpoint [0x00007f0fc02fc000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.<init>(SplitPackageBinding.java:68)
        at org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.combine(SplitPackageBinding.java:50)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.combineWithPackagesFromOtherRelevantModules(ModuleBinding.java:670)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getVisiblePackage(ModuleBinding.java:614)
        at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getTopLevelPackage(ModuleBinding.java:551)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.computePackageFrom(LookupEnvironment.java:757)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:259)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1735)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.problemType(Scope.java:3134)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getPackage(Scope.java:3106)
        at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.getTypeBinding(QualifiedTypeReference.java:111)
        at org.eclipse.jdt.internal.compiler.ast.JavadocQualifiedTypeReference.internalResolveType(JavadocQualifiedTypeReference.java:58)
        at org.eclipse.jdt.internal.compiler.ast.JavadocQualifiedTypeReference.resolveType(JavadocQualifiedTypeReference.java:112)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:630)
        at org.eclipse.jdt.internal.compiler.ast.Javadoc.resolveReference(Javadoc.java:446)
        at org.eclipse.jdt.internal.compiler.ast.Javadoc.resolve(Javadoc.java:273)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1513)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1622)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1397)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1622)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1397)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:667)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2032)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1362)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1399)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1541)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
        at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
        at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by trancexpress** [comment]
Odd, the error is seen also when the Java 17 project doesn't reference the Java 8 project.

**Comment by iloveeclipse** [comment]
> Odd, the error is seen also when the Java 17 project doesn't reference the Java 8 project.

In a new workspace, or existing one?

**Comment by trancexpress** [comment]
> In a new workspace, or existing one?

Clean (new) workspace, newly imported (after changing the Java 17 project and exporting both to a zip) and after a clean build (if that makes a difference for the indexer).

**Comment by trancexpress** [comment]
The `QualifiedTypeReference` causing the exception is created with this stack trace:

```
"Worker-14: Fetching children of internal" #88 prio=5 os_prio=0 cpu=5176.56ms elapsed=4347.21s tid=0x00007f14a409cab0 nid=0x233d at breakpoint [0x00007f14bfcfd000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.<init>(QualifiedTypeReference.java:29)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRecordDeclaration(Parser.java:11206)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7387)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13152)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13407)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13364)
        at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11750)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.parseAndBuildBindings(MatchLocator.java:1942)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1299)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1400)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1542)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
        at org.eclipse.jdt.internal.corext.callhierarchy.CallerMethodWrapper.findChildren(CallerMethodWrapper.java:155)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.performSearch(MethodWrapper.java:266)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.doFindChildren(MethodWrapper.java:197)
        at org.eclipse.jdt.internal.corext.callhierarchy.MethodWrapper.getCalls(MethodWrapper.java:88)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.getCalls(DeferredMethodWrapper.java:70)
        at org.eclipse.jdt.internal.ui.callhierarchy.DeferredMethodWrapper.fetchDeferredChildren(DeferredMethodWrapper.java:78)
        at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:219)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The code is:

```
	TypeReference superClass = new QualifiedTypeReference(TypeConstants.JAVA_LANG_RECORD, new long[] {0});
	superClass.bits |= ASTNode.IsSuperType;
	typeDecl.superclass = superClass;
```


It was added for: https://bugs.eclipse.org/bugs/show_bug.cgi?id=558343
Commit is: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/000ab51015adb5b5d88d38ccbfa78e41777fbda8
And in particular this part: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/000ab51015adb5b5d88d38ccbfa78e41777fbda8#diff-f433fb6b2d6da39370e49994c0170bad309a3a5a2ede0dafce3404adfa21a1a1


`TypeConstants.JAVA_LANG_RECORD` has length 3, which doesn't match the length of the 2nd argument to the constructor of `QualifiedTypeReference`.

```
char[][] JAVA_LANG_RECORD = {JAVA, LANG, RECORD_CLASS};
```

From what I can tell, it was always with length 3. I.e. the code code in `QualifiedTypeReference.getTypeBinding(Scope)` must have always been broken due to it.

https://github.com/eclipse-jdt/eclipse.jdt.core/commit/1274842e69404e830c473943e03e17daad328a73#diff-849db7bf93cd735ee96709b8a58b241fd0b1b3fcee5e95501f1670a489359449

I'll see if I can create a reproducer that doesn't depend on the JRE. Might be difficult though, since the JRE itself has an example that breaks this code (so its hard to tell if the call hierarchy broke because of the JRE code or the user code).
