### ISSUE TITLE
No completion on generic anonymous class instance objects

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#802]
```
ArrayList field = new ArrayList() {}.|
```

No completions are shown.

But if the ArrayList is replaced with a non final non generic class, the completions work.

**Comment by gayanper** [comment]
@snjeza were you working on something similar ?

**Comment by snjeza** [comment]
@gayanper No, I wasn't. I will try it now.

**Comment by snjeza** [comment]
@gayanper I can't reproduce the issue in the jdt.core master branch.

![802](https://user-images.githubusercontent.com/388609/221923881-781f6487-b882-4fc2-9255-cb6e718feff7.gif)

**Comment by gayanper** [comment]
I will try with the master then and get back to here.

**Comment by gayanper** [comment]
Seems like its working in JDT master, will report this to jdt.ls since found in vscode java.

**Comment by snjeza** [comment]
The issue can be reproduced when apply the for template.
![2508](https://user-images.githubusercontent.com/388609/222484113-dbef7a4f-7ab4-4063-9b13-70abaf595d1b.gif)

Eclipse reports the following exception:
```
!ENTRY org.eclipse.ui 4 0 2023-03-02 02:13:50.678
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: slave can only serve one master
	at org.eclipse.jdt.internal.ui.text.template.contentassist.MultiVariableGuess.addDependency(MultiVariableGuess.java:280)
	at org.eclipse.jdt.internal.corext.template.java.JavaContext.addDependency(JavaContext.java:150)
	at org.eclipse.jdt.internal.corext.template.java.TypeResolver.resolve(TypeResolver.java:58)
	at org.eclipse.jdt.internal.corext.template.java.ActualTypeResolver.resolve(ActualTypeResolver.java:90)
	at org.eclipse.jface.text.templates.TemplateContextType.resolve(TemplateContextType.java:276)
	at org.eclipse.jface.text.templates.TemplateContextType.resolve(TemplateContextType.java:243)
	at org.eclipse.jdt.internal.corext.template.java.JavaContextCore.evaluate(JavaContextCore.java:157)
	at org.eclipse.jdt.internal.corext.template.java.JavaContext.evaluate(JavaContext.java:107)
	at org.eclipse.jdt.internal.corext.template.java.JavaPostfixContext.evaluate(JavaPostfixContext.java:412)
	at org.eclipse.jdt.internal.ui.text.template.contentassist.TemplateProposal.getAdditionalProposalInfo(TemplateProposal.java:447)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$4.lambda$0(AdditionalInfoController.java:183)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
See https://github.com/eclipse/eclipse.jdt.ls/pull/2508#issuecomment-1451110809
