### ISSUE TITLE
ReconcilerTests.testBug36032* need the indexer

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#82]
Running ReconcilerTests in isolation (i.e., outside AllJavaModelTests) hangs in testBug36032a(), stacktrace is:
```
        at java.lang.Thread.sleep(java.base@11.0.2/Native Method)
        at org.eclipse.jdt.core.tests.model.ReconcilerTests.assertNoProblem(ReconcilerTests.java:191)
        at org.eclipse.jdt.core.tests.model.ReconcilerTests.testBug36032a(ReconcilerTests.java:3921)
```

In the debugger I can see four jobs in `JobManager#awaitingJobs`, but due to `TestCase#indexDisabledForTest` being true, the index manager is disabled in `setUp()`.

**Comment by stephan-herrmann** [comment]
Similar (?) hang inWorkingCopyOwnerTests :
```
"main" #1 prio=5 os_prio=0 cpu=5267,33ms elapsed=73,04s tid=0x00007fe290012800 nid=0x584d in Object.wait()  [0x00007fe294ee0000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.2/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:284)
        - waiting to re-lock in wait() <0x000000074811f530> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.legacySearchAllPossibleSubTypes(IndexBasedHierarchyBuilder.java:605)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.searchAllPossibleSubTypes(IndexBasedHierarchyBuilder.java:506)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.determinePossibleSubTypes(IndexBasedHierarchyBuilder.java:465)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:158)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:323)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1319)
        - locked <0x0000000749f10f80> (a org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy)
        at org.eclipse.jdt.internal.core.CreateTypeHierarchyOperation.executeOperation(CreateTypeHierarchyOperation.java:94)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
        at org.eclipse.jdt.internal.core.SourceType.newTypeHierarchy(SourceType.java:950)
        at org.eclipse.jdt.core.tests.model.WorkingCopyOwnerTests.testHierarchy(WorkingCopyOwnerTests.java:939)
```

**Comment by stephan-herrmann** [comment]
SearchParticipantTests:
```
"main" #1 prio=5 os_prio=0 cpu=5953,35ms elapsed=30,49s tid=0x00007f10c0012800 nid=0x593f in Object.wait()  [0x00007f10c6495000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.2/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:284)
        - waiting to re-lock in wait() <0x0000000747dcb530> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllTypeNames(BasicSearchEngine.java:1923)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllTypeNames(BasicSearchEngine.java:1751)
        at org.eclipse.jdt.core.search.SearchEngine.searchAllTypeNames(SearchEngine.java:1100)
        at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.waitUntilIndexesReady(AbstractJavaModelTests.java:4009)
        at org.eclipse.jdt.core.tests.model.SearchParticipantTests.testIndexDocument01(SearchParticipantTests.java:228)
```

**Comment by stephan-herrmann** [comment]
JavaElement8Tests:
```
"main" #1 prio=5 os_prio=0 cpu=13235,02ms elapsed=105,62s tid=0x00007ff9f4012800 nid=0x7432 in Object.wait()  [0x00007ff9f8803000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.2/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:284)
        - waiting to re-lock in wait() <0x0000000747da6920> (a org.eclipse.jdt.internal.core.search.indexing.IndexManager)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.legacySearchAllPossibleSubTypes(IndexBasedHierarchyBuilder.java:605)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.searchAllPossibleSubTypes(IndexBasedHierarchyBuilder.java:506)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.determinePossibleSubTypes(IndexBasedHierarchyBuilder.java:465)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:158)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:323)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1319)
        - locked <0x000000074fa36988> (a org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy)
        at org.eclipse.jdt.internal.core.CreateTypeHierarchyOperation.executeOperation(CreateTypeHierarchyOperation.java:94)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
        at org.eclipse.jdt.internal.core.SourceType.newTypeHierarchy(SourceType.java:950)
        at org.eclipse.jdt.internal.core.SourceType.newTypeHierarchy(SourceType.java:907)
        at org.eclipse.jdt.core.tests.model.JavaElement8Tests.test429966(JavaElement8Tests.java:284)
```

**Comment by stephan-herrmann** [comment]
@iloveeclipse  are these examples of more work needed relating to `indexDisabledForTest`?

Background: whenever I see lack of isolation between tests (tests passing standalone but failing in the suite) I tend to bisect the list of tests in a suite. Every now and then fairly arbitrary subsets of tests reveal more dependencies/interaction between tests.

**Comment by iloveeclipse** [comment]
Most likely, yes.
