### ISSUE TITLE
Incomplete type hierarchy when using method reference

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#830]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=560545

To reproduce, compute the type hierarchy of `TestInterface` in the following snippet:

```
public class TestClass {

	interface TestInterface {
		void testMethod();
	}

	public TestInterface ti1 = TestClass.this::testMethod;
	public TestInterface ti2 = () -> testMethod();
	public TestInterface ti3 = new TestInterface() {
		public void testMethod() {
			TestClass.this.testMethod();
		}
	};

	public void testMethod() {
		System.out.println("TestClass.testMethod()");
	}

	public static void main(String[] args) {
		TestClass t = new TestClass();
		t.ti1.testMethod();
		t.ti2.testMethod();
		t.ti3.testMethod();
	}
}
```

Observe that no implementer is found for the method reference. Only for the lambda and the anonymous type.

**Comment by trancexpress** [comment]
Example stack trace when a subtype is found (the lambda):

```
"Worker-10: Computing type hierarchy of 'TestInterface - test.TestClass'..." #127 prio=5 os_prio=0 cpu=242.52ms elapsed=1052.78s tid=0x00007f50f0001670 nid=0xafcd at breakpoint [0x00007f512c1fe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.addSubtype(TypeHierarchy.java:232)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.cacheSuperclass(TypeHierarchy.java:285)
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyBuilder.connect(HierarchyBuilder.java:180)
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.reportHierarchy(HierarchyResolver.java:607)
        at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.resolve(HierarchyResolver.java:894)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildForProject(IndexBasedHierarchyBuilder.java:265)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildFromPotentialSubtypes(IndexBasedHierarchyBuilder.java:376)
        at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:166)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:323)
        at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1319)
        - locked <0x000000062bc21430> (a org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle.doHierarchyRefresh(TypeHierarchyLifeCycle.java:331)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle.doHierarchyRefreshBackground(TypeHierarchyLifeCycle.java:272)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyLifeCycle$1.run(TypeHierarchyLifeCycle.java:225)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

`HierarchyResolver.typeBindings` is being iterated over in `HierarchyResolver.reportHierarchy()`, it doesn't contain anything about the method reference.

**Comment by trancexpress** [comment]
Would be good if we also take care of or make progress towards this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=539602
