### ISSUE TITLE
Autocomplete blows up when trying to list the members for java.util.Optional.of(true ? 0 : "")

### ISSUE THREAD

**Issue by yeah-boi** [eclipse-jdt/eclipse.jdt.core#831]
Autocomplete blows up when trying to list the members for:

`java.util.Optional.of(true ? 0 : "")`

See the following image:

![image](https://user-images.githubusercontent.com/30007588/224806588-293928d8-6da0-4c7d-95f9-973a59e25c54.png)

I'm using the following version:

Version: 2022-12 (4.26.0)
Build id: 20221201-1913

**Comment by trancexpress** [comment]
```
java.lang.UnsupportedOperationException
	at org.eclipse.jdt.internal.compiler.lookup.IntersectionTypeBinding18.getPackage(IntersectionTypeBinding18.java:142)
	at org.eclipse.jdt.internal.compiler.lookup.TypeBinding.qualifiedPackageName(TypeBinding.java:1571)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findLocalMethods(CompletionEngine.java:9606)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findMethods(CompletionEngine.java:10964)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findFieldsAndMethods(CompletionEngine.java:7701)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnMemberAccess(CompletionEngine.java:3195)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2027)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2346)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:136)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:367)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:357)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalComputeCompletionProposals(JavaCompletionProposalComputer.java:256)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeCompletionProposals(JavaCompletionProposalComputer.java:218)
	at org.eclipse.jdt.internal.ui.text.java.JavaTypeCompletionProposalComputer.computeCompletionProposals(JavaTypeCompletionProposalComputer.java:65)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:348)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:333)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by yeah-boi** [comment]
Another minimal test case: Listing methods for `java.util.Optional.of(f(0, ""))` also blows up, if `f` is defined as `private static <T, U> T f(T t1, T t2) { return null; }`.

**Comment by trancexpress** [comment]
For the information below, the type hierarchy looks like this: `IntersectionTypeBinding18` extends `ReferenceBinding` extends `TypeBinding`

Considering `IntersectionTypeBinding18.getPackage()` throwing `UnsupportedOperationException` and `TypeBinding.qualifiedPackageName()` calling `TypeBinding.getPackage()`, from my POV its an oversight that `IntersectionTypeBinding18` doesn't override `qualifiedPackageName()` to do nothing. That or every caller should be aware of `IntersectionTypeBinding18` and do nothing instead of calling `qualifiedPackageName()`... which seems unrealistic.

I'll try to add a test and I'll open a PR to see if test fail with this proposal.

**Comment by iloveeclipse** [comment]
@trancexpress, @gayanper : please don't forget to set milestone and assignee after closing issues. This simplifies maintenance later (to see in which release which bug was fixed and whom to ask if some regression happens).

**Comment by trancexpress** [comment]
> @trancexpress, @gayanper : please don't forget to set milestone and assignee after closing issues. This simplifies maintenance later (to see in which release which bug was fixed and whom to ask if some regression happens).

Is there some page that lists the milestones and their time frames?

**Comment by iloveeclipse** [comment]
Go to issues page, there is a link to milestones, like https://github.com/eclipse-jdt/eclipse.jdt.core/milestones

But you see same list on each issue too, under "milestones" button.
