### ISSUE TITLE
Unexpected cast compile error for generic type argument

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#837]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=562230

To reproduce, paste the following snippet in Eclipse:

```
package test;

import java.util.Collections;
import java.util.List;

public class Test {

	public static <Z extends Comparable<? super Z>> String test(List<Z> in) {
		List<String> x = (List<String>) in;
		return x.get(0);
	}

    public static void main(String[] args) {
        List<String> list = Collections.singletonList("hello");
        String string = Test.<String>test(list);
        System.out.println(string);
    }
}
```

Compile and run with `javac`/`java` (OpenJDK 17), observe no errors:

```
➜  src /usr/lib/jvm/java-17-openjdk/bin/javac test/Test.java
Note: test/Test.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
```
➜  src /usr/lib/jvm/java-17-openjdk/bin/java test.Test      
hello
```

With `ecj`/Eclipse though, observe compile error:

```
Description	Resource	Path	Location	Type
Cannot cast from List<Z> to List<String>	Test.java	/TestBug562230/src/test	line 9	Java Problem
```

The problem is created here:

```
"org.eclipse.jdt.internal.ui.text.JavaReconciler" #82 daemon prio=1 os_prio=0 cpu=1512.91ms elapsed=1783.09s tid=0x00007f381e1e6bb0 nid=0x1251 at breakpoint [0x00007f377cae6000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:130)
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2679)
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.typeCastError(ProblemReporter.java:8542)
        at org.eclipse.jdt.internal.compiler.ast.CastExpression.resolveType(CastExpression.java:676)
        at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
        at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1506)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
        at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1069)
        at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1111)
        at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:282)
        at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:348)
        at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:193)
        at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
        at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1325)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
        at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
        at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
        at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
        at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

Changing the generics type argument to `Z extends Comparable<? extends Z>` results in no compile error with `ecj`.

**Comment by trancexpress** [comment]
The cast is determined to be between "provably distinct" types by this stack trace:

```
"Compiler Processing Task" #212 daemon prio=5 os_prio=0 cpu=34.46ms elapsed=83.57s tid=0x00007f35fc002a90 nid=0x2563 runnable  [0x00007f36126fc000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.TypeBinding.isProvablyDistinct(TypeBinding.java:943)
        at org.eclipse.jdt.internal.compiler.ast.CastExpression.checkUnsafeCast(CastExpression.java:416)
        at org.eclipse.jdt.internal.compiler.ast.CastExpression.checkUnsafeCast(CastExpression.java:400)
        at org.eclipse.jdt.internal.compiler.ast.Expression.checkCastTypesCompatibility(Expression.java:462)
        at org.eclipse.jdt.internal.compiler.ast.CastExpression.resolveType(CastExpression.java:654)
        at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:390)
        at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:259)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1506)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:905)
        at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
        at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)
```

**Comment by trancexpress** [comment]
Makes me wonder what `ecj` does for the method invocation. It must be something else since it allows the method invocation with `String` (but according to the cast expression, `String` is not an allowed type... which is wrong).

**Comment by stephan-herrmann** [comment]
FYI, cast compatibility is specified in [JLS 5.1.6.1](https://docs.oracle.com/javase/specs/jls/se19/html/jls-5.html#jls-5.1.6.1) which refers to the definition of "provably distinct" inside [JLS 4.5](https://docs.oracle.com/javase/specs/jls/se19/html/jls-4.html#jls-4.5). 

Here's a group of bugs that motivated our existing code:
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=158870
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=89940
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=90437

Apparently, Philipe was struggling with a fuzzy spec and worked from additional information about intended spec changes. 

To find out the intended semantics it should be worth looking into https://bugs.openjdk.org/browse/JDK-6790039 and children. E.g., Mauricio mentions replacing captures with wildcards as essential in javac's implementation, which is absent from the spec as far as I can see.

**Comment by stephan-herrmann** [comment]
A recent hint from https://mail.openjdk.org/pipermail/compiler-dev/2025-February/029342.html :

>  Note that capture conversion is always problematic when it comes to cast expressions -- because the cast has to "relax" some of the captured variable that might be introduced by capture conversion. This is an area of the specification that is underspecified, so javac (and other implementations) have to workaround such issues the best they can.

See also https://bugs.openjdk.org/browse/JDK-8349857

In my book this should be fixed in JLS first. Any changes we'd make here, even if they bring us closer to javac _for this example_, might actually introduce new differences for other cases.  Ergo, we'd need very solid "common-sense" reasoning for any change, and common sense is always tricky to achieve when it comes to `<? super X>` in particular.
