### ISSUE TITLE
DeduplicationUtilTest fails randomly

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#86]
See 

* https://download.eclipse.org/eclipse/downloads/drops4/I20220516-0600/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
* https://download.eclipse.org/eclipse/downloads/drops4/I20220515-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
* https://download.eclipse.org/eclipse/downloads/drops4/I20220514-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-win32-java11_win32.win32.x86_64_11.html
* https://download.eclipse.org/eclipse/downloads/drops4/I20220513-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-win32-java11_win32.win32.x86_64_11.html
* May be more, haven't checked

I believe I've saw it also failing in some gerrit recently.

```
expected same:<[aNeverUsedBefore]> was not:<[aNeverUsedBefore]>

junit.framework.AssertionFailedError: expected same:<[aNeverUsedBefore]> was not:<[aNeverUsedBefore]>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotSame(Assert.java:325)
at junit.framework.Assert.assertSame(Assert.java:288)
at junit.framework.Assert.assertSame(Assert.java:296)
at junit.framework.TestCase.assertSame(TestCase.java:434)
at org.eclipse.jdt.core.tests.compiler.DeduplicationUtilTest.assertDeduplicationObject(DeduplicationUtilTest.java:108)
at org.eclipse.jdt.core.tests.compiler.DeduplicationUtilTest.testDeduplication(DeduplicationUtilTest.java:40)
```

I assume the GC isn't executed yet, so it is still returns previously cached but yet not GC released object.
May be some extra wait time could help. I will push a PR.

**Comment by jarthana** [comment]
Verified by code inspection. Looks good to me.

**Comment by iloveeclipse** [comment]
Still there in https://download.eclipse.org/eclipse/downloads/drops4/I20220523-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
expected same:<[aNeverUsedBefore]> was not:<[aNeverUsedBefore]>

junit.framework.AssertionFailedError: expected same:<[aNeverUsedBefore]> was not:<[aNeverUsedBefore]>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotSame(Assert.java:325)
at junit.framework.Assert.assertSame(Assert.java:288)
at junit.framework.Assert.assertSame(Assert.java:296)
at junit.framework.TestCase.assertSame(TestCase.java:434)
at org.eclipse.jdt.core.tests.compiler.DeduplicationUtilTest.assertDeduplicationObject(DeduplicationUtilTest.java:105)
at org.eclipse.jdt.core.tests.compiler.DeduplicationUtilTest.testDeduplication(DeduplicationUtilTest.java:40)
```

**Comment by iloveeclipse** [comment]
I **believe** this is Java 11 specific issue, due the bug in GC there. I think we could disable the test for Java 11.

**Comment by akurtakov** [comment]
We don't run Java 11 tests on Mac so it's probably time to switch Windows to Java 17 too.

**Comment by iloveeclipse** [comment]
> We don't run Java 11 tests on Mac so it's probably time to switch Windows to Java 17 too.

This would not help, the fail was on Linux/11 build

**Comment by akurtakov** [comment]
So it's time to stop testing on Java 11. After all Equinox still has 1.8 BREE but we don't run I-build tests on Java 11. That would have the extra effect of giving some room for tests on the releng jipp.

**Comment by akurtakov** [comment]
Furthermore all EPPs are shipping with Java 17. Having less unstable tests is critical if we want tests to be taken more seriously.

**Comment by iloveeclipse** [comment]
> Now that tests are not run on Java 11 anymore should this one be closed?

Yes, seem to be quiet last few builds. Let's close.
