### ISSUE TITLE
Field assignment to anonymous type breaks selection

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#860]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=430605#c31

Snippet:

```
package eclipse_bug;

public class CurrentTextSelectionCannotBeOpened {
	public static class Super {
		public boolean boolMethod(){return true;}
	}

	Object obj;
	public boolean somecode(){
		obj=new Object(){
			public boolean somecode(){
				Super sup=new Super();
				return sup.boolMethod();
			}
		};
		return false;
	}
}
```

Select `eclipse_bug.CurrentTextSelectionCannotBeOpened.Super.boolMethod()` use F3, observe status error at bottom left and F3 not navigating to the type.

**Comment by trancexpress** [comment]
I see this exception:

```
org.eclipse.jdt.internal.codeassist.select.SelectionNodeFound
	at org.eclipse.jdt.internal.codeassist.select.SelectionOnMessageSend.resolveType(SelectionOnMessageSend.java:111)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1113)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1506)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1086)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
	at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Probably due to this `ProblemReferenceBinding` for `sup`:

```
"Text Viewer Hover Presenter" #157 daemon prio=1 os_prio=0 cpu=3.63ms elapsed=36.60s tid=0x00007f8526c05570 nid=0x19a69 at breakpoint [0x00007f837c2fd000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.lookup.ProblemReferenceBinding.<init>(ProblemReferenceBinding.java:29)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3564)
        at org.eclipse.jdt.internal.compiler.lookup.Scope.getBinding(Scope.java:2291)
        at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.resolveType(SingleNameReference.java:1020)
        at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:739)
        at org.eclipse.jdt.internal.codeassist.select.SelectionOnMessageSend.resolveType(SelectionOnMessageSend.java:101)
        at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1113)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:662)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:388)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:571)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1506)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1631)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:668)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1086)
        at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
        at org.eclipse.jdt.internal.ui.text.java.hover.AbstractJavaEditorTextHover.getJavaElementsAt(AbstractJavaEditorTextHover.java:121)
        at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.internalGetHoverInfo(JavadocHover.java:662)
        at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo2(JavadocHover.java:658)
        at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
        at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
        at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
        at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

**Comment by trancexpress** [comment]
Comparing those 2 cases seems to be the easiest option:

```
	public boolean somecode(){
		new Object(){
			public boolean somecode(){
				Super sup=new Super();
				return sup.boolMethod();
			}
		};
		return false;
	}
```
(selection works)

```
	public boolean somecode(){
		obj=new Object(){
			public boolean somecode(){
				Super sup=new Super();
				return sup.boolMethod();
			}
		};
		return false;
	}
```
(selection doesn't work)

At this call, the parser stacks are in the same state:

```
"ModalContext" #704 prio=6 os_prio=0 cpu=2.64ms elapsed=18.68s tid=0x00007f0dea0e1640 nid=0xe390 at breakpoint [0x00007f0bd7bfe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.parser.Parser.classInstanceCreation(Parser.java:1358)
        at org.eclipse.jdt.internal.codeassist.select.SelectionParser.classInstanceCreation(SelectionParser.java:330)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeClassInstanceCreationExpression(Parser.java:2793)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7980)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13156)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:2100)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:1940)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:349)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:312)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1081)
        at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

`Parser.astPtr` is `-1` is and `Parser.astStack` is:

```
[
{
  public boolean somecode() {
    Super sup;
    return <SelectOnMessageSend:sup.boolMethod()>;
  }
},
public boolean somecode() {
  Super sup;
  return <SelectOnMessageSend:sup.boolMethod()>;
},
Super sup;,
return <SelectOnMessageSend:sup.boolMethod()>;
]
```

In the broken seclection case, `astPtr` is not changed anymore until this code is reacheed:

```
"ModalContext" #704 prio=6 os_prio=0 cpu=2.71ms elapsed=151.35s tid=0x00007f0dea0e1640 nid=0xe390 at breakpoint [0x00007f0bd7bfe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.buildInitialRecoveryState(AssistParser.java:251)
        at org.eclipse.jdt.internal.compiler.parser.Parser.resumeOnSyntaxError(Parser.java:14533)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13062)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:2100)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:1940)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:349)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:312)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1081)
        at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

And so the bad block is set for the selection evaluation.

In the working selection case, there is an extra call that sets `astPtr` to `0` (and so `AssistParser.buildInitialRecoveryState()` creates the full block for the selection):

```
"ModalContext" #721 prio=6 os_prio=0 cpu=2.88ms elapsed=63.95s tid=0x00007f0dea0f4970 nid=0xe651 at breakpoint [0x00007f0bd7dfe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.parser.Parser.setAstPtr(Parser.java:14787)
        at org.eclipse.jdt.internal.compiler.parser.Parser.pushOnAstStack(Parser.java:13940)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeExpressionStatement(Parser.java:4290)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7604)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13156)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:2100)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:1940)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:349)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:312)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1081)
        at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

The assignment `obj=` is parsed as an expression and is not part of  `astStack`, apparently:

```
"ModalContext" #757 prio=6 os_prio=0 cpu=9.62ms elapsed=28.49s tid=0x00007f0deaf13f60 nid=0xecb6 runnable  [0x00007f0bd7bfe000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeAssignment(Parser.java:1925)
        at org.eclipse.jdt.internal.codeassist.select.SelectionParser.consumeAssignment(SelectionParser.java:961)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:8296)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13156)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:2100)
        at org.eclipse.jdt.internal.codeassist.impl.AssistParser.parseBlockStatements(AssistParser.java:1940)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:349)
        at org.eclipse.jdt.internal.codeassist.impl.Engine.parseBlockStatements(Engine.java:312)
        at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:1081)
        at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
        at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter.codeResolve(SelectionConverter.java:270)
        at org.eclipse.jdt.internal.ui.actions.SelectionConverter$1CodeResolveRunnable.run(SelectionConverter.java:254)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

But the codde for expressions in `AssistParser.buildInitialRecoveryState()` does nothing with the assignment:

```
	// This is  copy of the code that processes astStack early in this method
	for (int i = 0; i <= this.expressionPtr; i++, lastNode = node) {
		node = this.expressionStack[i];
		if (node == null || !(node instanceof InstanceOfExpression)) continue;
```

I'm guessing we must add handling for expressions here.

**Comment by srikanth-sankaran** [comment]
This problem goes away with the commit  8cbe978792d366f6f792053f082b9fa2179056d4 that addressed a whole slew of defects 
(#1195, #769, #1263, #1360,  #1364,  #1278,  #1288) - I'll release a test case for the snippet from the problem description and close this defect.

For the record, the recovered parse tree now is
```
  public boolean somecode() {
    new Object() {
      public boolean somecode() {
        Super sup;
        return <SelectOnMessageSend:sup.boolMethod()>;
      }
    };
  }
```

**Comment by srikanth-sankaran** [comment]
Regression  test to verify right behavior here: https://github.com/srikanth-sankaran/eclipse.jdt.core/commit/574f4bf22d8bc5a5b5c4bf060199097d0c796dc5
