### ISSUE TITLE
[20] Internal error "info cannot be null" for nested generic record patterns (preview feature)

### ISSUE THREAD

**Issue by howlger** [eclipse-jdt/eclipse.jdt.core#900]
[_Java 20 Support for Eclipse 2023-03 (4.27)_](https://marketplace.eclipse.org/content/java-20-support-eclipse-2023-03-427) (version 1.2.300.v20230322-1359_BETA_JAVA20) with enabled preview features causes internal errors for record patterns that are both nested and generic.

Example taken from [JEP 432](https://openjdk.org/jeps/432):

```java
class Sample {

	record Box<T>(T t) {}
	
	// no issues
	static void test1(Box<String> bo) {
		if (bo instanceof Box<String>(var s)) {
			System.out.println("String " + s);
		}
	}
	
	// no issues
	static void test2(Box<String> bo) {
	    if (bo instanceof Box(var s)) {    // Inferred to be Box<String>(var s)
	        System.out.println("String " + s);
	    }
	}
	
	// "Errors occurred during the build": "info cannot be null"
	static void test3(Box<Box<String>> bo) {
	    if (bo instanceof Box<Box<String>>(Box(var s))) {    
	        System.out.println("String " + s);
	    }
	}
	
	// "Errors occurred during the build": "info cannot be null"
	static void test4(Box<Box<String>> bo) {
	    if (bo instanceof Box(Box(var s))) {    
	        System.out.println("String " + s);
	    }
	}

}
```

Stack trace that is logged:
```
java.lang.IllegalArgumentException: info cannot be null
	at org.eclipse.jdt.internal.compiler.codegen.StackMapFrame.addStackItem(StackMapFrame.java:90)
	at org.eclipse.jdt.internal.compiler.ClassFile.traverse(ClassFile.java:6816)
	at org.eclipse.jdt.internal.compiler.ClassFile.generateStackMapTableAttribute(ClassFile.java:5300)
	at org.eclipse.jdt.internal.compiler.ClassFile.completeCodeAttribute(ClassFile.java:1693)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:369)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:292)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:761)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:831)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1075)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:274)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:193)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:266)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
	at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1148)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:173)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1325)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

**Comment by howlger** [comment]
Verified in SDK-I20230413-1800.

Thanks for fixing it!
