### ISSUE TITLE
[20][record pattern] NPE with records pattern type inference

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#910]
Ref
interface I {
   int a();
}

record R<T>(T a) {}

public class X {

    private static boolean test(R<? extends I> p) {
        if (p instanceof R(String a)) {
             return a instanceof String;
        }
        return true;
    }

    public static void main(String argv[]) {
        System.out.println(test(new R<>((I) () -> 0))); 
    }
}

get this.resolved.type == null
Java Model Exception: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.isValidBinding()" because "this.resolvedType" is null
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:326)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:193)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:266)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
	at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1148)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:173)

**Comment by mpalat** [comment]
resolved
