### ISSUE TITLE
Path variable is null in ClasspathJep247.findClass

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#911]
@jarthana, @stephan-herrmann: When using JDT Core on Java 11 from an AspectJ regression test, I get this error:

```text
  java.lang.NullPointerException
  	at java.base/java.nio.file.Files.provider(Files.java:101)
  	at java.base/java.nio.file.Files.exists(Files.java:2433)
  	at org.aspectj.org.eclipse.jdt.internal.compiler.batch.ClasspathJep247.findClass(ClasspathJep247.java:85)
  	at org.aspectj.org.eclipse.jdt.internal.compiler.batch.FileSystem.internalFindClass(FileSystem.java:553)
  	at org.aspectj.org.eclipse.jdt.internal.compiler.batch.FileSystem.findClass(FileSystem.java:485)
  	at org.aspectj.org.eclipse.jdt.internal.compiler.batch.FileSystem.findType(FileSystem.java:645)
  	at org.aspectj.org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.findType(IModuleAwareNameEnvironment.java:101)
```

Please, do no be irritatet by the package relocation prefix `org.aspectj.` in the JDT classes.

Looking at the latest version of `ClasspathJep247.findClass`, I see this apprarently bogus code:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/8fd34a894917855e2780c786a402f90785336d29/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/batch/ClasspathJep247.java#L81-L90

See how in line 85 the `null` variable `Path p` is used? That does not look quite right to me.

**Comment by jarthana** [comment]
That one's on me. I will take this forward.

**Comment by jarthana** [comment]
Alexander, I will provide a fix for this. But I am unable to test this as our no longer run with < JDK17. Would you be able to confirm that the fix works for you? TIA!

**Comment by kriegaex** [comment]
Oh, really? The PMC already agreed and yor team abandoned Java 11 already? Is this on master already, because I just merged yesterday night or so. I thought that as of now, it is still supposed to work.

Of course, I can give it a try, as soon as it is on master or at least on a feature branch. Master would be ideal, because this is the usual branch for my upstream refreshes.

**Comment by jarthana** [comment]
No, batch compiler won't move to JDK 11 yet. But the test bundles (not jdt, but the ones that we depend on) have already moved to 17 and therefore I have no way to run the tests with JDK 11 now, at least not an easy way.

**Comment by jarthana** [comment]
Fix released. Closing this now.

**Comment by kriegaex** [comment]
Thanks, Jay. It is working for me locally. A small commit for a man, a giant leap for mankind. 😉
