### ISSUE TITLE
indexing: AIOOBE

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#982]
on a fresh OOmphed Platform (https://github.com/eclipse-platform/.github/issues/114) i ran into:
```
eclipse.buildId=4.28.0.I20230417-1800
java.version=19.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\JKubitz\eclipseDev\platform-sdk20230418\Latest

org.eclipse.jdt.core
Warning
Tue Apr 18 10:17:32 CEST 2023
The Java indexing could not index /.org.eclipse.jdt.core.external.folders/.link38/workspace/AttachSourceTests/src/A.class. This .class file doesn't follow the class file format specification. Please report this issue against the .class file vendor

org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:523)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:200)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:661)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:91)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:676)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1291)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:514)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused in /.org.eclipse.jdt.core.external.folders/.link38/workspace/AttachSourceTests/src/A.class by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileStruct.u2At(ClassFileStruct.java:55)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:227)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:200)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:661)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:91)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:676)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1291)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:514)
	at java.base/java.lang.Thread.run(Thread.java:1589)


```

Don't know how to reproduce. Length==0 reads like the .class file is not (not yet or no anymore?) available.

**Comment by iloveeclipse** [comment]
Please provide steps to reproduce. I can run /org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AttachSourceTests.java on Java 19 without issues from my IDE, they are also executed on Java 19 regularly without issues: https://download.eclipse.org/eclipse/downloads/drops4/I20230416-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep428I-unit-cen64-gtk3-java19_linux.gtk.x86_64_19.html

**Comment by jukzi** [comment]
Reproducable by OOmphing Platform via https://github.com/eclipse-platform/.github/blame/main/CONTRIBUTING.md#L68

```
eclipse.buildId=4.28.0.I20230507-1800
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\JKubitz\eclipseDev\platform-sdk2023-05-08\Latest

This is a continuation of log file C:\Users\JKubitz\eclipseDev\platform-sdk2023-05-08\Latest\.metadata\.bak_0.log
Created Time: 2023-05-08 10:10:41.333

org.eclipse.jdt.core
Warning
Mon May 08 10:12:22 CEST 2023
The Java indexing could not index /.org.eclipse.jdt.core.external.folders/.link21/workspace/AttachSourceTests/src/A.class. This .class file doesn't follow the class file format specification. Please report this issue against the .class file vendor

org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:523)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:200)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:666)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:91)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:676)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1291)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:514)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused in /.org.eclipse.jdt.core.external.folders/.link21/workspace/AttachSourceTests/src/A.class by: java.lang.ArrayIndexOutOfBoundsException

```

**Comment by jukzi** [comment]
> I can run /org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AttachSourceTests.java on Java 19 without issues

Has nothing todo with running AttachSourceTests, it's only that this file is checked in an is indeed an illegal .class file because it has length 0.
