### ISSUE TITLE
RecordElementsTests	testPreviewFlagTrue fails since Java 20 is used / I20230419-0650

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#994]
Also org.eclipse.jdt.compiler.apt.tests.RecordElementsTests are failing, not only [batch compiler](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/992)  tests, [after the build started to use Java 20](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1033).:

- https://download.eclipse.org/eclipse/downloads/drops4/I20230420-1800/testresults/html/org.eclipse.jdt.compiler.apt.tests_ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html

```
Compilation failed : ---------- 1. ERROR in /home/jenkins/agent/workspace/AutomatedTests/ep428I-unit-cen64-gtk3-java20/tmp/eclipse-temp/src/mod_locations/records/mod.records/records/Record2.java (at line 0) package records; ^ Internal compiler error: java.lang.Exception: org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor$AssertionFailedError: Should support the latest compliance, expected RELEASE_20 but was RELEASE_6 (Binary mode= false) at org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor.reportError(BaseElementProcessor.java:125) at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.reportError(RecordElementProcessor.java:1) at org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor.assertEquals(BaseElementProcessor.java:199) at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.assertEquals(RecordElementProcessor.java:1) at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.testPreviewFlagTrue(RecordElementProcessor.java:139) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) at java.base/java.lang.reflect.Method.invoke(Method.java:578) at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.invokeTestMethods(RecordElementProcessor.java:107) at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.process(RecordElementProcessor.java:82) at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142) at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124) at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172) at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953) (Binary mode= false) at org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor.reportError(BaseElementProcessor.java:125) ---------- 2. WARNING in /home/jenkins/agent/workspace/AutomatedTests/ep428I-unit-cen64-gtk3-java20/tmp/eclipse-temp/src/mod_locations/records/mod.records/records/Record2.java (at line 4) public strictfp record Record2(int x, BigInteger i, Record3 r, Test t) { ^^^^^^^^ Floating-point expressions are always strictly evaluated from source level 17. Keyword 'strictfp' is not required. ---------- 3. WARNING: No SupportedSourceVersion annotation found on org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor, returning RELEASE_6. 3 problems (1 error, 2 warnings)

junit.framework.AssertionFailedError: Compilation failed : ----------
1. ERROR in /home/jenkins/agent/workspace/AutomatedTests/ep428I-unit-cen64-gtk3-java20/tmp/eclipse-temp/src/mod_locations/records/mod.records/records/Record2.java (at line 0)
package records;
^
Internal compiler error: java.lang.Exception: org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor$AssertionFailedError: Should support the latest compliance, expected RELEASE_20 but was RELEASE_6 (Binary mode= false)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor.reportError(BaseElementProcessor.java:125)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.reportError(RecordElementProcessor.java:1)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor.assertEquals(BaseElementProcessor.java:199)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.assertEquals(RecordElementProcessor.java:1)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.testPreviewFlagTrue(RecordElementProcessor.java:139)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.invokeTestMethods(RecordElementProcessor.java:107)
at org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor.process(RecordElementProcessor.java:82)
at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953) (Binary mode= false) at org.eclipse.jdt.compiler.apt.tests.processors.elements.BaseElementProcessor.reportError(BaseElementProcessor.java:125)
----------
2. WARNING in /home/jenkins/agent/workspace/AutomatedTests/ep428I-unit-cen64-gtk3-java20/tmp/eclipse-temp/src/mod_locations/records/mod.records/records/Record2.java (at line 4)
public strictfp record Record2(int x, BigInteger i, Record3 r, Test t) {
^^^^^^^^
Floating-point expressions are always strictly evaluated from source level 17. Keyword 'strictfp' is not required.
----------
3. WARNING: No SupportedSourceVersion annotation found on org.eclipse.jdt.compiler.apt.tests.processors.elements.RecordElementProcessor, returning RELEASE_6.
3 problems (1 error, 2 warnings)

at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.jdt.compiler.apt.tests.BatchTestUtils.compileInModuleMode(BatchTestUtils.java:190)
at org.eclipse.jdt.compiler.apt.tests.RecordElementsTests.internalTestWithPreview(RecordElementsTests.java:197)
at org.eclipse.jdt.compiler.apt.tests.RecordElementsTests.internalTestWithPreview(RecordElementsTests.java:169)
at org.eclipse.jdt.compiler.apt.tests.RecordElementsTests.testPreviewFlagTrue(RecordElementsTests.java:39)
```

**Comment by iloveeclipse** [comment]
OK, this is a regression from 3 (!) changes:
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/965 (enabled `org.eclipse.jdt.internal.compiler.apt.dispatch.BaseProcessingEnvImpl.getSourceVersion()`to recognize JDL > 17)
- https://github.com/eclipse-jdt/eclipse.jdt.core/commit/66115de462f67f145f71fbe530cd8bad0265eaf5 (changed `assertNotSame` to `assertEquals` )
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1033

Each changed a bit, and all together on Java 20 fail :-)

I will push a patch in a moment.
